# -*- coding: utf-8 -*-
# Passage 1 data: text + comprehensive vocab (elementary -> advanced)

PARAGRAPHS = [
"People from almost every culture love collecting things. They might collect stamps, books, cards, priceless paintings or worthless ticket stubs to old sports games. Their collection might hang on the walls of a mansion or be stored in a box under the bed. So what is it that drives people to collect? Psychologist Dr Maria Richter argues that the urge to collect is a basic human characteristic. According to her, in the very first years of life we form emotional connections with lifeless objects such as soft toys. And these positive relationships are the starting point for our fascination with collecting objects. In fact, the desire to collect may go back further still. Scientists suggest that for some ancient humans living hundreds of thousands of years ago, collecting may have had a serious purpose. Only by collecting sufficient food supplies to last through freezing winters or dry summers could our ancestors stay alive until the weather improved.",
"It turns out that even collecting for pleasure has a very long history. In 1925, the archaeologist Leonard Woolley was working at a site in the historic Babylonian city of Ur. Woolley had travelled to the region intending only to excavate the site of a palace. Instead, to his astonishment, he dug up artefacts which appeared to belong to a 2,500-year-old museum. Among the objects was part of a statue and a piece of a local building. And accompanying some of the artefacts were descriptions like modern-day labels. These texts appeared in three languages and were carved into pieces of clay. It seems likely that this early private collection of objects was created by Princess Ennigaldi, the daughter of King Nabonidus. However, very little else is known about Princess Ennigaldi or what her motivations were for setting up her collection.",
"This may have been one of the first large private collections, but it was not the last. Indeed, the fashion for establishing collections really got started in Europe around 2,000 years later with the so-called 'Cabinets of Curiosities'. These were collections, usually belonging to wealthy families, that were displayed in cabinets or small rooms. Cabinets of Curiosities typically included fine paintings and drawings, but equal importance was given to exhibits from the natural world such as animal specimens, shells and plants.",
"Some significant private collections of this sort date from the fifteenth century. One of the first belonged to the Medici family. The Medicis became a powerful political family in Italy and later a royal house, but banking was originally the source of all their wealth. The family started by collecting coins and valuable gems, then artworks and antiques from around Europe. In 1570 a secret 'studio' was built inside the Palazzo Medici to house their growing collection. This exhibition room had solid walls without windows to keep the valuable collection safe.",
"In the seventeenth century, another fabulous collection was created by a Danish physician named Ole Worm. His collection room contained numerous skeletons and specimens, as well as ancient texts and a laboratory. One of Ole Worm's motivations was to point out when other researchers had made mistakes, such as the false claim that birds of paradise had no feet. He also owned a great auk, a species of bird that has now become extinct, and the illustration he produced of it has been of value to later scientists.",
"The passion for collecting was just as strong in the nineteenth century. Lady Charlotte Guest spoke at least six languages and became well-known for translating English books into Welsh. She also travelled widely throughout Europe acquiring old and rare pottery, which she added to her collection at home in southern England. When Lady Charlotte died in 1895 this collection was given to the Victoria and Albert Museum in London. At around the same time in the north of England, a wealthy goldsmith named Joseph Mayer was building up an enormous collection of artefacts, particularly those dug up from sites in his local area. His legacy, the Mayer Trust, continues to fund public lectures in accordance with his wishes.",
"In the twentieth century, the writer Beatrix Potter had a magnificent collection of books, insects, plants and other botanical specimens. Most of these were donated to London's Natural History Museum, but Beatrix held on to her cabinets of fossils, which she was particularly proud of. In the United States, President Franklin D. Roosevelt began his stamp collection as a child and continued to add to it all his life. The stress associated with being president was easier to cope with, Roosevelt said, by taking time out to focus on his collection. By the end of his life this had expanded to include model ships, coins and artworks.",
"Most of us will never own collections so large or valuable as these. However, the examples given here suggest that collecting is a passion that has been shared by countless people over many centuries.",
]

E = lambda hl, word, d, coll="", fam="": {"hl": hl, "word": word, "def": d, "coll": coll, "fam": fam}

ENTRIES = [
 E(["culture"], "Culture", "the ideas, customs and way of life of a particular group of people", "every culture", "culture \u2192 cultural \u2192 culturally"),
 E(["collecting","collect","collection","collections"], "Collect", "to gather or bring together objects of one type, often as a hobby", "collect stamps", "collect \u2192 collection \u2192 collector \u2192 collective \u2192 collectively"),
 E(["stamps"], "Stamps", "small printed pieces of paper stuck on letters to show postage has been paid", "a sheet of stamps"),
 E(["cards"], "Cards", "small pieces of stiff paper, here used for collecting (e.g. trading cards)", "a set of cards"),
 E(["priceless"], "Priceless", "so valuable that the price cannot be calculated; extremely precious", "a priceless painting", "price \u2192 priceless \u2192 pricey"),
 E(["paintings","painting"], "Painting", "a picture made using paint", "a famous painting", "paint \u2192 painting \u2192 painter"),
 E(["worthless"], "Worthless", "having no value at all", "worthless objects", "worth \u2192 worthless \u2192 worthwhile"),
 E(["ticket stubs"], "Ticket stub", "the part of a ticket kept as proof after it has been torn", "an old ticket stub"),
 E(["hang"], "Hang", "to fix something so it is held above the ground, e.g. on a wall", "hang on the wall", "hang \u2192 hung \u2192 hanging"),
 E(["walls","wall"], "Wall", "an upright structure that encloses or divides a room or building", "on the walls"),
 E(["mansion"], "Mansion", "a very large, impressive house", "a grand mansion"),
 E(["stored","stored in","store"], "Store", "to keep something in a place for use in the future", "stored in a box", "store \u2192 storage \u2192 storeroom"),
 E(["drives","drive"], "Drive (sb to)", "to make someone behave in a particular way; to motivate strongly", "what drives people to collect", "drive \u2192 driven \u2192 driving force"),
 E(["psychologist"], "Psychologist", "a scientist who studies the mind and human behaviour", "according to the psychologist", "psychology \u2192 psychologist \u2192 psychological"),
 E(["argues","argue"], "Argue", "to give reasons for an opinion; to claim something is true", "argues that", "argue \u2192 argument \u2192 arguably"),
 E(["urge"], "Urge", "a strong wish or need to do something", "the urge to collect", "urge \u2192 urgent \u2192 urgency"),
 E(["basic"], "Basic", "forming the simplest and most essential part of something", "a basic human need", "base \u2192 basic \u2192 basically"),
 E(["human characteristic","characteristic"], "Characteristic", "a typical or noticeable feature of someone or something", "a basic human characteristic", "character \u2192 characteristic \u2192 characterise"),
 E(["according to"], "According to", "as stated or shown by (a person or source)", "according to her"),
 E(["form"], "Form (v)", "to create or develop something gradually", "form connections", "form \u2192 formation \u2192 formative"),
 E(["emotional"], "Emotional", "relating to feelings", "an emotional connection", "emotion \u2192 emotional \u2192 emotionally"),
 E(["connections","connection"], "Connection", "a relationship or link between things or people", "emotional connections", "connect \u2192 connection \u2192 connected"),
 E(["lifeless"], "Lifeless", "not alive; without life", "lifeless objects", "life \u2192 lifeless \u2192 lifelike"),
 E(["objects","object"], "Object (n)", "a thing that can be seen or touched", "everyday objects"),
 E(["positive"], "Positive", "good, helpful or favourable", "a positive relationship", "positive \u2192 positively \u2192 positivity"),
 E(["relationships","relationship"], "Relationship", "the way in which people or things are connected", "form relationships", "relate \u2192 relationship \u2192 related"),
 E(["starting point"], "Starting point", "the place or idea from which something begins", "the starting point for"),
 E(["fascination"], "Fascination", "a very strong attraction or interest", "a fascination with collecting", "fascinate \u2192 fascination \u2192 fascinating"),
 E(["desire"], "Desire", "a strong feeling of wanting something", "the desire to collect", "desire \u2192 desirable \u2192 desirous"),
 E(["ancient"], "Ancient", "belonging to the very distant past; very old", "ancient humans", "ancient \u2192 antiquity"),
 E(["humans","human"], "Human", "a person; relating to people", "ancient humans", "human \u2192 humanity \u2192 humankind"),
 E(["hundreds of thousands"], "Hundreds of thousands", "a very large number (i.e. 100,000s)", "hundreds of thousands of years"),
 E(["serious"], "Serious", "important and needing careful thought; not trivial", "a serious purpose", "serious \u2192 seriously \u2192 seriousness"),
 E(["purpose"], "Purpose", "the reason for which something is done", "a serious purpose", "purpose \u2192 purposeful \u2192 purposely"),
 E(["sufficient"], "Sufficient", "enough for a particular need", "sufficient supplies", "suffice \u2192 sufficient \u2192 sufficiently"),
 E(["food supplies","supplies","supply"], "Supplies", "amounts of food or materials kept for use", "food supplies", "supply \u2192 supplies \u2192 supplier"),
 E(["freezing"], "Freezing", "extremely cold", "freezing winters", "freeze \u2192 freezing \u2192 frozen"),
 E(["dry"], "Dry", "without rain or moisture", "a dry summer", "dry \u2192 drought \u2192 dryness"),
 E(["ancestors","ancestor"], "Ancestor", "a person from whom one is descended; a forefather", "our ancestors", "ancestor \u2192 ancestral \u2192 ancestry"),
 E(["stay alive"], "Stay alive", "to continue to live; to survive", "stay alive through winter"),
 E(["weather"], "Weather", "the state of the atmosphere (rain, sun, temperature, etc.)", "until the weather improved"),
 E(["improved","improve"], "Improve", "to become or make better", "the weather improved", "improve \u2192 improvement \u2192 improved"),
 E(["turns out","turn out"], "Turn out", "to be discovered or proved to be the case", "it turns out that"),
 E(["pleasure"], "Pleasure", "a feeling of enjoyment or satisfaction", "collecting for pleasure", "please \u2192 pleasure \u2192 pleasurable"),
 E(["history"], "History", "the study or record of past events", "a long history", "history \u2192 historic \u2192 historical \u2192 historian"),
 E(["archaeologist"], "Archaeologist", "a scientist who studies the past through physical remains", "the archaeologist discovered", "archaeology \u2192 archaeologist \u2192 archaeological"),
 E(["site","sites"], "Site", "a place where something is located or where work is done", "an archaeological site"),
 E(["historic"], "Historic", "famous or important in history", "the historic city", "history \u2192 historic \u2192 historical"),
 E(["region"], "Region", "a large area of land; a part of a country", "travelled to the region", "region \u2192 regional \u2192 regionally"),
 E(["intending","intending only","intend"], "Intend", "to plan or mean to do something", "intending to excavate", "intend \u2192 intention \u2192 intentional"),
 E(["excavate"], "Excavate", "to dig carefully in the ground to find ancient objects", "excavate the site", "excavate \u2192 excavation \u2192 excavator"),
 E(["palace"], "Palace", "the official home of a king, queen or ruler", "the site of a palace"),
 E(["astonishment"], "Astonishment", "very great surprise", "to his astonishment", "astonish \u2192 astonishment \u2192 astonishing"),
 E(["dug up","dug","dig up"], "Dig up", "to remove something from the ground by digging", "dug up artefacts", "dig \u2192 dug \u2192 digging"),
 E(["artefacts","artefact"], "Artefact", "an object made by a human, especially of historical interest", "ancient artefacts"),
 E(["belong","belonged","belonging"], "Belong", "to be the property of, or be part of, something", "belong to a museum", "belong \u2192 belonging \u2192 belongings"),
 E(["museum"], "Museum", "a building where objects of historical or artistic interest are displayed", "a 2,500-year-old museum"),
 E(["statue"], "Statue", "a carved or moulded figure of a person or animal", "part of a statue"),
 E(["accompanying","accompany"], "Accompany", "to go or exist together with something", "accompanying the artefacts", "accompany \u2192 accompaniment \u2192 accompanying"),
 E(["descriptions","description"], "Description", "a spoken or written account of something", "detailed descriptions", "describe \u2192 description \u2192 descriptive"),
 E(["modern-day","modern"], "Modern", "relating to the present time; up to date", "modern-day labels", "modern \u2192 modernise \u2192 modernity"),
 E(["labels","label"], "Label", "a piece of paper or writing attached to something to identify it", "modern-day labels", "label \u2192 labelled \u2192 labelling"),
 E(["texts","text"], "Text", "written or printed words", "ancient texts"),
 E(["languages","language"], "Language", "a system of communication used by a people or nation", "three languages", "language \u2192 linguistic \u2192 linguist"),
 E(["carved","carve"], "Carve", "to cut a shape or words into a hard material", "carved into clay", "carve \u2192 carving \u2192 carved"),
 E(["clay"], "Clay", "a heavy, sticky earth used for making pottery and bricks", "pieces of clay"),
 E(["private"], "Private", "belonging to one person or group, not public", "a private collection", "private \u2192 privately \u2192 privacy"),
 E(["created","create"], "Create", "to make or bring something into existence", "created by the princess", "create \u2192 creation \u2192 creative \u2192 creator"),
 E(["princess"], "Princess", "the daughter of a king or queen", "Princess Ennigaldi"),
 E(["daughter"], "Daughter", "a female child in relation to her parents", "the king's daughter"),
 E(["motivations","motivation"], "Motivation", "the reason or desire that makes someone act", "her motivations were unclear", "motivate \u2192 motivation \u2192 motivated"),
 E(["setting up","set up"], "Set up", "to establish or start something", "setting up a collection"),
 E(["indeed"], "Indeed", "used to emphasise or confirm a statement", "indeed, it was true"),
 E(["fashion"], "Fashion", "a popular trend or style at a particular time", "the fashion for collecting", "fashion \u2192 fashionable \u2192 fashionably"),
 E(["establishing","establish"], "Establish", "to set up or start something that lasts", "establishing collections", "establish \u2192 establishment \u2192 established"),
 E(["so-called"], "So-called", "used to show that a name or description may be doubtful or unusual", "the so-called 'Cabinets of Curiosities'"),
 E(["curiosities","curiosity"], "Curiosity", "a rare or unusual object; a strong desire to know", "cabinets of curiosities", "curious \u2192 curiosity \u2192 curiously"),
 E(["wealthy"], "Wealthy", "having a great deal of money; rich", "wealthy families", "wealth \u2192 wealthy \u2192 wealthier"),
 E(["families","family"], "Family", "a group of related people", "wealthy families"),
 E(["displayed","display"], "Display", "to put something where it can be seen", "objects were displayed", "display \u2192 displayed \u2192 on display"),
 E(["cabinets","cabinet"], "Cabinet", "a piece of furniture with shelves or drawers for storing or showing things", "displayed in cabinets"),
 E(["typically"], "Typically", "in most cases; usually", "typically included", "typical \u2192 typically \u2192 typify"),
 E(["fine"], "Fine (adj)", "of high quality; excellent", "fine paintings"),
 E(["drawings","drawing"], "Drawing", "a picture made with a pencil or pen", "fine drawings", "draw \u2192 drawing \u2192 drawn"),
 E(["equal"], "Equal", "the same in amount, value or importance", "equal importance", "equal \u2192 equally \u2192 equality"),
 E(["importance"], "Importance", "the quality of being significant or valued", "given equal importance", "important \u2192 importance \u2192 importantly"),
 E(["exhibits","exhibit"], "Exhibit (n)", "an object shown in a museum or exhibition", "exhibits from the natural world", "exhibit \u2192 exhibition \u2192 exhibitor"),
 E(["natural world"], "Natural world", "the physical world of plants, animals and landscapes", "exhibits from the natural world"),
 E(["specimens","specimen"], "Specimen", "an example of something, especially studied or collected", "animal specimens"),
 E(["shells","shell"], "Shell", "the hard outer covering of a sea creature, egg or nut", "shells and plants"),
 E(["significant"], "Significant", "important; large enough to have an effect", "significant collections", "signify \u2192 significant \u2192 significance \u2192 significantly"),
 E(["sort"], "Sort (n)", "a type or kind of something", "of this sort"),
 E(["date from","date"], "Date from", "to have existed since a particular time", "collections date from the 15th century"),
 E(["century","centuries"], "Century", "a period of one hundred years", "the fifteenth century"),
 E(["powerful"], "Powerful", "having great power or influence", "a powerful family", "power \u2192 powerful \u2192 powerfully"),
 E(["political"], "Political", "relating to government or public affairs", "a political family", "politics \u2192 political \u2192 politician"),
 E(["royal house","royal"], "Royal", "relating to or belonging to a king or queen", "a royal house", "royal \u2192 royalty \u2192 royally"),
 E(["banking"], "Banking", "the business activity of banks", "banking was the source of wealth", "bank \u2192 banking \u2192 banker"),
 E(["originally","original"], "Originally", "at first; in the beginning", "originally the source", "origin \u2192 original \u2192 originally"),
 E(["source"], "Source", "the place or thing from which something comes", "the source of their wealth", "source \u2192 sourced \u2192 sourcing"),
 E(["wealth"], "Wealth", "a large amount of money or valuable possessions", "the source of their wealth", "wealth \u2192 wealthy \u2192 well-off"),
 E(["coins","coin"], "Coin", "a piece of metal money", "collecting coins"),
 E(["valuable"], "Valuable", "worth a lot of money; very useful", "valuable gems", "value \u2192 valuable \u2192 invaluable"),
 E(["gems","gem"], "Gem", "a precious stone, especially when cut and polished", "valuable gems"),
 E(["artworks","artwork"], "Artwork", "a work of art such as a painting or sculpture", "artworks and antiques"),
 E(["antiques","antique"], "Antique", "an old and often valuable object from an earlier period", "antiques from Europe"),
 E(["secret"], "Secret", "kept hidden from others", "a secret studio", "secret \u2192 secretly \u2192 secrecy"),
 E(["built","build"], "Build", "to make something by putting parts together", "a studio was built", "build \u2192 built \u2192 building"),
 E(["house"], "House (v)", "to provide space for; to contain", "to house their collection"),
 E(["growing","grow"], "Growing", "increasing in size or amount", "a growing collection", "grow \u2192 growth \u2192 growing"),
 E(["exhibition"], "Exhibition", "a public display of works or objects", "an exhibition room", "exhibit \u2192 exhibition \u2192 exhibitor"),
 E(["solid"], "Solid", "firm, hard and without gaps", "solid walls", "solid \u2192 solidly \u2192 solidify"),
 E(["windows","window"], "Window", "an opening in a wall fitted with glass", "without windows"),
 E(["keep","keep the","safe"], "Keep safe", "to protect something from harm or loss", "to keep the collection safe"),
 E(["fabulous"], "Fabulous", "extremely good or impressive; wonderful", "a fabulous collection"),
 E(["Danish"], "Danish", "relating to Denmark or its people", "a Danish physician"),
 E(["physician"], "Physician", "a doctor, especially one treating illness with medicine", "a Danish physician"),
 E(["contained","contain"], "Contain", "to have something inside; to hold", "the room contained skeletons", "contain \u2192 container \u2192 containment"),
 E(["numerous"], "Numerous", "many; a large number of", "numerous skeletons", "number \u2192 numerous \u2192 innumerable"),
 E(["skeletons","skeleton"], "Skeleton", "the framework of bones in a body", "numerous skeletons"),
 E(["laboratory"], "Laboratory", "a room equipped for scientific experiments", "a laboratory", "laboratory \u2192 lab \u2192 laboratory technician"),
 E(["point out"], "Point out", "to tell or show someone a fact or mistake", "to point out mistakes"),
 E(["researchers","researcher"], "Researcher", "a person who studies a subject in detail to discover new facts", "other researchers", "research \u2192 researcher \u2192 researched"),
 E(["mistakes","mistake"], "Mistake", "something done incorrectly; an error", "made mistakes", "mistake \u2192 mistaken \u2192 mistakenly"),
 E(["false claim","false"], "False", "not true or correct", "a false claim", "false \u2192 falsely \u2192 falsify"),
 E(["claim"], "Claim (n)", "a statement that something is true without proof", "a false claim", "claim \u2192 claimant \u2192 claimed"),
 E(["birds of paradise"], "Birds of paradise", "brightly coloured birds found mainly in New Guinea", "the false claim about birds of paradise"),
 E(["owned","own"], "Own (v)", "to have or possess something", "he owned a great auk", "own \u2192 owner \u2192 ownership"),
 E(["species"], "Species", "a group of living things that can breed with each other", "a species of bird"),
 E(["extinct"], "Extinct", "no longer existing as a living species", "become extinct", "extinct \u2192 extinction"),
 E(["illustration"], "Illustration", "a picture used to explain or decorate", "an illustration of the bird", "illustrate \u2192 illustration \u2192 illustrator"),
 E(["produced","produce"], "Produce (v)", "to make or create something", "the illustration he produced", "produce \u2192 production \u2192 product \u2192 producer"),
 E(["value"], "Value (n)", "the importance, usefulness or worth of something", "of value to scientists", "value \u2192 valuable \u2192 valued"),
 E(["passion"], "Passion", "a very strong feeling or enthusiasm", "a passion for collecting", "passion \u2192 passionate \u2192 passionately"),
 E(["strong"], "Strong", "powerful; intense", "a strong passion", "strong \u2192 strength \u2192 strongly"),
 E(["at least"], "At least", "not less than; as a minimum", "at least six languages"),
 E(["well-known"], "Well-known", "known by many people; famous", "well-known for translating"),
 E(["translating","translate"], "Translate", "to change words from one language into another", "translating books", "translate \u2192 translation \u2192 translator"),
 E(["widely"], "Widely", "over a large area; by many people", "travelled widely", "wide \u2192 widely \u2192 widespread"),
 E(["throughout"], "Throughout", "in or through every part of", "throughout Europe"),
 E(["acquiring","acquire"], "Acquire", "to get or obtain something", "acquiring rare pottery", "acquire \u2192 acquisition \u2192 acquired"),
 E(["rare"], "Rare", "not common; seldom found", "rare pottery", "rare \u2192 rarely \u2192 rarity"),
 E(["pottery"], "Pottery", "objects made of baked clay", "rare pottery"),
 E(["added","add"], "Add", "to put something with another to increase it", "added to her collection", "add \u2192 addition \u2192 additional"),
 E(["died","die"], "Die", "to stop living", "she died in 1895", "die \u2192 death \u2192 dead"),
 E(["goldsmith"], "Goldsmith", "a person who makes objects out of gold", "a wealthy goldsmith"),
 E(["building up","build up"], "Build up", "to gradually increase or develop", "building up a collection"),
 E(["enormous"], "Enormous", "extremely large; huge", "an enormous collection", "enormous \u2192 enormously \u2192 enormity"),
 E(["particularly"], "Particularly", "especially; more than usual", "particularly those dug up", "particular \u2192 particularly"),
 E(["local area","local"], "Local", "relating to a nearby or particular area", "his local area", "local \u2192 locally \u2192 locality"),
 E(["legacy"], "Legacy", "money, property or things left or passed on from the past", "his legacy", "legacy \u2192 bequest"),
 E(["trust"], "Trust (n)", "an organisation that manages money or property for a purpose", "the Mayer Trust"),
 E(["continues","continued","continue"], "Continue", "to keep happening or doing something", "continues to fund lectures", "continue \u2192 continuation \u2192 continuous"),
 E(["fund"], "Fund (v)", "to provide money for something", "to fund public lectures", "fund \u2192 funding \u2192 funded"),
 E(["public lectures","lectures","lecture"], "Lecture", "a formal talk given to teach people about a subject", "public lectures", "lecture \u2192 lecturer \u2192 lecturing"),
 E(["in accordance with"], "In accordance with", "in a way that follows (a rule or wish)", "in accordance with his wishes"),
 E(["wishes","wish"], "Wish (n)", "a desire or hope for something", "in accordance with his wishes"),
 E(["magnificent"], "Magnificent", "extremely impressive or beautiful", "a magnificent collection", "magnificent \u2192 magnificence \u2192 magnificently"),
 E(["insects","insect"], "Insect", "a small creature with six legs and usually wings", "insects and plants"),
 E(["botanical"], "Botanical", "relating to plants or the study of plants", "botanical specimens", "botany \u2192 botanical \u2192 botanist"),
 E(["donated","donate"], "Donate", "to give something, especially to a good cause", "donated to the museum", "donate \u2192 donation \u2192 donor"),
 E(["held on to","hold on to"], "Hold on to", "to keep something and not give it away", "held on to her fossils"),
 E(["fossils","fossil"], "Fossil", "the preserved remains of a prehistoric organism in rock", "cabinets of fossils", "fossil \u2192 fossilise \u2192 fossilised"),
 E(["proud"], "Proud", "feeling pleasure and satisfaction about something", "proud of her collection", "proud \u2192 pride \u2192 proudly"),
 E(["president"], "President", "the elected head of a country or organisation", "the President began", "president \u2192 presidency \u2192 presidential"),
 E(["continued to add","add to it"], "Add to", "to increase something by including more", "continued to add to it"),
 E(["stress"], "Stress", "mental or emotional strain or pressure", "the stress of the job", "stress \u2192 stressful \u2192 stressed"),
 E(["associated","associate"], "Associated with", "connected with or related to", "stress associated with being president", "associate \u2192 association \u2192 associated"),
 E(["cope with","cope"], "Cope with", "to deal successfully with a difficulty", "easier to cope with", "cope \u2192 coping"),
 E(["taking time out","time out"], "Take time out", "to stop normal activity in order to rest", "by taking time out"),
 E(["focus"], "Focus (v)", "to give attention to one thing", "focus on his collection", "focus \u2192 focused \u2192 focusing"),
 E(["expanded","expand"], "Expand", "to become larger or more extensive", "the collection expanded", "expand \u2192 expansion \u2192 expansive"),
 E(["model ships","model"], "Model (n)", "a small copy of an object", "model ships"),
 E(["own"], "Own (collections)", "to possess or have as property", "own a collection"),
 E(["examples","example"], "Example", "a thing that is typical of, or illustrates, something", "the examples given here", "example \u2192 exemplify \u2192 exemplary"),
 E(["suggest"], "Suggest", "to put forward an idea; to indicate", "the examples suggest", "suggest \u2192 suggestion \u2192 suggestive"),
 E(["shared","share"], "Share", "to have or experience something with others", "a passion shared by many", "share \u2192 shared \u2192 sharing"),
 E(["countless"], "Countless", "too many to count; very many", "countless people", "count \u2192 countless \u2192 uncountable"),
]
