# -*- coding: utf-8 -*-
# Passage 3 data: "Jellyfish: A Remarkable Marine Life Form" + comprehensive vocab

PARAGRAPHS = [
"When viewed in the wild, jellyfish are perhaps the most graceful and vividly coloured of all sea creatures. But few people have ever seen a jellyfish living in its natural habitat. Instead, they might see a dead and shapeless specimen lying on the beach, or perhaps receive a painful sting while swimming, so it is inevitable that jellyfish are often considered ugly and possibly dangerous. This misunderstanding can be partly traced back to the 20th century, when the use of massive nets and mechanical winches often damaged the delicate jellyfish that scientists managed to recover. As a result, disappointingly little research was carried out into jellyfish, as marine biologists took the easy option and focused on physically stronger species such as fish, crabs and shrimp. Fortunately, however, new techniques are now being developed. For example, scientists have discovered that sound bounces harmlessly off jellyfish, so in the Arctic and Norway researchers are using sonar to monitor jellyfish beneath the ocean's surface. This, together with aeroplane surveys, satellite imagery and underwater cameras, has provided a wealth of new information in recent years.",
"Scientists now believe that in shallow water alone there are at least 38 million tonnes of jellyfish and that these creatures inhabit every type of marine habitat, including deep water. Furthermore, jellyfish were once regarded as relatively solitary, but this is another area where the science has evolved. Dr Karen Hansen was the first to suggest that jellyfish are in fact the centre of entire ecosystems, as shrimp, lobster and fish shelter and feed among their tentacles. This proposition has subsequently been conclusively proven by independent studies. DNA sequencing and isotope analysis have provided further insights, including the identification of numerous additional species of jellyfish unknown to science only a few years ago.",
"This brings us to the issue of climate change. Research studies around the world have recorded a massive growth in jellyfish populations in recent years and some scientists have linked this to climate change. However, while this may be credible, it cannot be established with certainty as other factors might be involved. Related to this was the longstanding academic belief that jellyfish had no predators and therefore there was no natural process to limit their numbers. However, observations made by Paul Dewar and his team showed that this was incorrect. As a result, the scientific community now recognises that species including sharks, tuna, swordfish and some salmon all prey on jellyfish.",
"It is still widely assumed that jellyfish are among the simplest lifeforms, as they have no brain or central nervous system. While this is true, we now know they possess senses that allow them to see, feel and interact with their environment in subtle ways. What is more, analysis of the so-called 'upside-down jellyfish' shows that they shut down their bodies and rest in much the same way that humans do at night, something once widely believed to be impossible for jellyfish. Furthermore, far from 'floating' in the water as they are still sometimes thought to do, analysis has shown jellyfish to be the most economical swimmers in the animal kingdom. In short, scientific progress in recent years has shown that many of our established beliefs about jellyfish were inaccurate.",
]

E = lambda hl, word, d, coll="", fam="": {"hl": hl, "word": word, "def": d, "coll": coll, "fam": fam}

ENTRIES = [
 E(["viewed","view"], "View (v)", "to look at or observe something", "viewed in the wild", "view \u2192 viewer \u2192 viewing"),
 E(["wild"], "Wild (the)", "a natural environment, not controlled by humans", "in the wild", "wild \u2192 wildlife \u2192 wilderness"),
 E(["jellyfish"], "Jellyfish", "a sea creature with a soft, transparent body and stinging tentacles", "a jellyfish in the sea"),
 E(["graceful"], "Graceful", "moving in a smooth, attractive and elegant way", "graceful sea creatures", "grace \u2192 graceful \u2192 gracefully"),
 E(["vividly","vivid"], "Vividly", "in a bright, clear and intense way", "vividly coloured", "vivid \u2192 vividly \u2192 vividness"),
 E(["coloured","colour"], "Coloured", "having a particular colour", "vividly coloured", "colour \u2192 coloured \u2192 colourful"),
 E(["sea creatures","creatures","creature"], "Creature", "a living being, especially an animal", "sea creatures"),
 E(["natural habitat","habitat"], "Habitat", "the natural home or environment of an animal or plant", "its natural habitat"),
 E(["dead"], "Dead", "no longer alive", "a dead specimen", "die \u2192 death \u2192 dead"),
 E(["shapeless"], "Shapeless", "having no definite or clear shape", "a shapeless specimen", "shape \u2192 shapeless \u2192 shapely"),
 E(["specimen"], "Specimen", "an example of an animal or plant, often for study", "a specimen on the beach"),
 E(["lying","lie"], "Lie (v)", "to be in a flat or resting position", "lying on the beach", "lie \u2192 lay \u2192 lying"),
 E(["beach"], "Beach", "an area of sand or stones beside the sea", "on the beach"),
 E(["receive"], "Receive", "to get or be given something", "receive a sting", "receive \u2192 receipt \u2192 receiver"),
 E(["painful"], "Painful", "causing physical pain", "a painful sting", "pain \u2192 painful \u2192 painfully"),
 E(["sting"], "Sting (n)", "a wound or pain caused by an animal's stinging part", "a painful sting", "sting \u2192 stinging \u2192 stung"),
 E(["swimming","swim"], "Swim", "to move through water using the body", "while swimming", "swim \u2192 swimmer \u2192 swimming"),
 E(["inevitable"], "Inevitable", "certain to happen; unavoidable", "it is inevitable that", "inevitable \u2192 inevitably \u2192 inevitability"),
 E(["considered","consider"], "Consider", "to think of someone or something in a particular way", "considered ugly", "consider \u2192 consideration \u2192 considerable"),
 E(["ugly"], "Ugly", "unpleasant or unattractive to look at", "considered ugly", "ugly \u2192 ugliness"),
 E(["possibly"], "Possibly", "perhaps; maybe", "possibly dangerous", "possible \u2192 possibly \u2192 possibility"),
 E(["dangerous"], "Dangerous", "likely to cause harm or injury", "possibly dangerous", "danger \u2192 dangerous \u2192 dangerously"),
 E(["misunderstanding"], "Misunderstanding", "a failure to understand something correctly", "this misunderstanding", "understand \u2192 misunderstand \u2192 misunderstanding"),
 E(["partly"], "Partly", "to some extent; not completely", "partly traced back", "part \u2192 partly \u2192 partial"),
 E(["traced back","trace back","traced"], "Trace back", "to find the origin of something in the past", "traced back to the 20th century", "trace \u2192 traceable \u2192 tracing"),
 E(["massive"], "Massive", "extremely large or great", "massive nets", "mass \u2192 massive \u2192 massively"),
 E(["nets","net"], "Net", "an open material of crossed threads used for catching things", "massive nets"),
 E(["mechanical"], "Mechanical", "operated by or relating to machines", "mechanical winches", "mechanic \u2192 mechanical \u2192 mechanically"),
 E(["winches","winch"], "Winch", "a machine for lifting or pulling using a rope or chain", "mechanical winches"),
 E(["damaged","damage"], "Damage (v)", "to harm or spoil something", "damaged the jellyfish", "damage \u2192 damaged \u2192 damaging"),
 E(["delicate"], "Delicate", "easily broken or harmed; fragile", "the delicate jellyfish", "delicate \u2192 delicately \u2192 delicacy"),
 E(["managed to","manage"], "Manage to", "to succeed in doing something difficult", "scientists managed to recover", "manage \u2192 management \u2192 manageable"),
 E(["recover"], "Recover", "to get something back; to retrieve", "managed to recover the specimens", "recover \u2192 recovery \u2192 recoverable"),
 E(["as a result"], "As a result", "because of this; consequently", "as a result, little research was done"),
 E(["disappointingly","disappointing"], "Disappointingly", "in a way that fails to meet hopes or expectations", "disappointingly little research", "disappoint \u2192 disappointing \u2192 disappointment"),
 E(["research"], "Research", "careful study to discover new facts", "little research was carried out", "research \u2192 researcher \u2192 researched"),
 E(["carried out","carry out"], "Carry out", "to perform or complete a task", "research was carried out"),
 E(["marine biologists","biologists","biologist"], "Biologist", "a scientist who studies living things", "marine biologists", "biology \u2192 biologist \u2192 biological"),
 E(["marine"], "Marine", "relating to the sea or sea life", "marine biologists"),
 E(["easy option","option"], "Option", "a choice; something that can be chosen", "took the easy option", "opt \u2192 option \u2192 optional"),
 E(["focused","focus"], "Focus (v)", "to give attention to one particular thing", "focused on stronger species", "focus \u2192 focused \u2192 focusing"),
 E(["physically","physical"], "Physically", "in relation to the body or material things", "physically stronger species", "physical \u2192 physically \u2192 physique"),
 E(["stronger","strong"], "Stronger", "more powerful or tough", "physically stronger species", "strong \u2192 stronger \u2192 strength"),
 E(["species"], "Species", "a group of living things that can breed together", "stronger species"),
 E(["crabs","crab"], "Crab", "a sea animal with a hard shell and pincers", "fish, crabs and shrimp"),
 E(["shrimp"], "Shrimp", "a small edible shellfish with a long body", "crabs and shrimp"),
 E(["fortunately"], "Fortunately", "luckily; by good fortune", "fortunately, new techniques exist", "fortune \u2192 fortunate \u2192 fortunately"),
 E(["techniques","technique"], "Technique", "a particular method of doing something", "new techniques", "technique \u2192 technical \u2192 technician"),
 E(["developed","develop"], "Develop", "to grow or create gradually", "techniques are being developed", "develop \u2192 development \u2192 developed"),
 E(["discovered","discover"], "Discover", "to find or learn something for the first time", "scientists discovered that", "discover \u2192 discovery \u2192 discovered"),
 E(["sound"], "Sound (n)", "something that can be heard; vibrations in the air", "sound bounces off jellyfish"),
 E(["bounces","bounce"], "Bounce (off)", "to spring back after hitting a surface", "sound bounces harmlessly", "bounce \u2192 bouncing \u2192 bounced"),
 E(["harmlessly","harmless"], "Harmlessly", "without causing any harm or damage", "bounces harmlessly off", "harm \u2192 harmless \u2192 harmlessly"),
 E(["sonar"], "Sonar", "a system using sound waves to detect objects underwater", "using sonar to monitor"),
 E(["monitor"], "Monitor (v)", "to watch and check something over time", "monitor jellyfish", "monitor \u2192 monitoring \u2192 monitored"),
 E(["beneath"], "Beneath", "under or below something", "beneath the surface"),
 E(["ocean","ocean's"], "Ocean", "a very large area of sea", "the ocean's surface", "ocean \u2192 oceanic"),
 E(["surface"], "Surface", "the top or outer layer of something", "the ocean's surface"),
 E(["aeroplane"], "Aeroplane", "a powered flying vehicle with wings", "aeroplane surveys"),
 E(["surveys","survey"], "Survey", "an act of examining or measuring an area or group", "aeroplane surveys", "survey \u2192 surveyor \u2192 surveying"),
 E(["satellite imagery","satellite"], "Satellite", "a device sent into space to orbit and gather data", "satellite imagery"),
 E(["imagery"], "Imagery", "visual images, especially produced by technology", "satellite imagery", "image \u2192 imagery \u2192 imaging"),
 E(["underwater"], "Underwater", "located or happening below the surface of water", "underwater cameras"),
 E(["a wealth of","wealth of"], "A wealth of", "a large amount of something valuable", "a wealth of information"),
 E(["recent"], "Recent", "happening or done a short time ago", "in recent years", "recent \u2192 recently"),
 E(["shallow"], "Shallow", "not deep; having little depth", "shallow water", "shallow \u2192 shallowness"),
 E(["at least"], "At least", "not less than; as a minimum", "at least 38 million tonnes"),
 E(["tonnes","tonne"], "Tonne", "a metric unit of weight equal to 1,000 kilograms", "38 million tonnes"),
 E(["inhabit"], "Inhabit", "to live in or occupy a place", "creatures inhabit every habitat", "inhabit \u2192 inhabitant \u2192 inhabited"),
 E(["deep"], "Deep", "extending far down from the top or surface", "deep water", "deep \u2192 depth \u2192 deeply"),
 E(["furthermore"], "Furthermore", "in addition; moreover", "furthermore, jellyfish were once..."),
 E(["regarded","regard"], "Regard (as)", "to think of or consider in a particular way", "regarded as solitary", "regard \u2192 regarding \u2192 regarded"),
 E(["relatively"], "Relatively", "in comparison with something else; fairly", "relatively solitary", "relative \u2192 relatively \u2192 relativity"),
 E(["solitary"], "Solitary", "living or being alone", "regarded as solitary", "solitary \u2192 solitude"),
 E(["evolved","evolve"], "Evolve", "to develop gradually over time", "the science has evolved", "evolve \u2192 evolution \u2192 evolutionary"),
 E(["suggest"], "Suggest", "to put forward an idea for consideration", "the first to suggest that", "suggest \u2192 suggestion \u2192 suggestive"),
 E(["centre"], "Centre", "the middle or most important point of something", "the centre of ecosystems", "centre \u2192 central \u2192 centralise"),
 E(["entire"], "Entire", "whole; complete", "entire ecosystems", "entire \u2192 entirely \u2192 entirety"),
 E(["ecosystems","ecosystem"], "Ecosystem", "all the living things in an area and their environment", "entire ecosystems", "eco \u2192 ecosystem \u2192 ecological"),
 E(["lobster"], "Lobster", "a large edible shellfish with claws", "shrimp, lobster and fish"),
 E(["shelter"], "Shelter (v)", "to find or give protection from danger or weather", "shelter among tentacles", "shelter \u2192 sheltered \u2192 sheltering"),
 E(["feed"], "Feed", "to eat; to give food to", "shelter and feed", "feed \u2192 feeding \u2192 fed"),
 E(["tentacles","tentacle"], "Tentacle", "a long, flexible limb of certain animals", "among their tentacles"),
 E(["proposition"], "Proposition", "a statement or idea put forward for consideration", "this proposition", "propose \u2192 proposition \u2192 proposal"),
 E(["subsequently","subsequent"], "Subsequently", "afterwards; later", "subsequently proven", "subsequent \u2192 subsequently"),
 E(["conclusively","conclusive"], "Conclusively", "in a way that proves something beyond doubt", "conclusively proven", "conclude \u2192 conclusion \u2192 conclusive \u2192 conclusively"),
 E(["proven","prove"], "Prove", "to show that something is true", "proven by studies", "prove \u2192 proof \u2192 proven"),
 E(["independent"], "Independent", "not influenced or controlled by others", "independent studies", "independent \u2192 independently \u2192 independence"),
 E(["DNA sequencing","sequencing"], "Sequencing", "the process of determining the order of parts (e.g. of DNA)", "DNA sequencing", "sequence \u2192 sequencing \u2192 sequential"),
 E(["isotope analysis","isotope"], "Isotope", "a form of an element with a different atomic weight", "isotope analysis"),
 E(["analysis"], "Analysis", "detailed examination of something", "isotope analysis", "analyse \u2192 analysis \u2192 analytical \u2192 analyst"),
 E(["insights","insight"], "Insight", "a deep and accurate understanding of something", "further insights", "insight \u2192 insightful"),
 E(["identification"], "Identification", "the act of recognising or naming something", "the identification of new species", "identify \u2192 identification \u2192 identifiable"),
 E(["numerous"], "Numerous", "many; a large number of", "numerous additional species", "number \u2192 numerous \u2192 innumerable"),
 E(["additional"], "Additional", "extra; added to what exists", "additional species", "add \u2192 addition \u2192 additional"),
 E(["unknown"], "Unknown", "not known or discovered", "unknown to science", "know \u2192 known \u2192 unknown"),
 E(["issue"], "Issue (n)", "an important topic or problem", "the issue of climate change", "issue \u2192 issues"),
 E(["climate change","climate"], "Climate change", "long-term change in global or regional weather patterns", "linked to climate change", "climate \u2192 climatic"),
 E(["recorded","record"], "Record (v)", "to write down or store information for the future", "studies have recorded a growth", "record \u2192 recording \u2192 recorded"),
 E(["growth"], "Growth", "an increase in size, amount or number", "a massive growth", "grow \u2192 growth \u2192 growing"),
 E(["populations","population"], "Population", "all the individuals of a species in an area", "jellyfish populations", "populate \u2192 population \u2192 populated"),
 E(["linked","link"], "Link (v)", "to connect one thing with another", "linked to climate change", "link \u2192 linked \u2192 linkage"),
 E(["credible"], "Credible", "able to be believed; convincing", "while this may be credible", "credible \u2192 credibility \u2192 credibly"),
 E(["established","establish"], "Establish", "to prove or show something to be true", "cannot be established with certainty", "establish \u2192 established \u2192 establishment"),
 E(["certainty"], "Certainty", "the state of being completely sure", "with certainty", "certain \u2192 certainty \u2192 certainly"),
 E(["factors","factor"], "Factor", "one of the things that influence a result", "other factors", "factor \u2192 factors"),
 E(["involved","involve"], "Involve", "to include or affect as a necessary part", "other factors might be involved", "involve \u2192 involvement \u2192 involved"),
 E(["related to","related"], "Related to", "connected with or associated with", "related to this", "relate \u2192 related \u2192 relation"),
 E(["longstanding"], "Longstanding", "having existed for a long time", "the longstanding belief"),
 E(["academic"], "Academic", "relating to education, scholarship or study", "an academic belief", "academic \u2192 academy \u2192 academically"),
 E(["belief"], "Belief", "something accepted as true; an opinion", "the academic belief", "believe \u2192 belief \u2192 believable"),
 E(["predators","predator"], "Predator", "an animal that hunts and eats other animals", "jellyfish had no predators", "predator \u2192 predatory \u2192 prey"),
 E(["therefore"], "Therefore", "for that reason; as a result", "therefore there was no process"),
 E(["process"], "Process", "a natural series of changes or actions", "no natural process to limit", "process \u2192 procedure \u2192 processing"),
 E(["limit"], "Limit (v)", "to keep something within a maximum amount", "to limit their numbers", "limit \u2192 limited \u2192 limitation"),
 E(["observations","observation"], "Observation", "the act of watching carefully; a remark based on this", "observations made by the team", "observe \u2192 observation \u2192 observer"),
 E(["team"], "Team", "a group of people working together", "his team showed", "team \u2192 teamwork \u2192 teammate"),
 E(["incorrect"], "Incorrect", "not correct; wrong", "this was incorrect", "correct \u2192 incorrect \u2192 incorrectly"),
 E(["scientific community","community"], "Community", "a group of people sharing interests or characteristics", "the scientific community", "community \u2192 communal"),
 E(["recognises","recognise"], "Recognise", "to accept or acknowledge as true", "now recognises that", "recognise \u2192 recognition \u2192 recognisable"),
 E(["sharks","shark"], "Shark", "a large, often dangerous sea fish", "sharks and tuna"),
 E(["tuna"], "Tuna", "a large sea fish used for food", "tuna and swordfish"),
 E(["swordfish"], "Swordfish", "a large sea fish with a long, sword-like jaw", "tuna, swordfish and salmon"),
 E(["salmon"], "Salmon", "a large edible fish with pink flesh", "some salmon"),
 E(["prey on","prey"], "Prey on", "to hunt and kill for food", "sharks prey on jellyfish", "prey \u2192 predator \u2192 predatory"),
 E(["widely"], "Widely", "by many people; over a large area", "widely assumed", "wide \u2192 widely \u2192 widespread"),
 E(["assumed","assume"], "Assume", "to accept something as true without proof", "it is widely assumed", "assume \u2192 assumption \u2192 assumed"),
 E(["simplest","simple"], "Simple", "easy to understand; not complex", "the simplest lifeforms", "simple \u2192 simplest \u2192 simplicity \u2192 simplify"),
 E(["lifeforms","lifeform"], "Lifeform", "any living thing", "the simplest lifeforms"),
 E(["brain"], "Brain", "the organ in the head that controls thought and the body", "no brain", "brain \u2192 brainy \u2192 brainstorm"),
 E(["central nervous system","nervous system"], "Nervous system", "the network of nerves and the brain controlling the body", "no central nervous system"),
 E(["possess"], "Possess", "to have or own something", "they possess senses", "possess \u2192 possession \u2192 possessive"),
 E(["senses","sense"], "Sense (n)", "a faculty such as sight, hearing or touch", "they possess senses", "sense \u2192 sensory \u2192 sensitive"),
 E(["interact"], "Interact", "to act on or communicate with each other", "interact with their environment", "interact \u2192 interaction \u2192 interactive"),
 E(["environment"], "Environment", "the surroundings in which something lives", "their environment", "environment \u2192 environmental \u2192 environmentally"),
 E(["subtle"], "Subtle", "not obvious; delicate and hard to notice", "in subtle ways", "subtle \u2192 subtlety \u2192 subtly"),
 E(["what is more"], "What is more", "in addition; moreover", "what is more, analysis shows..."),
 E(["upside-down"], "Upside-down", "turned so that the top is at the bottom", "the upside-down jellyfish"),
 E(["shut down","shut"], "Shut down", "to stop operating or functioning", "they shut down their bodies"),
 E(["bodies","body"], "Body", "the physical structure of a person or animal", "shut down their bodies"),
 E(["rest"], "Rest (v)", "to stop activity in order to relax or recover", "rest at night", "rest \u2192 restful \u2192 restless"),
 E(["impossible"], "Impossible", "not able to happen or be done", "believed to be impossible", "possible \u2192 impossible \u2192 impossibility"),
 E(["floating","float"], "Float", "to rest or move on the surface of water without sinking", "far from floating", "float \u2192 floating \u2192 floated"),
 E(["economical"], "Economical", "using resources or energy efficiently; not wasteful", "the most economical swimmers", "economy \u2192 economical \u2192 economically"),
 E(["swimmers","swimmer"], "Swimmer", "a person or animal that swims", "economical swimmers", "swim \u2192 swimmer \u2192 swimming"),
 E(["animal kingdom"], "Animal kingdom", "all animals considered as a group", "in the animal kingdom"),
 E(["in short"], "In short", "to sum up; briefly", "in short, beliefs were wrong"),
 E(["progress"], "Progress (n)", "forward movement or improvement", "scientific progress", "progress \u2192 progressive \u2192 progression"),
 E(["inaccurate"], "Inaccurate", "not correct or exact", "beliefs were inaccurate", "accurate \u2192 inaccurate \u2192 inaccuracy"),
]
