# -*- coding: utf-8 -*-
# Passage 2 data: "Making Documentary Films" + comprehensive vocab

PARAGRAPHS = [
"For much of the twentieth century, documentary films were overshadowed by their more successful Hollywood counterparts. For a number of reasons, documentaries were frequently ignored by critics and film studies courses at universities. Firstly, the very idea of a documentary film made some people suspicious. As the critic Dr Helmut Fischer put it, 'Documentary makers might have ambitions to tell the \"truth\" and show only \"facts\" but there is no such thing as a non-fiction film. That's because, as soon as you record an incident on camera, you are altering its reality in a fundamental way'. Secondly, even supporters of documentaries could not agree on a precise definition, which did little to improve the reputation of the genre. Lastly, there were also concerns about the ethics of filming subjects without their consent, which is a necessity in many documentary films.",
"None of this prevented documentaries from being produced, though exactly when the process started is open to question. It is often claimed that Nanook of the North was the first documentary. Made by the American filmmaker Robert J. Flaherty in 1922, the film depicts the hard, sometimes heroic lives of native American peoples in the Canadian Arctic. Nanook of the North is said to have set off a trend that continued through the 1920s with the films of Dziga Vertov in the Soviet Union and works by other filmmakers around the world. However, that 1922 starting point has been disputed by supporters of an earlier date. Among this group is film historian Anthony Berwick, who argues that the genre can be traced back as early as 1895, when similar films started to appear, including newsreels, scientific films and accounts of journeys of exploration.",
"In the years following 1922, one particular style of documentary started to appear. These films adopted a serious tone while depicting the lives of actual people. Cameras were mounted on tripods and subjects rehearsed and repeated activities for the purposes of the film. British filmmaker John Grierson was an important member of this group. Grierson's career lasted nearly 40 years, beginning with Drifters (1929) and culminating with I Remember, I Remember (1968). However, by the 1960s Grierson's style of film was being rejected by the Direct Cinema movement, which wanted to produce more natural and authentic films: cameras were hand-held; no additional lighting or sound was used; and the subjects did not rehearse. According to film writer Paula Murphy, the principles and methods of Direct Cinema brought documentaries to the attention of universities and film historians as never before. Documentaries started to be recognised as a distinct genre worthy of serious scholarly analysis.",
"Starting in the 1980s, the widespread availability of first video and then digital cameras transformed filmmaking. The flexibility and low cost of these devices meant that anyone could now be a filmmaker. Amateurs working from home could compete with professionals in ways never possible before. The appearance of online film-sharing platforms in the early 2000s only increased the new possibilities for amateur filmmakers. Nonetheless, while countless amateur documentaries were being made, perhaps the most popular documentary of 2006 was still the professionally made An Inconvenient Truth. New cameras and digital platforms revolutionised the making of films. But as critic Maria Fiala has pointed out, 'The argument sometimes put forward that these innovations immediately transformed what the public expected to see in a documentary isn't entirely accurate.'",
"However, a new generation of documentary filmmakers then emerged, and with them came a new philosophy of the genre. These filmmakers moved away from highlighting political themes or urgent social issues. Instead the focus moved inwards, exploring personal lives, relationships and emotions. It could be argued that Catfish (2010) was a perfect example of this new trend. The film chronicles the everyday lives and interactions of the social media generation and was both a commercial and critical success. Filmmaker Josh Camberwell maintains that Catfish embodies a new realisation that documentaries are inherently subjective and that this should be celebrated. Says Camberwell, 'It is a requirement for documentary makers to express a particular viewpoint and give personal responses to the material they are recording.'",
"The popularity and variety of documentaries today is illustrated by the large number of film festivals focusing on the genre around the world. The biggest of all must be the Hot Docs Festival in Canada, which over the years has showcased hundreds of documentaries from more than 50 different countries. Even older is the Hamburg International Short Film Festival. As its name suggests, Hamburg specialises in short films, but one category takes this to its limits - entries may not exceed three minutes in duration. The Short and Sweet Festival is a slightly smaller event held in Utah, USA. The small size of the festival means that for first timers this is the ideal venue to try to get some recognition for their films. Then there is the Atlanta Shortsfest, which is a great event for a wide variety of filmmakers. Atlanta welcomes all established types of documentaries and recognises the growing popularity of animations, with a category specifically for films of this type. These are just a few of the scores of film festivals on offer, and there are more being established every year. All in all, it has never been easier for documentary makers to get their films in front of an audience.",
]

E = lambda hl, word, d, coll="", fam="": {"hl": hl, "word": word, "def": d, "coll": coll, "fam": fam}

ENTRIES = [
 E(["documentary films","documentary","documentaries"], "Documentary", "a film or programme giving facts about a real subject", "a documentary film", "document \u2192 documentary \u2192 documentation"),
 E(["films","film"], "Film", "a story or set of moving images recorded for cinema or TV", "make a film", "film \u2192 filming \u2192 filmmaker"),
 E(["overshadowed","overshadow"], "Overshadow", "to make something seem less important or successful", "overshadowed by Hollywood", "shadow \u2192 overshadow \u2192 overshadowed"),
 E(["successful"], "Successful", "achieving aims; popular and admired", "more successful films", "succeed \u2192 success \u2192 successful \u2192 successfully"),
 E(["counterparts","counterpart"], "Counterpart", "a person or thing that matches another in a different place or system", "their Hollywood counterparts"),
 E(["frequently"], "Frequently", "often; many times", "frequently ignored", "frequent \u2192 frequently \u2192 frequency"),
 E(["ignored","ignore"], "Ignore", "to pay no attention to something", "ignored by critics", "ignore \u2192 ignorance \u2192 ignorant"),
 E(["critics","critic"], "Critic", "a person who judges the quality of art, films, etc.", "ignored by critics", "critic \u2192 critical \u2192 criticism \u2192 criticise"),
 E(["film studies","studies","study"], "Studies", "the academic subjects or research one is engaged in", "film studies courses"),
 E(["courses","course"], "Course", "a set of lessons or lectures on a subject", "university courses"),
 E(["universities","university"], "University", "an institution of higher education and research", "courses at universities"),
 E(["suspicious"], "Suspicious", "feeling that something is wrong or not to be trusted", "made people suspicious", "suspect \u2192 suspicion \u2192 suspicious \u2192 suspiciously"),
 E(["ambitions","ambition"], "Ambition", "a strong desire to achieve something", "have ambitions to tell the truth", "ambition \u2192 ambitious \u2192 ambitiously"),
 E(["truth"], "Truth", "the quality of being true; what is true", "tell the truth", "true \u2192 truth \u2192 truthful"),
 E(["facts","fact"], "Fact", "a thing that is known to be true", "show only facts", "fact \u2192 factual \u2192 factually"),
 E(["non-fiction"], "Non-fiction", "writing or film about real facts, not invented stories", "a non-fiction film", "fiction \u2192 non-fiction \u2192 fictional"),
 E(["record"], "Record (v)", "to capture sound or images for later use", "record an incident", "record \u2192 recording \u2192 recorded"),
 E(["incident"], "Incident", "an event, especially an unusual or notable one", "record an incident", "incident \u2192 incidental \u2192 incidentally"),
 E(["camera","cameras"], "Camera", "a device for taking photographs or filming", "on camera", "camera \u2192 cameraman \u2192 camerawork"),
 E(["altering","alter"], "Alter", "to change something, often slightly", "altering its reality", "alter \u2192 alteration \u2192 altered"),
 E(["reality"], "Reality", "the true state of things; what actually exists", "altering reality", "real \u2192 reality \u2192 realistic"),
 E(["fundamental"], "Fundamental", "forming an essential base; central and important", "in a fundamental way", "fundamental \u2192 fundamentally \u2192 fundamentals"),
 E(["supporters","supporter"], "Supporter", "a person who approves of and encourages something", "supporters of documentaries", "support \u2192 supporter \u2192 supportive"),
 E(["agree"], "Agree", "to have the same opinion; to accept", "could not agree on", "agree \u2192 agreement \u2192 agreeable"),
 E(["precise"], "Precise", "exact and accurate", "a precise definition", "precise \u2192 precisely \u2192 precision"),
 E(["definition"], "Definition", "a statement of the exact meaning of a word or thing", "a precise definition", "define \u2192 definition \u2192 definitive"),
 E(["reputation"], "Reputation", "the general opinion people have about someone or something", "improve the reputation", "reputation \u2192 reputable \u2192 reputed"),
 E(["genre"], "Genre", "a category or style of art, film or writing", "the documentary genre"),
 E(["concerns","concern"], "Concern (n)", "a worry or matter of interest", "concerns about ethics", "concern \u2192 concerned \u2192 concerning"),
 E(["ethics"], "Ethics", "moral principles about right and wrong behaviour", "the ethics of filming", "ethic \u2192 ethics \u2192 ethical \u2192 ethically"),
 E(["subjects","subject"], "Subject (n)", "a person or thing being filmed, studied or discussed", "filming subjects", "subject \u2192 subjective \u2192 subjectivity"),
 E(["consent"], "Consent", "permission for something to happen", "without their consent", "consent \u2192 consensual \u2192 consenting"),
 E(["necessity"], "Necessity", "something that is needed or unavoidable", "a necessity in many films", "necessary \u2192 necessity \u2192 necessitate"),
 E(["prevented","prevent"], "Prevent", "to stop something from happening", "prevented from being produced", "prevent \u2192 prevention \u2192 preventive"),
 E(["produced","produce"], "Produce (v)", "to make or create something", "documentaries being produced", "produce \u2192 production \u2192 producer \u2192 product"),
 E(["process"], "Process", "a series of actions to achieve a result", "when the process started", "process \u2192 procedure \u2192 processing"),
 E(["open to question"], "Open to question", "uncertain; able to be doubted or debated", "the date is open to question"),
 E(["claimed","claim"], "Claim (v)", "to state something is true without proof", "it is often claimed", "claim \u2192 claimed \u2192 claimant"),
 E(["filmmaker","filmmakers"], "Filmmaker", "a person who makes films", "the American filmmaker", "film \u2192 filmmaker \u2192 filmmaking"),
 E(["depicts","depicting","depict"], "Depict", "to show or represent in a picture or film", "the film depicts hard lives", "depict \u2192 depiction \u2192 depicted"),
 E(["heroic"], "Heroic", "very brave; like a hero", "heroic lives", "hero \u2192 heroic \u2192 heroism"),
 E(["native"], "Native", "belonging to a place by birth; original to a region", "native American peoples", "native \u2192 natively \u2192 nativity"),
 E(["peoples","people"], "Peoples", "groups of people forming communities or nations", "native peoples"),
 E(["Arctic"], "Arctic", "the cold region around the North Pole", "the Canadian Arctic"),
 E(["set off","set off a trend"], "Set off", "to start or cause something to begin", "set off a trend"),
 E(["trend"], "Trend", "a general direction in which something develops", "set off a trend", "trend \u2192 trendy \u2192 trending"),
 E(["continued","continue"], "Continue", "to keep happening or doing something", "the trend continued", "continue \u2192 continuation \u2192 continuous"),
 E(["works","work"], "Works", "creative products such as films, books or art", "works by other filmmakers"),
 E(["disputed","dispute"], "Dispute (v)", "to argue that something is not true or correct", "the date has been disputed", "dispute \u2192 disputed \u2192 disputable"),
 E(["earlier","early"], "Earlier", "before in time; more in the past", "an earlier date"),
 E(["historian","historians"], "Historian", "an expert in or student of history", "a film historian", "history \u2192 historian \u2192 historical"),
 E(["traced back","trace back","traced"], "Trace back", "to find the origin of something in the past", "traced back to 1895", "trace \u2192 traceable \u2192 tracing"),
 E(["similar"], "Similar", "alike; of the same kind", "similar films", "similar \u2192 similarly \u2192 similarity"),
 E(["appear"], "Appear", "to begin to exist or be seen", "films started to appear", "appear \u2192 appearance \u2192 apparent"),
 E(["newsreels","newsreel"], "Newsreel", "a short film of news shown in cinemas in the past", "including newsreels"),
 E(["scientific"], "Scientific", "relating to or using science", "scientific films", "science \u2192 scientific \u2192 scientifically"),
 E(["accounts","account"], "Account (n)", "a written or spoken report of an event", "accounts of journeys", "account \u2192 accounts \u2192 accountable"),
 E(["journeys","journey"], "Journey", "an act of travelling from one place to another", "journeys of exploration"),
 E(["exploration"], "Exploration", "the act of travelling to discover unknown places", "journeys of exploration", "explore \u2192 exploration \u2192 explorer"),
 E(["following"], "Following", "coming after in time", "in the years following 1922"),
 E(["particular"], "Particular", "specific; relating to one thing rather than others", "one particular style", "particular \u2192 particularly \u2192 particularity"),
 E(["style"], "Style", "a distinctive manner of doing something", "a style of documentary", "style \u2192 stylish \u2192 stylistic"),
 E(["adopted","adopt"], "Adopt", "to take up or start to use (a method, attitude, etc.)", "adopted a serious tone", "adopt \u2192 adoption \u2192 adopted"),
 E(["tone"], "Tone", "the general feeling or attitude expressed", "a serious tone", "tone \u2192 tonal"),
 E(["actual"], "Actual", "existing in fact; real", "actual people", "actual \u2192 actually \u2192 actuality"),
 E(["mounted","mount"], "Mount (v)", "to fix something onto a support", "cameras mounted on tripods", "mount \u2192 mounted \u2192 mounting"),
 E(["tripods","tripod"], "Tripod", "a three-legged stand for a camera", "mounted on tripods"),
 E(["rehearsed","rehearse"], "Rehearse", "to practise something before performing it", "subjects rehearsed activities", "rehearse \u2192 rehearsal \u2192 rehearsed"),
 E(["repeated","repeat"], "Repeat", "to do or say something again", "repeated activities", "repeat \u2192 repetition \u2192 repeated \u2192 repeatedly"),
 E(["purposes","purpose"], "Purpose", "the reason for which something is done", "for the purposes of the film", "purpose \u2192 purposeful \u2192 purposely"),
 E(["career"], "Career", "a person's working life or profession", "his career lasted 40 years", "career \u2192 careerist"),
 E(["lasted","last"], "Last (v)", "to continue for a period of time", "his career lasted", "last \u2192 lasting \u2192 long-lasting"),
 E(["culminating","culminate"], "Culminate", "to reach the highest or final point", "culminating with his last film", "culminate \u2192 culmination \u2192 culminating"),
 E(["rejected","reject"], "Reject", "to refuse to accept or use", "his style was rejected", "reject \u2192 rejection \u2192 rejected"),
 E(["movement"], "Movement", "a group of people sharing ideas or aims", "the Direct Cinema movement", "move \u2192 movement \u2192 mover"),
 E(["natural"], "Natural", "existing in nature; not artificial", "more natural films", "nature \u2192 natural \u2192 naturally"),
 E(["authentic"], "Authentic", "genuine; real and true", "authentic films", "authentic \u2192 authenticity \u2192 authenticate"),
 E(["hand-held"], "Hand-held", "small enough to be held and used in the hand", "cameras were hand-held"),
 E(["additional"], "Additional", "extra; added to what already exists", "no additional lighting", "add \u2192 addition \u2192 additional \u2192 additionally"),
 E(["lighting"], "Lighting", "the arrangement or quality of light", "additional lighting", "light \u2192 lighting \u2192 lit"),
 E(["principles","principle"], "Principle", "a basic rule or belief that guides behaviour", "the principles of Direct Cinema", "principle \u2192 principled"),
 E(["methods","method"], "Method", "a way of doing something", "principles and methods", "method \u2192 methodical \u2192 methodology"),
 E(["attention"], "Attention", "notice taken of someone or something", "brought to the attention of", "attend \u2192 attention \u2192 attentive"),
 E(["recognised","recognise"], "Recognise", "to accept or acknowledge as valid or important", "recognised as a genre", "recognise \u2192 recognition \u2192 recognisable"),
 E(["distinct"], "Distinct", "clearly separate or different", "a distinct genre", "distinct \u2192 distinctly \u2192 distinction \u2192 distinctive"),
 E(["worthy"], "Worthy", "deserving of attention or respect", "worthy of analysis", "worth \u2192 worthy \u2192 worthwhile"),
 E(["scholarly"], "Scholarly", "relating to serious academic study", "scholarly analysis", "scholar \u2192 scholarly \u2192 scholarship"),
 E(["analysis"], "Analysis", "detailed examination of something", "serious analysis", "analyse \u2192 analysis \u2192 analytical \u2192 analyst"),
 E(["widespread"], "Widespread", "existing or happening over a large area or among many", "widespread availability", "wide \u2192 widespread \u2192 widely"),
 E(["availability"], "Availability", "the state of being able to be obtained or used", "the availability of cameras", "available \u2192 availability"),
 E(["digital"], "Digital", "using electronic technology that stores data as numbers", "digital cameras", "digital \u2192 digitally \u2192 digitise"),
 E(["transformed","transform"], "Transform", "to change something completely", "transformed filmmaking", "transform \u2192 transformation \u2192 transformative"),
 E(["flexibility"], "Flexibility", "the quality of being adaptable or easy to change", "the flexibility of devices", "flexible \u2192 flexibility \u2192 flexibly"),
 E(["low cost","cost"], "Cost", "the amount of money needed to buy or do something", "the low cost", "cost \u2192 costly \u2192 costing"),
 E(["devices","device"], "Device", "a tool or piece of equipment made for a purpose", "digital devices", "device \u2192 devise"),
 E(["amateurs","amateur"], "Amateur", "a person who does something for pleasure, not as a profession", "amateurs working from home", "amateur \u2192 amateurish"),
 E(["compete"], "Compete", "to try to be more successful than others", "compete with professionals", "compete \u2192 competition \u2192 competitive \u2192 competitor"),
 E(["professionals","professional","professionally"], "Professional", "a person paid and trained to do a job; done to a high standard", "compete with professionals", "profession \u2192 professional \u2192 professionally"),
 E(["appearance"], "Appearance", "the act of coming into existence or being seen", "the appearance of platforms", "appear \u2192 appearance \u2192 apparent"),
 E(["online"], "Online", "connected to or available on the internet", "online platforms"),
 E(["film-sharing","sharing"], "Sharing", "the act of letting others have or use something", "film-sharing platforms", "share \u2192 sharing \u2192 shared"),
 E(["platforms","platform"], "Platform", "an online service or system for a particular activity", "digital platforms"),
 E(["possibilities","possibility"], "Possibility", "a thing that may happen or be done", "new possibilities", "possible \u2192 possibility \u2192 possibly"),
 E(["nonetheless"], "Nonetheless", "in spite of that; nevertheless", "nonetheless, films were made"),
 E(["countless"], "Countless", "too many to count; very many", "countless documentaries", "count \u2192 countless \u2192 uncountable"),
 E(["popular"], "Popular", "liked or enjoyed by many people", "the most popular documentary", "popular \u2192 popularity \u2192 popularise"),
 E(["revolutionised","revolutionise"], "Revolutionise", "to change something completely and dramatically", "revolutionised filmmaking", "revolution \u2192 revolutionise \u2192 revolutionary"),
 E(["pointed out","point out"], "Point out", "to draw attention to a fact", "as the critic pointed out"),
 E(["argument"], "Argument", "a set of reasons given to support an idea", "the argument put forward", "argue \u2192 argument \u2192 arguable"),
 E(["put forward"], "Put forward", "to suggest or propose an idea", "the argument put forward"),
 E(["innovations","innovation"], "Innovation", "a new idea, method or device", "these innovations", "innovate \u2192 innovation \u2192 innovative"),
 E(["immediately"], "Immediately", "at once; without delay", "transformed immediately", "immediate \u2192 immediately"),
 E(["expected","expect"], "Expect", "to think or believe something will happen", "what the public expected", "expect \u2192 expectation \u2192 expected"),
 E(["entirely"], "Entirely", "completely; fully", "isn't entirely accurate", "entire \u2192 entirely \u2192 entirety"),
 E(["accurate"], "Accurate", "correct and exact; without errors", "not entirely accurate", "accurate \u2192 accuracy \u2192 accurately"),
 E(["generation"], "Generation", "all the people of about the same age or period", "a new generation", "generate \u2192 generation \u2192 generational"),
 E(["emerged","emerge"], "Emerge", "to come out or become known", "a new generation emerged", "emerge \u2192 emergence \u2192 emerging"),
 E(["philosophy"], "Philosophy", "a set of beliefs or guiding principles", "a new philosophy of the genre", "philosophy \u2192 philosophical \u2192 philosopher"),
 E(["moved away from","move away from"], "Move away from", "to stop using or doing something", "moved away from political themes"),
 E(["highlighting","highlight"], "Highlight (v)", "to give special attention to something", "highlighting political themes", "highlight \u2192 highlighted \u2192 highlighting"),
 E(["political"], "Political", "relating to government or public affairs", "political themes", "politics \u2192 political \u2192 politician"),
 E(["themes","theme"], "Theme", "the main subject or idea", "political themes", "theme \u2192 thematic \u2192 thematically"),
 E(["urgent"], "Urgent", "needing immediate attention or action", "urgent social issues", "urge \u2192 urgent \u2192 urgency"),
 E(["social issues","issues","issue"], "Issue (n)", "an important topic or problem for debate", "social issues"),
 E(["focus"], "Focus (n)", "the main centre of attention or interest", "the focus moved inwards", "focus \u2192 focused \u2192 focusing"),
 E(["exploring","explore"], "Explore", "to examine or study something in detail", "exploring personal lives", "explore \u2192 exploration \u2192 explorer"),
 E(["emotions","emotion"], "Emotion", "a strong feeling such as love or anger", "lives and emotions", "emotion \u2192 emotional \u2192 emotionally"),
 E(["argued","argue"], "Argue", "to give reasons for an opinion", "it could be argued", "argue \u2192 argument \u2192 arguably"),
 E(["chronicles","chronicle"], "Chronicle (v)", "to record events in the order they happened", "the film chronicles their lives", "chronicle \u2192 chronicler \u2192 chronological"),
 E(["interactions","interaction"], "Interaction", "communication or contact between people", "everyday interactions", "interact \u2192 interaction \u2192 interactive"),
 E(["social media"], "Social media", "websites and apps for sharing content and communicating", "the social media generation"),
 E(["commercial"], "Commercial", "relating to buying and selling; making a profit", "a commercial success", "commerce \u2192 commercial \u2192 commercially"),
 E(["critical"], "Critical", "relating to critics' judgement; expressing analysis", "a critical success", "critic \u2192 critical \u2192 critically"),
 E(["success"], "Success", "the achievement of a desired aim", "a commercial success", "succeed \u2192 success \u2192 successful"),
 E(["maintains","maintain"], "Maintain", "to state firmly that something is true", "Camberwell maintains that", "maintain \u2192 maintenance \u2192 maintained"),
 E(["embodies","embody"], "Embody", "to represent or be a clear example of an idea", "Catfish embodies a new idea", "embody \u2192 embodiment \u2192 embodied"),
 E(["realisation"], "Realisation", "the act of becoming aware of something", "a new realisation", "realise \u2192 realisation \u2192 realised"),
 E(["inherently"], "Inherently", "in a basic or permanent way; by nature", "inherently subjective", "inherent \u2192 inherently"),
 E(["subjective"], "Subjective", "based on personal feelings rather than facts", "documentaries are subjective", "subject \u2192 subjective \u2192 subjectivity"),
 E(["celebrated","celebrate"], "Celebrate", "to praise or honour; to mark with joy", "should be celebrated", "celebrate \u2192 celebration \u2192 celebrated"),
 E(["requirement"], "Requirement", "something that is needed or demanded", "it is a requirement", "require \u2192 requirement \u2192 required"),
 E(["express"], "Express (v)", "to show or state thoughts and feelings", "express a viewpoint", "express \u2192 expression \u2192 expressive"),
 E(["viewpoint"], "Viewpoint", "a particular way of thinking about something", "a particular viewpoint"),
 E(["responses","response"], "Response", "a reaction or answer to something", "personal responses", "respond \u2192 response \u2192 responsive"),
 E(["material"], "Material (n)", "information or content used for a particular purpose", "the material they record", "material \u2192 materials"),
 E(["popularity"], "Popularity", "the state of being liked by many people", "the popularity of documentaries", "popular \u2192 popularity \u2192 popularise"),
 E(["variety"], "Variety", "a number of different types of things", "the variety of documentaries", "vary \u2192 variety \u2192 various"),
 E(["illustrated","illustrate"], "Illustrate", "to show or demonstrate something clearly", "illustrated by festivals", "illustrate \u2192 illustration \u2192 illustrative"),
 E(["film festivals","festivals","festival"], "Festival", "an organised series of events celebrating something", "film festivals"),
 E(["focusing","focus on"], "Focus on", "to concentrate attention on something", "festivals focusing on the genre"),
 E(["showcased","showcase"], "Showcase (v)", "to present or display in an attractive way", "has showcased documentaries", "showcase \u2192 showcased"),
 E(["specialises","specialise"], "Specialise", "to concentrate on a particular area or activity", "Hamburg specialises in short films", "special \u2192 specialise \u2192 specialist \u2192 specialised"),
 E(["category"], "Category", "a group of things with shared features", "one category", "category \u2192 categorise \u2192 categorical"),
 E(["limits","limit"], "Limit (n)", "the greatest amount or point that is allowed", "takes this to its limits", "limit \u2192 limited \u2192 limitation"),
 E(["entries","entry"], "Entry", "a film, work or person taking part in a competition", "entries may not exceed", "enter \u2192 entry \u2192 entrant"),
 E(["exceed"], "Exceed", "to be greater than a set limit", "may not exceed three minutes", "exceed \u2192 excessive \u2192 excess"),
 E(["duration"], "Duration", "the length of time something lasts", "three minutes in duration", "endure \u2192 duration \u2192 durable"),
 E(["slightly"], "Slightly", "to a small degree; a little", "a slightly smaller event", "slight \u2192 slightly"),
 E(["event"], "Event", "a planned public or social occasion", "a smaller event", "event \u2192 eventful \u2192 eventual"),
 E(["ideal"], "Ideal", "the best possible; perfect for a purpose", "the ideal venue", "ideal \u2192 ideally \u2192 idealise"),
 E(["venue"], "Venue", "the place where an event happens", "the ideal venue"),
 E(["recognition"], "Recognition", "public acknowledgement of achievement", "get some recognition", "recognise \u2192 recognition \u2192 recognisable"),
 E(["welcomes","welcome"], "Welcome (v)", "to accept or receive gladly", "Atlanta welcomes all types", "welcome \u2192 welcoming \u2192 welcomed"),
 E(["established"], "Established", "accepted and recognised; long in existence", "established types", "establish \u2192 established \u2192 establishment"),
 E(["animations","animation"], "Animation", "a film made from drawings or models that seem to move", "the popularity of animations", "animate \u2192 animation \u2192 animated"),
 E(["specifically"], "Specifically", "for a particular purpose; precisely", "a category specifically for", "specific \u2192 specifically \u2192 specify"),
 E(["scores of","scores"], "Scores of", "very many; large numbers of", "scores of festivals"),
 E(["on offer"], "On offer", "available to be used, bought or chosen", "festivals on offer"),
 E(["audience"], "Audience", "the people who watch or listen to something", "in front of an audience", "audience \u2192 audio \u2192 auditorium"),
]
