# -*- coding: utf-8 -*-
# Test 4 Reading: 3 passages + comprehensive vocab (elementary -> advanced)
E = lambda hl, word, d, coll="", fam="": {"hl": hl, "word": word, "def": d, "coll": coll, "fam": fam}

P1_PARAS = [
"As Katherine Sheen rested on the banks of Hensham river on 3 August 2005, her gaze fell upon a small, dirt-covered object amongst a tangle of tree roots. Cleaning away the soil, she realised it was a leather pouch. It fell apart as Katherine opened it, and the items inside fell to the ground. Although her university degree had merely touched on the Roman occupation of ancient Britain, providing a very general overview of everyday activities, once she'd rubbed off some of the dirt, Katherine immediately identified the coins in her hand as coming from that era. Despite their discoloration, Katherine had no doubt they were historically significant. As soon as she got home, she informed the police of her find.",
"That might have been the end of the story - except for the fact that the farmer who owned the adjacent field then mentioned the lines of large stones his plough kept running into. By mid-August, with the farmer's permission, a team of archaeologists, led by Professor Kevin Durrand, were camped out in the field. Durrand had previously worked on other projects where pieces of ancient pottery and the discovery of an old sword had led archaeologists to unearth sizeable Roman settlements. He was keen to start excavations at Hensham, and had got funding for a three-month dig. What his team eventually discovered, three weeks into excavations, were the remains of the outer walls of a Roman villa. As many Romans in Britain simply lived in wooden houses with thatched roofs, the family that occupied the villa must have been very wealthy. As the team continued their work, they looked for evidence that might indicate whether the villa had been attacked and purposely demolished, or fallen into such a poor state that it eventually collapsed. Looking at the way a set of slate roof tiles had fallen to the ground, they decided on the latter. What caused the noble Roman family and their servants to abandon the villa remains open to speculation.",
"Another find was six blue beads, crafted from glass, which the archaeologists speculated were part of a necklace. Durrand has previously found gold bracelets on other sites, but for him the beads are no less significant. 'Every find contributes to the story,' he says. On the outer western wall, the archaeologists uncovered a number of foundation stones. On one is carved what the archaeologists made out to be a Latin inscription. But as the stone itself has endured centuries of erosion, the team has yet to work out what it says. Another find was a section of traditional Roman mosaic. Although incomplete, enough pieces remain to show a geometrical pattern and stylised fish. From this, Durrand assumes that a bath house would have been a feature of the villa. While his team have so far not found any hard proof of this, Durrand is confident it will turn out to be the case.",
"Something that the team are particularly excited about is evidence of a heating system, which would have served the Roman family and their visitors well in winter months. Although much of the system has long since crumbled at Hensham, Durrand and his team believe it would have been based on a typical Roman hypocaust; they have created a model for visitors to see. The furnace that produced the hot air needed to be kept burning all the time, a task that would have fallen to the villa's slaves. As large branches would have taken too long to produce the heat required, it is more likely that twigs would have been gathered from surrounding woodland instead. Another fuel source used in some Roman hypocausts was charcoal, but evidence for this at Hensham has not presented itself. The underfloor space was made by setting the floor on top of piles of square stones. Known as pilae, these stones stood approximately two feet high. The gap this created meant that the hot air coming out of the furnace was not trapped and restricted. Instead its distribution around the pilae and under the floor was free flowing.",
"Floor tiles were not placed directly onto the pilae but separated by a layer of concrete, or at least a primitive version of it. This would have made the whole structure more solid, and helped reduce the risk of fire spreading to upper levels. The walls of the rooms above the heating system were made of bricks, but the key point here is that they were hollow, in order to allow heat to rise around the rooms and provide insulation. Some have been recovered from the Hensham villa and are now undergoing preservation treatment. Another feature of the heating system that archaeologists have identified at Hensham was its clay pipes. These were cleverly built into the wall so as not to take up space. The principal reason for including the pipes was to let out air through a vent in the roof once it had cooled down. What the Romans may not have realised, however, was that gas produced by the burning fuel was expelled in this way too. In high doses, it could have been lethal if it had leaked into the upper levels.",
"Inside the rooms in the villa, a layer of plaster would have been applied to the walls and painted in rich colours. Sadly, none of the original plaster at Hensham still exists. However, some of the tiles that the family would have walked on have survived. They would certainly have felt warm underfoot and helped generate an indoor climate that the family could relax in. In its day, the Hensham hypocaust would have been a remarkable piece of engineering.",
]

P1_ENTRIES = [
 E(["rested","rest"], "Rest (v)", "to stop activity to relax or recover", "rested on the banks", "rest \u2192 restful \u2192 rested"),
 E(["banks","bank"], "Bank (of a river)", "the land along the side of a river", "the banks of the river"),
 E(["gaze"], "Gaze (n)", "a long, steady look", "her gaze fell upon", "gaze \u2192 gazing"),
 E(["fell upon","fell"], "Fall upon", "to come to notice; to land on", "her gaze fell upon an object", "fall \u2192 fell \u2192 fallen"),
 E(["dirt-covered","dirt"], "Dirt-covered", "covered in dust or earth", "a dirt-covered object", "dirt \u2192 dirty \u2192 dirtied"),
 E(["object"], "Object (n)", "a thing that can be seen or touched", "a small object"),
 E(["tangle"], "Tangle (n)", "a confused, twisted mass", "a tangle of tree roots", "tangle \u2192 tangled \u2192 entangle"),
 E(["roots","root"], "Root", "the part of a plant that grows underground", "tree roots", "root \u2192 rooted \u2192 rooting"),
 E(["soil"], "Soil", "the top layer of earth in which plants grow", "cleaning away the soil"),
 E(["realised","realise"], "Realise", "to become aware of something", "she realised it was leather", "realise \u2192 realisation \u2192 realised"),
 E(["leather"], "Leather", "material made from animal skin", "a leather pouch", "leather \u2192 leathery"),
 E(["pouch"], "Pouch", "a small bag", "a leather pouch"),
 E(["fell apart","fall apart"], "Fall apart", "to break into pieces", "it fell apart", "fall \u2192 fell \u2192 fallen"),
 E(["items","item"], "Item", "a single thing in a list or group", "the items inside", "item \u2192 itemise"),
 E(["degree"], "Degree", "a qualification from a university", "her university degree"),
 E(["merely"], "Merely", "only; just", "had merely touched on", "mere \u2192 merely"),
 E(["touched on","touch on"], "Touch on", "to mention or deal with briefly", "touched on the Roman occupation"),
 E(["occupation"], "Occupation (of a land)", "the control of an area by a foreign power", "the Roman occupation", "occupy \u2192 occupation \u2192 occupied"),
 E(["ancient"], "Ancient", "very old; from the distant past", "ancient Britain", "ancient \u2192 antiquity"),
 E(["overview"], "Overview", "a general summary or description", "a general overview", "overview \u2192 overviews"),
 E(["everyday"], "Everyday", "ordinary; happening daily", "everyday activities"),
 E(["rubbed off","rub off","rub"], "Rub off", "to remove by rubbing", "rubbed off the dirt", "rub \u2192 rubbed \u2192 rubbing"),
 E(["immediately"], "Immediately", "at once; without delay", "immediately identified the coins", "immediate \u2192 immediately"),
 E(["identified","identify"], "Identify", "to recognise and name something", "identified the coins", "identify \u2192 identification \u2192 identifiable"),
 E(["coins","coin"], "Coin", "a piece of metal money", "the coins in her hand"),
 E(["era"], "Era", "a long, distinct period of history", "coming from that era"),
 E(["discoloration"], "Discoloration", "a change or spoiling of colour", "despite their discoloration", "colour \u2192 discolour \u2192 discoloration"),
 E(["no doubt","doubt"], "No doubt", "certainly; without question", "she had no doubt", "doubt \u2192 doubtful \u2192 undoubtedly"),
 E(["historically","historical"], "Historically", "in relation to history", "historically significant", "history \u2192 historical \u2192 historically"),
 E(["significant"], "Significant", "important; meaningful", "historically significant", "signify \u2192 significant \u2192 significance"),
 E(["informed","inform"], "Inform", "to tell someone about something officially", "she informed the police", "inform \u2192 information \u2192 informant"),
 E(["find"], "Find (n)", "something valuable or interesting that is discovered", "her find"),
 E(["farmer"], "Farmer", "a person who manages or works on a farm", "the farmer who owned the field", "farm \u2192 farmer \u2192 farming"),
 E(["owned","own"], "Own (v)", "to possess something", "the farmer who owned the field", "own \u2192 owner \u2192 ownership"),
 E(["adjacent"], "Adjacent", "next to or near something", "the adjacent field", "adjacent \u2192 adjacency"),
 E(["mentioned","mention"], "Mention", "to refer to something briefly", "he mentioned the stones", "mention \u2192 mentioned \u2192 mentioning"),
 E(["plough"], "Plough (n)", "a farming tool for turning over soil", "his plough kept running into stones"),
 E(["running into","run into"], "Run into", "to hit or come up against", "his plough kept running into stones"),
 E(["permission"], "Permission", "official consent to do something", "with the farmer's permission", "permit \u2192 permission \u2192 permissible"),
 E(["team"], "Team", "a group working together", "a team of archaeologists", "team \u2192 teamwork \u2192 teammate"),
 E(["archaeologists","archaeologist"], "Archaeologist", "a scientist who studies the past from remains", "a team of archaeologists", "archaeology \u2192 archaeologist \u2192 archaeological"),
 E(["led by","led","lead"], "Led by", "guided or directed by", "led by Professor Durrand", "lead \u2192 led \u2192 leader"),
 E(["camped out","camped","camp"], "Camp out", "to live or stay outdoors in a camp", "camped out in the field", "camp \u2192 camped \u2192 camping"),
 E(["previously"], "Previously", "before now; in the past", "had previously worked", "previous \u2192 previously"),
 E(["projects","project"], "Project", "a planned piece of work", "other projects", "project \u2192 projection"),
 E(["pottery"], "Pottery", "objects made of baked clay", "ancient pottery", "pottery \u2192 potter"),
 E(["discovery"], "Discovery", "the act of finding something", "the discovery of a sword", "discover \u2192 discovery \u2192 discovered"),
 E(["sword"], "Sword", "a weapon with a long metal blade", "an old sword"),
 E(["unearth"], "Unearth", "to dig up or uncover from the ground", "to unearth settlements", "earth \u2192 unearth \u2192 unearthed"),
 E(["sizeable"], "Sizeable", "fairly large", "sizeable Roman settlements", "size \u2192 sizeable"),
 E(["settlements","settlement"], "Settlement", "a place where people have established a community", "Roman settlements", "settle \u2192 settlement \u2192 settler"),
 E(["keen to","keen"], "Keen to", "very eager to do something", "keen to start excavations", "keen \u2192 keenly \u2192 keenness"),
 E(["excavations","excavation","excavate"], "Excavation", "the act of digging to uncover remains", "start excavations", "excavate \u2192 excavation \u2192 excavator"),
 E(["funding","fund"], "Funding", "money provided for a purpose", "funding for a dig", "fund \u2192 funding \u2192 funded"),
 E(["dig"], "Dig (n)", "an organised archaeological excavation", "a three-month dig", "dig \u2192 dug \u2192 digging"),
 E(["eventually"], "Eventually", "in the end; after some time", "eventually discovered", "eventual \u2192 eventually"),
 E(["remains"], "Remains (n)", "the parts left after something is destroyed", "the remains of the walls"),
 E(["outer"], "Outer", "on the outside; external", "the outer walls", "out \u2192 outer \u2192 outermost"),
 E(["walls","wall"], "Wall", "an upright structure enclosing an area", "the outer walls"),
 E(["villa"], "Villa", "a large country house, especially Roman", "a Roman villa"),
 E(["wooden"], "Wooden", "made of wood", "wooden houses", "wood \u2192 wooden"),
 E(["thatched","thatch"], "Thatched", "covered with a roof of straw or reeds", "thatched roofs", "thatch \u2192 thatched"),
 E(["roofs","roof"], "Roof", "the top covering of a building", "thatched roofs"),
 E(["occupied","occupy"], "Occupy", "to live in or use a space", "the family that occupied the villa", "occupy \u2192 occupation \u2192 occupant"),
 E(["wealthy"], "Wealthy", "having a lot of money; rich", "must have been wealthy", "wealth \u2192 wealthy \u2192 wealthier"),
 E(["continued","continue"], "Continue", "to keep doing something", "as the team continued", "continue \u2192 continuation \u2192 continuous"),
 E(["evidence"], "Evidence", "facts or signs showing what is true", "looked for evidence", "evident \u2192 evidence \u2192 evidently"),
 E(["indicate"], "Indicate", "to show or point to something", "evidence that might indicate", "indicate \u2192 indication \u2192 indicator"),
 E(["attacked","attack"], "Attack (v)", "to act violently against someone or something", "the villa had been attacked", "attack \u2192 attacker \u2192 attacked"),
 E(["purposely","purpose"], "Purposely", "on purpose; deliberately", "purposely demolished", "purpose \u2192 purposely \u2192 purposeful"),
 E(["demolished","demolish"], "Demolish", "to pull or knock down a building", "purposely demolished", "demolish \u2192 demolition \u2192 demolished"),
 E(["poor state","state"], "State (n)", "the condition of something", "a poor state", "state \u2192 stated"),
 E(["collapsed","collapse"], "Collapse", "to fall down suddenly", "it eventually collapsed", "collapse \u2192 collapsed \u2192 collapsing"),
 E(["slate"], "Slate", "a grey rock that splits into thin sheets", "slate roof tiles"),
 E(["tiles","tile"], "Tile", "a thin flat piece used to cover roofs or floors", "roof tiles", "tile \u2192 tiled \u2192 tiling"),
 E(["the latter","latter"], "The latter", "the second of two things mentioned", "they decided on the latter", "former \u2192 latter"),
 E(["noble"], "Noble", "belonging to the highest social class", "the noble Roman family", "noble \u2192 nobility \u2192 nobleman"),
 E(["servants","servant"], "Servant", "a person employed to do household work", "their servants", "serve \u2192 servant"),
 E(["abandon"], "Abandon", "to leave a place permanently", "to abandon the villa", "abandon \u2192 abandonment \u2192 abandoned"),
 E(["open to speculation","speculation","speculated","speculate"], "Speculation", "the forming of opinions without firm evidence", "remains open to speculation", "speculate \u2192 speculation \u2192 speculative"),
 E(["beads","bead"], "Bead", "a small, often round object with a hole, used in jewellery", "six blue beads"),
 E(["crafted","craft"], "Crafted", "made skilfully by hand", "crafted from glass", "craft \u2192 crafted \u2192 craftsman"),
 E(["glass"], "Glass", "a hard, transparent material", "crafted from glass"),
 E(["necklace"], "Necklace", "a piece of jewellery worn around the neck", "part of a necklace"),
 E(["bracelets","bracelet"], "Bracelet", "a piece of jewellery worn around the wrist", "gold bracelets"),
 E(["sites","site"], "Site", "a place where something is located or done", "other sites"),
 E(["contributes","contribute"], "Contribute", "to add to or help with something", "every find contributes", "contribute \u2192 contribution \u2192 contributor"),
 E(["uncovered","uncover"], "Uncover", "to discover or reveal something hidden", "uncovered foundation stones", "cover \u2192 uncover \u2192 uncovered"),
 E(["foundation"], "Foundation", "the solid base on which a building rests", "foundation stones", "found \u2192 foundation \u2192 foundational"),
 E(["carved","carve"], "Carve", "to cut a shape or words into hard material", "carved into the stone", "carve \u2192 carving \u2192 carved"),
 E(["made out to be","made out"], "Make out", "to manage to see or understand with difficulty", "what they made out to be Latin"),
 E(["Latin"], "Latin", "the language of ancient Rome", "a Latin inscription"),
 E(["inscription"], "Inscription", "words carved or written on a surface", "a Latin inscription", "inscribe \u2192 inscription"),
 E(["endured","endure"], "Endure", "to suffer or last through something difficult", "endured centuries of erosion", "endure \u2192 endurance \u2192 enduring"),
 E(["erosion"], "Erosion", "the gradual wearing away of a surface", "centuries of erosion", "erode \u2192 erosion \u2192 eroded"),
 E(["work out"], "Work out", "to find the answer by thinking", "to work out what it says"),
 E(["section"], "Section", "a part of something larger", "a section of mosaic", "section \u2192 sectional"),
 E(["mosaic"], "Mosaic", "a picture made of small pieces of coloured stone", "a Roman mosaic"),
 E(["incomplete"], "Incomplete", "not finished; lacking some parts", "although incomplete", "complete \u2192 incomplete \u2192 incompletely"),
 E(["geometrical"], "Geometrical", "made of regular lines and shapes", "a geometrical pattern", "geometry \u2192 geometrical \u2192 geometric"),
 E(["stylised","stylise"], "Stylised", "represented in a simplified, artistic way", "stylised fish", "style \u2192 stylise \u2192 stylised"),
 E(["assumes","assume"], "Assume", "to suppose something is true without proof", "Durrand assumes", "assume \u2192 assumption \u2192 assumed"),
 E(["bath house"], "Bath house", "a building containing baths for washing", "a bath house"),
 E(["feature"], "Feature (n)", "a distinctive part or characteristic", "a feature of the villa", "feature \u2192 featured \u2192 featuring"),
 E(["hard proof","proof"], "Proof", "evidence that shows something is true", "no hard proof", "prove \u2192 proof \u2192 proven"),
 E(["confident"], "Confident", "feeling sure about something", "Durrand is confident", "confidence \u2192 confident \u2192 confidently"),
 E(["turn out","turn out to be the case"], "Turn out", "to prove to be the case in the end", "it will turn out to be the case"),
 E(["particularly"], "Particularly", "especially; more than usual", "particularly excited", "particular \u2192 particularly"),
 E(["heating system","heating"], "Heating system", "equipment that warms a building", "evidence of a heating system", "heat \u2192 heating \u2192 heated"),
 E(["served","serve"], "Serve", "to be useful to; to provide for", "served the family well", "serve \u2192 service \u2192 server"),
 E(["visitors","visitor"], "Visitor", "a person who visits a place", "the family and their visitors", "visit \u2192 visitor \u2192 visiting"),
 E(["crumbled","crumble"], "Crumble", "to break into small pieces; to fall apart", "the system has crumbled", "crumble \u2192 crumbled \u2192 crumbling"),
 E(["typical"], "Typical", "having the usual qualities of a type", "a typical Roman hypocaust", "type \u2192 typical \u2192 typically"),
 E(["hypocaust"], "Hypocaust", "an ancient Roman under-floor heating system", "a Roman hypocaust"),
 E(["model"], "Model (n)", "a small copy or representation of something", "a model for visitors"),
 E(["furnace"], "Furnace", "an enclosed space for producing great heat", "the furnace produced hot air"),
 E(["burning","burn"], "Burning", "being on fire; producing heat by fire", "kept burning", "burn \u2192 burning \u2192 burned"),
 E(["task"], "Task", "a piece of work to be done", "a task for the slaves", "task \u2192 tasks"),
 E(["slaves","slave"], "Slave", "a person owned by and forced to work for another", "the villa's slaves", "slave \u2192 slavery \u2192 enslave"),
 E(["branches","branch"], "Branch", "a part of a tree growing from the trunk", "large branches"),
 E(["twigs","twig"], "Twig", "a small thin branch of a tree", "twigs were gathered"),
 E(["gathered","gather"], "Gather", "to collect things from various places", "twigs were gathered", "gather \u2192 gathering \u2192 gathered"),
 E(["surrounding","surround"], "Surrounding", "all around a place", "surrounding woodland", "surround \u2192 surrounding \u2192 surrounded"),
 E(["woodland"], "Woodland", "land covered with trees", "surrounding woodland", "wood \u2192 woodland"),
 E(["fuel"], "Fuel", "material burned to produce heat or power", "another fuel source", "fuel \u2192 fuelled \u2192 fuelling"),
 E(["charcoal"], "Charcoal", "a black fuel made by burning wood slowly", "fuel such as charcoal"),
 E(["presented itself","present"], "Present itself", "to appear or become available", "evidence has not presented itself"),
 E(["underfloor"], "Underfloor", "located beneath the floor", "the underfloor space"),
 E(["piles","pile"], "Pile", "a number of things lying one on top of another", "piles of stones", "pile \u2192 piled \u2192 piling"),
 E(["square"], "Square (adj)", "having four equal straight sides", "square stones"),
 E(["approximately","approximate"], "Approximately", "about; roughly", "approximately two feet high", "approximate \u2192 approximately \u2192 approximation"),
 E(["gap"], "Gap", "an empty space between things", "the gap this created"),
 E(["trapped","trap"], "Trapped", "kept in a place with no way out", "the air was not trapped", "trap \u2192 trapped \u2192 trapping"),
 E(["restricted","restrict"], "Restricted", "limited or controlled", "trapped and restricted", "restrict \u2192 restriction \u2192 restricted"),
 E(["distribution"], "Distribution", "the way something is spread out", "the distribution of air", "distribute \u2192 distribution \u2192 distributor"),
 E(["free flowing","flowing","flow"], "Free flowing", "moving freely without blockage", "the air was free flowing", "flow \u2192 flowing \u2192 flowed"),
 E(["placed","place"], "Place (v)", "to put something in a position", "tiles were placed onto the pilae", "place \u2192 placed \u2192 placement"),
 E(["directly","direct"], "Directly", "in a straight line; without anything between", "placed directly onto", "direct \u2192 directly \u2192 direction"),
 E(["separated","separate"], "Separate (v)", "to keep or set apart", "separated by concrete", "separate \u2192 separation \u2192 separated"),
 E(["layer"], "Layer", "a thickness of material covering a surface", "a layer of concrete", "layer \u2192 layered \u2192 layering"),
 E(["concrete"], "Concrete (n)", "a hard building material of cement and stone", "a layer of concrete"),
 E(["primitive"], "Primitive", "simple and basic; from an early stage", "a primitive version", "primitive \u2192 primitively"),
 E(["solid"], "Solid", "firm and strong; not hollow", "more solid", "solid \u2192 solidly \u2192 solidify"),
 E(["reduce the risk","risk"], "Reduce the risk", "to make a danger less likely", "reduce the risk of fire"),
 E(["spreading","spread"], "Spread (v)", "to extend over a wider area", "fire spreading to upper levels", "spread \u2192 spreading"),
 E(["upper levels","levels","level"], "Level (n)", "a floor or layer of a building", "the upper levels"),
 E(["bricks","brick"], "Brick", "a block of baked clay used for building", "made of bricks"),
 E(["key point","key"], "Key (adj)", "most important", "the key point", "key \u2192 keys"),
 E(["hollow"], "Hollow", "having an empty space inside", "they were hollow", "hollow \u2192 hollowed"),
 E(["rise"], "Rise (v)", "to move upward", "allow heat to rise", "rise \u2192 rising \u2192 risen"),
 E(["insulation"], "Insulation", "material that prevents heat loss", "provide insulation", "insulate \u2192 insulation \u2192 insulated"),
 E(["recovered","recover"], "Recover", "to get back or retrieve something", "some have been recovered", "recover \u2192 recovery \u2192 recovered"),
 E(["undergoing","undergo"], "Undergo", "to experience or be subjected to", "undergoing treatment", "undergo \u2192 underwent \u2192 undergone"),
 E(["preservation"], "Preservation", "the act of keeping something in good condition", "preservation treatment", "preserve \u2192 preservation \u2192 preserved"),
 E(["clay pipes","pipes","pipe"], "Pipe", "a tube through which liquid or gas flows", "clay pipes"),
 E(["cleverly","clever"], "Cleverly", "in a skilful or intelligent way", "cleverly built into the wall", "clever \u2192 cleverly \u2192 cleverness"),
 E(["take up","take up space"], "Take up", "to use or occupy space", "so as not to take up space"),
 E(["principal"], "Principal (adj)", "main; most important", "the principal reason", "principal \u2192 principally"),
 E(["let out"], "Let out", "to allow to escape or come out", "to let out air"),
 E(["vent"], "Vent", "an opening allowing air or gas to pass", "a vent in the roof"),
 E(["cooled down","cool down","cool"], "Cool down", "to become less hot", "once it had cooled down", "cool \u2192 cooled \u2192 cooling"),
 E(["gas"], "Gas", "an air-like substance, often produced by burning", "gas produced by the fuel"),
 E(["expelled","expel"], "Expel", "to force or drive out", "gas was expelled", "expel \u2192 expulsion \u2192 expelled"),
 E(["doses","dose"], "Dose", "a measured amount of something", "in high doses", "dose \u2192 dosage"),
 E(["lethal"], "Lethal", "able to cause death; deadly", "could have been lethal", "lethal \u2192 lethally"),
 E(["leaked","leak"], "Leak (v)", "to escape through a hole or crack", "if it had leaked", "leak \u2192 leakage \u2192 leaking"),
 E(["plaster"], "Plaster (n)", "a soft mixture spread on walls to make them smooth", "a layer of plaster"),
 E(["applied","apply"], "Apply", "to put or spread something onto a surface", "plaster applied to the walls", "apply \u2192 application \u2192 applied"),
 E(["painted","paint"], "Paint (v)", "to cover with paint or make a picture", "painted in rich colours", "paint \u2192 painting \u2192 painted"),
 E(["rich colours","rich"], "Rich (colour)", "deep and strong in colour", "rich colours", "rich \u2192 richly \u2192 richness"),
 E(["original"], "Original", "existing from the beginning; first", "the original plaster", "origin \u2192 original \u2192 originally"),
 E(["exists","exist"], "Exist", "to be present or real", "none still exists", "exist \u2192 existence \u2192 existing"),
 E(["survived","survive"], "Survive", "to continue to exist or live", "some tiles have survived", "survive \u2192 survival \u2192 survivor"),
 E(["underfoot"], "Underfoot", "under one's feet; on the ground", "warm underfoot"),
 E(["generate"], "Generate", "to produce or create", "helped generate a climate", "generate \u2192 generation \u2192 generator"),
 E(["indoor"], "Indoor", "located or done inside a building", "an indoor climate", "indoor \u2192 indoors"),
 E(["climate"], "Climate", "the general conditions of an environment", "an indoor climate", "climate \u2192 climatic"),
 E(["relax"], "Relax", "to rest and become less tense", "the family could relax", "relax \u2192 relaxation \u2192 relaxed"),
 E(["remarkable"], "Remarkable", "extraordinary; worthy of attention", "a remarkable piece of engineering", "remark \u2192 remarkable \u2192 remarkably"),
 E(["engineering"], "Engineering", "the design and building of structures or machines", "a piece of engineering", "engineer \u2192 engineering"),
]


P2_PARAS = [
"An area of scientific study that caught the public imagination during the 1970s involved a gorilla called Koko. Animal psychologist Francine Patterson claimed to have taught Koko a simplified form of American Sign Language, and through signing, Koko could apparently communicate basic ideas such as 'food' and 'more', as well as concepts such as 'good' and 'sorry'. But Koko also used signs to blame other people for damage she had caused herself. While today there is some dispute about whether Koko truly understood the meaning of all the signs she made, Professor Karen Goodger believes she was certainly capable of dishonesty. 'People use words to lie, but for animals with higher brain functions, there's also a higher probability that they'll demonstrate manipulative behaviours. We see this not just in gorillas, but in other creatures with a large neocortex.'",
"Human societies may appear to disapprove of lying, but that doesn't mean we don't all do it. And it seems that the ability, or at least the desire to deceive, starts from an early age. In one study run by psychologist Kang Lee, children were individually brought into a laboratory and asked to face a wall. They were asked to guess what toy one of Lee's fellow researchers had placed on a table behind them - for example, a fluffy cat or dog. The researcher would then announce they had to leave the lab to take a phone call, reminding the child not to turn around. The research team were well aware that many children would be unable to resist peeking at the toy. Secret cameras showed that 30% of two-year-old children lied about not looking. This went up to 50% for three-year-olds and almost 80% of eight-year-olds. Interestingly, whereas the younger children simply named the toy and denied taking a peek, the older ones came up with some interesting reasons to explain how they had identified the toy correctly. Lee is reassured by this trend, seeing it as evidence in each case that the cognitive growth of a human child is progressing as it should. Parents, of course, may not be so pleased.",
"Adults, however, can hardly criticise children. According to Professor Richard Wiseman, it appears that adults typically tell two major lies per day, and that one third of adult conversations contain an element of dishonesty. Other research indicates that spouses lie in one out of every 10 interactions. This probably comes as no surprise to Tali Sharot at University College London, who has run a series of experiments proving we become desensitised to lying over time. She has found that while we might initially experience a sense of shame about small lies, this feeling eventually wears off. The result, Sharot has found, is that we progress to more serious ones.",
"Other researchers, including Tim Levine at the University of Alabama, have analysed our motives for lying. By far the most common is our desire to cover up our own wrongdoing. Second to this are lies we tell to gain economic advantage - we might lie during an interview to increase the chances of getting a job. Interestingly, 'white lies', the kind we tell to avoid hurting people's feelings, account only for a small percentage of our untruths. But if we recognise our own tendency to lie, why don't we recognise it in others? Professor Goodger thinks it has something to do with our strong desire for certain information we hear to be true, even when we might suspect it isn't. This is because we might be 'comforted by others' lies or excited by the promise of a good outcome', Goodger says.",
"We might not expect ordinary people to be good at recognising lies, but what about people whose job it is to investigate the behaviour of others? Paul Ekman is a psychologist from the University of California. As part of his research into deception, he has invited a range of experts to view videos of people telling lies and of others telling the truth. Among the experts have been judges, psychiatrists and people who operate polygraph machines for police investigations. None of these experts have shown they can detect dishonesty any better than people without their experience. Part of the problem is that so many myths still prevail about 'give-away signs' indicating that someone is lying.",
"A common claim, for example, is that liars won't look people in the eye during their explanations or while being questioned. Another is that they are likely to gesture as they tell their story, but so frequently that it seems unnatural - as if they are trying to convince others of their sincerity. However, many researchers have come to reject these ideas, suggesting a more effective approach is to listen to their narration style. A difficulty that liars face is having to remember exactly what they said, which is why they don't provide as many details as a person giving an honest account would. It is also typical of liars to mentally rehearse their story, and this is why one stage follows another in apparently chronological fashion. Honest stories, however, feature revisions and repetition. Recent research has also disproved the widely believed notion that liars have a habit of fidgeting in their seats. Rather, it seems that they keep still, especially in the upper body, possibly hoping to give the impression of self-assurance. Liars also put some psychological distance between themselves and their lies. For that reason, they avoid the use of 'I' when narrating their stories. The reverse is true, however, when people write fake reviews of, say, a hotel or restaurant. In these instances, 'I' features again and again as they attempt to convince us that their experience was real.",
]

P2_ENTRIES = [
 E(["scientific study","study"], "Study (n)", "a piece of detailed research", "an area of scientific study", "study \u2192 studies \u2192 studied"),
 E(["caught the public imagination","imagination"], "Capture the imagination", "to attract strong interest and excitement", "caught the public imagination"),
 E(["involved","involve"], "Involve", "to include as a necessary part", "study that involved a gorilla", "involve \u2192 involvement \u2192 involved"),
 E(["gorilla"], "Gorilla", "the largest of the apes", "a gorilla called Koko"),
 E(["psychologist"], "Psychologist", "a scientist who studies the mind and behaviour", "animal psychologist", "psychology \u2192 psychologist \u2192 psychological"),
 E(["claimed","claim"], "Claim (v)", "to state something as true without proof", "claimed to have taught Koko", "claim \u2192 claimed \u2192 claimant"),
 E(["simplified","simplify"], "Simplified", "made easier or less complex", "a simplified form of language", "simple \u2192 simplify \u2192 simplified"),
 E(["Sign Language","signing","signs","sign"], "Sign language", "communication using hand movements", "American Sign Language"),
 E(["apparently","apparent"], "Apparently", "according to what seems true", "could apparently communicate", "apparent \u2192 apparently"),
 E(["communicate"], "Communicate", "to share information or ideas", "communicate basic ideas", "communicate \u2192 communication \u2192 communicative"),
 E(["concepts","concept"], "Concept", "an abstract idea", "concepts such as 'good'", "concept \u2192 conceptual \u2192 conceptualise"),
 E(["blame"], "Blame (v)", "to hold someone responsible for something bad", "to blame other people", "blame \u2192 blameless \u2192 blamed"),
 E(["damage"], "Damage (n)", "physical harm reducing value or function", "damage she had caused", "damage \u2192 damaging \u2192 damaged"),
 E(["caused","cause"], "Cause (v)", "to make something happen", "damage she had caused", "cause \u2192 caused \u2192 causing"),
 E(["dispute"], "Dispute (n)", "a disagreement or argument", "some dispute about it", "dispute \u2192 disputed \u2192 disputable"),
 E(["truly","true"], "Truly", "genuinely; really", "whether Koko truly understood", "true \u2192 truly \u2192 truth"),
 E(["meaning"], "Meaning", "what something signifies or represents", "the meaning of the signs", "mean \u2192 meaning \u2192 meaningful"),
 E(["capable of","capable"], "Capable of", "having the ability to do something", "capable of dishonesty", "capable \u2192 capability \u2192 capably"),
 E(["dishonesty"], "Dishonesty", "the quality of not being truthful", "capable of dishonesty", "honest \u2192 dishonesty \u2192 dishonest"),
 E(["lie"], "Lie (v)", "to say something untrue deliberately", "people use words to lie", "lie \u2192 liar \u2192 lying"),
 E(["brain functions","functions","function"], "Function (n)", "the natural purpose or activity of something", "higher brain functions", "function \u2192 functional \u2192 functioning"),
 E(["probability"], "Probability", "the likelihood of something happening", "a higher probability", "probable \u2192 probability \u2192 probably"),
 E(["demonstrate"], "Demonstrate", "to show clearly by example", "demonstrate manipulative behaviours", "demonstrate \u2192 demonstration \u2192 demonstrative"),
 E(["manipulative","manipulate"], "Manipulative", "controlling others unfairly for one's own gain", "manipulative behaviours", "manipulate \u2192 manipulation \u2192 manipulative"),
 E(["behaviours","behaviour"], "Behaviour", "the way someone or something acts", "manipulative behaviours", "behave \u2192 behaviour \u2192 behavioural"),
 E(["creatures","creature"], "Creature", "a living being, especially an animal", "other creatures"),
 E(["neocortex"], "Neocortex", "the part of the brain involved in higher functions", "a large neocortex"),
 E(["societies","society"], "Society", "people living together in a community", "human societies", "society \u2192 social \u2192 societal"),
 E(["disapprove of","disapprove"], "Disapprove of", "to have a negative opinion about", "disapprove of lying", "approve \u2192 disapprove \u2192 disapproval"),
 E(["ability"], "Ability", "the power or skill to do something", "the ability to deceive", "able \u2192 ability \u2192 enable"),
 E(["desire"], "Desire", "a strong wish for something", "the desire to deceive", "desire \u2192 desirable \u2192 desirous"),
 E(["deceive"], "Deceive", "to make someone believe something untrue", "the desire to deceive", "deceive \u2192 deception \u2192 deceptive"),
 E(["early age","age"], "Early age", "a young stage of life", "from an early age"),
 E(["individually","individual"], "Individually", "one at a time; separately", "children brought in individually", "individual \u2192 individually \u2192 individuality"),
 E(["laboratory","lab"], "Laboratory", "a room equipped for scientific work", "into a laboratory", "laboratory \u2192 lab"),
 E(["face"], "Face (v)", "to turn toward; to confront", "asked to face a wall", "face \u2192 facing \u2192 faced"),
 E(["guess"], "Guess (v)", "to give an answer without being sure", "asked to guess the toy", "guess \u2192 guessing \u2192 guessed"),
 E(["toy"], "Toy", "an object for children to play with", "what toy was placed"),
 E(["fellow"], "Fellow (adj)", "belonging to the same group", "a fellow researcher", "fellow \u2192 fellowship"),
 E(["placed","place"], "Place (v)", "to put in a position", "had placed on a table", "place \u2192 placed \u2192 placement"),
 E(["fluffy"], "Fluffy", "soft and covered in fur or fibres", "a fluffy cat or dog", "fluff \u2192 fluffy"),
 E(["announce"], "Announce", "to make something known publicly", "announce they had to leave", "announce \u2192 announcement \u2192 announcer"),
 E(["reminding","remind"], "Remind", "to make someone remember something", "reminding the child", "remind \u2192 reminder \u2192 reminding"),
 E(["turn around"], "Turn around", "to face the opposite direction", "not to turn around"),
 E(["well aware","aware"], "Aware", "having knowledge of something", "well aware that children would peek", "aware \u2192 awareness \u2192 unaware"),
 E(["resist"], "Resist", "to stop oneself from doing something", "unable to resist peeking", "resist \u2192 resistance \u2192 resistant"),
 E(["peeking","peek"], "Peek (v)", "to look quickly and secretly", "peeking at the toy", "peek \u2192 peeking \u2192 peeked"),
 E(["secret"], "Secret", "kept hidden from others", "secret cameras", "secret \u2192 secretly \u2192 secrecy"),
 E(["cameras","camera"], "Camera", "a device for recording images", "secret cameras"),
 E(["lied","lie"], "Lie (v)", "to tell an untruth", "children lied about looking", "lie \u2192 lied \u2192 lying"),
 E(["whereas"], "Whereas", "in contrast to the fact that", "whereas younger children named it"),
 E(["denied","deny"], "Deny", "to say something is not true", "denied taking a peek", "deny \u2192 denial \u2192 denied"),
 E(["came up with","come up with"], "Come up with", "to think of or produce an idea", "came up with reasons"),
 E(["explain"], "Explain", "to make something clear or understandable", "to explain how they knew", "explain \u2192 explanation \u2192 explanatory"),
 E(["correctly","correct"], "Correctly", "in a way that is right or accurate", "identified the toy correctly", "correct \u2192 correctly \u2192 correction"),
 E(["reassured","reassure"], "Reassure", "to comfort and remove someone's doubts", "Lee is reassured", "assure \u2192 reassure \u2192 reassurance"),
 E(["trend"], "Trend", "a general direction of development", "reassured by this trend", "trend \u2192 trendy \u2192 trending"),
 E(["cognitive"], "Cognitive", "relating to thinking and understanding", "cognitive growth", "cognition \u2192 cognitive \u2192 cognitively"),
 E(["growth"], "Growth", "the process of developing or increasing", "cognitive growth", "grow \u2192 growth \u2192 growing"),
 E(["progressing","progress"], "Progress (v)", "to develop toward a better state", "progressing as it should", "progress \u2192 progression \u2192 progressive"),
 E(["pleased"], "Pleased", "happy or satisfied", "parents may not be pleased", "please \u2192 pleased \u2192 pleasing"),
 E(["hardly"], "Hardly", "almost not; barely", "can hardly criticise children", ""),
 E(["criticise"], "Criticise", "to express disapproval of someone", "criticise children", "critic \u2192 criticise \u2192 criticism"),
 E(["typically","typical"], "Typically", "usually; in most cases", "adults typically tell lies", "typical \u2192 typically \u2192 typify"),
 E(["major"], "Major (adj)", "important or serious", "two major lies", "major \u2192 majority"),
 E(["conversations","conversation"], "Conversation", "an informal spoken exchange", "adult conversations", "converse \u2192 conversation \u2192 conversational"),
 E(["contain"], "Contain", "to have something inside", "contain an element of dishonesty", "contain \u2192 container \u2192 containment"),
 E(["element"], "Element", "a part or feature of something", "an element of dishonesty", "element \u2192 elemental"),
 E(["indicates","indicate"], "Indicate", "to show or suggest", "research indicates that", "indicate \u2192 indication \u2192 indicator"),
 E(["spouses","spouse"], "Spouse", "a husband or wife", "spouses lie often"),
 E(["interactions","interaction"], "Interaction", "communication between people", "out of every 10 interactions", "interact \u2192 interaction \u2192 interactive"),
 E(["comes as no surprise","surprise"], "Come as no surprise", "to be expected; not surprising", "comes as no surprise"),
 E(["series"], "Series", "a number of related things in order", "a series of experiments", "series \u2192 serial"),
 E(["experiments","experiment"], "Experiment", "a test to discover or prove something", "a series of experiments", "experiment \u2192 experimental \u2192 experimentation"),
 E(["desensitised","desensitise"], "Desensitised", "made less sensitive or affected", "desensitised to lying", "sensitive \u2192 desensitise \u2192 desensitised"),
 E(["over time"], "Over time", "gradually, as time passes", "desensitised over time"),
 E(["initially","initial"], "Initially", "at first; in the beginning", "we initially feel shame", "initial \u2192 initially"),
 E(["sense of shame","shame"], "Shame", "a painful feeling caused by wrong behaviour", "a sense of shame", "shame \u2192 ashamed \u2192 shameful"),
 E(["wears off","wear off"], "Wear off", "to gradually disappear", "this feeling wears off"),
 E(["progress to","progress"], "Progress to", "to move on to something more advanced", "we progress to serious lies"),
 E(["serious"], "Serious", "important; not trivial or minor", "more serious lies", "serious \u2192 seriously \u2192 seriousness"),
 E(["analysed","analyse"], "Analyse", "to examine something in detail", "analysed our motives", "analyse \u2192 analysis \u2192 analytical"),
 E(["motives","motive"], "Motive", "a reason for doing something", "our motives for lying", "motive \u2192 motivate \u2192 motivation"),
 E(["by far"], "By far", "by a great amount; clearly", "by far the most common"),
 E(["common"], "Common", "happening often; widespread", "the most common motive", "common \u2192 commonly \u2192 commonness"),
 E(["cover up","cover up our own wrongdoing"], "Cover up", "to hide something wrong from others", "to cover up wrongdoing"),
 E(["wrongdoing"], "Wrongdoing", "illegal or dishonest behaviour", "our own wrongdoing", "wrong \u2192 wrongdoing \u2192 wrongdoer"),
 E(["gain"], "Gain (v)", "to obtain or win something", "to gain economic advantage", "gain \u2192 gained \u2192 gaining"),
 E(["economic"], "Economic", "relating to money, trade and wealth", "economic advantage", "economy \u2192 economic \u2192 economically"),
 E(["advantage"], "Advantage", "a condition giving a benefit", "economic advantage", "advantage \u2192 advantageous"),
 E(["interview"], "Interview", "a formal meeting to assess someone", "lie during an interview", "interview \u2192 interviewer \u2192 interviewee"),
 E(["increase","increase the chances"], "Increase", "to make greater in number or amount", "increase the chances", "increase \u2192 increasing \u2192 increased"),
 E(["white lies"], "White lie", "a harmless lie told to be polite", "'white lies'"),
 E(["avoid"], "Avoid", "to keep away from or prevent", "to avoid hurting feelings", "avoid \u2192 avoidance \u2192 avoidable"),
 E(["hurting","hurt"], "Hurt (v)", "to cause pain or upset", "hurting people's feelings", "hurt \u2192 hurtful \u2192 hurting"),
 E(["feelings","feeling"], "Feelings", "emotional states or reactions", "people's feelings"),
 E(["account for","account"], "Account for", "to form or make up a part of", "account for a small percentage"),
 E(["percentage"], "Percentage", "a proportion expressed as parts per hundred", "a small percentage", "percent \u2192 percentage"),
 E(["untruths","untruth"], "Untruth", "a lie; a false statement", "our untruths", "true \u2192 untrue \u2192 untruth"),
 E(["recognise"], "Recognise", "to identify or be aware of", "recognise our own tendency", "recognise \u2192 recognition \u2192 recognisable"),
 E(["tendency"], "Tendency", "an inclination to behave in a certain way", "our tendency to lie", "tend \u2192 tendency \u2192 tending"),
 E(["suspect"], "Suspect (v)", "to believe something may be true, often bad", "we suspect it isn't true", "suspect \u2192 suspicion \u2192 suspicious"),
 E(["comforted","comfort"], "Comfort (v)", "to make someone feel less worried", "comforted by others' lies", "comfort \u2192 comforted \u2192 comforting"),
 E(["excited","excite"], "Excited", "feeling eager and enthusiastic", "excited by the promise", "excite \u2192 excited \u2192 exciting"),
 E(["promise"], "Promise (n)", "an indication of future success or a good thing", "the promise of a good outcome", "promise \u2192 promising \u2192 promised"),
 E(["outcome"], "Outcome", "the result of an action or event", "a good outcome", "outcome \u2192 outcomes"),
 E(["ordinary"], "Ordinary", "normal; not special", "ordinary people", "ordinary \u2192 ordinarily \u2192 extraordinary"),
 E(["recognising","recognise"], "Recognise", "to identify something correctly", "good at recognising lies", "recognise \u2192 recognition \u2192 recognisable"),
 E(["investigate"], "Investigate", "to examine carefully to find the truth", "investigate the behaviour of others", "investigate \u2192 investigation \u2192 investigator"),
 E(["deception"], "Deception", "the act of deceiving someone", "research into deception", "deceive \u2192 deception \u2192 deceptive"),
 E(["invited","invite"], "Invite", "to ask someone to take part", "invited experts", "invite \u2192 invitation \u2192 inviting"),
 E(["range"], "Range", "a variety of similar things", "a range of experts", "range \u2192 ranging"),
 E(["experts","expert"], "Expert", "a person with great skill or knowledge", "a range of experts", "expert \u2192 expertise \u2192 expertly"),
 E(["judges","judge"], "Judge (n)", "an official who decides cases in a law court", "judges and psychiatrists", "judge \u2192 judgement \u2192 judging"),
 E(["psychiatrists","psychiatrist"], "Psychiatrist", "a doctor who treats mental illness", "judges and psychiatrists", "psychiatry \u2192 psychiatrist \u2192 psychiatric"),
 E(["operate"], "Operate", "to control the working of a machine", "people who operate machines", "operate \u2192 operation \u2192 operator"),
 E(["polygraph"], "Polygraph", "a machine that detects lying (a lie detector)", "polygraph machines"),
 E(["investigations","investigation"], "Investigation", "a careful examination to find facts", "police investigations", "investigate \u2192 investigation \u2192 investigator"),
 E(["detect"], "Detect", "to discover or notice something", "detect dishonesty", "detect \u2192 detection \u2192 detector"),
 E(["myths","myth"], "Myth", "a widely held but false belief", "many myths still prevail", "myth \u2192 mythical \u2192 mythology"),
 E(["prevail"], "Prevail", "to be widespread or common", "myths prevail", "prevail \u2192 prevailing \u2192 prevalent"),
 E(["give-away signs","give-away"], "Give-away", "something that reveals a hidden fact", "'give-away signs'"),
 E(["indicating","indicate"], "Indicate", "to be a sign of something", "signs indicating lying", "indicate \u2192 indication \u2192 indicator"),
 E(["claim"], "Claim (n)", "a statement that something is true", "a common claim", "claim \u2192 claimed \u2192 claimant"),
 E(["liars","liar"], "Liar", "a person who tells lies", "liars won't look you in the eye", "lie \u2192 liar \u2192 lying"),
 E(["look people in the eye","in the eye"], "Look someone in the eye", "to look directly at someone honestly", "won't look people in the eye"),
 E(["explanations","explanation"], "Explanation", "a statement that makes something clear", "during their explanations", "explain \u2192 explanation \u2192 explanatory"),
 E(["questioned","question"], "Question (v)", "to ask someone about something", "while being questioned", "question \u2192 questioning \u2192 questionable"),
 E(["gesture"], "Gesture (v)", "to make movements to express meaning", "they gesture as they speak", "gesture \u2192 gesturing \u2192 gestured"),
 E(["unnatural"], "Unnatural", "not normal or expected", "it seems unnatural", "nature \u2192 natural \u2192 unnatural"),
 E(["convince"], "Convince", "to make someone believe something", "trying to convince others", "convince \u2192 convincing \u2192 conviction"),
 E(["sincerity"], "Sincerity", "the quality of being honest and genuine", "their sincerity", "sincere \u2192 sincerity \u2192 sincerely"),
 E(["reject"], "Reject", "to refuse to accept", "reject these ideas", "reject \u2192 rejection \u2192 rejected"),
 E(["effective"], "Effective", "producing the intended result", "a more effective approach", "effect \u2192 effective \u2192 effectively"),
 E(["narration","narrating"], "Narration", "the act of telling a story", "their narration style", "narrate \u2192 narration \u2192 narrator"),
 E(["provide"], "Provide", "to give or supply something", "they don't provide details", "provide \u2192 provision \u2192 provider"),
 E(["details","detail"], "Detail", "an individual fact or piece of information", "as many details", "detail \u2192 detailed \u2192 detailing"),
 E(["honest account","honest"], "Honest", "truthful and sincere", "an honest account", "honest \u2192 honesty \u2192 honestly"),
 E(["account"], "Account (n)", "a report or description of an event", "an honest account", "account \u2192 accounts"),
 E(["mentally","mental"], "Mentally", "in the mind; relating to the mind", "mentally rehearse", "mental \u2192 mentally \u2192 mentality"),
 E(["rehearse"], "Rehearse", "to practise something beforehand", "rehearse their story", "rehearse \u2192 rehearsal \u2192 rehearsed"),
 E(["stage"], "Stage", "a point or step in a process", "one stage follows another", "stage \u2192 stages"),
 E(["chronological"], "Chronological", "arranged in order of time", "chronological fashion", "chronology \u2192 chronological \u2192 chronologically"),
 E(["fashion"], "Fashion (manner)", "a way or manner of doing something", "in chronological fashion"),
 E(["feature"], "Feature (v)", "to have as a noticeable part", "honest stories feature revisions", "feature \u2192 featured \u2192 featuring"),
 E(["revisions","revision"], "Revision", "a change made to improve something", "revisions and repetition", "revise \u2192 revision \u2192 revised"),
 E(["repetition"], "Repetition", "the act of doing or saying again", "revisions and repetition", "repeat \u2192 repetition \u2192 repetitive"),
 E(["disproved","disprove"], "Disprove", "to show that something is false", "research has disproved the notion", "prove \u2192 disprove \u2192 disproved"),
 E(["widely believed","widely"], "Widely believed", "thought to be true by many people", "the widely believed notion", "wide \u2192 widely \u2192 widespread"),
 E(["notion"], "Notion", "an idea or belief", "a notion about liars", "notion \u2192 notional"),
 E(["habit"], "Habit", "a regular, often automatic behaviour", "a habit of fidgeting", "habit \u2192 habitual \u2192 habitually"),
 E(["fidgeting","fidget"], "Fidget (v)", "to make small restless movements", "fidgeting in their seats", "fidget \u2192 fidgeting \u2192 fidgety"),
 E(["keep still","still"], "Keep still", "to remain without moving", "they keep still"),
 E(["upper body"], "Upper body", "the part of the body above the waist", "still in the upper body"),
 E(["impression"], "Impression", "an effect or feeling produced in someone's mind", "give the impression of confidence", "impress \u2192 impression \u2192 impressive"),
 E(["self-assurance","assurance"], "Self-assurance", "confidence in oneself", "an impression of self-assurance", "assure \u2192 assurance \u2192 self-assurance"),
 E(["psychological distance","psychological"], "Psychological", "relating to the mind and mental processes", "psychological distance", "psychology \u2192 psychological \u2192 psychologically"),
 E(["distance"], "Distance", "the amount of space or separation between things", "psychological distance", "distance \u2192 distant \u2192 distantly"),
 E(["narrating","narrate"], "Narrate", "to tell a story or describe events", "when narrating their stories", "narrate \u2192 narration \u2192 narrator"),
 E(["reverse"], "Reverse (n)", "the opposite of something", "the reverse is true", "reverse \u2192 reversal \u2192 reversible"),
 E(["fake reviews","fake","reviews","review"], "Fake review", "a dishonest, invented online opinion", "write fake reviews"),
 E(["instances","instance"], "Instance", "a particular example or case", "in these instances", "instance \u2192 instances"),
 E(["attempt"], "Attempt (v)", "to try to do something", "they attempt to convince us", "attempt \u2192 attempted \u2192 attempting"),
]


P3_PARAS = [
"That so many copies of Peter Wohlleben's book The Hidden Life of Trees have been sold is no surprise. Life in the urban jungle can be overwhelming, and many of us long to escape by seeking more natural environments. We hope an encounter with nature might make us feel more 'alive'. Would we use this same term to describe nature itself, though? Forests and the trees that form them are commonly perceived as objects lacking awareness, like rocks or stones. But here, Wohlleben would beg to differ. From his observations, he has concluded that they are conscious in a way we do not fully understand.",
"In recent decades, a number of writers have investigated our planet's flora. The Cabaret of Plants by Richard Mabey and What a Plant Knows by Daniel Chamovitz, for example, have done much to reformulate our views about the green world. Central to many of these books is a serious message about sustainability, and The Hidden Life of Trees is no exception. What sets it apart is its approach to description: at the start Wohlleben announces that 'When you know that trees have memories and that tree parents live together with their children, then you can no longer just chop them down.' Not everyone will be comfortable with this kind of anthropomorphism.",
"Nevertheless, Wohlleben's experience of working in a beech forest in the Eifel mountains of Germany may put him in a better position than many to write a book about trees. In the introduction, he explains that he started out as a state-employed forester, taking care of trees purely for industrial reasons. The straighter they were, the more high-quality logs could be sawn. But after a while he began to appreciate trees for more than just their commercial worth. He gives some of the credit for this realisation to the tourists that would come to the forest, who were more enchanted by bent, crooked trees, which did not conform to the straight ideal.",
"An anecdote that stands out is Wohlleben's encounter with 'the gnarled remains of an enormous tree stump' in the Eifel forest. More than anything else, it was this encounter that prompted him to look further into the hidden behaviour of trees. To his surprise, after scraping at the outside layer of bark covering the stump, he discovered a green layer underneath. This was chlorophyll, the pigment normally produced by living trees. Wohlleben realised that the only way the stump could still be alive was if the surrounding beeches were providing it with a sugar solution through their own roots.",
"Wohlleben is not the first person to claim that trees are cooperative. In the 1990s, Dr Suzanne Simard realised that fir and birch trees were supplying each other with carbon. Simard's findings made complete sense to Wohlleben, who believes that this kind of nutrient exchange between neighbours is typical of a healthy forest. Wohlleben also had the opportunity to deepen his understanding of tree biology when researchers from Aachen University set up investigative programmes in his beech forest. Discussions with them reinforced his beliefs about the way trees thrived, and Wohlleben eventually found himself strongly opposed to some traditional forestry practices. He finally succeeded in persuading local villagers that the forest should be allowed to return to a natural state: this involved banning the use of machinery for logging, and giving up on pesticides for a start. Since then, Wohlleben has been noting how his beech forest has developed, and his observations formed the foundation for the book. Humour and a straightforward narrative make it instantly appealing to readers without a science background - elements that have successfully been translated into over a dozen languages.",
"Those that do have scientific training, however, will be more demanding. Critics of Wohlleben point out that proper academic studies need to be done to prove all his claims are factually accurate. This seems a fair point. What the book will certainly do is transform nature lovers' experiences of a forest walk. Once you know what is happening below ground, you can't help but marvel at the complex life of trees. Will it transform the way we produce timber for the manufacturing industry? As large corporations tend to focus on immediate profits, they are hardly likely to adopt the longer-term practices that Wohlleben recommends.",
"One of these is allowing trees to grow nearer to each other. This is the opposite of what happens in many state-owned forests, where foresters deliberately space out trees so they can get more sunlight and grow faster. But Wohlleben claims this spacing prevents vital root interaction, and so lowers resistance to drought. Older, established trees, he explains, draw up moisture through their deep roots and provide this to juvenile trees growing below them. Without this assistance, they could die. The relationship between fungi and trees is also given attention. For instance, when pines require more nitrogen, the fungi growing at their base release a poison into the soil. This poison kills many minute organisms, which release nitrogen as they die, and this is absorbed by the trees' roots. In return, the fungi receive photosynthesised sugar from the pines. Then Wohlleben explores the way trees employ scent, giving the example of acacia trees in sub-Saharan Africa. When giraffes begin feeding on an acacia's leaves, the tree emits ethylene gas as a warning to neighbouring acacias. These then pump tannins into their leaves - substances toxic to giraffes. More controversial is Wohlleben's suggestion that trees feel pain. Although scientific research has now established that if branches are broken off or the trunk is hit with an axe, a tree will emit electrical signals from the site of the wound, the application of the concept of 'pain' might be an instance where readers are unconvinced.",
]

P3_ENTRIES = [
 E(["copies","copy"], "Copy (n)", "a single example of a book or item produced", "many copies of the book", "copy \u2192 copies \u2192 copied"),
 E(["no surprise","surprise"], "No surprise", "something expected; not surprising", "is no surprise", "surprise \u2192 surprising \u2192 surprised"),
 E(["urban jungle","urban"], "Urban jungle", "a crowded, busy city environment", "the urban jungle", "urban \u2192 urbanise"),
 E(["overwhelming","overwhelm"], "Overwhelming", "very great or intense; hard to cope with", "can be overwhelming", "overwhelm \u2192 overwhelming \u2192 overwhelmed"),
 E(["long to","long"], "Long to", "to want something very much", "long to escape", "long \u2192 longing"),
 E(["escape"], "Escape", "to get away from a place or situation", "escape by seeking nature", "escape \u2192 escaped \u2192 escaping"),
 E(["seeking","seek"], "Seek", "to try to find or obtain", "seeking natural environments", "seek \u2192 sought \u2192 seeking"),
 E(["natural"], "Natural", "existing in or from nature", "natural environments", "nature \u2192 natural \u2192 naturally"),
 E(["environments","environment"], "Environment", "the surroundings or conditions one lives in", "natural environments", "environment \u2192 environmental \u2192 environmentally"),
 E(["encounter"], "Encounter (n)", "an unexpected meeting or experience", "an encounter with nature", "encounter \u2192 encountered"),
 E(["nature"], "Nature", "the physical world of plants and animals", "an encounter with nature", "nature \u2192 natural \u2192 naturally"),
 E(["term"], "Term", "a word or phrase with a specific meaning", "this same term", "term \u2192 terminology"),
 E(["describe"], "Describe", "to say what something is like", "to describe nature", "describe \u2192 description \u2192 descriptive"),
 E(["forests","forest"], "Forest", "a large area covered with trees", "forests and trees", "forest \u2192 forestry \u2192 forested"),
 E(["form"], "Form (v)", "to make up or constitute", "the trees that form them", "form \u2192 formation \u2192 formative"),
 E(["commonly","common"], "Commonly", "usually; often", "commonly perceived", "common \u2192 commonly \u2192 commonness"),
 E(["perceived","perceive"], "Perceive", "to see or understand in a particular way", "perceived as objects", "perceive \u2192 perception \u2192 perceptive"),
 E(["lacking","lack"], "Lacking", "not having something needed", "lacking awareness", "lack \u2192 lacking"),
 E(["awareness","aware"], "Awareness", "knowledge or consciousness of something", "lacking awareness", "aware \u2192 awareness \u2192 unaware"),
 E(["beg to differ","differ"], "Beg to differ", "to politely disagree", "Wohlleben would beg to differ", "differ \u2192 different \u2192 difference"),
 E(["observations","observation"], "Observation", "the act of watching carefully; a remark", "from his observations", "observe \u2192 observation \u2192 observer"),
 E(["concluded","conclude"], "Conclude", "to decide after considering the facts", "he has concluded that", "conclude \u2192 conclusion \u2192 conclusive"),
 E(["conscious"], "Conscious", "aware and able to respond", "trees are conscious", "conscious \u2192 consciously \u2192 consciousness"),
 E(["fully"], "Fully", "completely; entirely", "do not fully understand", "full \u2192 fully"),
 E(["recent decades","decades","decade"], "Decade", "a period of ten years", "in recent decades", "decade \u2192 decades"),
 E(["investigated","investigate"], "Investigate", "to study or examine carefully", "writers have investigated flora", "investigate \u2192 investigation \u2192 investigative"),
 E(["flora"], "Flora", "the plants of a particular region", "our planet's flora"),
 E(["reformulate"], "Reformulate", "to express or plan in a new way", "reformulate our views", "formulate \u2192 reformulate \u2192 formulation"),
 E(["views","view"], "View (n)", "an opinion or belief", "our views about plants", "view \u2192 viewpoint"),
 E(["central to","central"], "Central to", "of the most importance to", "central to many books", "centre \u2192 central \u2192 centrally"),
 E(["message"], "Message", "an important idea that is communicated", "a serious message", "message \u2192 messaging"),
 E(["sustainability","sustainable"], "Sustainability", "use of resources without harming the future", "a message about sustainability", "sustain \u2192 sustainable \u2192 sustainability"),
 E(["no exception","exception"], "No exception", "the same as the others; not different", "is no exception", "except \u2192 exception \u2192 exceptional"),
 E(["sets it apart","set apart"], "Set apart", "to make different or special", "what sets it apart"),
 E(["approach"], "Approach (n)", "a way of dealing with something", "its approach to description", "approach \u2192 approaches"),
 E(["description"], "Description", "a statement of what something is like", "its approach to description", "describe \u2192 description \u2192 descriptive"),
 E(["announces","announce"], "Announce", "to state something publicly", "Wohlleben announces that", "announce \u2192 announcement \u2192 announcer"),
 E(["memories","memory"], "Memory", "the ability to remember; a thing remembered", "trees have memories", "memory \u2192 memorise \u2192 memorable"),
 E(["chop them down","chop down","chop"], "Chop down", "to cut down a tree", "chop them down", "chop \u2192 chopped \u2192 chopping"),
 E(["comfortable"], "Comfortable", "free from worry or difficulty; at ease", "comfortable with this idea", "comfort \u2192 comfortable \u2192 comfortably"),
 E(["anthropomorphism"], "Anthropomorphism", "giving human qualities to animals or things", "this kind of anthropomorphism", "anthropomorphic \u2192 anthropomorphism"),
 E(["Nevertheless","nevertheless"], "Nevertheless", "in spite of that; however", "nevertheless, his experience helps"),
 E(["beech forest","beech"], "Beech", "a type of large tree with smooth bark", "a beech forest"),
 E(["mountains","mountain"], "Mountain", "a very high, steep area of land", "the Eifel mountains"),
 E(["put him in a better position","position"], "Position", "a situation or condition someone is in", "put him in a better position"),
 E(["introduction"], "Introduction", "the opening part of a book", "in the introduction", "introduce \u2192 introduction \u2192 introductory"),
 E(["started out","start out"], "Start out", "to begin a career or activity", "he started out as a forester"),
 E(["state-employed"], "State-employed", "employed by the government", "a state-employed forester", "employ \u2192 employed \u2192 employer"),
 E(["forester"], "Forester", "a person who manages forests", "a state-employed forester", "forest \u2192 forester \u2192 forestry"),
 E(["taking care of","care"], "Take care of", "to look after something", "taking care of trees"),
 E(["purely","pure"], "Purely", "only; entirely", "purely for industrial reasons", "pure \u2192 purely \u2192 purity"),
 E(["industrial"], "Industrial", "relating to industry or manufacturing", "industrial reasons", "industry \u2192 industrial \u2192 industrialise"),
 E(["straighter","straight"], "Straight", "without bends or curves", "the straighter they were", "straight \u2192 straighten \u2192 straightness"),
 E(["high-quality","quality"], "High-quality", "of a very good standard", "high-quality logs", "quality \u2192 qualitative"),
 E(["logs","log"], "Log", "a piece of a tree trunk that has been cut", "high-quality logs"),
 E(["sawn","saw"], "Saw (v)", "to cut something using a saw", "logs could be sawn", "saw \u2192 sawn \u2192 sawing"),
 E(["appreciate"], "Appreciate", "to recognise the value of something", "appreciate trees", "appreciate \u2192 appreciation \u2192 appreciative"),
 E(["commercial"], "Commercial", "relating to business and making money", "their commercial worth", "commerce \u2192 commercial \u2192 commercially"),
 E(["worth"], "Worth (n)", "the value or usefulness of something", "their commercial worth", "worth \u2192 worthy \u2192 worthwhile"),
 E(["credit"], "Credit (n)", "praise or recognition for an achievement", "gives the credit to tourists", "credit \u2192 credited \u2192 creditable"),
 E(["realisation"], "Realisation", "the act of becoming aware of something", "credit for this realisation", "realise \u2192 realisation \u2192 realised"),
 E(["tourists","tourist"], "Tourist", "a person who travels for pleasure", "the tourists that came", "tour \u2192 tourist \u2192 tourism"),
 E(["enchanted","enchant"], "Enchanted", "filled with delight; charmed", "enchanted by crooked trees", "enchant \u2192 enchanting \u2192 enchanted"),
 E(["bent"], "Bent", "curved; not straight", "bent, crooked trees", "bend \u2192 bent \u2192 bending"),
 E(["crooked"], "Crooked", "bent or twisted out of shape", "crooked trees"),
 E(["conform to","conform"], "Conform to", "to match or follow a standard", "did not conform to the ideal", "conform \u2192 conformity \u2192 conformist"),
 E(["ideal"], "Ideal (n)", "a standard of perfection", "the straight ideal", "ideal \u2192 ideally \u2192 idealise"),
 E(["anecdote"], "Anecdote", "a short, interesting personal story", "an anecdote that stands out", "anecdote \u2192 anecdotal"),
 E(["stands out","stand out"], "Stand out", "to be easily noticed or remarkable", "an anecdote that stands out"),
 E(["gnarled"], "Gnarled", "rough, twisted and knotty, as with age", "the gnarled remains", "gnarl \u2192 gnarled"),
 E(["remains"], "Remains", "the parts of something left over", "the gnarled remains"),
 E(["enormous"], "Enormous", "extremely large", "an enormous tree stump", "enormous \u2192 enormously \u2192 enormity"),
 E(["stump"], "Stump", "the part of a tree left after it is cut down", "a tree stump"),
 E(["prompted","prompt"], "Prompt (v)", "to cause someone to do something", "prompted him to look further", "prompt \u2192 prompted \u2192 prompting"),
 E(["hidden"], "Hidden", "kept out of sight; not obvious", "the hidden behaviour", "hide \u2192 hidden \u2192 hiding"),
 E(["behaviour"], "Behaviour", "the way something acts or functions", "the behaviour of trees", "behave \u2192 behaviour \u2192 behavioural"),
 E(["scraping","scrape"], "Scrape (v)", "to remove a surface layer by rubbing with something sharp", "scraping at the bark", "scrape \u2192 scraping \u2192 scraped"),
 E(["bark"], "Bark", "the hard outer covering of a tree", "the layer of bark"),
 E(["covering","cover"], "Covering", "a layer that covers something", "bark covering the stump", "cover \u2192 covering \u2192 covered"),
 E(["underneath"], "Underneath", "below or beneath something", "a green layer underneath"),
 E(["chlorophyll"], "Chlorophyll", "the green substance in plants used in photosynthesis", "this was chlorophyll"),
 E(["pigment"], "Pigment", "a natural substance that gives colour", "the green pigment", "pigment \u2192 pigmentation"),
 E(["surrounding","surround"], "Surrounding", "all around something", "the surrounding beeches", "surround \u2192 surrounding \u2192 surrounded"),
 E(["sugar solution","solution"], "Solution", "a liquid in which something is dissolved", "a sugar solution"),
 E(["roots","root"], "Root", "the underground part of a plant", "through their roots", "root \u2192 rooted \u2192 rooting"),
 E(["cooperative"], "Cooperative", "willing to work together with others", "trees are cooperative", "cooperate \u2192 cooperation \u2192 cooperative"),
 E(["fir"], "Fir", "a type of evergreen tree", "fir and birch trees"),
 E(["birch"], "Birch", "a type of tree with thin bark", "fir and birch trees"),
 E(["supplying","supply"], "Supply (v)", "to provide something needed", "supplying each other with carbon", "supply \u2192 supplier \u2192 supplies"),
 E(["carbon"], "Carbon", "a chemical element found in all living things", "supplying carbon"),
 E(["findings","finding"], "Findings", "the results of research", "Simard's findings", "find \u2192 finding \u2192 findings"),
 E(["made complete sense","sense"], "Make sense", "to be reasonable or understandable", "made complete sense"),
 E(["nutrient"], "Nutrient", "a substance that provides nourishment", "nutrient exchange", "nutrient \u2192 nutrition \u2192 nutritious"),
 E(["exchange"], "Exchange (n)", "the act of giving and receiving in return", "nutrient exchange", "exchange \u2192 exchanged \u2192 exchanging"),
 E(["neighbours","neighbour"], "Neighbour", "a person or thing situated nearby", "between neighbours", "neighbour \u2192 neighbourhood \u2192 neighbouring"),
 E(["healthy"], "Healthy", "in good condition; good for health", "a healthy forest", "health \u2192 healthy \u2192 healthily"),
 E(["opportunity"], "Opportunity", "a chance to do something", "the opportunity to deepen understanding", "opportunity \u2192 opportune \u2192 opportunistic"),
 E(["deepen","deep"], "Deepen", "to make or become deeper or greater", "deepen his understanding", "deep \u2192 deepen \u2192 deeply"),
 E(["biology"], "Biology", "the scientific study of living things", "tree biology", "biology \u2192 biological \u2192 biologist"),
 E(["set up","set up investigative programmes"], "Set up", "to establish or start something", "set up programmes"),
 E(["investigative","investigate"], "Investigative", "relating to careful examination or research", "investigative programmes", "investigate \u2192 investigation \u2192 investigative"),
 E(["programmes","programme"], "Programme", "a planned set of activities or research", "investigative programmes"),
 E(["Discussions","discussions","discussion"], "Discussion", "a talk about something to exchange ideas", "discussions with them", "discuss \u2192 discussion \u2192 discussed"),
 E(["reinforced","reinforce"], "Reinforce", "to make stronger; to support", "reinforced his beliefs", "reinforce \u2192 reinforcement \u2192 reinforced"),
 E(["beliefs","belief"], "Belief", "an idea accepted as true", "his beliefs about trees", "believe \u2192 belief \u2192 believable"),
 E(["thrived","thrive"], "Thrive", "to grow or develop well", "the way trees thrived", "thrive \u2192 thriving \u2192 thrived"),
 E(["opposed to","opposed","oppose"], "Opposed to", "disagreeing with or against", "opposed to forestry practices", "oppose \u2192 opposition \u2192 opposed"),
 E(["forestry"], "Forestry", "the science of managing forests", "forestry practices", "forest \u2192 forestry \u2192 forester"),
 E(["practices","practice"], "Practice (n)", "a usual or customary way of doing something", "traditional practices", "practise \u2192 practice \u2192 practical"),
 E(["succeeded in","succeeded","succeed"], "Succeed in", "to achieve a desired aim", "succeeded in persuading", "succeed \u2192 success \u2192 successful"),
 E(["persuading","persuade"], "Persuade", "to make someone agree by giving reasons", "persuading local villagers", "persuade \u2192 persuasion \u2192 persuasive"),
 E(["villagers","villager"], "Villager", "a person who lives in a village", "local villagers", "village \u2192 villager"),
 E(["natural state","state"], "Natural state", "the original, untouched condition", "return to a natural state"),
 E(["banning","ban"], "Ban (v)", "to officially forbid something", "banning machinery", "ban \u2192 banned \u2192 banning"),
 E(["machinery"], "Machinery", "machines as a group", "machinery for logging", "machine \u2192 machinery"),
 E(["logging","log"], "Logging", "the activity of cutting down trees for wood", "machinery for logging", "log \u2192 logging \u2192 logger"),
 E(["giving up on","give up"], "Give up on", "to stop using or trying something", "giving up on pesticides"),
 E(["pesticides","pesticide"], "Pesticide", "a chemical used to kill pests", "giving up pesticides"),
 E(["noting","note"], "Note (v)", "to observe and record", "noting how the forest developed", "note \u2192 noting \u2192 noted"),
 E(["developed","develop"], "Develop", "to grow or change over time", "how the forest developed", "develop \u2192 development \u2192 developed"),
 E(["foundation"], "Foundation", "the basis on which something is built", "the foundation for the book", "found \u2192 foundation \u2192 foundational"),
 E(["humour"], "Humour", "the quality of being amusing", "humour and narrative", "humour \u2192 humorous \u2192 humourless"),
 E(["straightforward"], "Straightforward", "simple and easy to understand", "a straightforward narrative", "forward \u2192 straightforward"),
 E(["narrative"], "Narrative", "a spoken or written account; a story", "a straightforward narrative", "narrate \u2192 narrative \u2192 narrator"),
 E(["instantly","instant"], "Instantly", "immediately", "instantly appealing", "instant \u2192 instantly \u2192 instance"),
 E(["appealing","appeal"], "Appealing", "attractive or interesting", "instantly appealing", "appeal \u2192 appealing \u2192 appealingly"),
 E(["background"], "Background", "a person's training and experience", "a science background", "background \u2192 backgrounds"),
 E(["elements","element"], "Element", "a part or feature of something", "elements that have been translated", "element \u2192 elemental"),
 E(["successfully","successful"], "Successfully", "in a way that achieves the aim", "successfully translated", "succeed \u2192 successful \u2192 successfully"),
 E(["translated","translate"], "Translate", "to express in another language", "translated into many languages", "translate \u2192 translation \u2192 translator"),
 E(["dozen"], "Dozen", "a group of twelve", "over a dozen languages"),
 E(["scientific training","training"], "Training", "the process of learning skills", "scientific training", "train \u2192 training \u2192 trainer"),
 E(["demanding"], "Demanding", "requiring much effort or high standards", "will be more demanding", "demand \u2192 demanding \u2192 demanded"),
 E(["Critics","critics","critic"], "Critic", "a person who judges and finds fault", "critics of Wohlleben", "critic \u2192 critical \u2192 criticism"),
 E(["point out"], "Point out", "to draw attention to a fact", "critics point out that"),
 E(["proper"], "Proper", "correct, suitable or thorough", "proper academic studies", "proper \u2192 properly"),
 E(["academic"], "Academic", "relating to formal study and scholarship", "academic studies", "academic \u2192 academy \u2192 academically"),
 E(["prove"], "Prove", "to show that something is true", "to prove his claims", "prove \u2192 proof \u2192 proven"),
 E(["claims","claim"], "Claim (n)", "a statement that something is true", "his claims", "claim \u2192 claimed \u2192 claimant"),
 E(["factually","factual"], "Factually", "in a way based on facts", "factually accurate", "fact \u2192 factual \u2192 factually"),
 E(["accurate"], "Accurate", "correct and exact", "factually accurate", "accurate \u2192 accuracy \u2192 accurately"),
 E(["fair point","fair"], "Fair point", "a reasonable argument", "this seems a fair point", "fair \u2192 fairly \u2192 fairness"),
 E(["transform"], "Transform", "to change completely", "transform their experiences", "transform \u2192 transformation \u2192 transformative"),
 E(["below ground","ground"], "Below ground", "under the surface of the earth", "happening below ground"),
 E(["marvel at","marvel"], "Marvel at", "to be filled with wonder at something", "marvel at the life of trees", "marvel \u2192 marvellous \u2192 marvelling"),
 E(["complex"], "Complex (adj)", "complicated; with many parts", "the complex life of trees", "complex \u2192 complexity"),
 E(["timber"], "Timber", "wood prepared for building or use", "produce timber"),
 E(["manufacturing"], "Manufacturing", "the making of goods, especially in factories", "the manufacturing industry", "manufacture \u2192 manufacturing \u2192 manufacturer"),
 E(["corporations","corporation"], "Corporation", "a large company", "large corporations", "corporate \u2192 corporation"),
 E(["tend to","tend"], "Tend to", "to be likely or inclined to", "corporations tend to focus on profits", "tend \u2192 tendency"),
 E(["immediate"], "Immediate", "happening at once; near in time", "immediate profits", "immediate \u2192 immediately"),
 E(["profits","profit"], "Profit", "money gained from business", "immediate profits", "profit \u2192 profitable \u2192 profitability"),
 E(["hardly likely","hardly"], "Hardly likely", "very unlikely", "hardly likely to adopt"),
 E(["adopt"], "Adopt", "to start to use a method or idea", "adopt longer-term practices", "adopt \u2192 adoption \u2192 adopted"),
 E(["recommends","recommend"], "Recommend", "to advise as good or suitable", "practices Wohlleben recommends", "recommend \u2192 recommendation \u2192 recommended"),
 E(["nearer","near"], "Nearer", "closer in distance", "grow nearer to each other", "near \u2192 nearer \u2192 nearby"),
 E(["opposite"], "Opposite (n)", "a person or thing completely different", "the opposite of this", "oppose \u2192 opposite \u2192 opposition"),
 E(["state-owned"], "State-owned", "owned by the government", "state-owned forests", "own \u2192 owned \u2192 state-owned"),
 E(["deliberately","deliberate"], "Deliberately", "intentionally; on purpose", "deliberately space out trees", "deliberate \u2192 deliberately \u2192 deliberation"),
 E(["space out","space"], "Space out", "to arrange with gaps between", "space out trees"),
 E(["sunlight"], "Sunlight", "the light from the sun", "more sunlight", "sun \u2192 sunlight \u2192 sunny"),
 E(["spacing","space"], "Spacing", "the arrangement of gaps between things", "this spacing", "space \u2192 spacing \u2192 spaced"),
 E(["vital"], "Vital", "absolutely necessary; essential", "vital root interaction", "vital \u2192 vitally \u2192 vitality"),
 E(["interaction"], "Interaction", "the action of things affecting each other", "root interaction", "interact \u2192 interaction \u2192 interactive"),
 E(["lowers","lower"], "Lower (v)", "to reduce in amount or level", "lowers resistance", "low \u2192 lower \u2192 lowered"),
 E(["resistance"], "Resistance", "the ability to withstand something", "resistance to drought", "resist \u2192 resistance \u2192 resistant"),
 E(["drought"], "Drought", "a long period without rain", "resistance to drought"),
 E(["established"], "Established", "long-existing and well developed", "established trees", "establish \u2192 established \u2192 establishment"),
 E(["draw up","draw"], "Draw up", "to pull or take in (a liquid)", "draw up moisture", "draw \u2192 drew \u2192 drawn"),
 E(["moisture"], "Moisture", "small amounts of water in or on something", "draw up moisture", "moist \u2192 moisture \u2192 moisturise"),
 E(["deep roots","deep"], "Deep", "extending far down", "their deep roots", "deep \u2192 depth \u2192 deeply"),
 E(["juvenile"], "Juvenile", "young; not yet fully developed", "juvenile trees", "juvenile \u2192 juveniles"),
 E(["assistance","assist"], "Assistance", "help or support", "without this assistance", "assist \u2192 assistance \u2192 assistant"),
 E(["relationship"], "Relationship", "the way two things are connected", "the relationship between fungi and trees", "relate \u2192 relationship \u2192 related"),
 E(["fungi","fungus"], "Fungi", "organisms such as mushroods and moulds", "fungi and trees"),
 E(["given attention","attention"], "Given attention", "made the focus of consideration", "is also given attention", "attend \u2192 attention \u2192 attentive"),
 E(["pines","pine"], "Pine", "a type of evergreen tree", "when pines need nitrogen"),
 E(["require"], "Require", "to need something", "pines require nitrogen", "require \u2192 requirement \u2192 required"),
 E(["nitrogen"], "Nitrogen", "a gas that is a vital nutrient for plants", "more nitrogen"),
 E(["base"], "Base (n)", "the lowest part of something", "the fungi at their base", "base \u2192 basis \u2192 basic"),
 E(["release"], "Release (v)", "to let out or set free", "release a poison", "release \u2192 released \u2192 releasing"),
 E(["poison"], "Poison (n)", "a substance that causes harm or death", "release a poison", "poison \u2192 poisonous \u2192 poisoned"),
 E(["minute"], "Minute (adj)", "extremely small", "minute organisms", "minute \u2192 minutely"),
 E(["organisms","organism"], "Organism", "an individual living thing", "minute organisms", "organism \u2192 organic"),
 E(["absorbed","absorb"], "Absorb", "to take in a substance", "absorbed by the roots", "absorb \u2192 absorption \u2192 absorbed"),
 E(["in return"], "In return", "as a response or exchange", "in return, the fungi receive sugar"),
 E(["receive"], "Receive", "to get or be given", "the fungi receive sugar", "receive \u2192 receipt \u2192 receiver"),
 E(["photosynthesised","photosynthesis"], "Photosynthesised", "produced by plants using sunlight", "photosynthesised sugar", "photosynthesis \u2192 photosynthesise \u2192 photosynthesised"),
 E(["employ"], "Employ", "to use something for a purpose", "trees employ scent", "employ \u2192 employment \u2192 employed"),
 E(["scent"], "Scent", "a pleasant or distinctive smell", "trees employ scent", "scent \u2192 scented"),
 E(["acacia trees","acacia","acacias"], "Acacia", "a thorny tree found in warm regions", "acacia trees"),
 E(["sub-Saharan"], "Sub-Saharan", "relating to Africa south of the Sahara", "sub-Saharan Africa"),
 E(["giraffes","giraffe"], "Giraffe", "a tall African animal with a very long neck", "giraffes feeding on leaves"),
 E(["feeding","feed"], "Feed (v)", "to eat; to take food", "feeding on leaves", "feed \u2192 feeding \u2192 fed"),
 E(["leaves","leaf"], "Leaf", "a flat green part of a plant", "an acacia's leaves", "leaf \u2192 leaves \u2192 leafy"),
 E(["emits","emit"], "Emit", "to send out or give off", "the tree emits gas", "emit \u2192 emission \u2192 emitted"),
 E(["ethylene"], "Ethylene", "a gas produced naturally by plants", "ethylene gas"),
 E(["warning","warn"], "Warning", "a statement of possible danger", "as a warning", "warn \u2192 warning \u2192 warned"),
 E(["neighbouring","neighbour"], "Neighbouring", "located nearby; adjacent", "neighbouring acacias", "neighbour \u2192 neighbouring \u2192 neighbourhood"),
 E(["pump"], "Pump (v)", "to force a liquid or substance through", "pump tannins into their leaves", "pump \u2192 pumped \u2192 pumping"),
 E(["tannins","tannin"], "Tannin", "a bitter substance found in some plants", "pump tannins"),
 E(["substances","substance"], "Substance", "a particular kind of matter or material", "substances toxic to giraffes", "substance \u2192 substantial"),
 E(["toxic"], "Toxic", "poisonous; harmful to living things", "toxic to giraffes", "toxic \u2192 toxicity \u2192 toxin"),
 E(["controversial"], "Controversial", "causing disagreement or argument", "more controversial", "controversy \u2192 controversial \u2192 controversially"),
 E(["suggestion","suggest"], "Suggestion", "an idea put forward for consideration", "Wohlleben's suggestion", "suggest \u2192 suggestion \u2192 suggestive"),
 E(["feel pain","pain"], "Pain", "an unpleasant physical sensation; suffering", "trees feel pain", "pain \u2192 painful \u2192 painless"),
 E(["established"], "Established (proved)", "shown to be true", "research has established", "establish \u2192 established \u2192 establishment"),
 E(["broken off","break off","broken"], "Break off", "to separate or remove by force", "if branches are broken off"),
 E(["trunk"], "Trunk", "the main woody stem of a tree", "the trunk is hit", "trunk \u2192 trunks"),
 E(["axe"], "Axe", "a tool with a heavy blade for chopping", "hit with an axe"),
 E(["electrical signals","signals","signal"], "Signal (n)", "a sign or impulse carrying information", "emit electrical signals", "signal \u2192 signalling \u2192 signalled"),
 E(["site"], "Site", "the place where something happens", "the site of the wound", "site \u2192 sites"),
 E(["wound"], "Wound (n)", "an injury to the body or surface", "the site of the wound", "wound \u2192 wounded"),
 E(["application"], "Application", "the act of using or applying something", "the application of the concept", "apply \u2192 application \u2192 applied"),
 E(["concept"], "Concept", "an abstract idea", "the concept of 'pain'", "concept \u2192 conceptual \u2192 conceptualise"),
 E(["instance"], "Instance", "an example or particular case", "an instance where readers doubt", "instance \u2192 instances"),
 E(["unconvinced","convinced"], "Unconvinced", "not persuaded that something is true", "readers are unconvinced", "convince \u2192 convinced \u2192 unconvinced"),
]

PASSAGES = [
 {"num": 1, "title": "The Romans Reveal their Secrets", "paragraphs": P1_PARAS, "entries": P1_ENTRIES},
 {"num": 2, "title": "The Truth about Lying", "paragraphs": P2_PARAS, "entries": P2_ENTRIES},
 {"num": 3, "title": "Review: The Hidden Life of Trees", "paragraphs": P3_PARAS, "entries": P3_ENTRIES},
]
