# -*- coding: utf-8 -*-
# Test 2 Reading: 3 passages + comprehensive vocab (elementary -> advanced)
E = lambda hl, word, d, coll="", fam="": {"hl": hl, "word": word, "def": d, "coll": coll, "fam": fam}

P1_PARAS = [
"The first groups of people to discover New Zealand came from Polynesia. Exactly when these explorers arrived has often been a matter of debate, but today the general understanding is that it was during the 13th century that their canoes eventually landed on New Zealand's shores. In some ways the new country must have seemed like an ideal place to settle: the land was fertile, and thick forests provided firewood, shelter and building materials. Still, life would have been challenging for the different Polynesian tribes, who had to adapt to a new environment. The tribes only began to refer to themselves as Maori, meaning 'ordinary people', when Europeans in search of new opportunities began arriving in the 18th century. To the Maori, of course, the European settlers and sailors were not 'ordinary', but very strange.",
"It was not only a knowledge of canoe-building and navigation that the Polynesians brought to New Zealand. They were also skilled craftsmen. There is archaeological evidence that the tools they produced were of high quality and would have enabled tribes to plant and harvest crops. Craftsmen were also occupied with making weapons such as knives and axes, which were used for both construction and fighting. Interestingly, some crafts that had once been popular in Polynesian islands were no longer done in New Zealand, although researchers are unsure why. Pottery is an example of this, despite the fact that the clay needed to make pots and bowls could easily be found in the new country.",
"The Maori word whakairo can be translated as 'decorative work' - this can refer to bone, wood and greenstone carving. Although Maori carvers were influenced by their Polynesian heritage, they developed their own style, including the curved patterns and spirals inspired by New Zealand plants. The same term can also apply to weaving; the crafting of, for example, woven baskets and mats all required knowledge and skill. Carving greenstone, or pounamu as it is called in Maori, was a long process, requiring great patience. Further, because of this mineral's rarity, any greenstone object, such as a piece of jewellery or cutting blade, was a prized possession. For that reason, it was the few people of high status rather than low-ranking members of a tribe who would possess such objects.",
"As New Zealand had no native mammals except for bats, dolphins and whales, Maori largely had to depend on plants to provide material for their clothing, including their cloaks. Weavers experimented with the inner bark of the houhere, the lacebark tree, but found it unsuitable. But the dried-out leaves and fibres of the flax plant provided a solution. Once a cloak had been woven from flax, it could be decorated. Borders might be dyed black or red, for example. In the case of superior ones made for chiefs or the more important members of a tribe, feathers from kiwi, pigeons or other native birds might be attached. All flax cloaks were rectangular in shape, so had no sleeves, and neither was a hood a feature of this garment. Short cloaks were fastened around a person's neck, and came only to the waist. Pins made of bone, wood or greenstone allowed longer cloaks to be secured at the shoulder; these were a type that were often used for ceremonial occasions. Of course, the construction of the cloaks was influenced by the plant material available to Maori weavers. This meant that cloaks were loose-fitting, and while they protected wearers from New Zealand's strong sunshine, they were not useful during the winter months. A cloak made from fur or wool could provide insulation from the cold, but not so a cloak made of flax.",
"The warriors of a tribe required a different kind of cloak to help protect them. To create these special cloaks, the tough fibres of the mountain cabbage tree were used instead. It is not clear to researchers what the entire process involved, but they believe the fibres were left to soak in water over a period of time in order to soften them and make them easier to weave together. Later, once the whole cloak had been constructed, it would be dyed black. To do this, Maori weavers covered it in a special kind of mud they had collected from riverbeds. This was rich in iron due to New Zealand's volcanic landscape. The particular advantage of these cloaks was that the tough cabbage tree fibres they were woven from could reduce the impact of spear tips during a fight with enemy tribes. It is fortunate that some cloaks from the 1800s still survive and can provide us with further insight into the materials and construction techniques that Maori craftsmen used.",
]

P1_ENTRIES = [
 E(["discover"], "Discover", "to find or learn about something for the first time", "discover a new land", "discover \u2192 discovery \u2192 discoverer"),
 E(["explorers","explorer"], "Explorer", "a person who travels to unknown places to learn about them", "early explorers", "explore \u2192 exploration \u2192 explorer"),
 E(["arrived","arriving","arrive"], "Arrive", "to reach a place", "explorers arrived", "arrive \u2192 arrival"),
 E(["matter of debate","debate"], "Debate", "a discussion or argument about a subject", "a matter of debate", "debate \u2192 debatable \u2192 debating"),
 E(["general understanding","understanding"], "Understanding", "a person's knowledge or interpretation of something", "the general understanding", "understand \u2192 understanding \u2192 understandable"),
 E(["century"], "Century", "a period of one hundred years", "the 13th century", "century \u2192 centurial"),
 E(["canoes","canoe"], "Canoe", "a narrow boat moved with a paddle", "their canoes landed", "canoe \u2192 canoeing \u2192 canoeist"),
 E(["eventually"], "Eventually", "in the end; after a long time", "eventually landed", "eventual \u2192 eventually"),
 E(["shores","shore"], "Shore", "the land along the edge of a sea or lake", "New Zealand's shores"),
 E(["ideal"], "Ideal", "perfect; the best possible", "an ideal place to settle", "ideal \u2192 ideally \u2192 idealise"),
 E(["settle"], "Settle", "to go to live in a place permanently", "an ideal place to settle", "settle \u2192 settlement \u2192 settler"),
 E(["fertile"], "Fertile", "(of land) able to produce many crops or plants", "the land was fertile", "fertile \u2192 fertility \u2192 fertilise"),
 E(["thick"], "Thick", "dense; with many things close together", "thick forests", "thick \u2192 thickness \u2192 thicken"),
 E(["forests","forest"], "Forest", "a large area covered with trees", "thick forests", "forest \u2192 forestry \u2192 forested"),
 E(["firewood"], "Firewood", "wood used as fuel for a fire", "provided firewood"),
 E(["shelter"], "Shelter (n)", "a place giving protection from weather or danger", "firewood and shelter", "shelter \u2192 sheltered \u2192 sheltering"),
 E(["building materials","materials","material"], "Materials", "the substances from which something is made", "building materials"),
 E(["challenging"], "Challenging", "difficult in a way that tests ability", "life was challenging", "challenge \u2192 challenging \u2192 challenger"),
 E(["tribes","tribe"], "Tribe", "a group of people sharing customs, language and ancestry", "Polynesian tribes", "tribe \u2192 tribal \u2192 tribesman"),
 E(["adapt"], "Adapt", "to change in order to suit new conditions", "adapt to a new environment", "adapt \u2192 adaptation \u2192 adaptable"),
 E(["environment"], "Environment", "the natural surroundings in which one lives", "a new environment", "environment \u2192 environmental \u2192 environmentally"),
 E(["refer to","refer"], "Refer to", "to call or describe by a particular name", "refer to themselves as Maori", "refer \u2192 reference \u2192 referral"),
 E(["ordinary"], "Ordinary", "normal; not special or unusual", "'ordinary people'", "ordinary \u2192 ordinarily \u2192 extraordinary"),
 E(["in search of","search"], "In search of", "looking for; trying to find", "in search of opportunities", "search \u2192 searching \u2192 searcher"),
 E(["opportunities","opportunity"], "Opportunity", "a chance to do something good", "new opportunities", "opportunity \u2192 opportune \u2192 opportunistic"),
 E(["settlers","settler"], "Settler", "a person who goes to live in a new place", "European settlers", "settle \u2192 settler \u2192 settlement"),
 E(["sailors","sailor"], "Sailor", "a person who works on or sails a ship", "settlers and sailors", "sail \u2192 sailor \u2192 sailing"),
 E(["strange"], "Strange", "unusual or unfamiliar", "very strange", "strange \u2192 strangely \u2192 stranger"),
 E(["knowledge"], "Knowledge", "information and skills gained through experience", "a knowledge of navigation", "know \u2192 knowledge \u2192 knowledgeable"),
 E(["navigation"], "Navigation", "the skill of finding the way, especially by sea", "canoe-building and navigation", "navigate \u2192 navigation \u2192 navigator"),
 E(["skilled"], "Skilled", "having or needing ability and training", "skilled craftsmen", "skill \u2192 skilled \u2192 skilful"),
 E(["craftsmen","craftsman"], "Craftsman", "a worker skilled in making things by hand", "skilled craftsmen", "craft \u2192 craftsman \u2192 craftsmanship"),
 E(["archaeological"], "Archaeological", "relating to the study of human history through remains", "archaeological evidence", "archaeology \u2192 archaeological \u2192 archaeologist"),
 E(["evidence"], "Evidence", "facts or signs showing something is true", "archaeological evidence", "evident \u2192 evidence \u2192 evidently"),
 E(["tools","tool"], "Tool", "an instrument used to do work", "the tools they produced", "tool \u2192 tooling \u2192 toolkit"),
 E(["high quality","quality"], "Quality", "how good or bad something is; a high standard", "tools of high quality", "quality \u2192 qualitative"),
 E(["enabled","enable"], "Enable", "to make something possible", "enabled tribes to plant crops", "enable \u2192 enabled \u2192 enabling"),
 E(["plant"], "Plant (v)", "to put seeds or plants in the ground to grow", "plant and harvest crops", "plant \u2192 plantation \u2192 planting"),
 E(["harvest"], "Harvest", "to gather crops that are ready", "harvest crops", "harvest \u2192 harvesting \u2192 harvester"),
 E(["crops","crop"], "Crop", "a plant grown in large amounts for food", "plant crops"),
 E(["occupied with","occupied"], "Occupied with", "busy doing something", "occupied with making weapons", "occupy \u2192 occupied \u2192 occupation"),
 E(["weapons","weapon"], "Weapon", "an object used to fight or attack", "making weapons", "weapon \u2192 weaponry"),
 E(["knives","knife"], "Knife", "a tool with a blade for cutting", "knives and axes"),
 E(["axes","axe"], "Axe", "a tool with a heavy blade for chopping wood", "knives and axes"),
 E(["construction"], "Construction", "the act of building something", "used for construction", "construct \u2192 construction \u2192 constructive"),
 E(["fighting","fight"], "Fighting", "the act of physical conflict or battle", "construction and fighting", "fight \u2192 fighter \u2192 fighting"),
 E(["crafts","craft"], "Craft", "an activity needing skill with the hands", "some crafts were no longer done", "craft \u2192 crafted \u2192 craftsmanship"),
 E(["popular"], "Popular", "liked or done by many people", "crafts that had been popular", "popular \u2192 popularity \u2192 popularise"),
 E(["islands","island"], "Island", "a piece of land surrounded by water", "Polynesian islands", "island \u2192 islander"),
 E(["researchers","researcher"], "Researcher", "a person who studies a subject to find new facts", "researchers are unsure", "research \u2192 researcher \u2192 researched"),
 E(["unsure"], "Unsure", "not certain; having doubts", "researchers are unsure why", "sure \u2192 unsure \u2192 unsurely"),
 E(["pottery"], "Pottery", "objects made from baked clay", "pottery is an example", "pottery \u2192 potter"),
 E(["despite"], "Despite", "without being affected by; in spite of", "despite the fact", ""),
 E(["clay"], "Clay", "heavy, sticky earth used to make pots", "the clay needed for pots"),
 E(["pots","pot"], "Pot", "a round container, e.g. for cooking or plants", "pots and bowls"),
 E(["bowls","bowl"], "Bowl", "a round, deep dish", "pots and bowls"),
 E(["translated","translate"], "Translate", "to express words in another language", "can be translated as", "translate \u2192 translation \u2192 translator"),
 E(["decorative"], "Decorative", "intended to make something look attractive", "decorative work", "decorate \u2192 decorative \u2192 decoration"),
 E(["bone"], "Bone", "the hard parts that form an animal's skeleton", "bone and wood carving"),
 E(["greenstone"], "Greenstone", "a hard green stone (jade) valued for carving", "greenstone carving"),
 E(["carving","carvers","carve"], "Carving", "the art of cutting designs into wood or stone", "greenstone carving", "carve \u2192 carving \u2192 carver"),
 E(["influenced","influence"], "Influence (v)", "to affect the way something develops", "influenced by their heritage", "influence \u2192 influential \u2192 influencer"),
 E(["heritage"], "Heritage", "traditions and culture passed down from the past", "their Polynesian heritage"),
 E(["developed","develop"], "Develop", "to grow or create gradually", "developed their own style", "develop \u2192 development \u2192 developed"),
 E(["style"], "Style", "a distinctive way of doing or making something", "their own style", "style \u2192 stylish \u2192 stylistic"),
 E(["curved"], "Curved", "having a smooth, bent shape", "curved patterns", "curve \u2192 curved \u2192 curvy"),
 E(["patterns","pattern"], "Pattern", "a repeated decorative design", "curved patterns"),
 E(["spirals","spiral"], "Spiral", "a curve that winds round a central point", "patterns and spirals"),
 E(["inspired by","inspired","inspire"], "Inspire", "to give someone the idea for something", "inspired by plants", "inspire \u2192 inspiration \u2192 inspiring"),
 E(["apply to","apply"], "Apply to", "to be relevant to; to concern", "the term can apply to weaving", "apply \u2192 application \u2192 applicable"),
 E(["weaving","woven","weave"], "Weave", "to make cloth by crossing threads over and under", "the crafting of woven baskets", "weave \u2192 weaving \u2192 weaver \u2192 woven"),
 E(["baskets","basket"], "Basket", "a container made of woven material", "woven baskets and mats"),
 E(["mats","mat"], "Mat", "a flat piece of material for covering a floor", "baskets and mats"),
 E(["required","require"], "Require", "to need something", "required knowledge and skill", "require \u2192 requirement \u2192 required"),
 E(["skill"], "Skill", "the ability to do something well", "knowledge and skill", "skill \u2192 skilled \u2192 skilful"),
 E(["process"], "Process", "a series of actions to achieve a result", "a long process", "process \u2192 procedure \u2192 processing"),
 E(["patience"], "Patience", "the ability to wait or endure without complaint", "requiring great patience", "patient \u2192 patience \u2192 patiently"),
 E(["mineral","mineral's"], "Mineral", "a natural solid substance found in the earth", "this mineral's rarity", "mineral \u2192 mineralogy"),
 E(["rarity"], "Rarity", "the state of being uncommon", "because of its rarity", "rare \u2192 rarity \u2192 rarely"),
 E(["jewellery"], "Jewellery", "decorative objects worn on the body", "a piece of jewellery", "jewel \u2192 jewellery \u2192 jeweller"),
 E(["blade"], "Blade", "the flat cutting part of a knife or tool", "a cutting blade"),
 E(["prized possession","prized"], "Prized", "highly valued and treasured", "a prized possession", "prize \u2192 prized"),
 E(["possession","possess"], "Possession", "a thing that is owned", "a prized possession", "possess \u2192 possession \u2192 possessive"),
 E(["high status","status"], "Status", "a person's rank or position in society", "people of high status", "status \u2192 statuses"),
 E(["low-ranking","ranking"], "Low-ranking", "having a low position or rank", "low-ranking members", "rank \u2192 ranking \u2192 ranked"),
 E(["members","member"], "Member", "a person belonging to a group", "members of a tribe", "member \u2192 membership"),
 E(["possess"], "Possess", "to have or own something", "who would possess such objects", "possess \u2192 possession \u2192 possessor"),
 E(["native"], "Native", "originating naturally in a particular place", "no native mammals", "native \u2192 natively \u2192 nativity"),
 E(["mammals","mammal"], "Mammal", "a warm-blooded animal that feeds young with milk", "native mammals"),
 E(["depend on","depend"], "Depend on", "to rely on something for support", "depend on plants", "depend \u2192 dependence \u2192 dependent"),
 E(["clothing"], "Clothing", "garments worn on the body", "material for their clothing", "clothe \u2192 clothing \u2192 clothes"),
 E(["cloaks","cloak"], "Cloak", "a loose outer garment without sleeves", "their cloaks"),
 E(["experimented","experiment"], "Experiment (v)", "to try out new methods or ideas", "weavers experimented with bark", "experiment \u2192 experimental \u2192 experimentation"),
 E(["bark"], "Bark", "the hard outer covering of a tree", "the inner bark"),
 E(["unsuitable"], "Unsuitable", "not right or appropriate for a purpose", "found it unsuitable", "suit \u2192 suitable \u2192 unsuitable"),
 E(["dried-out","dried"], "Dried-out", "having lost all moisture", "the dried-out leaves", "dry \u2192 dried \u2192 drying"),
 E(["fibres","fibre"], "Fibre", "a thin thread of natural or man-made material", "leaves and fibres", "fibre \u2192 fibrous"),
 E(["flax"], "Flax", "a plant whose fibres are used to make cloth", "the flax plant"),
 E(["solution"], "Solution", "a way of solving a problem", "provided a solution", "solve \u2192 solution"),
 E(["decorated","decorate"], "Decorate", "to add things to make more attractive", "it could be decorated", "decorate \u2192 decoration \u2192 decorative"),
 E(["borders","border"], "Border", "the edge or boundary of something", "borders might be dyed", "border \u2192 bordering"),
 E(["dyed","dye"], "Dye (v)", "to change the colour of something using a substance", "dyed black or red", "dye \u2192 dyed \u2192 dyeing"),
 E(["superior"], "Superior", "higher in quality or rank", "superior ones for chiefs", "superior \u2192 superiority"),
 E(["chiefs","chief"], "Chief", "the leader of a tribe or group", "made for chiefs", "chief \u2192 chiefly \u2192 chieftain"),
 E(["feathers","feather"], "Feather", "one of the light parts covering a bird's body", "feathers from kiwi", "feather \u2192 feathered \u2192 feathery"),
 E(["attached","attach"], "Attach", "to fasten or join one thing to another", "feathers might be attached", "attach \u2192 attachment \u2192 attached"),
 E(["rectangular"], "Rectangular", "shaped like a rectangle", "rectangular in shape", "rectangle \u2192 rectangular"),
 E(["sleeves","sleeve"], "Sleeve", "the part of a garment covering the arm", "had no sleeves"),
 E(["hood"], "Hood", "a covering for the head attached to a garment", "neither was a hood a feature"),
 E(["garment"], "Garment", "a piece of clothing", "a feature of this garment"),
 E(["fastened","fasten"], "Fasten", "to close or join firmly", "fastened around the neck", "fasten \u2192 fastener \u2192 fastening"),
 E(["waist"], "Waist", "the narrow part of the body above the hips", "came only to the waist"),
 E(["pins","pin"], "Pin", "a thin pointed piece of metal for fastening", "pins made of bone"),
 E(["secured","secure"], "Secure (v)", "to fasten or fix something firmly", "secured at the shoulder", "secure \u2192 secured \u2192 security"),
 E(["shoulder"], "Shoulder", "the part of the body where the arm joins", "at the shoulder"),
 E(["ceremonial"], "Ceremonial", "used for or relating to formal occasions", "ceremonial occasions", "ceremony \u2192 ceremonial \u2192 ceremonially"),
 E(["occasions","occasion"], "Occasion", "a particular event or time", "ceremonial occasions", "occasion \u2192 occasional \u2192 occasionally"),
 E(["available"], "Available", "able to be obtained or used", "the material available", "avail \u2192 available \u2192 availability"),
 E(["loose-fitting","loose"], "Loose-fitting", "not tight; hanging loosely", "cloaks were loose-fitting", "loose \u2192 loosely \u2192 loosen"),
 E(["protected","protect"], "Protect", "to keep safe from harm", "protected wearers from sun", "protect \u2192 protection \u2192 protective"),
 E(["wearers","wearer"], "Wearer", "a person who wears something", "protected wearers", "wear \u2192 wearer \u2192 wearable"),
 E(["sunshine"], "Sunshine", "the light and warmth of the sun", "strong sunshine", "sun \u2192 sunshine \u2192 sunny"),
 E(["fur"], "Fur", "the soft hair covering some animals", "a cloak made from fur"),
 E(["wool"], "Wool", "the soft hair of sheep used to make cloth", "fur or wool"),
 E(["insulation"], "Insulation", "material that keeps in heat or keeps out cold", "insulation from the cold", "insulate \u2192 insulation \u2192 insulated"),
 E(["warriors","warrior"], "Warrior", "a person who fights in battles; a soldier", "the warriors of a tribe"),
 E(["tough"], "Tough", "strong and not easily broken", "tough fibres", "tough \u2192 toughness \u2192 toughen"),
 E(["mountain cabbage tree","cabbage tree"], "Cabbage tree", "a tall New Zealand tree with tough fibrous leaves", "the mountain cabbage tree"),
 E(["entire"], "Entire", "whole; complete", "the entire process", "entire \u2192 entirely \u2192 entirety"),
 E(["involved","involve"], "Involve", "to include as a necessary part", "what the process involved", "involve \u2192 involvement \u2192 involved"),
 E(["soak"], "Soak", "to leave something in liquid to become wet", "left to soak in water", "soak \u2192 soaked \u2192 soaking"),
 E(["soften"], "Soften", "to make or become softer", "to soften them", "soft \u2192 soften \u2192 softener"),
 E(["constructed","construct"], "Construct", "to build or make something", "the cloak was constructed", "construct \u2192 construction \u2192 constructed"),
 E(["mud"], "Mud", "soft, wet earth", "a special kind of mud"),
 E(["collected","collect"], "Collect", "to gather things together", "mud collected from riverbeds", "collect \u2192 collection \u2192 collector"),
 E(["riverbeds","riverbed"], "Riverbed", "the bottom of a river", "collected from riverbeds"),
 E(["rich in","rich"], "Rich in", "containing a large amount of something", "rich in iron", "rich \u2192 richness \u2192 enrich"),
 E(["iron"], "Iron", "a strong, common metallic element", "rich in iron"),
 E(["volcanic"], "Volcanic", "relating to or produced by volcanoes", "volcanic landscape", "volcano \u2192 volcanic"),
 E(["landscape"], "Landscape", "the visible features of an area of land", "volcanic landscape", "landscape \u2192 landscaping"),
 E(["advantage"], "Advantage", "a condition giving a benefit", "the particular advantage", "advantage \u2192 advantageous"),
 E(["reduce"], "Reduce", "to make smaller or less", "reduce the impact", "reduce \u2192 reduction \u2192 reduced"),
 E(["impact"], "Impact (n)", "a strong effect or influence", "reduce the impact of spears", "impact \u2192 impactful"),
 E(["spear tips","spear"], "Spear", "a weapon with a long shaft and pointed tip", "the impact of spear tips"),
 E(["enemy"], "Enemy", "a person or group that is hostile to another", "enemy tribes", "enemy \u2192 enmity"),
 E(["fortunate"], "Fortunate", "lucky", "it is fortunate that", "fortune \u2192 fortunate \u2192 fortunately"),
 E(["survive"], "Survive", "to continue to exist or live", "some cloaks still survive", "survive \u2192 survival \u2192 survivor"),
 E(["insight"], "Insight", "a clear, deep understanding", "further insight", "insight \u2192 insightful"),
 E(["techniques","technique"], "Technique", "a particular way of doing something", "construction techniques", "technique \u2192 technical \u2192 technician"),
]


P2_PARAS = [
"Matthew Walker dreads the question 'What do you do?' On an aeroplane it usually means that while everyone else watches movies, he will find himself giving a talk for the benefit of passengers and crew alike. To be specific, Walker is the director of the Center for Human Sleep Science at the University of California. No wonder people long for his advice. As the line between work and leisure grows more blurred, rare is the person who doesn't worry about their sleep. Indeed, it's Walker's conviction that we are in the midst of a 'catastrophic sleep-loss epidemic'. He has now written Why We Sleep, the idea being that once people know of the powerful links between sleep loss and poor health, they will try harder to get the recommended eight hours a night. Sleep deprivation constitutes anything less than seven. 'No one is doing anything about it but things have to change. But when did you ever see a national health service poster urging sleep on people? When did a doctor prescribe, not sleeping pills, but sleep itself? It needs to be prioritised.'",
"Why are we so sleep-deprived in this century? In 1942, less than 8% of the population was trying to survive on six hours or less sleep a night; in 2017, almost one in two people is. Some reasons are obvious, but Walker believes, too, that in the developed world sleep is strongly associated with weakness. 'We want to seem busy, and one way we express that is by proclaiming how little sleep we're getting. When I give lectures, people wait behind until there is no one around and then tell me quietly: \"I seem to be one of those people who need eight or nine hours' sleep.\" It's embarrassing to say it in public.'",
"Walker has found clear evidence that without sleep, there is low energy and disease, and with sleep, there is vitality and health. More than 20 studies all report the same relationship: the shorter your sleep, the shorter your life. For example, adults aged 45 years or older who sleep less than six hours a night are 200% more likely to have a heart attack, as compared with those sleeping seven or eight. This is because even one night of sleep reduction will affect a person's heart and significantly increase their blood pressure as a result. Walker also points out that when your sleep becomes short, you are susceptible to weight gain. Among the reasons for this are the fact that inadequate sleep increases levels of the hunger-signalling hormone, ghrelin. 'I'm not going to say that the obesity crisis is caused by the sleep-loss epidemic alone,' says Walker. 'However, processed food and sedentary lifestyles do not adequately explain its rise. It's now clear that sleep is that third ingredient.'",
"Sleep also has a powerful effect on the immune system, which is why, when we have flu, our first instinct is to go to bed. If you are tired, you are more likely to get sick. The well-rested also respond better to the flu vaccine, so this is something people should bear in mind before visiting their doctors. Walker's book also includes a long section on dreams. Here he details the various ways in which deep sleep - the part when we begin to dream - helps us deal with our emotional experiences. He points to how important deep sleep is to young children. If they don't get enough, managing aggressive behaviour becomes harder and harder. Does Walker take his own advice when it comes to sleep? 'Yes. I give myself a non-negotiable eight-hour sleep opportunity every night, and I keep very regular hours. I take my sleep incredibly seriously because I have seen the evidence.'",
"Sleep research shows that we sleep in 90-minute cycles, and it's only towards the end of each that we go into deep sleep. Each cycle comprises of NREM sleep (non-rapid eye movement sleep), followed by REM (rapid eye movement) sleep. 'During NREM sleep your body settles into this lovely low state of energy,' Walker explains. 'REM sleep, on the other hand, is an incredibly active brain state. Your heart and nervous system go through spurts of activity.' Because we need four or five of these cycles to stay healthy, it's important for people to break bad sleep habits. For example, they should not be regularly working late into the night as this affects cognitive functioning. Depending on sleeping pills is also not a good idea, as it can have a damaging effect on memory.",
"So what can individuals do to ensure they get the right amount of sleep? Firstly, we could think about getting ready for sleep in the same way we prepare for the end of a workout - say, on a spin bike. 'People use alarms to wake up,' Walker says. 'So why don't we have a bedtime alarm to tell us we've got half an hour, that we should start cycling down?' Companies should think about rewarding sleep. Productivity will rise and motivation will be improved. We can also systematically measure our sleep by using personal tracking devices, Walker says, and points out that some far-sighted companies in the US already give employees time off if they get enough of it. While some researchers recommend banning digital devices from the bedroom because of their effect on the sleep-inducing hormone melatonin, Walker believes that technology will eventually be an aid to sleep, as it helps us discover more about the way we function.",
]

P2_ENTRIES = [
 E(["dreads","dread"], "Dread", "to feel great fear or worry about something", "he dreads the question", "dread \u2192 dreadful \u2192 dreaded"),
 E(["aeroplane"], "Aeroplane", "a powered flying vehicle with wings", "on an aeroplane"),
 E(["benefit"], "Benefit (n)", "an advantage or help", "for the benefit of passengers", "benefit \u2192 beneficial \u2192 beneficiary"),
 E(["passengers","passenger"], "Passenger", "a person travelling in a vehicle but not driving", "passengers and crew"),
 E(["crew"], "Crew", "the people who work on a ship, plane or train", "passengers and crew"),
 E(["alike"], "Alike", "in a similar way; both equally", "passengers and crew alike", ""),
 E(["director"], "Director", "a person who manages or leads an organisation", "the director of the Center", "direct \u2192 director \u2192 directorship"),
 E(["no wonder","wonder"], "No wonder", "it is not surprising", "no wonder people want his advice"),
 E(["long for","long"], "Long for", "to want something very much", "people long for his advice", "long \u2192 longing"),
 E(["advice"], "Advice", "an opinion offered about what to do", "his advice", "advise \u2192 advice \u2192 adviser"),
 E(["leisure"], "Leisure", "free time when one can relax", "work and leisure", "leisure \u2192 leisurely"),
 E(["blurred","blur"], "Blurred", "not clear or distinct", "the line grows more blurred", "blur \u2192 blurred \u2192 blurry"),
 E(["worry"], "Worry (v)", "to feel anxious about something", "worry about their sleep", "worry \u2192 worried \u2192 worrying"),
 E(["conviction"], "Conviction", "a firmly held belief", "it's Walker's conviction", "convince \u2192 conviction \u2192 convinced"),
 E(["in the midst of","midst"], "In the midst of", "in the middle of; during", "in the midst of an epidemic"),
 E(["catastrophic"], "Catastrophic", "extremely harmful; disastrous", "a catastrophic epidemic", "catastrophe \u2192 catastrophic \u2192 catastrophically"),
 E(["sleep-loss","sleep loss"], "Sleep loss", "the condition of not getting enough sleep", "a sleep-loss epidemic"),
 E(["epidemic"], "Epidemic", "the rapid spread of something through a population", "a sleep-loss epidemic", "epidemic \u2192 epidemiology"),
 E(["powerful"], "Powerful", "having great effect or strength", "powerful links", "power \u2192 powerful \u2192 powerfully"),
 E(["links","link"], "Link (n)", "a connection between two things", "links between sleep and health", "link \u2192 linked \u2192 linkage"),
 E(["poor health","health"], "Health", "the state of being well in body and mind", "poor health", "health \u2192 healthy \u2192 healthily"),
 E(["recommended","recommend"], "Recommend", "to advise as good or suitable", "the recommended eight hours", "recommend \u2192 recommendation \u2192 recommended"),
 E(["sleep deprivation","deprivation"], "Deprivation", "the lack of something needed", "sleep deprivation", "deprive \u2192 deprivation \u2192 deprived"),
 E(["constitutes","constitute"], "Constitute", "to be or amount to something", "deprivation constitutes less than seven", "constitute \u2192 constitution \u2192 constituent"),
 E(["national health service","health service"], "Health service", "a public system providing medical care", "a health service poster"),
 E(["urging","urge"], "Urge (v)", "to strongly advise or encourage", "urging sleep on people", "urge \u2192 urgent \u2192 urgency"),
 E(["prescribe"], "Prescribe", "(of a doctor) to officially advise treatment", "a doctor prescribe sleep", "prescribe \u2192 prescription \u2192 prescribed"),
 E(["sleeping pills","pills","pill"], "Sleeping pills", "medicine taken to help one sleep", "not sleeping pills"),
 E(["prioritised","prioritise"], "Prioritise", "to treat something as most important", "it needs to be prioritised", "priority \u2192 prioritise \u2192 prioritised"),
 E(["sleep-deprived","deprived"], "Sleep-deprived", "not having had enough sleep", "why are we so sleep-deprived", "deprive \u2192 deprived \u2192 deprivation"),
 E(["population"], "Population", "all the people living in an area", "8% of the population", "populate \u2192 population \u2192 populated"),
 E(["obvious"], "Obvious", "easy to see or understand; clear", "some reasons are obvious", "obvious \u2192 obviously"),
 E(["developed world","developed"], "Developed world", "the wealthier, industrialised countries", "in the developed world"),
 E(["associated with","associated"], "Associated with", "connected with in the mind", "sleep is associated with weakness", "associate \u2192 association \u2192 associated"),
 E(["weakness"], "Weakness", "a lack of strength", "associated with weakness", "weak \u2192 weakness \u2192 weaken"),
 E(["proclaiming","proclaim"], "Proclaim", "to announce publicly and firmly", "proclaiming how little sleep we get", "proclaim \u2192 proclamation"),
 E(["lectures","lecture"], "Lecture", "a formal talk to teach people", "when I give lectures", "lecture \u2192 lecturer \u2192 lecturing"),
 E(["embarrassing","embarrass"], "Embarrassing", "causing a feeling of awkward shame", "it's embarrassing to say", "embarrass \u2192 embarrassing \u2192 embarrassment"),
 E(["in public","public"], "In public", "in a place where others can see or hear", "to say it in public"),
 E(["clear evidence","evidence"], "Evidence", "facts that prove something is true", "clear evidence", "evident \u2192 evidence \u2192 evidently"),
 E(["disease"], "Disease", "an illness affecting the body", "low energy and disease", "disease \u2192 diseased"),
 E(["vitality"], "Vitality", "the state of being strong and full of energy", "vitality and health", "vital \u2192 vitality \u2192 vitally"),
 E(["studies","study"], "Study (n)", "a piece of research on a subject", "more than 20 studies", "study \u2192 studies \u2192 studied"),
 E(["relationship"], "Relationship", "the way things are connected", "report the same relationship", "relate \u2192 relationship \u2192 related"),
 E(["heart attack"], "Heart attack", "a sudden, dangerous failure of the heart", "more likely to have a heart attack"),
 E(["reduction","reduce"], "Reduction", "the act of making something less", "one night of sleep reduction", "reduce \u2192 reduction \u2192 reduced"),
 E(["significantly","significant"], "Significantly", "in an important or noticeable way", "significantly increase", "significant \u2192 significantly \u2192 significance"),
 E(["blood pressure"], "Blood pressure", "the force of blood pushing against artery walls", "increase blood pressure"),
 E(["points out","point out"], "Point out", "to draw attention to a fact", "Walker points out that"),
 E(["susceptible to","susceptible"], "Susceptible to", "easily affected or harmed by", "susceptible to weight gain", "susceptible \u2192 susceptibility"),
 E(["weight gain","gain"], "Weight gain", "an increase in body weight", "susceptible to weight gain"),
 E(["inadequate"], "Inadequate", "not enough; insufficient", "inadequate sleep", "adequate \u2192 inadequate \u2192 inadequacy"),
 E(["levels","level"], "Level (n)", "the amount of something present", "increases levels of ghrelin", "level \u2192 levels"),
 E(["hormone","hormones"], "Hormone", "a chemical in the body that controls functions", "the hunger-signalling hormone", "hormone \u2192 hormonal"),
 E(["obesity"], "Obesity", "the condition of being very overweight", "the obesity crisis", "obese \u2192 obesity"),
 E(["crisis"], "Crisis", "a time of great difficulty or danger", "the obesity crisis", "crisis \u2192 crises \u2192 critical"),
 E(["processed food","processed"], "Processed food", "food that has been treated or prepared industrially", "processed food", "process \u2192 processed \u2192 processing"),
 E(["sedentary"], "Sedentary", "involving much sitting and little exercise", "sedentary lifestyles", "sedentary \u2192 sedentariness"),
 E(["lifestyles","lifestyle"], "Lifestyle", "the way in which a person lives", "sedentary lifestyles"),
 E(["adequately","adequate"], "Adequately", "in a way that is enough or satisfactory", "do not adequately explain", "adequate \u2192 adequately \u2192 adequacy"),
 E(["ingredient"], "Ingredient", "one of the parts that make up a whole", "the third ingredient", "ingredient \u2192 ingredients"),
 E(["immune system","immune"], "Immune system", "the body's defence against illness", "effect on the immune system", "immune \u2192 immunity \u2192 immunise"),
 E(["flu"], "Flu", "a common infectious illness (influenza)", "when we have flu"),
 E(["instinct"], "Instinct", "a natural tendency to behave a certain way", "our first instinct", "instinct \u2192 instinctive \u2192 instinctively"),
 E(["tired"], "Tired", "in need of rest or sleep", "if you are tired", "tire \u2192 tired \u2192 tiring"),
 E(["sick"], "Sick", "ill; not well", "more likely to get sick", "sick \u2192 sickness \u2192 sickly"),
 E(["well-rested"], "Well-rested", "having had enough rest or sleep", "the well-rested respond better"),
 E(["respond"], "Respond", "to react to something", "respond better to the vaccine", "respond \u2192 response \u2192 responsive"),
 E(["vaccine"], "Vaccine", "a substance that protects against a disease", "the flu vaccine", "vaccine \u2192 vaccinate \u2192 vaccination"),
 E(["bear in mind"], "Bear in mind", "to remember and consider something", "something to bear in mind"),
 E(["dreams","dream"], "Dream", "images and thoughts during sleep", "a section on dreams", "dream \u2192 dreaming \u2192 dreamer"),
 E(["details","detail"], "Detail (v)", "to describe fully and exactly", "he details the ways", "detail \u2192 detailed \u2192 detailing"),
 E(["deep sleep"], "Deep sleep", "the stage of sleep that is hardest to wake from", "how important deep sleep is"),
 E(["deal with"], "Deal with", "to take action to manage something", "deal with our emotional experiences"),
 E(["emotional"], "Emotional", "relating to feelings", "emotional experiences", "emotion \u2192 emotional \u2192 emotionally"),
 E(["managing","manage"], "Manage", "to control or deal with successfully", "managing aggressive behaviour", "manage \u2192 management \u2192 manageable"),
 E(["aggressive"], "Aggressive", "ready to attack or behave angrily", "aggressive behaviour", "aggression \u2192 aggressive \u2192 aggressively"),
 E(["behaviour"], "Behaviour", "the way in which one acts", "aggressive behaviour", "behave \u2192 behaviour \u2192 behavioural"),
 E(["non-negotiable"], "Non-negotiable", "not able to be changed or discussed", "a non-negotiable opportunity", "negotiate \u2192 negotiable \u2192 non-negotiable"),
 E(["regular hours","regular"], "Regular", "happening at fixed, even times", "I keep regular hours", "regular \u2192 regularly \u2192 regularity"),
 E(["incredibly","incredible"], "Incredibly", "extremely; very", "incredibly seriously", "incredible \u2192 incredibly"),
 E(["cycles","cycle"], "Cycle (n)", "a series of events that repeats regularly", "90-minute cycles", "cycle \u2192 cyclical \u2192 cycling"),
 E(["comprises","comprise"], "Comprise", "to consist of; to be made up of", "each cycle comprises NREM sleep", "comprise \u2192 comprised"),
 E(["settles into","settle"], "Settle into", "to become comfortable in a state", "your body settles into a low state", "settle \u2192 settled \u2192 settling"),
 E(["active"], "Active", "doing things; full of energy or movement", "an active brain state", "act \u2192 active \u2192 activity"),
 E(["nervous system"], "Nervous system", "the body's network of nerves and the brain", "heart and nervous system"),
 E(["spurts","spurt"], "Spurt", "a sudden short burst of activity", "spurts of activity"),
 E(["healthy"], "Healthy", "in good health; good for health", "to stay healthy", "health \u2192 healthy \u2192 healthily"),
 E(["habits","habit"], "Habit", "a regular, often automatic, behaviour", "break bad sleep habits", "habit \u2192 habitual \u2192 habitually"),
 E(["cognitive"], "Cognitive", "relating to thinking and understanding", "cognitive functioning", "cognition \u2192 cognitive \u2192 cognitively"),
 E(["functioning","function"], "Functioning", "the way something works or operates", "cognitive functioning", "function \u2192 functioning \u2192 functional"),
 E(["damaging","damage"], "Damaging", "causing harm", "a damaging effect", "damage \u2192 damaging \u2192 damaged"),
 E(["memory"], "Memory", "the ability to remember information", "effect on memory", "memory \u2192 memorise \u2192 memorable"),
 E(["individuals","individual"], "Individual", "a single person", "what can individuals do", "individual \u2192 individually \u2192 individuality"),
 E(["ensure"], "Ensure", "to make certain something happens", "ensure they get enough sleep", "ensure \u2192 ensured"),
 E(["prepare"], "Prepare", "to make ready", "prepare for the end of a workout", "prepare \u2192 preparation \u2192 prepared"),
 E(["workout"], "Workout", "a period of physical exercise", "the end of a workout", "work out \u2192 workout"),
 E(["alarms","alarm"], "Alarm", "a device that warns or signals with a sound", "people use alarms", "alarm \u2192 alarming \u2192 alarmed"),
 E(["bedtime"], "Bedtime", "the time when one usually goes to bed", "a bedtime alarm"),
 E(["rewarding","reward"], "Reward (v)", "to give something in return for good behaviour", "rewarding sleep", "reward \u2192 rewarding \u2192 rewarded"),
 E(["productivity"], "Productivity", "the rate at which work is done", "productivity will rise", "produce \u2192 productivity \u2192 productive"),
 E(["motivation"], "Motivation", "the reason or drive to do something", "motivation will improve", "motivate \u2192 motivation \u2192 motivated"),
 E(["systematically","systematic"], "Systematically", "in an organised, methodical way", "measure our sleep systematically", "system \u2192 systematic \u2192 systematically"),
 E(["measure"], "Measure (v)", "to find the size or amount of something", "measure our sleep", "measure \u2192 measurement \u2192 measurable"),
 E(["tracking devices","tracking","device","devices"], "Tracking device", "equipment that records and follows activity", "personal tracking devices", "track \u2192 tracking \u2192 tracker"),
 E(["far-sighted"], "Far-sighted", "able to plan wisely for the future", "far-sighted companies", "sight \u2192 far-sighted"),
 E(["employees","employee"], "Employee", "a person who works for an organisation", "give employees time off", "employ \u2192 employee \u2192 employer"),
 E(["time off"], "Time off", "a period away from work", "give employees time off"),
 E(["banning","ban"], "Ban (v)", "to officially forbid something", "banning digital devices", "ban \u2192 banned \u2192 banning"),
 E(["sleep-inducing","inducing"], "Sleep-inducing", "causing or helping sleep", "the sleep-inducing hormone", "induce \u2192 inducing \u2192 induction"),
 E(["melatonin"], "Melatonin", "a hormone that helps control the sleep cycle", "the hormone melatonin"),
 E(["technology"], "Technology", "machines and methods based on science", "technology will be an aid", "technology \u2192 technological \u2192 technologically"),
 E(["aid"], "Aid (n)", "help or support", "an aid to sleep", "aid \u2192 aided"),
 E(["function"], "Function (v)", "to work or operate", "the way we function", "function \u2192 functional \u2192 functioning"),
]


P3_PARAS = [
"The World Health Organisation has produced a report predicting that 9.8 billion of us will be living on this planet by 2050. Of that number, 72% will be living in urban areas - a higher proportion than ever before. Presented with this information, governments have a duty to consider how best to meet the needs of city residents, and not just for the short-term. Certain problems associated with urban living have been highlighted by research company Richmond-Carver in its latest global survey. At the top of the list of survey respondents' concerns is the fact that competition amongst tenants for rental properties has driven the median price up - so much so people need to hold down two or more jobs to meet all their expenses. Another issue the survey highlighted is the difficulty commuters face. Overcrowding means that seats are often not available on long journeys, but more significant is that schedules are unreliable. Many studies have shown the effect that has on a country's productivity. Interestingly, certain problems seem more common in some cities than others: respondents from increasingly crowded European cities, including Manchester and Barcelona, commented on how their quality of life was affected by loud machinery, other people's music and car alarms. Something the survey failed to ask about was the value people placed on having access to nature in urban neighbourhoods. However, some countries are already moving forward. Singapore is a prime example; its rooftop gardens make the city a far more desirable place to live. It is the Singaporean government that is behind this push for sustainable living.",
"Perhaps some clearer government direction would benefit other cities. Take New York City, a place where I frequently meet up with other researchers in my field. Luckily for me, I am driven from the airport to the research centre, so do not need to navigate the freeways and constant congestion. Admittedly my experience of the urban lifestyle here is limited to the hotels I stay in, and the blocks within a three-kilometre walk. But whenever I leave my room in search of an outlet providing fruit or anything with nutritional value, none can be found. It seems ridiculous that this should be the case. New York has made great advances in redeveloping its museums and arts centres, but authorities must recognise that people's basic needs must be met first.",
"Sometimes these basic needs are misunderstood. In some urban areas, new residential developments are provided with security features such as massive metal fences and multiple gates in the belief that these will make residents safer. There is little evidence such steps make a difference in this way, but we do know they make residents feel reluctant to go outside and walk around their neighbourhood. Instead they are more likely to remain inactive indoors. Grassy areas inside fenced developments are hardly used by householders or tenants either. All this adds up to a feeling of being cut off from others.",
"So where are planners and developers going wrong? Inviting a group of locals to attend a consultation event is the conventional method for discovering what a community might want. The issue here is that it often attracts the same few voices with the same few wishes. But the internet now makes it possible for others to contribute. A community website can be a place where local people propose ideas for making their neighbourhood a better place to live. Developers that pay attention to these ideas can get a clearer picture of the things residents actually want and reduce the risk of throwing away money on things they don't.",
"An example of a project that truly meets the needs of residents is Container City - a development in London's Docklands area. Constructed from metal containers once used to transport cargo on ships, it is a five-storey architectural masterpiece. The containers have been turned into sunny work studios, and despite their limited size, some come with a bed, shower and kitchen unit. Smart planning and skilful construction mean they take up very little room. Furniture and fittings are made from recycled products. Other countries have their own versions of Container City - Amsterdam and Copenhagen have created container dormitories to house students - but the Docklands site shows how work and living areas can effectively be combined. The units are ideal for young entrepreneurs hoping to establish a business while keeping costs down.",
"Successful development is taking place in many urban areas around the world, and city planners have a duty to see for themselves the transforming effect this can have on residents' lives. There is no better way to do this than to visit these places in person. These might be neighbourhoods constructed for the first time, or developers might have transformed what was already there. In either case, the idea of cars determining urban planning, and indeed the whole concept of private car ownership, is now outdated and must be abandoned. Instead, the layout of an area under development must make it easier for people to meet up in pedestrianised zones and community spaces. At the heart of the development should be a cultural area, providing venues for art, music and street theatre. Such activities bring communities together, and do far more for positive relations than a new mall or shopping precinct. For this reason, these kinds of performance spaces should be prioritised. Finally, planners and developers must be obliged to create, within the same neighbourhood, different types of homes for wealthy professionals, for families, for the elderly and for young people just starting out. This kind of mix is essential to ensure people can buy a home in an area convenient for work, and for a community to stay alive.",
]

P3_ENTRIES = [
 E(["predicting","predict"], "Predict", "to say what will happen in the future", "a report predicting growth", "predict \u2192 prediction \u2192 predictable"),
 E(["billion"], "Billion", "the number 1,000,000,000", "9.8 billion of us"),
 E(["planet"], "Planet", "a large body in space orbiting a star, e.g. Earth", "living on this planet", "planet \u2192 planetary"),
 E(["urban areas","urban"], "Urban", "relating to a town or city", "living in urban areas", "urban \u2192 urbanise \u2192 urbanisation"),
 E(["proportion"], "Proportion", "a part or share of a whole", "a higher proportion", "proportion \u2192 proportional \u2192 proportionate"),
 E(["governments","government"], "Government", "the group of people who rule a country", "governments have a duty", "govern \u2192 government \u2192 governmental"),
 E(["duty"], "Duty", "something one is required to do", "a duty to consider", "duty \u2192 dutiful"),
 E(["consider"], "Consider", "to think carefully about something", "consider how to meet needs", "consider \u2192 consideration \u2192 considerable"),
 E(["meet the needs","needs","need"], "Meet the needs", "to satisfy what is required", "meet the needs of residents"),
 E(["residents","resident"], "Resident", "a person who lives in a place", "city residents", "reside \u2192 resident \u2192 residence"),
 E(["short-term"], "Short-term", "lasting only a short time", "not just for the short-term", "term \u2192 short-term \u2192 long-term"),
 E(["associated with","associated"], "Associated with", "connected with", "problems associated with urban living", "associate \u2192 association \u2192 associated"),
 E(["highlighted","highlight"], "Highlight (v)", "to draw attention to something", "highlighted by the survey", "highlight \u2192 highlighted"),
 E(["global"], "Global", "relating to the whole world", "a global survey", "globe \u2192 global \u2192 globally"),
 E(["survey"], "Survey", "a study of opinions or facts from many people", "its latest survey", "survey \u2192 surveyor"),
 E(["respondents","respondent"], "Respondent", "a person who answers a survey or question", "survey respondents", "respond \u2192 respondent \u2192 response"),
 E(["concerns","concern"], "Concern (n)", "a worry or matter of importance", "respondents' concerns", "concern \u2192 concerned \u2192 concerning"),
 E(["competition"], "Competition", "rivalry to obtain something", "competition amongst tenants", "compete \u2192 competition \u2192 competitive"),
 E(["tenants","tenant"], "Tenant", "a person who rents a property", "competition amongst tenants", "tenant \u2192 tenancy"),
 E(["rental properties","rental","properties","property"], "Property", "a building or land owned by someone", "rental properties", "property \u2192 properties"),
 E(["driven","drive"], "Drive up", "to cause an amount to rise sharply", "driven the price up", "drive \u2192 driven \u2192 driving"),
 E(["median"], "Median", "the middle value in a set of numbers", "the median price", "median \u2192 medium"),
 E(["hold down","hold down two"], "Hold down (a job)", "to keep a job over time", "hold down two jobs"),
 E(["expenses","expense"], "Expense", "money spent on something; a cost", "to meet their expenses", "expense \u2192 expenses \u2192 expensive"),
 E(["issue"], "Issue (n)", "an important problem or topic", "another issue", "issue \u2192 issues"),
 E(["commuters","commuter"], "Commuter", "a person who travels to work regularly", "the difficulty commuters face", "commute \u2192 commuter \u2192 commuting"),
 E(["overcrowding","crowded"], "Overcrowding", "the state of too many people in one space", "overcrowding means no seats", "crowd \u2192 overcrowding \u2192 crowded"),
 E(["journeys","journey"], "Journey", "an act of travelling from one place to another", "long journeys"),
 E(["significant"], "Significant", "important enough to have an effect", "more significant", "signify \u2192 significant \u2192 significance"),
 E(["schedules","schedule"], "Schedule", "a plan of times for events or activities", "schedules are unreliable", "schedule \u2192 scheduled \u2192 scheduling"),
 E(["unreliable"], "Unreliable", "not able to be trusted or depended on", "schedules are unreliable", "rely \u2192 reliable \u2192 unreliable"),
 E(["effect"], "Effect (n)", "a result or change produced", "the effect on productivity", "effect \u2192 effective \u2192 effectively"),
 E(["productivity"], "Productivity", "the rate at which work is produced", "a country's productivity", "produce \u2192 productivity \u2192 productive"),
 E(["common"], "Common", "happening often; widespread", "more common in some cities", "common \u2192 commonly \u2192 commonness"),
 E(["quality of life"], "Quality of life", "the general well-being of a person", "their quality of life"),
 E(["machinery"], "Machinery", "machines as a group", "loud machinery", "machine \u2192 machinery"),
 E(["access to","access"], "Access (n)", "the right or ability to use something", "access to nature", "access \u2192 accessible \u2192 accessibility"),
 E(["nature"], "Nature", "the natural world of plants, animals and land", "access to nature", "nature \u2192 natural \u2192 naturally"),
 E(["neighbourhoods","neighbourhood"], "Neighbourhood", "a district or area within a town", "urban neighbourhoods", "neighbour \u2192 neighbourhood \u2192 neighbouring"),
 E(["moving forward","move forward"], "Move forward", "to make progress", "some countries are moving forward"),
 E(["prime example","prime"], "Prime", "of the best quality; main", "a prime example", "prime \u2192 primary \u2192 primarily"),
 E(["rooftop gardens","rooftop"], "Rooftop", "the top outer surface of a building", "its rooftop gardens"),
 E(["desirable"], "Desirable", "worth having; attractive", "a more desirable place", "desire \u2192 desirable \u2192 desirability"),
 E(["push for","push"], "Push (n)", "a determined effort to achieve something", "this push for sustainable living", "push \u2192 pushed \u2192 pushing"),
 E(["sustainable living","sustainable"], "Sustainable", "able to continue without harming the environment", "sustainable living", "sustain \u2192 sustainable \u2192 sustainability"),
 E(["direction"], "Direction", "guidance or instruction on what to do", "clearer government direction", "direct \u2192 direction \u2192 directional"),
 E(["benefit"], "Benefit (v)", "to be helpful or useful to", "would benefit other cities", "benefit \u2192 beneficial \u2192 beneficiary"),
 E(["frequently"], "Frequently", "often", "I frequently meet up", "frequent \u2192 frequently \u2192 frequency"),
 E(["field"], "Field", "a subject of study or area of work", "researchers in my field", "field \u2192 fields"),
 E(["navigate"], "Navigate", "to find one's way through a place", "navigate the freeways", "navigate \u2192 navigation \u2192 navigator"),
 E(["freeways","freeway"], "Freeway", "a wide, fast road for vehicles", "the freeways", ""),
 E(["constant"], "Constant", "happening all the time; continuous", "constant congestion", "constant \u2192 constantly \u2192 constancy"),
 E(["congestion"], "Congestion", "overcrowding causing blockage, e.g. of traffic", "constant congestion", "congest \u2192 congestion \u2192 congested"),
 E(["admittedly","admit"], "Admittedly", "used to admit something is true", "admittedly my experience is limited", "admit \u2192 admittedly \u2192 admission"),
 E(["limited to","limited"], "Limited", "small in amount or extent; restricted", "limited to the hotels", "limit \u2192 limited \u2192 limitation"),
 E(["blocks","block"], "Block (n)", "an area of buildings between streets", "within a three-kilometre walk of blocks"),
 E(["outlet"], "Outlet", "a shop or place that sells goods", "an outlet providing fruit", "outlet \u2192 outlets"),
 E(["nutritional value","nutritional"], "Nutritional", "relating to the food needed for health", "nutritional value", "nutrition \u2192 nutritional \u2192 nutritionist"),
 E(["ridiculous"], "Ridiculous", "very silly or unreasonable", "it seems ridiculous", "ridicule \u2192 ridiculous \u2192 ridiculously"),
 E(["advances","advance"], "Advance (n)", "progress or improvement", "great advances", "advance \u2192 advanced \u2192 advancement"),
 E(["redeveloping","redevelop"], "Redevelop", "to build or improve an area again", "redeveloping its museums", "develop \u2192 redevelop \u2192 redevelopment"),
 E(["authorities","authority"], "Authority", "an official body with power to make decisions", "authorities must recognise", "authority \u2192 authorities \u2192 authorise"),
 E(["recognise"], "Recognise", "to accept or be aware of something", "authorities must recognise", "recognise \u2192 recognition \u2192 recognisable"),
 E(["basic needs","basic"], "Basic", "forming the simplest, most essential part", "basic needs", "base \u2192 basic \u2192 basically"),
 E(["misunderstood","misunderstand"], "Misunderstood", "wrongly understood", "basic needs are misunderstood", "understand \u2192 misunderstand \u2192 misunderstood"),
 E(["residential"], "Residential", "consisting of homes where people live", "residential developments", "reside \u2192 residential \u2192 residence"),
 E(["developments","development"], "Development (n)", "an area of newly built homes or buildings", "new residential developments", "develop \u2192 development \u2192 developer"),
 E(["security features","security"], "Security", "protection against danger or crime", "security features", "secure \u2192 security \u2192 securely"),
 E(["features","feature"], "Feature (n)", "a distinctive part or characteristic", "security features", "feature \u2192 featured \u2192 featuring"),
 E(["massive"], "Massive", "very large", "massive metal fences", "mass \u2192 massive \u2192 massively"),
 E(["fences","fence"], "Fence", "a barrier of wood or metal around an area", "metal fences"),
 E(["multiple"], "Multiple", "many; more than one", "multiple gates", "multiple \u2192 multiply \u2192 multiplicity"),
 E(["gates","gate"], "Gate", "a movable barrier in a fence or wall", "multiple gates"),
 E(["belief"], "Belief", "an idea accepted as true", "in the belief that", "believe \u2192 belief \u2192 believable"),
 E(["little evidence","evidence"], "Evidence", "facts showing whether something is true", "little evidence", "evident \u2192 evidence \u2192 evidently"),
 E(["make a difference","difference"], "Make a difference", "to have a noticeable effect", "such steps make a difference"),
 E(["reluctant"], "Reluctant", "unwilling and hesitant", "residents feel reluctant", "reluctant \u2192 reluctance \u2192 reluctantly"),
 E(["inactive"], "Inactive", "not active; doing little", "remain inactive indoors", "active \u2192 inactive \u2192 inactivity"),
 E(["indoors"], "Indoors", "inside a building", "inactive indoors", "indoor \u2192 indoors"),
 E(["grassy"], "Grassy", "covered with grass", "grassy areas", "grass \u2192 grassy"),
 E(["householders","householder"], "Householder", "a person who owns or rents a house", "used by householders", "house \u2192 household \u2192 householder"),
 E(["adds up to","add up to"], "Add up to", "to result in; to amount to", "all this adds up to a feeling"),
 E(["cut off from","cut off"], "Cut off from", "isolated or separated from", "being cut off from others"),
 E(["planners","planner"], "Planner", "a person who designs the layout of areas", "planners and developers", "plan \u2192 planner \u2192 planning"),
 E(["developers","developer"], "Developer", "a person or company that builds on land", "planners and developers", "develop \u2192 developer \u2192 development"),
 E(["going wrong","go wrong"], "Go wrong", "to make a mistake; to fail", "where are planners going wrong"),
 E(["inviting","invite"], "Invite", "to ask someone to come or take part", "inviting a group of locals", "invite \u2192 invitation \u2192 inviting"),
 E(["locals","local"], "Locals", "people who live in a particular area", "a group of locals", "local \u2192 locally \u2192 locality"),
 E(["consultation"], "Consultation", "a meeting to discuss and get opinions", "a consultation event", "consult \u2192 consultation \u2192 consultant"),
 E(["conventional"], "Conventional", "following what is traditional or usual", "the conventional method", "convention \u2192 conventional \u2192 conventionally"),
 E(["community"], "Community", "the people living in one area", "what a community wants", "community \u2192 communal \u2192 communities"),
 E(["attracts","attract"], "Attract", "to cause to come; to draw in", "it attracts the same voices", "attract \u2192 attraction \u2192 attractive"),
 E(["voices","voice"], "Voice (n)", "an expressed opinion", "the same few voices"),
 E(["contribute"], "Contribute", "to give or add to something", "the internet lets others contribute", "contribute \u2192 contribution \u2192 contributor"),
 E(["propose"], "Propose", "to suggest a plan or idea", "propose ideas", "propose \u2192 proposal \u2192 proposition"),
 E(["pay attention to","attention"], "Pay attention to", "to take notice of; to focus on", "developers that pay attention"),
 E(["clearer picture","picture"], "A clearer picture", "a better understanding of a situation", "get a clearer picture"),
 E(["reduce the risk","risk"], "Risk (n)", "the chance of something bad happening", "reduce the risk", "risk \u2192 risky \u2192 risking"),
 E(["throwing away","throw away"], "Throw away", "to waste; to get rid of", "throwing away money"),
 E(["truly","true"], "Truly", "genuinely; really", "truly meets the needs", "true \u2192 truly \u2192 truth"),
 E(["containers","container"], "Container", "a large metal box for transporting goods", "metal containers", "contain \u2192 container \u2192 containment"),
 E(["transport"], "Transport (v)", "to carry goods or people from place to place", "used to transport cargo", "transport \u2192 transportation \u2192 transporter"),
 E(["cargo"], "Cargo", "goods carried by ship, plane or vehicle", "transport cargo on ships"),
 E(["five-storey","storey"], "Storey", "a single level or floor of a building", "a five-storey masterpiece", "storey \u2192 multi-storey"),
 E(["architectural"], "Architectural", "relating to the design of buildings", "an architectural masterpiece", "architect \u2192 architecture \u2192 architectural"),
 E(["masterpiece"], "Masterpiece", "a work of outstanding skill", "an architectural masterpiece"),
 E(["studios","studio"], "Studio", "a room for working, especially creative work", "sunny work studios"),
 E(["skilful"], "Skilful", "having or showing skill", "skilful construction", "skill \u2192 skilful \u2192 skilfully"),
 E(["take up","take up very little room"], "Take up", "to use or occupy space", "they take up little room"),
 E(["furniture"], "Furniture", "movable items like chairs and tables", "furniture and fittings"),
 E(["fittings","fitting"], "Fittings", "fixed equipment or furnishings in a building", "furniture and fittings"),
 E(["recycled","recycle"], "Recycled", "made from used materials processed again", "recycled products", "recycle \u2192 recycled \u2192 recycling"),
 E(["versions","version"], "Version", "a particular form of something", "their own versions", "version \u2192 versions"),
 E(["dormitories","dormitory"], "Dormitory", "a building providing sleeping rooms, e.g. for students", "container dormitories"),
 E(["house"], "House (v)", "to provide accommodation for", "to house students", "house \u2192 housing \u2192 housed"),
 E(["effectively"], "Effectively", "in a way that produces the desired result", "effectively combined", "effect \u2192 effective \u2192 effectively"),
 E(["combined","combine"], "Combine", "to join or mix together", "areas can be combined", "combine \u2192 combination \u2192 combined"),
 E(["units","unit"], "Unit", "a single thing forming part of a whole", "the units are ideal"),
 E(["entrepreneurs","entrepreneur"], "Entrepreneur", "a person who starts a business", "young entrepreneurs", "entrepreneur \u2192 entrepreneurial \u2192 entrepreneurship"),
 E(["establish"], "Establish", "to set up or start something", "establish a business", "establish \u2192 establishment \u2192 established"),
 E(["keeping costs down","costs","cost"], "Keep costs down", "to limit how much money is spent", "while keeping costs down"),
 E(["taking place","take place"], "Take place", "to happen or occur", "development is taking place"),
 E(["transforming","transform"], "Transforming", "completely changing something", "the transforming effect", "transform \u2192 transformation \u2192 transforming"),
 E(["in person","person"], "In person", "physically present, not remotely", "visit these places in person"),
 E(["determining","determine"], "Determine", "to control or decide something", "cars determining urban planning", "determine \u2192 determination \u2192 determined"),
 E(["concept"], "Concept", "an idea or general notion", "the whole concept", "concept \u2192 conceptual \u2192 conceptualise"),
 E(["ownership"], "Ownership", "the state of owning something", "private car ownership", "own \u2192 owner \u2192 ownership"),
 E(["outdated"], "Outdated", "no longer useful; old-fashioned", "is now outdated", "date \u2192 outdated \u2192 dated"),
 E(["abandoned","abandon"], "Abandon", "to give up or stop using something", "must be abandoned", "abandon \u2192 abandonment \u2192 abandoned"),
 E(["layout"], "Layout", "the way parts are arranged", "the layout of an area", "lay out \u2192 layout"),
 E(["meet up","meet up in"], "Meet up", "to come together with others", "people to meet up"),
 E(["pedestrianised","pedestrian"], "Pedestrianised", "made for walkers, with no vehicles", "pedestrianised zones", "pedestrian \u2192 pedestrianise \u2192 pedestrianised"),
 E(["zones","zone"], "Zone", "an area set aside for a particular purpose", "pedestrianised zones", "zone \u2192 zoning"),
 E(["at the heart of","heart"], "At the heart of", "at the centre or most important part of", "at the heart of the development"),
 E(["cultural"], "Cultural", "relating to the arts and customs of a society", "a cultural area", "culture \u2192 cultural \u2192 culturally"),
 E(["venues","venue"], "Venue", "a place where an event happens", "providing venues for art", "venue \u2192 venues"),
 E(["street theatre","theatre"], "Theatre", "a place or art form for live performances", "art, music and street theatre"),
 E(["positive"], "Positive", "good, favourable or constructive", "positive relations", "positive \u2192 positively \u2192 positivity"),
 E(["relations","relation"], "Relations", "the way people or groups get on together", "positive relations", "relate \u2192 relation \u2192 relationship"),
 E(["mall"], "Mall", "a large enclosed shopping area", "a new mall"),
 E(["shopping precinct","precinct"], "Precinct", "a shopping area, often closed to traffic", "a shopping precinct"),
 E(["performance spaces","performance"], "Performance space", "an area designed for live shows", "performance spaces", "perform \u2192 performance \u2192 performer"),
 E(["obliged to","obliged","oblige"], "Be obliged to", "to be required or forced to do something", "must be obliged to create", "oblige \u2192 obligation \u2192 obliged"),
 E(["wealthy"], "Wealthy", "having a lot of money; rich", "wealthy professionals", "wealth \u2192 wealthy \u2192 wealthier"),
 E(["professionals","professional"], "Professional", "a person doing skilled, paid work", "wealthy professionals", "profession \u2192 professional \u2192 professionally"),
 E(["the elderly","elderly"], "The elderly", "old people considered as a group", "homes for the elderly"),
 E(["starting out","start out"], "Start out", "to begin a career or activity", "young people just starting out"),
 E(["mix"], "Mix (n)", "a combination of different things", "this kind of mix", "mix \u2192 mixture \u2192 mixed"),
 E(["essential"], "Essential", "completely necessary", "this mix is essential", "essence \u2192 essential \u2192 essentially"),
 E(["convenient"], "Convenient", "easy to use or get to; suitable", "an area convenient for work", "convenient \u2192 convenience \u2192 conveniently"),
 E(["stay alive"], "Stay alive", "to continue to exist or survive", "for a community to stay alive"),
]

PASSAGES = [
 {"num": 1, "title": "New Zealand's Early Crafts and Traditions", "paragraphs": P1_PARAS, "entries": P1_ENTRIES},
 {"num": 2, "title": "Sleep Should Be Prescribed", "paragraphs": P2_PARAS, "entries": P2_ENTRIES},
 {"num": 3, "title": "The Future of Cities", "paragraphs": P3_PARAS, "entries": P3_ENTRIES},
]
