# -*- coding: utf-8 -*-
# Test 6 Reading: 3 passages + comprehensive vocab (elementary -> advanced)
E = lambda hl, word, d, coll="", fam="": {"hl": hl, "word": word, "def": d, "coll": coll, "fam": fam}

P1_PARAS = [
"Lake Poopo used to be Bolivia's second largest lake. Situated in the Altiplano Mountains at an altitude of around 3,700m, the lake in winter would cover an area of some 2,700 square kilometres as it was fed by swollen rivers. With very little rainfall during summer, this reduced to around 1,000, still a remarkable size. This was the pattern in previous centuries, but in December 2015, satellites confirmed the reports of local people that the lake had gone. While scientists had suspected that Poopo would eventually run dry, they didn't expect that this would occur for at least another thousand years. The local mining industry had already contributed to the pollution of the lake, but scientists believe global warming, drought and irrigation projects are all responsible for its disappearance. Today the consequences of Lake Poopo's disappearance are dramatic; many people who lived in the villages around it have left, since there are no more fish to be caught. Environmentalists also point to the fact that the lake had been the stopover point for thousands of birds as they migrated to other regions. Their numbers will certainly fall now the lake has gone.",
"Lake Poopo is not the only vast area of water to have disappeared. The Aral Sea in Central Asia was once the world's fourth largest lake but then it began to shrink in the 1960s. As a shallow lake, it depended on rivers to keep its level up. But then water from these rivers was diverted for irrigation purposes. Rice is a crop that needs huge quantities of water to survive in desert areas. Fields planted with cotton also require a regular supply. Now the water level is so low that fishing has stopped altogether. And it is not just the immediate area that is affected. Because the floor of the lake is now exposed, the salt that lies there is often carried by the wind across a radius of 300 kilometres. This impacts on agriculture as it damages growing plants and is absorbed by the soil.",
"For some lakes, the biggest threat is from climate change. On average, the surface water of the world's lakes has gone up in temperature by 0.34 degrees every ten years since 1985. Lake Tanganyika in East Africa is a lake where this trend has been observed, although it is by no means the most extreme example. This would be Lake Fracksjon in Sweden, where an increase of 1.35 degrees per decade has been observed - a figure which is estimated to rise. For Lake Tanganyika, however, the consequences have been severe. Warming has disrupted its ecosystem, and fish numbers have dropped sharply. In turn, this decline in fish stocks has impacted on families living in villages and towns around the lake, since they have no other source of protein. Furthermore, around 100,000 people depend on the fisheries established around Lake Tanganyika. These companies provide them with regular employment, without which communities will not survive.",
"In Iran, Lake Urmia's waters have also been affected by unusually hot summers, but dams and irrigation projects have also played a part. In the past, people admired its beautiful green-blue colour. However, the water now has a red tint. The reason for this is that bacteria quickly multiply in the warm waters of a shallow lake. Now local communities are understandably concerned about the future. One of their concerns is that Lake Urmia is no longer seen as a place where people can bathe to improve their health. As a result, in the last decade, there has been a downturn in tourism in the area, an industry many people depended on.",
"In some cases, it can be a challenge for scientists to predict outcomes for a lake or to recognise the factors that threaten it. Take, for example, Lake Waiau in Hawaii, a lake that was used in healing rituals by native Hawaiians. It is a fairly small lake, approximately 100m across, with some variation as the water level rises and falls. However, in early 2010, the lake began to decrease in size. By September 2013, it could only be described as a pond. The cause of the lake's decline has not yet been established, but drought is among the suspects. Then there is Scott Lake in central Florida. In June 2006 a massive sinkhole opened up beneath the lake - acting like a plug hole in a bath. It only took two weeks for the water to drain away. Local residents called meetings to decide what action to take, but in the end, nature took care of the problem. Clay, sand and other fine material plugged the hole and the lake started to fill with water again. Nevertheless, as geologists point out, sinkholes can occur with some frequency in Florida, so there is a chance that Scott Lake will drain away again.",
]

P1_ENTRIES = [
 E(["Lake","lake"], "Lake", "a large area of water surrounded by land", "Bolivia's largest lake"),
 E(["used to be","used to"], "Used to be", "was in the past but not now", "used to be the largest lake"),
 E(["largest","large"], "Largest", "biggest in size", "the second largest lake", "large \u2192 larger \u2192 largest"),
 E(["Situated","situated","situate"], "Situated", "located in a particular place", "situated in the mountains", "situate \u2192 situated \u2192 situation"),
 E(["altitude"], "Altitude", "the height above sea level", "at an altitude of 3,700m", "altitude \u2192 altitudes"),
 E(["cover"], "Cover (v)", "to spread over an area", "would cover 2,700 square kilometres", "cover \u2192 covering \u2192 covered"),
 E(["area"], "Area", "a region or extent of a surface", "an area of 2,700 km", "area \u2192 areas"),
 E(["square kilometres","kilometres","kilometre"], "Square kilometre", "a unit of area measuring 1km by 1km", "2,700 square kilometres"),
 E(["fed by","fed","feed"], "Fed by", "supplied with water by", "fed by swollen rivers", "feed \u2192 fed \u2192 feeding"),
 E(["swollen","swell"], "Swollen", "increased in size, especially with water", "swollen rivers", "swell \u2192 swollen \u2192 swelling"),
 E(["rivers","river"], "River", "a large natural stream of water", "swollen rivers"),
 E(["rainfall"], "Rainfall", "the amount of rain that falls", "little rainfall", "rain \u2192 rainfall \u2192 rainy"),
 E(["reduced","reduce"], "Reduce", "to make smaller in amount", "reduced to around 1,000", "reduce \u2192 reduction \u2192 reduced"),
 E(["remarkable"], "Remarkable", "extraordinary; worthy of attention", "a remarkable size", "remark \u2192 remarkable \u2192 remarkably"),
 E(["pattern"], "Pattern", "a regular, repeated way things happen", "this was the pattern", "pattern \u2192 patterned"),
 E(["previous"], "Previous", "happening before", "previous centuries", "previous \u2192 previously"),
 E(["centuries","century"], "Century", "a period of one hundred years", "previous centuries", "century \u2192 centuries"),
 E(["satellites","satellite"], "Satellite", "a device orbiting Earth to gather data", "satellites confirmed it", "satellite \u2192 satellites"),
 E(["confirmed","confirm"], "Confirm", "to show or prove to be true", "satellites confirmed the reports", "confirm \u2192 confirmation \u2192 confirmed"),
 E(["reports","report"], "Report (n)", "an account of facts or events", "the reports of local people", "report \u2192 reporter \u2192 reported"),
 E(["local"], "Local", "relating to a nearby area", "local people", "local \u2192 locally \u2192 locality"),
 E(["suspected","suspect"], "Suspect (v)", "to believe something is likely", "scientists had suspected", "suspect \u2192 suspicion \u2192 suspected"),
 E(["eventually"], "Eventually", "in the end; finally", "would eventually run dry", "eventual \u2192 eventually"),
 E(["run dry","dry"], "Run dry", "to become completely without water", "the lake would run dry"),
 E(["expect"], "Expect", "to think something will happen", "they didn't expect this", "expect \u2192 expectation \u2192 expected"),
 E(["occur"], "Occur", "to happen", "would occur for years", "occur \u2192 occurrence \u2192 occurring"),
 E(["at least"], "At least", "not less than; as a minimum", "at least another thousand years"),
 E(["mining industry","mining","industry"], "Mining industry", "the business of extracting minerals from the earth", "the local mining industry", "mine \u2192 mining \u2192 miner"),
 E(["contributed to","contributed","contribute"], "Contribute to", "to help cause something", "contributed to the pollution", "contribute \u2192 contribution \u2192 contributor"),
 E(["pollution"], "Pollution", "the contamination of the environment", "the pollution of the lake", "pollute \u2192 pollution \u2192 pollutant"),
 E(["global warming","warming"], "Global warming", "the gradual rise in Earth's temperature", "global warming and drought", "warm \u2192 warming \u2192 warmer"),
 E(["drought"], "Drought", "a long period without rain", "drought and irrigation", "drought \u2192 droughts"),
 E(["irrigation"], "Irrigation", "the supply of water to land for crops", "irrigation projects", "irrigate \u2192 irrigation \u2192 irrigated"),
 E(["projects","project"], "Project", "a planned piece of work", "irrigation projects", "project \u2192 projects"),
 E(["responsible for","responsible"], "Responsible for", "being the cause of something", "responsible for its disappearance", "responsible \u2192 responsibility \u2192 responsibly"),
 E(["disappearance"], "Disappearance", "the act of ceasing to exist or be seen", "the lake's disappearance", "disappear \u2192 disappearance \u2192 disappeared"),
 E(["consequences","consequence"], "Consequence", "a result or effect of something", "the consequences are dramatic", "consequence \u2192 consequent \u2192 consequently"),
 E(["dramatic"], "Dramatic", "sudden and striking", "the consequences are dramatic", "drama \u2192 dramatic \u2192 dramatically"),
 E(["villages","village"], "Village", "a small community in the countryside", "the villages around it", "village \u2192 villager"),
 E(["caught","catch"], "Catch (fish)", "to capture, especially fish", "no more fish to be caught", "catch \u2192 caught \u2192 catching"),
 E(["Environmentalists","environmentalists","environmentalist"], "Environmentalist", "a person who works to protect nature", "environmentalists point out", "environment \u2192 environmental \u2192 environmentalist"),
 E(["point to","point"], "Point to", "to draw attention to a fact", "environmentalists point to the fact"),
 E(["stopover point","stopover"], "Stopover", "a place to stop during a journey", "a stopover point for birds"),
 E(["migrated","migrate"], "Migrate", "to move from one region to another", "as they migrated", "migrate \u2192 migration \u2192 migratory"),
 E(["regions","region"], "Region", "a large area of land", "to other regions", "region \u2192 regional \u2192 regionally"),
 E(["fall"], "Fall (v)", "to decrease in number or amount", "their numbers will fall", "fall \u2192 fell \u2192 fallen"),
 E(["vast"], "Vast", "extremely large", "a vast area of water", "vast \u2192 vastly \u2192 vastness"),
 E(["disappeared","disappear"], "Disappear", "to cease to exist or be seen", "water to have disappeared", "disappear \u2192 disappearance \u2192 disappeared"),
 E(["shrink"], "Shrink", "to become smaller", "it began to shrink", "shrink \u2192 shrank \u2192 shrunk"),
 E(["shallow"], "Shallow", "not deep", "a shallow lake", "shallow \u2192 shallowness"),
 E(["depended on","depended","depend"], "Depend on", "to rely on for support", "depended on rivers", "depend \u2192 dependence \u2192 dependent"),
 E(["level"], "Level (n)", "the height of a surface, e.g. of water", "keep its level up", "level \u2192 levels"),
 E(["diverted","divert"], "Divert", "to change the direction of something", "water was diverted", "divert \u2192 diversion \u2192 diverted"),
 E(["purposes","purpose"], "Purpose", "the reason for which something is done", "for irrigation purposes", "purpose \u2192 purposeful \u2192 purposely"),
 E(["Rice","rice"], "Rice", "a cereal plant grown in wet conditions", "rice is a crop"),
 E(["crop"], "Crop", "a plant grown for food in large amounts", "a crop that needs water", "crop \u2192 crops"),
 E(["quantities","quantity"], "Quantity", "an amount of something", "huge quantities of water", "quantity \u2192 quantify \u2192 quantitative"),
 E(["survive"], "Survive", "to continue to live or exist", "to survive in deserts", "survive \u2192 survival \u2192 survivor"),
 E(["desert"], "Desert (n)", "a dry, barren area of land", "desert areas", "desert \u2192 deserted"),
 E(["Fields","fields","field"], "Field", "an area of land for growing crops", "fields planted with cotton"),
 E(["cotton"], "Cotton", "a soft fibre used to make cloth", "planted with cotton"),
 E(["require"], "Require", "to need something", "also require a supply", "require \u2192 requirement \u2192 required"),
 E(["regular"], "Regular", "happening at even, fixed intervals", "a regular supply", "regular \u2192 regularly \u2192 regularity"),
 E(["supply"], "Supply (n)", "an amount available for use", "a regular supply", "supply \u2192 supplier \u2192 supplies"),
 E(["altogether"], "Altogether", "completely; entirely", "fishing has stopped altogether"),
 E(["immediate"], "Immediate", "nearest; without anything between", "the immediate area", "immediate \u2192 immediately"),
 E(["affected","affect"], "Affect", "to have an influence on something", "the area is affected", "affect \u2192 affected \u2192 affecting"),
 E(["floor"], "Floor (of a lake)", "the bottom surface", "the floor of the lake"),
 E(["exposed","expose"], "Exposed", "uncovered; left without protection", "the floor is exposed", "expose \u2192 exposed \u2192 exposure"),
 E(["salt"], "Salt", "a white mineral used to season food", "the salt that lies there", "salt \u2192 salty \u2192 salted"),
 E(["carried by","carried","carry"], "Carry", "to move or transport something", "carried by the wind", "carry \u2192 carried \u2192 carrying"),
 E(["radius"], "Radius", "the distance from a centre point outward", "a radius of 300 km", "radius \u2192 radial"),
 E(["impacts on","impacts","impact"], "Impact on", "to have a strong effect on", "this impacts on agriculture", "impact \u2192 impactful"),
 E(["agriculture"], "Agriculture", "the practice of farming", "impacts on agriculture", "agriculture \u2192 agricultural \u2192 agriculturally"),
 E(["damages","damage"], "Damage (v)", "to harm or spoil something", "damages growing plants", "damage \u2192 damaging \u2192 damaged"),
 E(["absorbed","absorb"], "Absorb", "to take in a substance", "absorbed by the soil", "absorb \u2192 absorption \u2192 absorbed"),
 E(["soil"], "Soil", "the top layer of earth where plants grow", "absorbed by the soil"),
 E(["threat"], "Threat", "a possible source of danger", "the biggest threat", "threat \u2192 threaten \u2192 threatening"),
 E(["climate change","climate"], "Climate change", "long-term change in weather patterns", "from climate change", "climate \u2192 climatic"),
 E(["on average","average"], "On average", "typically; calculated as a mean", "on average, temperatures rose", "average \u2192 averages"),
 E(["surface"], "Surface", "the top or outer layer", "the surface water", "surface \u2192 surfaces"),
 E(["temperature"], "Temperature", "the degree of heat or cold", "gone up in temperature", "temperature \u2192 temperatures"),
 E(["trend"], "Trend", "a general direction of change", "this trend has been observed", "trend \u2192 trendy \u2192 trending"),
 E(["observed","observe"], "Observe", "to notice or watch carefully", "the trend has been observed", "observe \u2192 observation \u2192 observer"),
 E(["by no means","means"], "By no means", "not at all; certainly not", "by no means the most extreme"),
 E(["extreme"], "Extreme", "very great in degree", "the most extreme example", "extreme \u2192 extremely \u2192 extremity"),
 E(["increase"], "Increase (n)", "a rise in amount or size", "an increase of 1.35 degrees", "increase \u2192 increasing \u2192 increased"),
 E(["decade"], "Decade", "a period of ten years", "per decade", "decade \u2192 decades"),
 E(["estimated","estimate"], "Estimated", "calculated approximately", "estimated to rise", "estimate \u2192 estimated \u2192 estimation"),
 E(["severe"], "Severe", "very serious or harsh", "the consequences are severe", "severe \u2192 severely \u2192 severity"),
 E(["disrupted","disrupt"], "Disrupt", "to disturb or interrupt", "warming has disrupted the ecosystem", "disrupt \u2192 disruption \u2192 disruptive"),
 E(["ecosystem"], "Ecosystem", "a community of living things and their environment", "its ecosystem", "eco \u2192 ecosystem \u2192 ecological"),
 E(["dropped sharply","dropped","drop"], "Drop sharply", "to decrease suddenly and greatly", "fish numbers dropped sharply", "drop \u2192 dropped \u2192 dropping"),
 E(["In turn","in turn"], "In turn", "as a result; one after another", "in turn, this decline affected families"),
 E(["decline"], "Decline (n)", "a decrease or worsening", "this decline in fish stocks", "decline \u2192 declining \u2192 declined"),
 E(["stocks","stock"], "Stock (n)", "a supply or quantity available", "fish stocks", "stock \u2192 stocks"),
 E(["source"], "Source", "a place where something comes from", "a source of protein", "source \u2192 sourced \u2192 sourcing"),
 E(["protein"], "Protein", "a nutrient essential for the body", "a source of protein", "protein \u2192 proteins"),
 E(["Furthermore","furthermore"], "Furthermore", "in addition; moreover", "furthermore, people depend on fisheries"),
 E(["fisheries","fishery"], "Fishery", "a place or business for catching fish", "the fisheries", "fish \u2192 fishery \u2192 fisheries"),
 E(["established"], "Established", "set up and existing", "fisheries established here", "establish \u2192 established \u2192 establishment"),
 E(["employment"], "Employment", "the state of having paid work", "regular employment", "employ \u2192 employment \u2192 employer"),
 E(["communities","community"], "Community", "a group of people living in one area", "communities will not survive", "community \u2192 communal \u2192 communities"),
 E(["unusually","unusual"], "Unusually", "in an abnormal or uncommon way", "unusually hot summers", "usual \u2192 unusual \u2192 unusually"),
 E(["dams","dam"], "Dam", "a barrier built to hold back water", "dams and irrigation projects"),
 E(["played a part","play a part"], "Play a part", "to be one of the causes", "have also played a part"),
 E(["admired","admire"], "Admire", "to regard with respect or pleasure", "people admired its colour", "admire \u2192 admiration \u2192 admired"),
 E(["tint"], "Tint", "a slight shade of a colour", "a red tint", "tint \u2192 tinted"),
 E(["bacteria"], "Bacteria", "tiny living organisms, some causing disease", "bacteria multiply", "bacteria \u2192 bacterial"),
 E(["multiply"], "Multiply", "to increase greatly in number", "bacteria multiply", "multiply \u2192 multiplication \u2192 multiple"),
 E(["understandably","understandable"], "Understandably", "in a way that is easy to understand", "understandably concerned", "understand \u2192 understandable \u2192 understandably"),
 E(["concerned about","concerned","concern"], "Concerned about", "worried about something", "concerned about the future", "concern \u2192 concerned \u2192 concerning"),
 E(["concerns","concern"], "Concern (n)", "a worry or matter of importance", "one of their concerns", "concern \u2192 concerned \u2192 concerning"),
 E(["bathe"], "Bathe", "to swim or wash in water", "people can bathe", "bathe \u2192 bathing \u2192 bathed"),
 E(["downturn"], "Downturn", "a decline in activity or success", "a downturn in tourism", "turn \u2192 downturn"),
 E(["tourism"], "Tourism", "the business of providing for tourists", "a downturn in tourism", "tour \u2192 tourism \u2192 tourist"),
 E(["challenge"], "Challenge (n)", "a difficult task that tests ability", "a challenge for scientists", "challenge \u2192 challenging \u2192 challenger"),
 E(["predict"], "Predict", "to say what will happen in advance", "to predict outcomes", "predict \u2192 prediction \u2192 predictable"),
 E(["outcomes","outcome"], "Outcome", "the result of something", "predict outcomes", "outcome \u2192 outcomes"),
 E(["recognise"], "Recognise", "to identify or be aware of", "to recognise the factors", "recognise \u2192 recognition \u2192 recognisable"),
 E(["factors","factor"], "Factor", "one of the things influencing a result", "the factors that threaten it", "factor \u2192 factors"),
 E(["threaten"], "Threaten", "to be a danger to something", "the factors that threaten it", "threat \u2192 threaten \u2192 threatening"),
 E(["healing rituals","healing","rituals","ritual"], "Ritual", "a set of actions done in a fixed way, often religious", "healing rituals", "ritual \u2192 ritualistic"),
 E(["native"], "Native", "belonging to a place by birth", "native Hawaiians", "native \u2192 natively \u2192 nativity"),
 E(["fairly"], "Fairly", "to a moderate degree; quite", "a fairly small lake", "fair \u2192 fairly"),
 E(["approximately","approximate"], "Approximately", "about; roughly", "approximately 100m across", "approximate \u2192 approximately \u2192 approximation"),
 E(["variation","vary"], "Variation", "a change or difference in amount", "with some variation", "vary \u2192 variation \u2192 variable"),
 E(["rises and falls","rises","rise"], "Rise and fall", "to go up and down", "as the water level rises and falls", "rise \u2192 rising \u2192 risen"),
 E(["decrease"], "Decrease", "to become smaller in size or amount", "began to decrease in size", "decrease \u2192 decreasing \u2192 decreased"),
 E(["described","describe"], "Describe", "to say what something is like", "could only be described as a pond", "describe \u2192 description \u2192 descriptive"),
 E(["pond"], "Pond", "a small area of still water", "described as a pond"),
 E(["cause"], "Cause (n)", "the reason something happens", "the cause of the decline", "cause \u2192 caused \u2192 causing"),
 E(["established"], "Established (proved)", "shown to be true or certain", "has not yet been established", "establish \u2192 established \u2192 establishment"),
 E(["suspects","suspect"], "Suspect (n)", "a likely cause or culprit", "among the suspects", "suspect \u2192 suspicion \u2192 suspected"),
 E(["massive"], "Massive", "extremely large", "a massive sinkhole", "mass \u2192 massive \u2192 massively"),
 E(["sinkhole","sinkholes"], "Sinkhole", "a hole formed when ground collapses", "a massive sinkhole"),
 E(["opened up","open up"], "Open up", "to appear or form an opening", "a sinkhole opened up"),
 E(["beneath"], "Beneath", "under; below", "beneath the lake"),
 E(["plug hole","plug"], "Plug hole", "the hole through which water drains away", "like a plug hole"),
 E(["drain away","drain"], "Drain away", "to flow away gradually", "the water drained away", "drain \u2192 drainage \u2192 drained"),
 E(["residents","resident"], "Resident", "a person who lives in a place", "local residents", "reside \u2192 resident \u2192 residence"),
 E(["meetings","meeting"], "Meeting", "an assembly of people for discussion", "called meetings", "meet \u2192 meeting"),
 E(["action"], "Action", "the process of doing something", "what action to take", "act \u2192 action \u2192 active"),
 E(["took care of","take care of"], "Take care of", "to deal with; to handle", "nature took care of the problem"),
 E(["fine material","fine"], "Fine (material)", "made of very small particles", "fine material", "fine \u2192 finely"),
 E(["plugged","plug"], "Plug (v)", "to block or fill a hole", "plugged the hole", "plug \u2192 plugged \u2192 plugging"),
 E(["fill"], "Fill (v)", "to make or become full", "the lake started to fill", "fill \u2192 filled \u2192 filling"),
 E(["Nevertheless","nevertheless"], "Nevertheless", "in spite of that; however", "nevertheless, geologists warn"),
 E(["geologists","geologist"], "Geologist", "a scientist who studies the earth's structure", "geologists point out", "geology \u2192 geologist \u2192 geological"),
 E(["frequency"], "Frequency", "the rate at which something occurs", "with some frequency", "frequent \u2192 frequency \u2192 frequently"),
 E(["chance"], "Chance", "the possibility of something happening", "there is a chance", "chance \u2192 chances"),
]


P2_PARAS = [
"On paper, biofuels seem the ideal replacement for oil, coal and gas, the fossil fuels we depend upon, and which drive global warming and disrupt weather patterns by releasing carbon dioxide into the atmosphere. But the past decade has seen the biofuel industry face tough questions over whether it can truly claim to be 'green'. One of the biggest criticisms of biofuel crops - at least those that produce the fuel ethanol - has been their impact on food markets and on traditional land use. Direct impacts - for example, cutting down forests to make way for a biofuel crop - are usually obvious, says Professor Bill Laurance, director of the Centre for Tropical Environmental and Sustainability Science at James Cook University. But, in his experience, indirect impacts can be no less devastating for the environment and are far more of a challenge to anticipate.",
"Let's take Brazil, for example. When farmers in the US opted out of soy in favour of corn as a biofuel crop, soy prices soared, suddenly making it an attractive crop for Brazilian farmers. In turn, this increased demand for freshly deforested cropland in Brazil. Similar situations are occurring all over the world. But while deforestation can certainly lead to economic benefits for farmers, it also puts biodiversity at risk. Then, once a biofuel crop has been planted on deforested land, farmers need to ensure that it grows as well as it can. That means applying large quantities of fertiliser, and while this helps the plants to shoot up, there is also the possibility it will lead to the contamination of local rivers.",
"Not all biofuels have been grown on land, but the once-popular idea of generating them from microscopic algae grown in ponds or tanks has largely been forgotten. Professor Rachel Burton, leader of the ARC Centre of Excellence for Plant Cell Walls at the University of Adelaide, thinks that there is a smarter way forward for biofuels and it starts with selecting the right crop for land not usually used for agriculture. Burton and others are looking to tough plants that grow on land too dry or salty for conventional crops. Australia, for example, could turn to crops such as agave, hemp or the native saltbush and wild-growing sorghum for the biofuels of the future, she says.",
"Researchers must also consider economic factors, however. While plant oils can be extracted and turned into biodiesel for vehicles and machinery, currently the process is very expensive - much more so than the process for fossil fuels. Dr Allan Green is innovation leader for bio-based products at CSIRO Agriculture and Food. His solution is to make plants oilier by genetically altering them so that they produce oil in their leaves, not just in their fruit or seeds. With more oil being produced on a particular section of land by the same number of plants, it would become cheaper to harvest and extract the oil. The technology, which has so far only been tested in tobacco, shows that oil production can be boosted to a third or more of a tobacco leaf's weight. If used in a different crop - one that already produces oil in its seeds or fruit - the hope is that oil output could be doubled, though that idea is yet to be put to the test.",
"A technology which is becoming increasingly popular in the biofuel industry is hydrothermal liquefaction. This is a process which uses heat and pressure to break apart molecules in whole plants and remove oxygen, so that the raw material is turned into 'bio-crude oil'. Then, just as we need to refine the crude oil made from fossil fuels, the plant-based oil is also refined. After this, it can then be turned into different kinds of fuel. One advantage of the hydrothermal liquefaction process is that many kinds of plant can be used. And if this process could run on energy from solar panels or wind farms, it would be much more environmentally sustainable.",
"New processing technologies are giving biofuel producers hope that, in future, they won't be limited to plants designed to be biofuel-only crops. Perhaps they will be able to choose species that deliver added benefits or sources of income. Hemp crops, for instance, could be used for their oil, but also for their fibre. Some car manufacturers have already used it as a soundproofing material in their vehicles, and others may do the same. And according to Kirsten Heimann, associate professor at the College of Science and Engineering at James Cook University, it might be possible, say, for algae not just to act as a biofuel, but to decontaminate water. Burton believes this kind of multi-purpose use for biofuel crops is the way forward. 'It's much more sophisticated thinking,' she says. 'Biofuels maybe don't need to be as cheap as we think they do, because you can make money out of the other things.' Eventually, the biofuel industry could well develop into a very diverse one, with no one crop or process dominating the market, according to Green. 'The amount of fuel we need to move away from petroleum is massive, so there's plenty of space for all technologies,' he says.",
]

P2_ENTRIES = [
 E(["On paper","paper"], "On paper", "in theory, judging by what is written", "on paper, biofuels seem ideal"),
 E(["biofuels","biofuel"], "Biofuel", "fuel made from living matter such as plants", "biofuels seem ideal", "bio \u2192 biofuel"),
 E(["ideal"], "Ideal", "perfect; the best possible", "the ideal replacement", "ideal \u2192 ideally \u2192 idealise"),
 E(["replacement"], "Replacement", "a person or thing that takes the place of another", "a replacement for oil", "replace \u2192 replacement \u2192 replaced"),
 E(["oil"], "Oil", "a thick liquid used as fuel or lubricant", "oil, coal and gas", "oil \u2192 oily \u2192 oilier"),
 E(["coal"], "Coal", "a hard black mineral burned as fuel", "oil, coal and gas"),
 E(["fossil fuels","fossil fuel","fossil"], "Fossil fuel", "fuel formed from ancient organic remains", "the fossil fuels we depend on", "fossil \u2192 fossilise"),
 E(["depend upon","depend"], "Depend upon", "to rely on for support", "fuels we depend upon", "depend \u2192 dependence \u2192 dependent"),
 E(["drive"], "Drive (v)", "to cause or power something", "which drive global warming", "drive \u2192 driven \u2192 driving"),
 E(["global warming","warming"], "Global warming", "the gradual rise in Earth's temperature", "drive global warming", "warm \u2192 warming"),
 E(["disrupt"], "Disrupt", "to disturb or interrupt", "disrupt weather patterns", "disrupt \u2192 disruption \u2192 disruptive"),
 E(["weather patterns","patterns","pattern"], "Weather pattern", "the usual way weather behaves over time", "disrupt weather patterns"),
 E(["releasing","release"], "Release (v)", "to let out a substance", "releasing carbon dioxide", "release \u2192 released \u2192 releasing"),
 E(["carbon dioxide"], "Carbon dioxide", "a gas produced by burning that traps heat", "releasing carbon dioxide"),
 E(["atmosphere"], "Atmosphere", "the layer of gases surrounding the Earth", "into the atmosphere", "atmosphere \u2192 atmospheric"),
 E(["decade"], "Decade", "a period of ten years", "the past decade", "decade \u2192 decades"),
 E(["industry"], "Industry", "an area of economic or manufacturing activity", "the biofuel industry", "industry \u2192 industrial \u2192 industrialise"),
 E(["face","face tough questions"], "Face (v)", "to confront or have to deal with", "face tough questions", "face \u2192 facing \u2192 faced"),
 E(["tough"], "Tough", "difficult; hard to deal with", "tough questions", "tough \u2192 toughness \u2192 toughen"),
 E(["truly","true"], "Truly", "genuinely; really", "truly claim to be green", "true \u2192 truly \u2192 truth"),
 E(["claim"], "Claim (v)", "to state something is true", "claim to be green", "claim \u2192 claimed \u2192 claimant"),
 E(["green"], "Green (adj)", "environmentally friendly", "claim to be 'green'", "green \u2192 greenness"),
 E(["criticisms","criticism"], "Criticism", "the expression of disapproval", "the biggest criticisms", "criticise \u2192 criticism \u2192 critical"),
 E(["crops","crop"], "Crop", "a plant grown in large amounts for use", "biofuel crops", "crop \u2192 crops"),
 E(["produce"], "Produce (v)", "to make or create", "crops that produce ethanol", "produce \u2192 production \u2192 producer"),
 E(["fuel"], "Fuel", "material burned to provide energy", "the fuel ethanol", "fuel \u2192 fuelled \u2192 fuelling"),
 E(["ethanol"], "Ethanol", "a type of alcohol used as a fuel", "the fuel ethanol"),
 E(["impact"], "Impact (n)", "a strong effect", "their impact on food markets", "impact \u2192 impactful"),
 E(["food markets","markets","market"], "Market", "the trade or buyers for goods", "food markets", "market \u2192 marketing \u2192 marketable"),
 E(["traditional"], "Traditional", "following established customs", "traditional land use", "tradition \u2192 traditional \u2192 traditionally"),
 E(["land use"], "Land use", "the way land is used by people", "traditional land use"),
 E(["Direct","direct"], "Direct (adj)", "without anything in between; immediate", "direct impacts", "direct \u2192 directly \u2192 direction"),
 E(["cutting down","cut down"], "Cut down", "to fell or remove (trees)", "cutting down forests"),
 E(["forests","forest"], "Forest", "a large area covered with trees", "cutting down forests", "forest \u2192 forestry \u2192 forested"),
 E(["make way for","make way"], "Make way for", "to clear space for something", "to make way for a crop"),
 E(["obvious"], "Obvious", "easy to see or understand", "usually obvious", "obvious \u2192 obviously"),
 E(["director"], "Director", "the head of an organisation", "director of the centre", "direct \u2192 director \u2192 directorship"),
 E(["Tropical","tropical"], "Tropical", "relating to the hot regions near the equator", "Tropical Environmental Science", "tropics \u2192 tropical"),
 E(["Sustainability","sustainability","sustainable"], "Sustainability", "use of resources without harming the future", "Sustainability Science", "sustain \u2192 sustainable \u2192 sustainability"),
 E(["experience"], "Experience", "knowledge gained from doing something", "in his experience", "experience \u2192 experienced \u2192 experiencing"),
 E(["indirect"], "Indirect", "not direct; happening as a side effect", "indirect impacts", "direct \u2192 indirect \u2192 indirectly"),
 E(["devastating","devastate"], "Devastating", "causing great damage", "devastating for the environment", "devastate \u2192 devastation \u2192 devastating"),
 E(["environment"], "Environment", "the natural surroundings", "for the environment", "environment \u2192 environmental \u2192 environmentally"),
 E(["challenge"], "Challenge (n)", "a difficult task that tests ability", "more of a challenge", "challenge \u2192 challenging \u2192 challenger"),
 E(["anticipate"], "Anticipate", "to expect or predict in advance", "a challenge to anticipate", "anticipate \u2192 anticipation \u2192 anticipated"),
 E(["farmers","farmer"], "Farmer", "a person who works on a farm", "farmers in the US", "farm \u2192 farmer \u2192 farming"),
 E(["opted out of","opted","opt"], "Opt out of", "to choose not to take part in", "opted out of soy", "opt \u2192 option \u2192 optional"),
 E(["soy"], "Soy", "the soya bean, used for food and oil", "opted out of soy"),
 E(["in favour of","favour"], "In favour of", "in support of; preferring", "in favour of corn", "favour \u2192 favourable \u2192 favoured"),
 E(["corn"], "Corn", "a cereal crop; maize", "corn as a biofuel crop"),
 E(["prices","price"], "Prices", "the amounts of money goods cost", "soy prices soared", "price \u2192 pricing \u2192 priced"),
 E(["soared","soar"], "Soar", "to rise quickly to a high level", "soy prices soared", "soar \u2192 soaring \u2192 soared"),
 E(["attractive"], "Attractive", "appealing; worth having", "an attractive crop", "attract \u2192 attractive \u2192 attraction"),
 E(["In turn","in turn"], "In turn", "as a result; consequently", "in turn, this increased demand"),
 E(["increased","increase"], "Increase (v)", "to make or become greater", "increased demand", "increase \u2192 increasing \u2192 increased"),
 E(["demand"], "Demand (n)", "the desire of buyers for goods", "increased demand", "demand \u2192 demanding \u2192 demanded"),
 E(["freshly","fresh"], "Freshly", "recently; newly", "freshly deforested cropland", "fresh \u2192 freshly \u2192 freshness"),
 E(["deforested","deforestation"], "Deforested", "having had the trees cleared away", "deforested cropland", "forest \u2192 deforest \u2192 deforestation"),
 E(["cropland"], "Cropland", "land used for growing crops", "deforested cropland"),
 E(["situations","situation"], "Situation", "a set of circumstances", "similar situations", "situate \u2192 situation \u2192 situated"),
 E(["occurring","occur"], "Occur", "to happen", "occurring all over the world", "occur \u2192 occurrence \u2192 occurring"),
 E(["deforestation"], "Deforestation", "the clearing of forests", "deforestation leads to benefits", "forest \u2192 deforest \u2192 deforestation"),
 E(["lead to","lead"], "Lead to", "to result in", "can lead to economic benefits", "lead \u2192 led \u2192 leading"),
 E(["economic"], "Economic", "relating to money and trade", "economic benefits", "economy \u2192 economic \u2192 economically"),
 E(["benefits","benefit"], "Benefit (n)", "an advantage or positive effect", "economic benefits", "benefit \u2192 beneficial \u2192 beneficiary"),
 E(["puts biodiversity at risk","at risk","risk"], "Put at risk", "to expose to danger", "puts biodiversity at risk"),
 E(["biodiversity"], "Biodiversity", "the variety of living things in an area", "biodiversity at risk", "diversity \u2192 biodiversity"),
 E(["planted","plant"], "Plant (v)", "to put in the ground to grow", "a crop has been planted", "plant \u2192 planting \u2192 plantation"),
 E(["ensure"], "Ensure", "to make certain something happens", "farmers need to ensure", "ensure \u2192 ensured \u2192 ensuring"),
 E(["applying","apply"], "Apply", "to put a substance onto something", "applying fertiliser", "apply \u2192 application \u2192 applied"),
 E(["quantities","quantity"], "Quantity", "an amount of something", "large quantities of fertiliser", "quantity \u2192 quantify \u2192 quantitative"),
 E(["fertiliser"], "Fertiliser", "a substance added to soil to help plants grow", "applying fertiliser", "fertile \u2192 fertiliser \u2192 fertilise"),
 E(["shoot up","shoot"], "Shoot up", "to grow very quickly", "helps the plants shoot up"),
 E(["possibility"], "Possibility", "a thing that may happen", "the possibility of contamination", "possible \u2192 possibility \u2192 possibly"),
 E(["contamination"], "Contamination", "the making of something impure or polluted", "contamination of rivers", "contaminate \u2192 contamination \u2192 contaminated"),
 E(["once-popular","popular"], "Once-popular", "formerly liked or widely used", "the once-popular idea", "popular \u2192 popularity \u2192 popularise"),
 E(["generating","generate"], "Generate", "to produce something", "generating biofuels", "generate \u2192 generation \u2192 generator"),
 E(["microscopic"], "Microscopic", "so small it can only be seen with a microscope", "microscopic algae", "microscope \u2192 microscopic"),
 E(["algae"], "Algae", "simple water plants without true roots or leaves", "microscopic algae"),
 E(["ponds","pond"], "Pond", "a small area of still water", "grown in ponds"),
 E(["tanks","tank"], "Tank", "a large container for liquid", "ponds or tanks"),
 E(["forgotten","forget"], "Forgotten", "no longer remembered or used", "has largely been forgotten", "forget \u2192 forgotten \u2192 forgetful"),
 E(["leader"], "Leader", "a person who guides or directs", "leader of the centre", "lead \u2192 leader \u2192 leadership"),
 E(["Excellence","excellence"], "Excellence", "the quality of being outstanding", "Centre of Excellence", "excel \u2192 excellence \u2192 excellent"),
 E(["smarter","smart"], "Smarter", "more clever or intelligent", "a smarter way forward", "smart \u2192 smarter \u2192 smartly"),
 E(["way forward"], "Way forward", "a plan or method for making progress", "a smarter way forward"),
 E(["selecting","select"], "Select", "to choose carefully", "selecting the right crop", "select \u2192 selection \u2192 selective"),
 E(["agriculture"], "Agriculture", "the practice of farming", "used for agriculture", "agriculture \u2192 agricultural \u2192 agriculturally"),
 E(["tough plants","tough"], "Tough (plants)", "strong and able to survive hard conditions", "tough plants", "tough \u2192 toughness"),
 E(["salty"], "Salty", "containing salt", "too dry or salty", "salt \u2192 salty \u2192 saltiness"),
 E(["conventional"], "Conventional", "ordinary; following the usual way", "conventional crops", "convention \u2192 conventional \u2192 conventionally"),
 E(["turn to","turn"], "Turn to", "to start using something for help", "could turn to crops like agave"),
 E(["hemp"], "Hemp", "a plant used for fibre and oil", "agave, hemp or saltbush"),
 E(["native"], "Native", "originating naturally in a place", "the native saltbush", "native \u2192 natively \u2192 nativity"),
 E(["wild-growing","wild"], "Wild-growing", "growing naturally without cultivation", "wild-growing sorghum", "wild \u2192 wilderness \u2192 wildly"),
 E(["consider"], "Consider", "to think carefully about", "consider economic factors", "consider \u2192 consideration \u2192 considerable"),
 E(["factors","factor"], "Factor", "one of the things affecting a result", "economic factors", "factor \u2192 factors"),
 E(["plant oils","oils","oil"], "Plant oil", "oil extracted from plants", "plant oils can be extracted"),
 E(["extracted","extract"], "Extract (v)", "to remove or take out", "oils can be extracted", "extract \u2192 extraction \u2192 extracted"),
 E(["biodiesel"], "Biodiesel", "a diesel fuel made from plant or animal matter", "turned into biodiesel"),
 E(["vehicles","vehicle"], "Vehicle", "a machine for transporting people or goods", "for vehicles and machinery", "vehicle \u2192 vehicular"),
 E(["machinery"], "Machinery", "machines as a group", "vehicles and machinery", "machine \u2192 machinery"),
 E(["currently","current"], "Currently", "at the present time", "currently the process is expensive", "current \u2192 currently \u2192 currency"),
 E(["process"], "Process", "a series of actions to achieve a result", "the process is expensive", "process \u2192 procedure \u2192 processing"),
 E(["expensive"], "Expensive", "costing a lot of money", "very expensive", "expense \u2192 expensive \u2192 expensively"),
 E(["innovation"], "Innovation", "a new method or idea", "innovation leader", "innovate \u2192 innovation \u2192 innovative"),
 E(["bio-based","based"], "Bio-based", "made from biological materials", "bio-based products"),
 E(["products","product"], "Product", "something made to be sold or used", "bio-based products", "produce \u2192 product \u2192 production"),
 E(["solution"], "Solution", "a way of solving a problem", "his solution is", "solve \u2192 solution \u2192 solvable"),
 E(["oilier","oily"], "Oily", "containing or covered with oil", "make plants oilier", "oil \u2192 oily \u2192 oilier"),
 E(["genetically","genetic"], "Genetically", "in a way relating to genes", "genetically altering them", "gene \u2192 genetic \u2192 genetically"),
 E(["altering","alter"], "Alter", "to change something", "altering them", "alter \u2192 alteration \u2192 altered"),
 E(["leaves","leaf"], "Leaf", "a flat green part of a plant", "oil in their leaves", "leaf \u2192 leaves \u2192 leafy"),
 E(["seeds","seed"], "Seed", "the small part of a plant from which it grows", "fruit or seeds", "seed \u2192 seeded \u2192 seedling"),
 E(["section"], "Section", "a part of something larger", "a section of land", "section \u2192 sectional"),
 E(["cheaper","cheap"], "Cheaper", "lower in cost", "cheaper to harvest", "cheap \u2192 cheaper \u2192 cheaply"),
 E(["harvest"], "Harvest (v)", "to gather a crop", "cheaper to harvest", "harvest \u2192 harvesting \u2192 harvester"),
 E(["tested","test"], "Tested", "examined or tried out", "tested in tobacco", "test \u2192 tested \u2192 testing"),
 E(["tobacco"], "Tobacco", "a plant whose leaves are dried for smoking", "tested in tobacco"),
 E(["production"], "Production", "the act of making or growing something", "oil production", "produce \u2192 production \u2192 productive"),
 E(["boosted","boost"], "Boost", "to increase or improve", "can be boosted", "boost \u2192 boosted \u2192 boosting"),
 E(["weight"], "Weight", "how heavy something is", "a leaf's weight", "weigh \u2192 weight \u2192 weighty"),
 E(["output"], "Output", "the amount produced", "oil output", "output \u2192 outputs"),
 E(["doubled","double"], "Double (v)", "to make twice as great", "output could be doubled", "double \u2192 doubled \u2192 doubling"),
 E(["put to the test","test"], "Put to the test", "to try out to see if it works", "yet to be put to the test"),
 E(["increasingly"], "Increasingly", "more and more", "increasingly popular", "increase \u2192 increasingly \u2192 increased"),
 E(["hydrothermal liquefaction","liquefaction"], "Hydrothermal liquefaction", "a process using heat and water pressure to make oil", "hydrothermal liquefaction"),
 E(["pressure"], "Pressure", "the force pressing on something", "heat and pressure", "press \u2192 pressure \u2192 pressurise"),
 E(["break apart","break"], "Break apart", "to separate into pieces", "break apart molecules"),
 E(["molecules","molecule"], "Molecule", "the smallest unit of a chemical substance", "break apart molecules", "molecule \u2192 molecular"),
 E(["remove"], "Remove", "to take away", "remove oxygen", "remove \u2192 removal \u2192 removed"),
 E(["oxygen"], "Oxygen", "the gas that living things need to breathe", "remove oxygen"),
 E(["raw material","raw"], "Raw material", "basic material before processing", "the raw material", "raw \u2192 rawness"),
 E(["crude oil","crude"], "Crude oil", "unrefined oil as it comes from the ground", "bio-crude oil", "crude \u2192 crudely"),
 E(["refine"], "Refine", "to make pure by removing unwanted matter", "refine the oil", "refine \u2192 refinement \u2192 refinery"),
 E(["plant-based"], "Plant-based", "made from plants", "the plant-based oil"),
 E(["advantage"], "Advantage", "a beneficial feature", "one advantage", "advantage \u2192 advantageous"),
 E(["run on","run"], "Run on", "to be powered by", "run on solar energy"),
 E(["energy"], "Energy", "power used to do work", "energy from solar panels", "energy \u2192 energetic \u2192 energise"),
 E(["solar panels","solar"], "Solar panel", "a device that converts sunlight into energy", "solar panels", "solar \u2192 solarised"),
 E(["wind farms","wind"], "Wind farm", "a group of turbines that generate power from wind", "wind farms"),
 E(["environmentally","environmental"], "Environmentally", "in a way relating to the environment", "environmentally sustainable", "environment \u2192 environmental \u2192 environmentally"),
 E(["processing"], "Processing", "the act of treating raw material", "new processing technologies", "process \u2192 processing \u2192 processed"),
 E(["producers","producer"], "Producer", "a person or company that makes something", "biofuel producers", "produce \u2192 producer \u2192 production"),
 E(["limited to","limited"], "Limited to", "restricted to only", "limited to biofuel crops", "limit \u2192 limited \u2192 limitation"),
 E(["designed","design"], "Designed", "planned and made for a purpose", "designed to be crops", "design \u2192 designed \u2192 designer"),
 E(["species"], "Species", "a group of similar living things", "choose species", "species \u2192 speciation"),
 E(["deliver"], "Deliver", "to provide or produce", "species that deliver benefits", "deliver \u2192 delivery \u2192 delivered"),
 E(["added"], "Added", "extra; additional", "added benefits", "add \u2192 added \u2192 addition"),
 E(["sources of income","income","source"], "Source of income", "a way of earning money", "sources of income"),
 E(["fibre"], "Fibre", "a thin thread of natural material", "used for their fibre", "fibre \u2192 fibrous"),
 E(["manufacturers","manufacturer"], "Manufacturer", "a company that makes goods", "car manufacturers", "manufacture \u2192 manufacturer \u2192 manufacturing"),
 E(["soundproofing","soundproof"], "Soundproofing", "material that blocks sound", "soundproofing material", "sound \u2192 soundproof \u2192 soundproofing"),
 E(["associate professor","associate"], "Associate professor", "a senior university teacher below full professor", "associate professor"),
 E(["act as","act"], "Act as", "to perform the function of", "for algae to act as biofuel", "act \u2192 action \u2192 acting"),
 E(["decontaminate"], "Decontaminate", "to remove harmful substances from", "to decontaminate water", "contaminate \u2192 decontaminate \u2192 decontamination"),
 E(["multi-purpose","purpose"], "Multi-purpose", "having several uses", "multi-purpose use", "purpose \u2192 multi-purpose"),
 E(["sophisticated"], "Sophisticated", "advanced and complex; refined", "more sophisticated thinking", "sophisticated \u2192 sophistication"),
 E(["cheap"], "Cheap", "low in price", "as cheap as we think", "cheap \u2192 cheaper \u2192 cheaply"),
 E(["make money","money"], "Make money", "to earn or gain money", "make money out of other things"),
 E(["Eventually","eventually"], "Eventually", "in the end; finally", "eventually the industry could develop", "eventual \u2192 eventually"),
 E(["develop into","develop"], "Develop into", "to grow or change into", "develop into a diverse industry", "develop \u2192 development \u2192 developed"),
 E(["diverse"], "Diverse", "varied; of many different kinds", "a very diverse industry", "diverse \u2192 diversity \u2192 diversify"),
 E(["dominating","dominate"], "Dominate", "to control or be most powerful", "no crop dominating the market", "dominate \u2192 domination \u2192 dominant"),
 E(["petroleum"], "Petroleum", "crude oil and its products", "move away from petroleum"),
 E(["massive"], "Massive", "extremely large", "the amount is massive", "mass \u2192 massive \u2192 massively"),
 E(["plenty of","plenty"], "Plenty of", "a large amount; more than enough", "plenty of space"),
]


P3_PARAS = [
"At Poverty Point in the US state of Louisiana, a remarkable monument overlooks the Mississippi river. Built around 3,500 years ago entirely from earth, it consists of six semi-circular ridges and five mounds. 'Mound A', as archaeologists refer to it, is the largest at 22 metres high. The earth mounds at Poverty Point are not just impressive, they are also intriguing. Ancient monuments have always been regarded as products of large, hierarchical societies, built as tributes to gods and kings. But the creators of the Poverty Point monument were hunter-gatherers, who functioned in a more democratic way. They may have looked to elders for guidance, but these would not have exerted a commanding influence over their small groups. So who, or what, motivated building on such a grand scale?",
"Archaeologists have been excavating Poverty Point for more than a century. However, the truly remarkable nature of Mound A only emerged a few years ago. This was when a team led by Tristram Kidder of Washington University drilled into the mound. They saw for the first time that it consisted of neat layers of differently coloured earth. It rains a lot around Poverty Point, and we know that fluctuations in temperature and increased flooding eventually led to its abandonment. But Kidder could see no sign that the layers had combined, as you might expect if it had rained during construction. Kidder reached a startling conclusion: Mound A must have been built in one short period, perhaps in as little as 30 days, and probably no more than 90.",
"Mound A contains nearly 240,000 cubic metres of earth; the equivalent of 32,000 truckloads. There were no trucks then, of course, nor any other heavy machinery, animals like mules to carry the earth, or wheelbarrows. Assuming it did take 90 days, Kidder's group calculated that around 3,000 basket-carrying individuals would have been needed to get the job done. Given that people probably travelled in family groups, as many as 9,000 people may have assembled at Poverty Point during construction. 'If that's true, it was an extraordinarily large gathering,' says Kidder. Why would they have chosen to do this?",
"Another archaeologist, Carl Lipo, thinks he has the answer: the same reason that the people of Easter Island built their famous stone heads. When Lipo first went to Easter Island, the prevailing idea was that the enormous statues had been rolled into place using logs, and the resulting deforestation contributed to the human population's collapse. But Lipo and fellow archaeologist Terry Hunt showed the statues could have been 'walked' upright into place by cooperating bands of people using ropes, with no need for trees. They argue further that by making statues, people's energy was directed into peaceful interactions and information-sharing. They ceased crafting statues, Lipo claims, precisely because daily existence became less of a challenge, and it was no longer so important that they work together.",
"An ancient temple known as Gobekli Tepe in south-east Turkey is another site where a giant team-building project might have taken place. Since excavations started, archaeologists have uncovered nine enclosures formed of massive stone pillars. Given the vast size of these pillars, a considerable workforce would have been needed to move them. But what archaeologists have also discovered is that every so often, the workers filled in the enclosures with broken rock and built new ones. The apparent disposability of these monuments makes sense if the main aim was building a team rather than a lasting structure. Indeed, the many bones from animals such as gazelle found in the filled-in enclosures suggest people held feasts to celebrate the end of a collaborative effort.",
"A number of researchers share Lipo's view that the need to cooperate is what drove monument makers. But as you might expect when a major shift in thinking is proposed, not everyone goes along with it. The sceptics include Tristram Kidder. For him, the interesting question is not 'Did cooperative building promote group survival' but 'What did the builders think they were doing?' All human behaviour comes down to a pursuit of food and self-preservation, he says. As for why people came to Poverty Point, he and his colleagues have suggested it was a pilgrimage site.",
"If Lipo is right, have we in any way inherited our ancestors' tendency to work together for the sake of social harmony? Evolutionary biologist David Sloan Wilson thinks we have. Wilson cites the Burning Man festival, promoted as an experiment in community and art, which draws thousands of people to Nevada's Black Rock Desert each summer. Among the ten principles laid down by co-founder Larry Harvey are 'inclusion' and 'communal effort'. Another is 'leaving no trace', meaning that whatever festival-goers create they destroy before departing. In this way, the desert landscape is only temporarily disturbed. Wilson says there is evidence that such cooperative ventures matter more today than ever because we are dependent on a wider range of people than our ancestors were. Food, education, security: all are provided by people beyond our family group. Recently, as part of his Neighbourhood Project in Binghamton, Wilson and his colleagues helped locals create their own parks. 'This brought people together and enabled them to cooperate in numerous other contexts,' he explains. This included helping with repairs after a series of floods in 2011. Social psychologist Susan Fiske of Princeton University also sees value in community projects. Her research shows, for example, that they can help break down the ill-informed views that people hold towards others they have observed but do not usually interact with. So if modern projects really help build better communities, that will surely be a monumental achievement.",
]

P3_ENTRIES = [
 E(["remarkable"], "Remarkable", "extraordinary; worthy of attention", "a remarkable monument", "remark \u2192 remarkable \u2192 remarkably"),
 E(["monument"], "Monument", "a structure built to commemorate or impress", "a remarkable monument", "monument \u2192 monumental"),
 E(["overlooks","overlook"], "Overlook (v)", "to have a view over something from above", "overlooks the river", "overlook \u2192 overlooking"),
 E(["entirely","entire"], "Entirely", "completely; wholly", "entirely from earth", "entire \u2192 entirely \u2192 entirety"),
 E(["earth"], "Earth (soil)", "the substance of the ground; soil", "built from earth"),
 E(["consists of","consist"], "Consist of", "to be made up of", "it consists of ridges", "consist \u2192 consistent \u2192 consistency"),
 E(["semi-circular"], "Semi-circular", "shaped like half a circle", "semi-circular ridges", "circle \u2192 circular \u2192 semi-circular"),
 E(["ridges","ridge"], "Ridge", "a long, narrow raised strip of land", "six ridges"),
 E(["mounds","mound"], "Mound", "a rounded mass of earth or stones", "five mounds"),
 E(["archaeologists","archaeologist"], "Archaeologist", "a scientist who studies the past from remains", "as archaeologists refer to it", "archaeology \u2192 archaeologist \u2192 archaeological"),
 E(["refer to","refer"], "Refer to", "to call or name something", "as archaeologists refer to it", "refer \u2192 reference \u2192 referral"),
 E(["impressive"], "Impressive", "causing admiration", "not just impressive", "impress \u2192 impressive \u2192 impression"),
 E(["intriguing","intrigue"], "Intriguing", "very interesting; arousing curiosity", "they are also intriguing", "intrigue \u2192 intriguing \u2192 intrigued"),
 E(["Ancient","ancient"], "Ancient", "very old; from the distant past", "ancient monuments", "ancient \u2192 antiquity"),
 E(["regarded as","regarded","regard"], "Regarded as", "thought of or considered to be", "regarded as products", "regard \u2192 regarded \u2192 regarding"),
 E(["products","product"], "Product", "a result of a process or activity", "products of large societies", "produce \u2192 product \u2192 production"),
 E(["hierarchical","hierarchy"], "Hierarchical", "arranged in ranks or levels of power", "hierarchical societies", "hierarchy \u2192 hierarchical \u2192 hierarchically"),
 E(["societies","society"], "Society", "people living together in an organised community", "hierarchical societies", "society \u2192 social \u2192 societal"),
 E(["tributes","tribute"], "Tribute", "something done to show respect", "tributes to gods and kings", "tribute \u2192 tributes"),
 E(["gods","god"], "God", "a being worshipped as having power over nature", "tributes to gods"),
 E(["creators","creator"], "Creator", "a person who makes or builds something", "the creators of the monument", "create \u2192 creator \u2192 creation"),
 E(["hunter-gatherers","hunter-gatherer"], "Hunter-gatherer", "a person who lives by hunting and collecting food", "they were hunter-gatherers"),
 E(["functioned","function"], "Function (v)", "to work or operate in a particular way", "functioned in a democratic way", "function \u2192 functional \u2192 functioning"),
 E(["democratic"], "Democratic", "based on equal participation by all", "a more democratic way", "democracy \u2192 democratic \u2192 democratically"),
 E(["looked to","look to"], "Look to", "to rely on for help or guidance", "looked to elders for guidance"),
 E(["elders","elder"], "Elder", "an older, respected member of a group", "looked to elders", "old \u2192 elder \u2192 elderly"),
 E(["guidance"], "Guidance", "advice or direction", "for guidance", "guide \u2192 guidance \u2192 guided"),
 E(["exerted","exert"], "Exert", "to apply force or influence", "exerted a commanding influence", "exert \u2192 exertion \u2192 exerted"),
 E(["commanding"], "Commanding", "having a strong, controlling effect", "a commanding influence", "command \u2192 commanding \u2192 commander"),
 E(["influence"], "Influence (n)", "the power to affect something", "a commanding influence", "influence \u2192 influential \u2192 influencer"),
 E(["motivated","motivate"], "Motivate", "to give someone a reason to act", "what motivated building", "motivate \u2192 motivation \u2192 motivated"),
 E(["grand scale","scale","grand"], "On a grand scale", "to a very large extent", "on such a grand scale"),
 E(["excavating","excavate"], "Excavate", "to dig in the ground to find remains", "excavating Poverty Point", "excavate \u2192 excavation \u2192 excavator"),
 E(["century"], "Century", "a period of one hundred years", "for more than a century", "century \u2192 centuries"),
 E(["truly","true"], "Truly", "genuinely; really", "the truly remarkable nature", "true \u2192 truly \u2192 truth"),
 E(["nature"], "Nature (of sth)", "the basic qualities of something", "the nature of Mound A", "nature \u2192 natural"),
 E(["emerged","emerge"], "Emerge", "to become known or apparent", "only emerged a few years ago", "emerge \u2192 emergence \u2192 emerging"),
 E(["led by","led","lead"], "Led by", "directed or guided by", "a team led by Kidder", "lead \u2192 led \u2192 leader"),
 E(["drilled into","drilled","drill"], "Drill into", "to make a hole using a tool", "drilled into the mound", "drill \u2192 drilled \u2192 drilling"),
 E(["neat"], "Neat", "tidy and well-arranged", "neat layers", "neat \u2192 neatly \u2192 neatness"),
 E(["layers","layer"], "Layer", "a thickness of material on a surface", "neat layers of earth", "layer \u2192 layered \u2192 layering"),
 E(["differently coloured","coloured","colour"], "Coloured", "having a particular colour", "differently coloured earth", "colour \u2192 coloured \u2192 colourful"),
 E(["fluctuations","fluctuation"], "Fluctuation", "an irregular rising and falling", "fluctuations in temperature", "fluctuate \u2192 fluctuation \u2192 fluctuating"),
 E(["temperature"], "Temperature", "the degree of heat or cold", "fluctuations in temperature", "temperature \u2192 temperatures"),
 E(["flooding","flood"], "Flooding", "an overflow of water onto land", "increased flooding", "flood \u2192 flooding \u2192 flooded"),
 E(["abandonment","abandon"], "Abandonment", "the act of leaving something permanently", "led to its abandonment", "abandon \u2192 abandonment \u2192 abandoned"),
 E(["sign"], "Sign (n)", "an indication that something exists", "no sign that layers combined", "sign \u2192 signal \u2192 significant"),
 E(["combined","combine"], "Combine", "to join or mix together", "the layers had combined", "combine \u2192 combination \u2192 combined"),
 E(["construction"], "Construction", "the act of building", "during construction", "construct \u2192 construction \u2192 constructive"),
 E(["reached","reach"], "Reach (a conclusion)", "to arrive at a decision", "Kidder reached a conclusion", "reach \u2192 reached \u2192 reaching"),
 E(["startling","startle"], "Startling", "very surprising or alarming", "a startling conclusion", "startle \u2192 startling \u2192 startled"),
 E(["conclusion"], "Conclusion", "a judgement reached after thinking", "a startling conclusion", "conclude \u2192 conclusion \u2192 conclusive"),
 E(["short period","period"], "Period", "a length of time", "in one short period", "period \u2192 periodic \u2192 periodical"),
 E(["contains","contain"], "Contain", "to have inside; to hold", "contains 240,000 cubic metres", "contain \u2192 container \u2192 containment"),
 E(["cubic metres","cubic"], "Cubic metre", "a unit of volume (1m x 1m x 1m)", "240,000 cubic metres"),
 E(["equivalent"], "Equivalent (n)", "an equal amount or value", "the equivalent of 32,000 truckloads", "equivalent \u2192 equivalence"),
 E(["truckloads","truckload"], "Truckload", "the amount a truck can carry", "32,000 truckloads", "truck \u2192 truckload"),
 E(["trucks","truck"], "Truck", "a large road vehicle for carrying goods", "there were no trucks then"),
 E(["heavy machinery","machinery"], "Heavy machinery", "large powerful machines for big tasks", "no heavy machinery", "machine \u2192 machinery"),
 E(["mules","mule"], "Mule", "an animal used to carry heavy loads", "animals like mules"),
 E(["carry"], "Carry", "to move or transport something", "to carry the earth", "carry \u2192 carried \u2192 carrying"),
 E(["wheelbarrows","wheelbarrow"], "Wheelbarrow", "a small one-wheeled cart for carrying loads", "or wheelbarrows"),
 E(["Assuming","assuming","assume"], "Assuming", "supposing that something is true", "assuming it took 90 days", "assume \u2192 assuming \u2192 assumption"),
 E(["calculated","calculate"], "Calculate", "to work out by using numbers", "Kidder's group calculated", "calculate \u2192 calculation \u2192 calculator"),
 E(["basket-carrying","basket"], "Basket", "a container made of woven material", "basket-carrying individuals"),
 E(["individuals","individual"], "Individual", "a single person", "3,000 individuals", "individual \u2192 individually \u2192 individuality"),
 E(["get the job done","job"], "Get the job done", "to complete the necessary work", "needed to get the job done"),
 E(["Given that","given"], "Given that", "considering the fact that", "given that people travelled in groups"),
 E(["assembled","assemble"], "Assemble", "to gather together in one place", "people may have assembled", "assemble \u2192 assembly \u2192 assembled"),
 E(["extraordinarily","extraordinary"], "Extraordinarily", "to a very unusual degree", "an extraordinarily large gathering", "ordinary \u2192 extraordinary \u2192 extraordinarily"),
 E(["gathering"], "Gathering", "an assembly of people", "a large gathering", "gather \u2192 gathering \u2192 gathered"),
 E(["chosen","choose"], "Choose", "to select from options", "why they chose to do this", "choose \u2192 chosen \u2192 choice"),
 E(["answer"], "Answer (n)", "a solution or response", "he has the answer", "answer \u2192 answered \u2192 answering"),
 E(["famous"], "Famous", "known by many people", "their famous stone heads", "fame \u2192 famous \u2192 famously"),
 E(["statues","statue"], "Statue", "a carved or moulded figure", "the stone statues"),
 E(["prevailing","prevail"], "Prevailing", "most common or widely accepted", "the prevailing idea", "prevail \u2192 prevailing \u2192 prevalent"),
 E(["enormous"], "Enormous", "extremely large", "the enormous statues", "enormous \u2192 enormously \u2192 enormity"),
 E(["rolled into place","rolled","roll"], "Roll (v)", "to move by turning over and over", "rolled into place", "roll \u2192 rolled \u2192 rolling"),
 E(["logs","log"], "Log", "a piece of a tree trunk", "using logs"),
 E(["resulting","result"], "Resulting", "happening as a consequence", "the resulting deforestation", "result \u2192 resulting \u2192 resultant"),
 E(["deforestation"], "Deforestation", "the clearing of forests", "the resulting deforestation", "forest \u2192 deforest \u2192 deforestation"),
 E(["population's","population"], "Population", "all the people living in an area", "the population's collapse", "populate \u2192 population \u2192 populated"),
 E(["collapse"], "Collapse (n)", "a sudden failure or breakdown", "the population's collapse", "collapse \u2192 collapsed \u2192 collapsing"),
 E(["fellow"], "Fellow (adj)", "belonging to the same group", "fellow archaeologist", "fellow \u2192 fellowship"),
 E(["upright"], "Upright", "vertical; standing straight up", "walked upright into place", "upright \u2192 uprightness"),
 E(["cooperating","cooperate"], "Cooperate", "to work together", "cooperating bands of people", "cooperate \u2192 cooperation \u2192 cooperative"),
 E(["bands","band"], "Band (of people)", "a group of people acting together", "bands of people", "band \u2192 bands"),
 E(["ropes","rope"], "Rope", "thick cord made of twisted fibres", "using ropes"),
 E(["argue further","argue"], "Argue", "to give reasons for an opinion", "they argue further", "argue \u2192 argument \u2192 arguably"),
 E(["directed into","directed","direct"], "Direct (v)", "to aim or channel toward something", "energy was directed into interactions", "direct \u2192 directed \u2192 direction"),
 E(["peaceful"], "Peaceful", "free from conflict; calm", "peaceful interactions", "peace \u2192 peaceful \u2192 peacefully"),
 E(["interactions","interaction"], "Interaction", "communication between people", "peaceful interactions", "interact \u2192 interaction \u2192 interactive"),
 E(["information-sharing","sharing","share"], "Information-sharing", "the exchange of knowledge", "interactions and information-sharing", "share \u2192 sharing \u2192 shared"),
 E(["ceased","cease"], "Cease", "to stop doing something", "they ceased crafting statues", "cease \u2192 ceased \u2192 ceasing"),
 E(["crafting","craft"], "Craft (v)", "to make skilfully", "crafting statues", "craft \u2192 crafting \u2192 crafted"),
 E(["precisely","precise"], "Precisely", "exactly", "precisely because life was easier", "precise \u2192 precisely \u2192 precision"),
 E(["existence","exist"], "Existence", "the state of living or being", "daily existence", "exist \u2192 existence \u2192 existing"),
 E(["temple"], "Temple", "a building used for worship", "an ancient temple"),
 E(["site"], "Site", "the place where something is located", "another site", "site \u2192 sites"),
 E(["giant"], "Giant (adj)", "extremely large", "a giant project", "giant \u2192 gigantic"),
 E(["team-building","team"], "Team-building", "activity that improves group cooperation", "a team-building project"),
 E(["taken place","take place"], "Take place", "to happen or occur", "might have taken place"),
 E(["uncovered","uncover"], "Uncover", "to discover or reveal", "archaeologists uncovered enclosures", "cover \u2192 uncover \u2192 uncovered"),
 E(["enclosures","enclosure"], "Enclosure", "an area surrounded by a barrier", "nine enclosures", "enclose \u2192 enclosure \u2192 enclosed"),
 E(["formed of","formed","form"], "Formed of", "made up of", "formed of stone pillars", "form \u2192 formed \u2192 formation"),
 E(["massive"], "Massive", "extremely large and heavy", "massive stone pillars", "mass \u2192 massive \u2192 massively"),
 E(["pillars","pillar"], "Pillar", "a tall upright post supporting a structure", "stone pillars"),
 E(["vast"], "Vast", "extremely great in size", "the vast size", "vast \u2192 vastly \u2192 vastness"),
 E(["considerable"], "Considerable", "large in amount or degree", "a considerable workforce", "consider \u2192 considerable \u2192 considerably"),
 E(["workforce"], "Workforce", "all the workers available for a task", "a considerable workforce", "work \u2192 workforce \u2192 worker"),
 E(["every so often"], "Every so often", "occasionally; from time to time", "every so often, workers filled them in"),
 E(["filled in","filled","fill"], "Fill in", "to put material into a hole or space", "filled in the enclosures", "fill \u2192 filled \u2192 filling"),
 E(["broken rock","broken","break"], "Broken", "in pieces; not whole", "broken rock", "break \u2192 broken \u2192 breaking"),
 E(["apparent"], "Apparent", "seeming; clearly visible", "the apparent disposability", "apparent \u2192 apparently"),
 E(["disposability","disposable"], "Disposability", "the quality of being made to be thrown away", "the disposability of monuments", "dispose \u2192 disposable \u2192 disposability"),
 E(["makes sense","sense"], "Make sense", "to be reasonable or understandable", "makes sense if the aim was teamwork"),
 E(["aim"], "Aim (n)", "a goal or purpose", "the main aim", "aim \u2192 aimed \u2192 aiming"),
 E(["lasting"], "Lasting", "continuing for a long time", "a lasting structure", "last \u2192 lasting \u2192 long-lasting"),
 E(["structure"], "Structure", "something built; an arrangement of parts", "a lasting structure", "structure \u2192 structural \u2192 structured"),
 E(["bones","bone"], "Bone", "the hard parts of a skeleton", "bones from animals"),
 E(["gazelle"], "Gazelle", "a small, fast antelope", "animals such as gazelle"),
 E(["held feasts","feasts","feast"], "Feast (n)", "a large, celebratory meal", "people held feasts"),
 E(["celebrate"], "Celebrate", "to mark an event with enjoyment", "to celebrate the end", "celebrate \u2192 celebration \u2192 celebrated"),
 E(["collaborative"], "Collaborative", "involving people working together", "a collaborative effort", "collaborate \u2192 collaborative \u2192 collaboration"),
 E(["effort"], "Effort", "an attempt using energy and work", "a collaborative effort", "effort \u2192 effortless \u2192 effortlessly"),
 E(["share","share Lipo's view"], "Share (a view)", "to have the same opinion", "researchers share his view", "share \u2192 shared \u2192 sharing"),
 E(["cooperate"], "Cooperate", "to work together toward a goal", "the need to cooperate", "cooperate \u2192 cooperation \u2192 cooperative"),
 E(["drove","drive"], "Drive (v)", "to cause or motivate", "what drove monument makers", "drive \u2192 drove \u2192 driven"),
 E(["major shift","shift"], "Shift (n)", "a change in position or thinking", "a major shift in thinking", "shift \u2192 shifting \u2192 shifted"),
 E(["proposed","propose"], "Propose", "to put forward an idea", "when a shift is proposed", "propose \u2192 proposal \u2192 proposition"),
 E(["goes along with","go along with"], "Go along with", "to agree with or accept", "not everyone goes along with it"),
 E(["sceptics","sceptic"], "Sceptic", "a person who doubts accepted ideas", "the sceptics include Kidder", "sceptic \u2192 sceptical \u2192 scepticism"),
 E(["promote"], "Promote", "to encourage or support", "promote group survival", "promote \u2192 promotion \u2192 promotional"),
 E(["survival"], "Survival", "the state of continuing to live", "group survival", "survive \u2192 survival \u2192 survivor"),
 E(["builders","builder"], "Builder", "a person who builds things", "what the builders thought", "build \u2192 builder \u2192 building"),
 E(["behaviour"], "Behaviour", "the way someone acts", "all human behaviour", "behave \u2192 behaviour \u2192 behavioural"),
 E(["comes down to","come down to"], "Come down to", "to be essentially a matter of", "comes down to a pursuit of food"),
 E(["pursuit"], "Pursuit", "the act of trying to achieve something", "a pursuit of food", "pursue \u2192 pursuit \u2192 pursuing"),
 E(["self-preservation","preservation"], "Self-preservation", "the protection of oneself from harm", "food and self-preservation", "preserve \u2192 preservation \u2192 self-preservation"),
 E(["colleagues","colleague"], "Colleague", "a person one works with", "his colleagues", "colleague \u2192 colleagues"),
 E(["suggested","suggest"], "Suggest", "to put forward as a possibility", "they suggested it was a site", "suggest \u2192 suggestion \u2192 suggestive"),
 E(["pilgrimage"], "Pilgrimage", "a journey to a sacred place", "a pilgrimage site", "pilgrim \u2192 pilgrimage"),
 E(["inherited","inherit"], "Inherit", "to receive from those who came before", "inherited our ancestors' tendency", "inherit \u2192 inheritance \u2192 inherited"),
 E(["ancestors'","ancestors","ancestor"], "Ancestor", "a person from whom one is descended", "our ancestors' tendency", "ancestor \u2192 ancestral \u2192 ancestry"),
 E(["tendency"], "Tendency", "an inclination to behave in a way", "a tendency to work together", "tend \u2192 tendency \u2192 tending"),
 E(["for the sake of","sake"], "For the sake of", "for the benefit or purpose of", "for the sake of social harmony"),
 E(["social harmony","harmony"], "Harmony", "a state of peaceful agreement", "social harmony", "harmony \u2192 harmonious \u2192 harmonise"),
 E(["Evolutionary","evolutionary"], "Evolutionary", "relating to gradual development over time", "evolutionary biologist", "evolve \u2192 evolution \u2192 evolutionary"),
 E(["biologist"], "Biologist", "a scientist who studies living things", "evolutionary biologist", "biology \u2192 biologist \u2192 biological"),
 E(["cites","cite"], "Cite", "to mention as an example or proof", "Wilson cites the festival", "cite \u2192 citation \u2192 cited"),
 E(["festival"], "Festival", "an organised celebration or series of events", "the Burning Man festival", "festival \u2192 festive \u2192 festivities"),
 E(["promoted","promote"], "Promoted as", "advertised or presented as", "promoted as an experiment", "promote \u2192 promoted \u2192 promotion"),
 E(["experiment"], "Experiment", "a test or trial of an idea", "an experiment in community", "experiment \u2192 experimental \u2192 experimentation"),
 E(["draws","draw"], "Draw (v)", "to attract", "draws thousands of people", "draw \u2192 drew \u2192 drawn"),
 E(["principles","principle"], "Principle", "a basic rule or belief", "ten principles", "principle \u2192 principled"),
 E(["laid down","lay down"], "Lay down (rules)", "to establish a rule firmly", "principles laid down by Harvey"),
 E(["co-founder","founder"], "Co-founder", "one of the people who started something", "co-founder Larry Harvey", "found \u2192 founder \u2192 co-founder"),
 E(["inclusion"], "Inclusion", "the act of including everyone", "'inclusion' and 'communal effort'", "include \u2192 inclusion \u2192 inclusive"),
 E(["communal"], "Communal", "shared by all members of a community", "communal effort", "commune \u2192 communal \u2192 community"),
 E(["leaving no trace","trace"], "Leave no trace", "to leave no sign that one was there", "'leaving no trace'", "trace \u2192 traceable"),
 E(["festival-goers","festival-goer"], "Festival-goer", "a person who attends a festival", "whatever festival-goers create"),
 E(["destroy"], "Destroy", "to damage so badly it no longer exists", "they destroy it", "destroy \u2192 destruction \u2192 destructive"),
 E(["departing","depart"], "Depart", "to leave", "before departing", "depart \u2192 departure \u2192 departing"),
 E(["temporarily","temporary"], "Temporarily", "for a limited time only", "only temporarily disturbed", "temporary \u2192 temporarily"),
 E(["disturbed","disturb"], "Disturb", "to interfere with or upset", "the landscape is disturbed", "disturb \u2192 disturbance \u2192 disturbed"),
 E(["landscape"], "Landscape", "the visible features of an area of land", "the desert landscape", "landscape \u2192 landscaping"),
 E(["ventures","venture"], "Venture (n)", "a project, especially a risky one", "cooperative ventures", "venture \u2192 ventures"),
 E(["matter"], "Matter (v)", "to be important", "ventures matter more today", "matter \u2192 matters"),
 E(["dependent on","dependent"], "Dependent on", "needing or relying on", "dependent on a range of people", "depend \u2192 dependent \u2192 dependence"),
 E(["wider range","range"], "A wide range of", "a large variety of", "a wider range of people", "range \u2192 ranging"),
 E(["education"], "Education", "the process of teaching and learning", "food, education, security", "educate \u2192 education \u2192 educational"),
 E(["security"], "Security", "the state of being safe and protected", "food, education, security", "secure \u2192 security \u2192 securely"),
 E(["beyond"], "Beyond", "outside the range or limits of", "people beyond our family group", "beyond \u2192 beyond"),
 E(["Neighbourhood","neighbourhood"], "Neighbourhood", "a district within a town or city", "his Neighbourhood Project", "neighbour \u2192 neighbourhood \u2192 neighbouring"),
 E(["locals","local"], "Locals", "people who live in a particular area", "helped locals create parks", "local \u2192 locally \u2192 locality"),
 E(["parks","park"], "Park", "a public area of land for recreation", "create their own parks"),
 E(["brought people together","brought together"], "Bring together", "to unite people", "this brought people together"),
 E(["enabled","enable"], "Enable", "to make something possible", "enabled them to cooperate", "enable \u2192 enabled \u2192 enabling"),
 E(["contexts","context"], "Context", "the circumstances of a situation", "in other contexts", "context \u2192 contextual \u2192 contextualise"),
 E(["repairs","repair"], "Repair (n)", "the act of fixing something", "helping with repairs", "repair \u2192 repaired \u2192 repairing"),
 E(["series"], "Series", "a number of similar things in a row", "a series of floods", "series \u2192 serial"),
 E(["floods","flood"], "Flood", "an overflow of water onto dry land", "a series of floods", "flood \u2192 flooding \u2192 flooded"),
 E(["Social psychologist","psychologist"], "Psychologist", "a scientist who studies the mind and behaviour", "social psychologist", "psychology \u2192 psychologist \u2192 psychological"),
 E(["sees value in","value"], "See value in", "to recognise the usefulness of", "sees value in community projects"),
 E(["projects","project"], "Project", "a planned piece of work", "community projects", "project \u2192 projects"),
 E(["break down","break down the ill-informed views"], "Break down", "to reduce or remove (a barrier or view)", "break down the views"),
 E(["ill-informed"], "Ill-informed", "based on poor or wrong knowledge", "ill-informed views", "inform \u2192 informed \u2192 ill-informed"),
 E(["hold towards","hold"], "Hold (a view)", "to have an opinion or attitude", "views people hold", "hold \u2192 held \u2192 holding"),
 E(["interact with","interact"], "Interact with", "to communicate or deal with", "people they do not interact with", "interact \u2192 interaction \u2192 interactive"),
 E(["surely","sure"], "Surely", "certainly; without doubt", "that will surely be an achievement", "sure \u2192 surely \u2192 ensure"),
 E(["monumental"], "Monumental", "very great or important; like a monument", "a monumental achievement", "monument \u2192 monumental \u2192 monumentally"),
 E(["achievement"], "Achievement", "a thing done successfully", "a monumental achievement", "achieve \u2192 achievement \u2192 achievable"),
]

PASSAGES = [
 {"num": 1, "title": "Earth's Lakes Are Under Threat", "paragraphs": P1_PARAS, "entries": P1_ENTRIES},
 {"num": 2, "title": "Biofuels: Are They the Fuels of the Future?", "paragraphs": P2_PARAS, "entries": P2_ENTRIES},
 {"num": 3, "title": "Team Building", "paragraphs": P3_PARAS, "entries": P3_ENTRIES},
]
