# -*- coding: utf-8 -*-
# Test 3 Reading: 3 passages + comprehensive vocab (elementary -> advanced)
E = lambda hl, word, d, coll="", fam="": {"hl": hl, "word": word, "def": d, "coll": coll, "fam": fam}

P1_PARAS = [
"The birth of modern American dance occurred in the first years of the twentieth century. And, perhaps unusually for academics, dance historians hold remarkably similar views when it comes to identifying the individuals and influences that shaped the evolution of modern American dance. Starting in the early 1900s, we can see that dancers quite deliberately moved away from previous approaches. This included rejecting both the formal moves of ballet dancing and the entertainment of vaudeville dancing. As a result, dancers began the new century with a fresh start. One important figure at this time was Loie Fuller, who performed largely with her arms, perhaps because she had limited dance training. Fuller emphasised visual effects rather than storytelling, and pioneered the use of artificial lighting to create shadows while dancing.",
"Perhaps most influential in the early years was Isadora Duncan, who was well known in both America and Europe. Duncan refused to wear elaborate costumes, preferring to dance in plain dresses and bare feet. She is also notable for preferring music written by classical composers such as Chopin and Beethoven, rather than contemporary compositions. At a similar time, Ruth St Denis was bringing the influence of Eastern cultures to American dance, often performing solo. In 1915, St Denis opened a dance training academy with her husband with the intention of passing on her approach and style to the next generation of American dancers.",
"By the 1920s, the modern dance movement in America was well established. Audiences were enthusiastic and dancers were increasingly prepared to experiment with new ideas. Martha Graham was one of an important group who emerged in New York. Graham looked within herself to find her dance style, examining how her body moved as she breathed, but also observing the patterns made by her limbs when walking in order to find a new, naturalistic approach to dance. Doris Humphrey wanted her dance to reflect her personal experience of American life. She explored the concept of gravity, allowing her body to fall, only to recover at the last moment. Her book The Art of Making Dances, which detailed her approach to dance composition, was highly influential with later generations of dancers.",
"By the 1930s, modern dance was becoming an accepted, respectable art form. Universities such as Bennington College included modern dance in their performing arts programmes for the first time. In the 1940s, German-born dancer Hanya Holm embraced the changing times by including modern dance in mainstream musicals on the Broadway stage. Among Holm's many other innovations was bringing her own humour to these performances - audiences adored it.",
"Modern American dance has seldom stood still. Each new generation of dancers either developed the techniques of their teachers or rejected them outright. So by the 1950s the techniques of traditional European ballet dancing were again influential. This was certainly true of Erick Hawkins, who also incorporated Native American and Asian styles. Similarly, Merce Cunningham emphasised the leg actions and flexibility of the spine associated with ballet moves. Paul Taylor preferred his dance to reflect the experiences and interactions of ordinary people going about their everyday lives. Taylor's career was the subject of a documentary that provided valuable insights into this period of dance.",
"The middle decades of the 20th century were certainly a dynamic time. Increasingly, the modern dance movement recognised and reflected the fact that America was a multi-racial, multi-cultural society. Katherine Dunham, an anthropology graduate, used movements from Pacific, African and Caribbean dance to create her unique style. Pearl Primus was another champion of African dance, which she passed on through her dance school in New York. After retirement she travelled widely to universities throughout America lecturing on ethnic dance, which became her main priority.",
"Modern dance since the 1980s has become a mix of multiple forms of dance, as well as art more generally. For example, Mark Morris's hugely popular work The Hard Nut includes sensational costumes and a stage design inspired by the comics he'd always enjoyed. Another innovator has been Ohad Naharin, who studied in New York and has worked internationally. Naharin's 'Gaga' style is characterised by highly flexible limbs and backbones, while in rehearsal his dancers have no mirrors, feeling their movements from within themselves, a break from traditional dance custom. In many ways it was a fitting end to a 100-year period that had witnessed a transformation in dance. The emergence of modern American dance was very much a 20th-century phenomenon. The style drew on influences from home and abroad and in turn went on to influence global dance culture.",
]

P1_ENTRIES = [
 E(["birth"], "Birth", "the start or origin of something", "the birth of modern dance", "birth \u2192 born \u2192 rebirth"),
 E(["modern"], "Modern", "relating to the present or recent times", "modern American dance", "modern \u2192 modernise \u2192 modernity"),
 E(["occurred","occur"], "Occur", "to happen or take place", "the birth occurred", "occur \u2192 occurrence \u2192 occurring"),
 E(["century"], "Century", "a period of one hundred years", "the twentieth century", "century \u2192 centuries"),
 E(["unusually","unusual"], "Unusually", "in a way that is not normal or expected", "unusually for academics", "usual \u2192 unusual \u2192 unusually"),
 E(["academics","academic"], "Academic", "a person who teaches or researches at a university", "unusually for academics", "academic \u2192 academy \u2192 academically"),
 E(["historians","historian"], "Historian", "an expert in history", "dance historians", "history \u2192 historian \u2192 historical"),
 E(["remarkably","remarkable"], "Remarkably", "in a way that is worthy of attention; strikingly", "remarkably similar views", "remark \u2192 remarkable \u2192 remarkably"),
 E(["views","view"], "View (n)", "an opinion or belief", "similar views", "view \u2192 viewpoint \u2192 viewer"),
 E(["identifying","identify"], "Identify", "to recognise or name something", "identifying the individuals", "identify \u2192 identification \u2192 identifiable"),
 E(["individuals","individual"], "Individual", "a single person", "the individuals and influences", "individual \u2192 individually \u2192 individuality"),
 E(["influences","influence"], "Influence (n)", "the power to affect how something develops", "influences that shaped dance", "influence \u2192 influential \u2192 influencer"),
 E(["shaped","shape"], "Shape (v)", "to determine or strongly influence the form of", "influences that shaped dance", "shape \u2192 shaped \u2192 shaping"),
 E(["evolution"], "Evolution", "the gradual development of something", "the evolution of dance", "evolve \u2192 evolution \u2192 evolutionary"),
 E(["deliberately","deliberate"], "Deliberately", "in an intentional, planned way", "deliberately moved away", "deliberate \u2192 deliberately \u2192 deliberation"),
 E(["moved away from","moved away"], "Move away from", "to stop using or following something", "moved away from old approaches"),
 E(["previous"], "Previous", "existing or happening before", "previous approaches", "previous \u2192 previously"),
 E(["approaches","approach"], "Approach (n)", "a way of dealing with something", "previous approaches", "approach \u2192 approaches"),
 E(["rejecting","reject"], "Reject", "to refuse to accept or use", "rejecting formal moves", "reject \u2192 rejection \u2192 rejected"),
 E(["formal"], "Formal", "following strict rules or conventions", "the formal moves of ballet", "form \u2192 formal \u2192 formally"),
 E(["ballet"], "Ballet", "a formal, artistic style of dance", "ballet dancing"),
 E(["entertainment"], "Entertainment", "activity that amuses or interests people", "the entertainment of vaudeville", "entertain \u2192 entertainment \u2192 entertaining"),
 E(["vaudeville"], "Vaudeville", "a type of variety stage entertainment", "vaudeville dancing"),
 E(["fresh start","fresh"], "Fresh start", "a new beginning", "a fresh start"),
 E(["figure"], "Figure (n)", "an important or well-known person", "an important figure", "figure \u2192 figures"),
 E(["performed","perform"], "Perform", "to present an activity before an audience", "performed with her arms", "perform \u2192 performance \u2192 performer"),
 E(["largely"], "Largely", "mostly; to a great extent", "performed largely with her arms", "large \u2192 largely"),
 E(["limited"], "Limited", "small in amount; restricted", "limited dance training", "limit \u2192 limited \u2192 limitation"),
 E(["training"], "Training", "the process of learning a skill", "limited dance training", "train \u2192 training \u2192 trainer"),
 E(["emphasised","emphasise"], "Emphasise", "to give special importance to something", "emphasised visual effects", "emphasis \u2192 emphasise \u2192 emphatic"),
 E(["visual"], "Visual", "relating to seeing or sight", "visual effects", "vision \u2192 visual \u2192 visually"),
 E(["effects","effect"], "Effect (n)", "a result; a produced impression", "visual effects", "effect \u2192 effective \u2192 effectively"),
 E(["storytelling"], "Storytelling", "the activity of telling stories", "rather than storytelling", "story \u2192 storyteller \u2192 storytelling"),
 E(["pioneered","pioneer"], "Pioneer (v)", "to be the first to develop something", "pioneered artificial lighting", "pioneer \u2192 pioneering \u2192 pioneered"),
 E(["artificial"], "Artificial", "made by humans; not natural", "artificial lighting", "artificial \u2192 artificially \u2192 artificiality"),
 E(["lighting"], "Lighting", "the arrangement of lights", "artificial lighting", "light \u2192 lighting \u2192 lit"),
 E(["shadows","shadow"], "Shadow", "a dark shape made when light is blocked", "to create shadows", "shadow \u2192 shadowy"),
 E(["influential"], "Influential", "having great influence or effect", "most influential", "influence \u2192 influential \u2192 influentially"),
 E(["refused","refuse"], "Refuse", "to say one will not do something", "refused to wear costumes", "refuse \u2192 refusal \u2192 refused"),
 E(["elaborate"], "Elaborate", "detailed and complicated", "elaborate costumes", "elaborate \u2192 elaborately \u2192 elaboration"),
 E(["costumes","costume"], "Costume", "clothes worn for a performance", "elaborate costumes"),
 E(["preferring","preferred","prefer"], "Prefer", "to like one thing better than another", "preferring plain dresses", "prefer \u2192 preference \u2192 preferable"),
 E(["plain"], "Plain", "simple; without decoration", "plain dresses", "plain \u2192 plainly"),
 E(["bare feet","bare"], "Bare", "not covered or clothed", "bare feet", "bare \u2192 barely"),
 E(["notable"], "Notable", "worthy of attention; remarkable", "she is notable for", "note \u2192 notable \u2192 notably"),
 E(["classical"], "Classical", "relating to traditional, formal art or music", "classical composers", "classic \u2192 classical \u2192 classically"),
 E(["composers","composer"], "Composer", "a person who writes music", "classical composers", "compose \u2192 composer \u2192 composition"),
 E(["contemporary"], "Contemporary", "belonging to the present time; modern", "contemporary compositions", "contemporary \u2192 contemporaries"),
 E(["compositions","composition"], "Composition", "a piece of music or art that is created", "contemporary compositions", "compose \u2192 composition \u2192 composer"),
 E(["bringing the influence","bringing"], "Bring (influence)", "to introduce or carry something to a place", "bringing the influence of Eastern cultures", "bring \u2192 brought \u2192 bringing"),
 E(["Eastern"], "Eastern", "relating to the east, especially Asia", "Eastern cultures", "east \u2192 eastern \u2192 easterly"),
 E(["cultures","culture"], "Culture", "the customs and arts of a society", "Eastern cultures", "culture \u2192 cultural \u2192 culturally"),
 E(["solo"], "Solo", "done alone by one person", "performing solo", "solo \u2192 soloist"),
 E(["academy"], "Academy", "a school for special training", "a dance training academy", "academy \u2192 academic \u2192 academia"),
 E(["intention"], "Intention", "a plan or aim to do something", "with the intention of", "intend \u2192 intention \u2192 intentional"),
 E(["passing on","passing on her approach","pass on"], "Pass on", "to give knowledge or skills to others", "passing on her approach", "pass \u2192 passing \u2192 passed"),
 E(["generation"], "Generation", "all people of about the same age", "the next generation", "generate \u2192 generation \u2192 generational"),
 E(["movement"], "Movement", "a group sharing the same aims or ideas", "the modern dance movement", "move \u2192 movement \u2192 mover"),
 E(["well established","established","establish"], "Established", "firmly set up and accepted", "the movement was well established", "establish \u2192 established \u2192 establishment"),
 E(["audiences","audience"], "Audience", "the people watching a performance", "audiences were enthusiastic", "audience \u2192 audiences"),
 E(["enthusiastic"], "Enthusiastic", "showing great interest and excitement", "audiences were enthusiastic", "enthusiasm \u2192 enthusiastic \u2192 enthusiastically"),
 E(["increasingly"], "Increasingly", "more and more over time", "increasingly prepared", "increase \u2192 increasingly \u2192 increased"),
 E(["experiment"], "Experiment (v)", "to try new ideas or methods", "experiment with new ideas", "experiment \u2192 experimental \u2192 experimentation"),
 E(["emerged","emerge"], "Emerge", "to come out or become known", "an important group who emerged", "emerge \u2192 emergence \u2192 emerging"),
 E(["examining","examine"], "Examine", "to look at something closely", "examining how her body moved", "examine \u2192 examination \u2192 examiner"),
 E(["breathed","breathe"], "Breathe", "to take air into the lungs and let it out", "as she breathed", "breathe \u2192 breath \u2192 breathing"),
 E(["observing","observe"], "Observe", "to watch carefully", "observing the patterns", "observe \u2192 observation \u2192 observer"),
 E(["patterns","pattern"], "Pattern", "a regular, repeated arrangement", "the patterns made by her limbs"),
 E(["limbs","limb"], "Limb", "an arm or leg", "her limbs when walking"),
 E(["naturalistic"], "Naturalistic", "imitating real life or nature", "a naturalistic approach", "nature \u2192 natural \u2192 naturalistic"),
 E(["reflect"], "Reflect", "to show or express something", "reflect her personal experience", "reflect \u2192 reflection \u2192 reflective"),
 E(["personal"], "Personal", "relating to a particular individual", "her personal experience", "person \u2192 personal \u2192 personally"),
 E(["explored","explore"], "Explore", "to examine or investigate something", "she explored the concept of gravity", "explore \u2192 exploration \u2192 explorer"),
 E(["concept"], "Concept", "an abstract idea", "the concept of gravity", "concept \u2192 conceptual \u2192 conceptualise"),
 E(["gravity"], "Gravity", "the force that pulls objects toward the earth", "the concept of gravity", "gravity \u2192 gravitational"),
 E(["recover"], "Recover", "to return to a normal state", "only to recover at the last moment", "recover \u2192 recovery \u2192 recoverable"),
 E(["detailed","detail"], "Detail (v)", "to describe fully", "her book detailed her approach", "detail \u2192 detailed \u2192 detailing"),
 E(["composition"], "Composition (n)", "the way parts are arranged in a work", "dance composition", "compose \u2192 composition \u2192 compositional"),
 E(["generations","generation"], "Generation", "a stage in a family or period of people", "later generations of dancers"),
 E(["accepted","accept"], "Accepted", "generally approved or recognised", "an accepted art form", "accept \u2192 accepted \u2192 acceptance"),
 E(["respectable"], "Respectable", "considered to be good and proper", "a respectable art form", "respect \u2192 respectable \u2192 respectably"),
 E(["art form"], "Art form", "a recognised type of artistic activity", "a respectable art form"),
 E(["performing arts"], "Performing arts", "arts performed before an audience (e.g. dance)", "their performing arts programmes"),
 E(["programmes","programme"], "Programme", "a planned series of courses or events", "performing arts programmes"),
 E(["German-born","born"], "German-born", "born in Germany", "German-born dancer"),
 E(["embraced","embrace"], "Embrace", "to accept something willingly", "embraced the changing times", "embrace \u2192 embraced \u2192 embracing"),
 E(["mainstream"], "Mainstream", "accepted by or belonging to the majority", "mainstream musicals", "mainstream \u2192 mainstreaming"),
 E(["musicals","musical"], "Musical (n)", "a play or film with songs and dancing", "mainstream musicals"),
 E(["innovations","innovation"], "Innovation", "a new idea, method or invention", "her many innovations", "innovate \u2192 innovation \u2192 innovative"),
 E(["humour"], "Humour", "the quality of being amusing", "her own humour", "humour \u2192 humorous \u2192 humourless"),
 E(["adored","adore"], "Adore", "to love and admire greatly", "audiences adored it", "adore \u2192 adoration \u2192 adored"),
 E(["seldom"], "Seldom", "not often; rarely", "has seldom stood still", ""),
 E(["stood still","stand still"], "Stand still", "to stay the same; not change", "dance has seldom stood still"),
 E(["techniques","technique"], "Technique", "a particular method of doing something", "the techniques of their teachers", "technique \u2192 technical \u2192 technician"),
 E(["outright"], "Outright", "completely and immediately", "rejected them outright", "right \u2192 outright"),
 E(["traditional"], "Traditional", "following long-established customs", "traditional ballet", "tradition \u2192 traditional \u2192 traditionally"),
 E(["incorporated","incorporate"], "Incorporate", "to include as part of a whole", "incorporated Asian styles", "incorporate \u2192 incorporation \u2192 incorporated"),
 E(["similarly","similar"], "Similarly", "in a similar way; likewise", "similarly, Cunningham emphasised", "similar \u2192 similarly \u2192 similarity"),
 E(["flexibility"], "Flexibility", "the ability to bend or adapt easily", "flexibility of the spine", "flexible \u2192 flexibility \u2192 flexibly"),
 E(["spine"], "Spine", "the line of bones down the back; backbone", "the flexibility of the spine", "spine \u2192 spinal"),
 E(["associated with","associated"], "Associated with", "connected with", "associated with ballet moves", "associate \u2192 association \u2192 associated"),
 E(["interactions","interaction"], "Interaction", "communication or action between people", "the interactions of people", "interact \u2192 interaction \u2192 interactive"),
 E(["ordinary"], "Ordinary", "normal; not special", "ordinary people", "ordinary \u2192 ordinarily \u2192 extraordinary"),
 E(["everyday"], "Everyday", "happening or used daily; ordinary", "everyday lives", ""),
 E(["career"], "Career", "a person's professional life", "Taylor's career", "career \u2192 careerist"),
 E(["subject"], "Subject (n)", "the person or thing being discussed or shown", "the subject of a documentary", "subject \u2192 subjects"),
 E(["documentary"], "Documentary", "a film giving facts about a real subject", "a documentary", "document \u2192 documentary"),
 E(["valuable"], "Valuable", "very useful or important", "valuable insights", "value \u2192 valuable \u2192 invaluable"),
 E(["insights","insight"], "Insight", "a clear, deep understanding", "valuable insights", "insight \u2192 insightful"),
 E(["decades","decade"], "Decade", "a period of ten years", "the middle decades", "decade \u2192 decades"),
 E(["dynamic"], "Dynamic", "full of energy and change", "a dynamic time", "dynamic \u2192 dynamically \u2192 dynamism"),
 E(["recognised","recognise"], "Recognise", "to accept or acknowledge something", "the movement recognised the fact", "recognise \u2192 recognition \u2192 recognisable"),
 E(["multi-racial"], "Multi-racial", "including people of many races", "a multi-racial society", "race \u2192 racial \u2192 multi-racial"),
 E(["multi-cultural"], "Multi-cultural", "including people of many cultures", "a multi-cultural society", "culture \u2192 cultural \u2192 multi-cultural"),
 E(["society"], "Society", "people living together in a community", "American society", "society \u2192 social \u2192 societal"),
 E(["anthropology"], "Anthropology", "the study of human societies and cultures", "an anthropology graduate", "anthropology \u2192 anthropologist \u2192 anthropological"),
 E(["graduate"], "Graduate (n)", "a person who has completed a university degree", "an anthropology graduate", "graduate \u2192 graduation \u2192 graduated"),
 E(["movements","movement"], "Movement (n)", "an act of moving the body", "movements from Pacific dance"),
 E(["unique"], "Unique", "being the only one of its kind", "her unique style", "unique \u2192 uniquely \u2192 uniqueness"),
 E(["champion"], "Champion (n)", "a person who supports or defends a cause", "a champion of African dance", "champion \u2192 championing"),
 E(["passed on","pass on"], "Pass on", "to teach or give to others", "she passed on the dance", "pass \u2192 passing \u2192 passed"),
 E(["retirement"], "Retirement", "the time when one stops working", "after retirement", "retire \u2192 retirement \u2192 retired"),
 E(["widely"], "Widely", "over a large area; by many", "travelled widely", "wide \u2192 widely \u2192 widespread"),
 E(["lecturing","lecture"], "Lecture (v)", "to give a formal educational talk", "lecturing on ethnic dance", "lecture \u2192 lecturer \u2192 lecturing"),
 E(["ethnic"], "Ethnic", "relating to a cultural or racial group", "ethnic dance", "ethnic \u2192 ethnicity \u2192 ethnically"),
 E(["priority"], "Priority", "a thing treated as most important", "her main priority", "prior \u2192 priority \u2192 prioritise"),
 E(["multiple"], "Multiple", "many; consisting of several", "multiple forms of dance", "multiple \u2192 multiply \u2192 multiplicity"),
 E(["hugely","huge"], "Hugely", "to a very great extent", "hugely popular", "huge \u2192 hugely"),
 E(["sensational"], "Sensational", "causing great excitement; spectacular", "sensational costumes", "sensation \u2192 sensational \u2192 sensationally"),
 E(["stage design","design"], "Design (n)", "a plan or arrangement of something", "a stage design", "design \u2192 designer \u2192 designed"),
 E(["comics","comic"], "Comic (n)", "a magazine telling stories with pictures", "inspired by the comics"),
 E(["innovator"], "Innovator", "a person who introduces new ideas", "another innovator", "innovate \u2192 innovator \u2192 innovation"),
 E(["internationally","international"], "Internationally", "in or involving many countries", "worked internationally", "nation \u2192 international \u2192 internationally"),
 E(["characterised by","characterise"], "Characterised by", "having as a typical feature", "characterised by flexible limbs", "character \u2192 characterise \u2192 characteristic"),
 E(["flexible"], "Flexible", "able to bend easily; adaptable", "highly flexible limbs", "flex \u2192 flexible \u2192 flexibility"),
 E(["backbones","backbone"], "Backbone", "the spine; the line of bones in the back", "flexible limbs and backbones"),
 E(["rehearsal"], "Rehearsal", "a practice session before a performance", "in rehearsal", "rehearse \u2192 rehearsal \u2192 rehearsed"),
 E(["mirrors","mirror"], "Mirror", "a surface that reflects images", "dancers have no mirrors"),
 E(["custom"], "Custom", "a traditional way of behaving", "traditional dance custom", "custom \u2192 customary \u2192 customarily"),
 E(["fitting"], "Fitting (adj)", "suitable or appropriate", "a fitting end", "fit \u2192 fitting \u2192 fittingly"),
 E(["witnessed","witness"], "Witness (v)", "to see or experience an event", "had witnessed a transformation", "witness \u2192 witnessed \u2192 witnessing"),
 E(["transformation"], "Transformation", "a complete change in form or nature", "a transformation in dance", "transform \u2192 transformation \u2192 transformative"),
 E(["emergence"], "Emergence", "the process of coming into existence", "the emergence of modern dance", "emerge \u2192 emergence \u2192 emerging"),
 E(["phenomenon"], "Phenomenon", "a remarkable fact or occurrence", "a 20th-century phenomenon", "phenomenon \u2192 phenomena \u2192 phenomenal"),
 E(["drew on","draw on"], "Draw on", "to make use of a resource or source", "the style drew on influences", "draw \u2192 drew \u2192 drawn"),
 E(["abroad"], "Abroad", "in or to a foreign country", "influences from home and abroad", ""),
 E(["in turn"], "In turn", "as a result; one after another", "in turn went on to influence", ""),
 E(["global"], "Global", "relating to the whole world", "global dance culture", "globe \u2192 global \u2192 globally"),
]


P2_PARAS = [
"Human beings love to laugh. It's such an obvious fact that it's easy to overlook. Laughter, like music and language, is a fundamental human trait. Common sense tells us that laughter is associated with happiness. However, there is also a body of scientific evidence proving that laughter is good for us. Studies show that laughter strengthens relationships in both personal and professional life. It has also been established that laughter improves cardiovascular function, boosts the immune system and releases beneficial hormones into the bloodstream. However, according to psychologist Dr Peter Shrimpton, humans might all laugh, but they often don't remember doing it. 'All the studies show that we laugh more frequently than we realise,' says Dr Shrimpton. 'Perhaps because it is such a basic part of human nature, we tend not to notice when we are laughing.'",
"Infants typically give their first laugh around three to four months of age, long before they can talk. But according to biologists, this isn't because they find something amusing; it is rather a form of non-verbal communication. They laugh to form a closer connection to the people they are with, and adults are little different. 'There is a widespread belief outside the scientific community that we laugh because something is humorous,' says sociologist Jocelyn Barnes. 'While this is true, just as commonly the real purpose of laughter is to promote bonding with other individuals or groups.' This may be partly because it is almost impossible to imitate laughter; even trained actors struggle to mimic a laugh convincingly. So if someone is laughing, the chances are they are being genuine. There's even a difference between a real and a fake smile. In the 19th century, the French neurologist Guillaume Duchenne found that a genuine smile activates the zygomaticus major and orbicularis muscles, and this in turn causes lines to develop called 'crow's feet' at the outside corners of the eyes. No crow's feet appear if the smile is put on.",
"There is certainly nothing new about joking and laughter. Attempts to be humorous have been found from ancient Egypt, dating from 2600 BC. And a long and detailed joke book called The Laughter Lover, which was written in ancient Rome, still exists today. While of considerable historical value, it may not be all that amusing any more. A professor of classics, Heinrich Ahrends, has studied many such ancient sources and concluded that tastes in jokes have evolved markedly with the passing of the centuries and that the jokes of our forebears would not get much of a laugh today - and vice versa, no doubt. Nonetheless, studies show that almost everyone can find amusement in some form or other. There is a rare neurological disorder named aphonogelia that prevents some people from laughing out loud. However, they may still be amused or entertained, but just express it in different ways.",
"Much more common is contagious laughter: laughter that spreads uncontrollably between people, sometimes referred to as 'getting the giggles'. Many people will have experienced this themselves, particularly as children, though it also occurs in adults. On one infamous occasion, a group of BBC cricket commentators got the giggles while broadcasting live on radio. And in January 1962 in Tanzania contagious laughter spread through a group of students. Ninety-five pupils were affected and one girl laughed continuously for 16 days. Eventually the situation became so bad that the authorities at the school felt obliged to close it temporarily. In general, however, it is possible for most people to suppress laughter in circumstances where it would be inappropriate. Scientists believe this is possible because in the brain's cerebral cortex there appears to be a laughter switch over which humans have some conscious control.",
"What is becoming clear to scientists is that laughter is highly complex. It appears, for example, that laughter has the power to override other emotions, at least temporarily. Neurologist Nikki Sokolov is studying the network of brain circuits and neurotransmitters that regulate laughter and other emotions. She hopes her work may provide further insights to explain the processes involved when laughter occurs simultaneously with other, seemingly contradictory emotions, such as crying, for example. Another aspect of humour's complexity is that it is so subjective. What makes one person laugh will be met with stony silence by another. Writer David Mackenzie recognised this from the reactions his own jokes received. Intrigued, Mackenzie conducted an international online survey to establish exactly what makes people laugh and what doesn't, and was surprised by the diverse and often contradictory variety of topics and scenarios that were listed in each category. Understanding humour is still as much an art as a science, according to theatre critic Jake Gottlieb. 'Stand-up comedians are a remarkable type,' says Gottlieb. 'Making jokes for a living is a serious business. You need to be a psychologist and social commentator, be empathetic, self-aware, observant, stubborn and have great timing. Not many of us are so multi-talented.' Perhaps not, but we can still enjoy the instinctive humour of our family and friends, and perhaps sometimes buy a ticket for a show.",
]

P2_ENTRIES = [
 E(["Human beings","human beings"], "Human beings", "people; members of the human race", "human beings love to laugh"),
 E(["laugh"], "Laugh", "to make sounds and movements showing amusement", "love to laugh", "laugh \u2192 laughter \u2192 laughable"),
 E(["obvious"], "Obvious", "easy to see or understand", "such an obvious fact", "obvious \u2192 obviously"),
 E(["overlook"], "Overlook", "to fail to notice something", "easy to overlook", "overlook \u2192 overlooked"),
 E(["Laughter","laughter"], "Laughter", "the act or sound of laughing", "laughter is a human trait", "laugh \u2192 laughter"),
 E(["language"], "Language", "a system of human communication", "music and language", "language \u2192 linguistic \u2192 linguist"),
 E(["fundamental"], "Fundamental", "basic and essential", "a fundamental human trait", "fundamental \u2192 fundamentally"),
 E(["trait"], "Trait", "a particular quality or characteristic", "a human trait", "trait \u2192 traits"),
 E(["Common sense","common sense"], "Common sense", "practical good judgement", "common sense tells us"),
 E(["associated with","associated"], "Associated with", "connected with in the mind", "associated with happiness", "associate \u2192 association \u2192 associated"),
 E(["happiness"], "Happiness", "the state of being happy", "associated with happiness", "happy \u2192 happiness \u2192 happily"),
 E(["scientific evidence","evidence"], "Evidence", "facts proving something is true", "scientific evidence", "evident \u2192 evidence \u2192 evidently"),
 E(["proving","prove"], "Prove", "to show that something is true", "evidence proving laughter is good", "prove \u2192 proof \u2192 proven"),
 E(["strengthens","strengthen"], "Strengthen", "to make stronger", "laughter strengthens relationships", "strong \u2192 strength \u2192 strengthen"),
 E(["relationships","relationship"], "Relationship", "the way people are connected", "strengthens relationships", "relate \u2192 relationship \u2192 related"),
 E(["professional"], "Professional", "relating to one's work or job", "personal and professional life", "profession \u2192 professional \u2192 professionally"),
 E(["established"], "Established (it has been)", "shown or proved to be true", "it has been established that", "establish \u2192 established \u2192 establishment"),
 E(["improves","improve"], "Improve", "to make or become better", "laughter improves function", "improve \u2192 improvement \u2192 improved"),
 E(["cardiovascular"], "Cardiovascular", "relating to the heart and blood vessels", "cardiovascular function", ""),
 E(["function"], "Function (n)", "the natural activity of something", "cardiovascular function", "function \u2192 functional \u2192 functioning"),
 E(["boosts","boost"], "Boost", "to increase or improve something", "boosts the immune system", "boost \u2192 boosted \u2192 boosting"),
 E(["immune system","immune"], "Immune system", "the body's defence against disease", "boosts the immune system", "immune \u2192 immunity \u2192 immunise"),
 E(["releases","release"], "Release (v)", "to let something out or free", "releases hormones", "release \u2192 released \u2192 releasing"),
 E(["beneficial"], "Beneficial", "having a good or helpful effect", "beneficial hormones", "benefit \u2192 beneficial \u2192 beneficially"),
 E(["hormones","hormone"], "Hormone", "a chemical in the body controlling functions", "beneficial hormones", "hormone \u2192 hormonal"),
 E(["bloodstream"], "Bloodstream", "the blood flowing through the body", "into the bloodstream"),
 E(["psychologist"], "Psychologist", "a scientist who studies the mind", "psychologist Dr Shrimpton", "psychology \u2192 psychologist \u2192 psychological"),
 E(["frequently"], "Frequently", "often", "more frequently than we realise", "frequent \u2192 frequently \u2192 frequency"),
 E(["realise"], "Realise", "to become aware of something", "than we realise", "realise \u2192 realisation \u2192 realised"),
 E(["human nature","nature"], "Human nature", "the natural ways people think and behave", "a basic part of human nature"),
 E(["tend not to","tend"], "Tend to", "to be likely to do something", "we tend not to notice", "tend \u2192 tendency \u2192 tending"),
 E(["notice"], "Notice (v)", "to become aware of something", "notice when we are laughing", "notice \u2192 noticeable \u2192 noticeably"),
 E(["Infants","infants","infant"], "Infant", "a very young child or baby", "infants give their first laugh", "infant \u2192 infancy"),
 E(["typically"], "Typically", "in most cases; usually", "infants typically laugh", "typical \u2192 typically \u2192 typify"),
 E(["biologists","biologist"], "Biologist", "a scientist who studies living things", "according to biologists", "biology \u2192 biologist \u2192 biological"),
 E(["amusing","amusement","amused","amuse"], "Amusing", "causing laughter or enjoyment", "find something amusing", "amuse \u2192 amusement \u2192 amusing"),
 E(["non-verbal"], "Non-verbal", "not using words", "non-verbal communication", "verbal \u2192 non-verbal"),
 E(["communication"], "Communication", "the sharing of information", "a form of communication", "communicate \u2192 communication \u2192 communicative"),
 E(["form a","form"], "Form (v)", "to create or develop", "to form a connection", "form \u2192 formation \u2192 formative"),
 E(["connection"], "Connection", "a link or relationship", "a closer connection", "connect \u2192 connection \u2192 connected"),
 E(["widespread"], "Widespread", "existing over a large area or among many", "a widespread belief", "wide \u2192 widespread"),
 E(["belief"], "Belief", "an idea accepted as true", "a widespread belief", "believe \u2192 belief \u2192 believable"),
 E(["scientific community","community"], "Scientific community", "the group of all scientists and researchers", "outside the scientific community"),
 E(["humorous"], "Humorous", "funny; causing amusement", "because something is humorous", "humour \u2192 humorous \u2192 humorously"),
 E(["sociologist"], "Sociologist", "a scientist who studies society", "sociologist Jocelyn Barnes", "sociology \u2192 sociologist \u2192 sociological"),
 E(["purpose"], "Purpose", "the reason for which something is done", "the real purpose of laughter", "purpose \u2192 purposeful \u2192 purposely"),
 E(["promote"], "Promote", "to encourage or support something", "to promote bonding", "promote \u2192 promotion \u2192 promotional"),
 E(["bonding"], "Bonding", "the forming of close relationships", "promote bonding", "bond \u2192 bonding \u2192 bonded"),
 E(["individuals","individual"], "Individual", "a single person", "other individuals or groups", "individual \u2192 individually \u2192 individuality"),
 E(["impossible"], "Impossible", "not able to happen or be done", "almost impossible to imitate", "possible \u2192 impossible \u2192 impossibility"),
 E(["imitate"], "Imitate", "to copy the behaviour of someone", "impossible to imitate laughter", "imitate \u2192 imitation \u2192 imitator"),
 E(["trained","train"], "Trained", "having learned the skills for something", "even trained actors", "train \u2192 trained \u2192 training"),
 E(["struggle"], "Struggle (v)", "to find something very difficult", "actors struggle to mimic", "struggle \u2192 struggling \u2192 struggled"),
 E(["mimic"], "Mimic (v)", "to copy someone's voice or actions", "mimic a laugh", "mimic \u2192 mimicry \u2192 mimicking"),
 E(["convincingly","convincing"], "Convincingly", "in a way that makes people believe it", "mimic a laugh convincingly", "convince \u2192 convincing \u2192 convincingly"),
 E(["genuine"], "Genuine", "real; not false", "they are being genuine", "genuine \u2192 genuinely \u2192 genuineness"),
 E(["fake"], "Fake", "not real; false", "a real and a fake smile", "fake \u2192 faked \u2192 faking"),
 E(["neurologist"], "Neurologist", "a doctor who studies the nervous system", "the French neurologist", "neurology \u2192 neurologist \u2192 neurological"),
 E(["activates","activate"], "Activate", "to make something start working", "a smile activates the muscles", "activate \u2192 activation \u2192 activated"),
 E(["muscles","muscle"], "Muscle", "body tissue that produces movement", "the orbicularis muscles", "muscle \u2192 muscular"),
 E(["in turn"], "In turn", "as a result; subsequently", "this in turn causes lines"),
 E(["crow's feet"], "Crow's feet", "small wrinkles at the corner of the eyes", "lines called 'crow's feet'"),
 E(["put on"], "Put on (a smile)", "to pretend or fake an expression", "if the smile is put on"),
 E(["joking","joke"], "Joke", "something said to cause laughter", "joking and laughter", "joke \u2192 joker \u2192 joking"),
 E(["humorous Attempts","Attempts","attempt"], "Attempt (n)", "an act of trying to do something", "attempts to be humorous", "attempt \u2192 attempted \u2192 attempting"),
 E(["ancient"], "Ancient", "very old; from the distant past", "ancient Egypt", "ancient \u2192 antiquity"),
 E(["dating from","dating","date"], "Dating from", "having existed since a particular time", "dating from 2600 BC", "date \u2192 dating \u2192 dated"),
 E(["detailed","detail"], "Detailed", "having many facts or particulars", "a long and detailed book", "detail \u2192 detailed \u2192 detailing"),
 E(["exists","exist"], "Exist", "to be present or real", "still exists today", "exist \u2192 existence \u2192 existing"),
 E(["considerable"], "Considerable", "large in amount or importance", "of considerable value", "consider \u2192 considerable \u2192 considerably"),
 E(["historical"], "Historical", "relating to the past or history", "historical value", "history \u2192 historical \u2192 historically"),
 E(["professor"], "Professor", "a senior university teacher", "a professor of classics", "professor \u2192 professorship"),
 E(["classics","classic"], "Classics", "the study of ancient Greek and Roman culture", "a professor of classics"),
 E(["sources","source"], "Source", "a place or thing providing information", "ancient sources", "source \u2192 sourced \u2192 sourcing"),
 E(["concluded","conclude"], "Conclude", "to decide after considering facts", "concluded that tastes have changed", "conclude \u2192 conclusion \u2192 conclusive"),
 E(["tastes","taste"], "Taste (n)", "a person's preferences in things", "tastes in jokes", "taste \u2192 tasteful \u2192 tasteless"),
 E(["evolved","evolve"], "Evolve", "to develop gradually", "tastes have evolved", "evolve \u2192 evolution \u2192 evolved"),
 E(["markedly","marked"], "Markedly", "in a clearly noticeable way", "evolved markedly", "mark \u2192 marked \u2192 markedly"),
 E(["forebears","forebear"], "Forebear", "an ancestor", "the jokes of our forebears"),
 E(["vice versa"], "Vice versa", "the other way round; in reverse", "and vice versa"),
 E(["Nonetheless","nonetheless"], "Nonetheless", "in spite of that; nevertheless", "nonetheless, studies show"),
 E(["amusement"], "Amusement", "the feeling of being entertained", "find amusement", "amuse \u2192 amusement \u2192 amusing"),
 E(["rare"], "Rare", "not common; unusual", "a rare disorder", "rare \u2192 rarely \u2192 rarity"),
 E(["neurological"], "Neurological", "relating to the nervous system", "a neurological disorder", "neurology \u2192 neurological \u2192 neurologist"),
 E(["disorder"], "Disorder", "an illness or condition affecting the body", "a neurological disorder", "disorder \u2192 disordered"),
 E(["prevents","prevent"], "Prevent", "to stop something from happening", "prevents people from laughing", "prevent \u2192 prevention \u2192 preventive"),
 E(["out loud"], "Out loud", "aloud; in a way others can hear", "laughing out loud"),
 E(["entertained","entertain"], "Entertain", "to amuse or interest someone", "amused or entertained", "entertain \u2192 entertainment \u2192 entertaining"),
 E(["express"], "Express (v)", "to show feelings or thoughts", "express it in different ways", "express \u2192 expression \u2192 expressive"),
 E(["common"], "Common", "happening often; widespread", "much more common", "common \u2192 commonly \u2192 commonness"),
 E(["contagious"], "Contagious", "spreading easily from one to another", "contagious laughter", "contagious \u2192 contagion"),
 E(["spreads","spread"], "Spread (v)", "to extend over a wider area", "laughter that spreads", "spread \u2192 spreading"),
 E(["uncontrollably","uncontrollable"], "Uncontrollably", "in a way that cannot be controlled", "spreads uncontrollably", "control \u2192 uncontrollable \u2192 uncontrollably"),
 E(["referred to","refer"], "Referred to as", "called or described as", "referred to as 'the giggles'", "refer \u2192 reference \u2192 referral"),
 E(["giggles","giggle"], "Giggles", "silly, uncontrolled laughter", "getting the giggles", "giggle \u2192 giggling \u2192 giggly"),
 E(["experienced","experience"], "Experience (v)", "to feel or undergo something", "experienced this themselves", "experience \u2192 experienced \u2192 experiencing"),
 E(["occurs","occur"], "Occur", "to happen", "it also occurs in adults", "occur \u2192 occurrence \u2192 occurring"),
 E(["infamous"], "Infamous", "well known for something bad", "one infamous occasion", "fame \u2192 infamous \u2192 infamy"),
 E(["commentators","commentator"], "Commentator", "a person who describes events as they happen", "cricket commentators", "comment \u2192 commentator \u2192 commentary"),
 E(["broadcasting","broadcast"], "Broadcast (v)", "to send out a programme on radio or TV", "broadcasting live on radio", "broadcast \u2192 broadcasting \u2192 broadcaster"),
 E(["live"], "Live (adj)", "happening in real time, not recorded", "live on radio"),
 E(["pupils","pupil"], "Pupil", "a child being taught; a student", "ninety-five pupils"),
 E(["affected","affect"], "Affected", "influenced or changed by something", "pupils were affected", "affect \u2192 affected \u2192 affecting"),
 E(["continuously","continuous"], "Continuously", "without stopping", "laughed continuously", "continue \u2192 continuous \u2192 continuously"),
 E(["Eventually","eventually"], "Eventually", "in the end; finally", "eventually the situation became bad", "eventual \u2192 eventually"),
 E(["situation"], "Situation", "the circumstances at a particular time", "the situation became bad", "situate \u2192 situation \u2192 situated"),
 E(["authorities","authority"], "Authority", "people or bodies with official power", "the authorities at the school", "authority \u2192 authorities \u2192 authorise"),
 E(["felt obliged to","obliged","oblige"], "Be obliged to", "to feel forced or required to act", "felt obliged to close it", "oblige \u2192 obligation \u2192 obliged"),
 E(["temporarily","temporary"], "Temporarily", "for a limited time only", "to close it temporarily", "temporary \u2192 temporarily"),
 E(["in general"], "In general", "usually; on the whole", "in general it is possible"),
 E(["suppress"], "Suppress", "to hold back or prevent something", "suppress laughter", "suppress \u2192 suppression \u2192 suppressed"),
 E(["circumstances","circumstance"], "Circumstance", "a condition or fact affecting a situation", "in circumstances where", "circumstance \u2192 circumstantial"),
 E(["inappropriate"], "Inappropriate", "not suitable or proper", "would be inappropriate", "appropriate \u2192 inappropriate \u2192 inappropriately"),
 E(["cerebral cortex","cortex"], "Cerebral cortex", "the outer layer of the brain", "in the brain's cerebral cortex"),
 E(["switch"], "Switch (n)", "a device or mechanism for turning on/off", "a laughter switch"),
 E(["conscious"], "Conscious", "aware and able to control deliberately", "conscious control", "conscious \u2192 consciously \u2192 consciousness"),
 E(["complex"], "Complex (adj)", "complicated; having many parts", "laughter is highly complex", "complex \u2192 complexity"),
 E(["override"], "Override", "to be more important than; to cancel out", "override other emotions", "override \u2192 overriding"),
 E(["emotions","emotion"], "Emotion", "a strong feeling", "override other emotions", "emotion \u2192 emotional \u2192 emotionally"),
 E(["temporarily at least","at least temporarily"], "Temporarily", "for a short time", "at least temporarily"),
 E(["network"], "Network", "a connected system of things", "the network of brain circuits", "network \u2192 networking"),
 E(["circuits","circuit"], "Circuit", "a path around which something flows", "brain circuits"),
 E(["regulate"], "Regulate", "to control or manage something", "that regulate laughter", "regulate \u2192 regulation \u2192 regulator"),
 E(["insights","insight"], "Insight", "a deep understanding", "provide further insights", "insight \u2192 insightful"),
 E(["processes","process"], "Process", "a series of actions or changes", "the processes involved", "process \u2192 procedure \u2192 processing"),
 E(["simultaneously","simultaneous"], "Simultaneously", "at the same time", "occurs simultaneously", "simultaneous \u2192 simultaneously"),
 E(["seemingly","seeming"], "Seemingly", "in a way that appears to be true", "seemingly contradictory", "seem \u2192 seeming \u2192 seemingly"),
 E(["contradictory"], "Contradictory", "containing opposing ideas", "contradictory emotions", "contradict \u2192 contradiction \u2192 contradictory"),
 E(["aspect"], "Aspect", "a particular part or feature", "another aspect of humour", "aspect \u2192 aspects"),
 E(["complexity"], "Complexity", "the state of being complicated", "humour's complexity", "complex \u2192 complexity"),
 E(["subjective"], "Subjective", "based on personal feelings, not facts", "it is so subjective", "subject \u2192 subjective \u2192 subjectivity"),
 E(["stony silence","silence"], "Stony silence", "a complete, cold lack of response", "met with stony silence"),
 E(["reactions","reaction"], "Reaction", "a response to something", "the reactions his jokes received", "react \u2192 reaction \u2192 reactive"),
 E(["Intrigued","intrigued","intrigue"], "Intrigued", "very curious or interested", "intrigued, Mackenzie ran a survey", "intrigue \u2192 intrigued \u2192 intriguing"),
 E(["conducted","conduct"], "Conduct (v)", "to organise and carry out", "conducted a survey", "conduct \u2192 conducted \u2192 conducting"),
 E(["survey"], "Survey", "a study of people's opinions or facts", "an online survey", "survey \u2192 surveyor"),
 E(["establish"], "Establish", "to find out or prove a fact", "to establish what makes people laugh", "establish \u2192 established \u2192 establishment"),
 E(["diverse"], "Diverse", "very different and varied", "diverse topics", "diverse \u2192 diversity \u2192 diversify"),
 E(["variety"], "Variety", "a number of different things", "a variety of topics", "vary \u2192 variety \u2192 various"),
 E(["topics","topic"], "Topic", "a subject of discussion", "topics and scenarios", "topic \u2192 topical"),
 E(["scenarios","scenario"], "Scenario", "an imagined situation or sequence of events", "topics and scenarios"),
 E(["category"], "Category", "a group of similar things", "in each category", "category \u2192 categorise \u2192 categorical"),
 E(["theatre critic","critic"], "Critic", "a person who judges art or performances", "theatre critic Jake Gottlieb", "critic \u2192 critical \u2192 criticism"),
 E(["Stand-up comedians","comedians","comedian"], "Comedian", "a performer whose job is to make people laugh", "stand-up comedians", "comedy \u2192 comedian \u2192 comedic"),
 E(["for a living","living"], "For a living", "as a way of earning money", "making jokes for a living"),
 E(["social commentator"], "Social commentator", "a person who discusses social issues publicly", "be a social commentator"),
 E(["empathetic"], "Empathetic", "able to understand others' feelings", "be empathetic", "empathy \u2192 empathetic \u2192 empathise"),
 E(["self-aware"], "Self-aware", "conscious of one's own character and feelings", "be self-aware", "aware \u2192 self-aware \u2192 self-awareness"),
 E(["observant"], "Observant", "quick to notice things", "be observant", "observe \u2192 observant \u2192 observation"),
 E(["stubborn"], "Stubborn", "determined not to change one's mind", "be stubborn", "stubborn \u2192 stubbornly \u2192 stubbornness"),
 E(["timing"], "Timing", "the choice of when to do something", "have great timing", "time \u2192 timing \u2192 timed"),
 E(["multi-talented","talented"], "Multi-talented", "having many different skills", "so multi-talented", "talent \u2192 talented \u2192 multi-talented"),
 E(["instinctive"], "Instinctive", "based on natural feeling, not thought", "instinctive humour", "instinct \u2192 instinctive \u2192 instinctively"),
]


P3_PARAS = [
"Many economies today are witnessing the rise of socially responsible businesses, or SRBs. These are profit-making companies which have the additional goal of improving society in some way. Business commentators usually describe SRBs as a fundamentally 21st-century phenomenon. However, this common generalisation overlooks the significant contribution of Muhammad Yunus, among a number of other entrepreneurs. Yunus established a highly successful bank in Bangladesh in the 1980s lending money to small village business projects that could not attract conventional loans.",
"There are also those such as CEO Dan Rathbourne who dismiss SRBs as a passing fad which have had little impact on the real world of business. This cynical view is disproved by the evidence: in the UK alone, there are an estimated 80,000 SRBs, turning over about 25 billion a year. What is more, research by the Quorate Group based on interviews with over 5,000 respondents in twelve nations found that not only were consumers prepared to support SRBs but that employees preferred to work for them.",
"Ten years ago Christine Dubois used her experience in corporate finance to establish the Concern Consultancy, which coordinates advice and funding for SRB start-ups. As professional investors increasingly recognise the potential of SRBs, the number of niche firms such as Dubois's will almost inevitably multiply. Professor of business studies Joel Drew claims that this is partly a consequence of the digital revolution. In his persuasive analysis, digital networks have allowed consumers to identify socially responsible products and services in ways never possible before.",
"So what are some examples of SRBs? Many that have come to my attention recently are small-scale local companies, such as Renew, which searches demolition sites for old materials - wooden floorboards and other construction timber, for example. Rather than allow these resources to be wasted, the team at Renew have fashioned them into a range of tables, chairs and similar items that are sold at relatively low cost. Other SRBs have rather different goals. The first Indulge cafe was established by owner Derek Jardine in an area with few local amenities. The idea for the cafe was to provide a meeting place for local residents - a community hub - not only by serving food and drink but also by running workshops, film evenings and art exhibitions. There are now six Indulge cafes around the country with more planned. Of course, large corporations may not be in a position to change their products or services quickly. But one international telecommunications corporation, for example, enables its employees to take part in the Green Scheme, whereby staff give short periods of their time unpaid to plant trees in conservation areas, and numerous other large companies have similar initiatives.",
"Another small SRB that caught my eye is Bright Sparks, where engineer Johann Jensen is investigating the use of things such as bamboo and soya beans to make coffee capsules and takeaway cups that will break down and decay naturally. In the longer term, Jensen hopes to work on other kinds of packaging for the food and hospitality industries. Meanwhile, Greater Good is now in its second decade of running a farm-to-table vegetable and fruit delivery box service to inner city residents. Recent years have seen a significant increase in demand for this type of direct service, bypassing traditional retailers.",
"The increase in the number of such SRBs is associated with the rise of 'conscious consumers', who want to know exactly how the products they buy have been produced. What was the environmental impact? Were workers treated ethically? So the argument is sometimes put forward that SRBs are a response to new consumer values. But equally, many SRBs that I have studied were established by entrepreneurs who wanted to make a difference and have taken consumers along with them. In reality, both sides of the relationship have contributed to the fresh approach.",
"Consumers, of course, are not always members of the public. Recently I spoke to Lucinda Mitchell, procurement officer for my local council here in London, who told me that her organisation frequently purchases from SRBs because of shared values. Local, state and national authorities have huge purchasing power for both goods and services. And Mitchell's position is becoming commonplace internationally as these bodies are increasingly prepared to work with SRBs, provided they are competitive on price and quality.",
"In terms of goals, there are numerous types of social benefits that SRBs can hope to achieve. Many concern employment, whether creating opportunities in deprived areas, promoting gender equality in employment or providing jobs for disabled people. Others focus on fair and ethical treatment of employees and trading partners. Some SRBs add additional goals as they develop, which has worked well. Undoubtedly the most common goal, though, is environmental protection. While this is commendable and a reflection of deep concern in contemporary society, it would be good to see greater diversity as the SRB concept evolves.",
"As with any business, of course, there are issues to be faced. Some SRBs are set up with considerable energy and dedication, but with little knowledge or experience of business, and find it difficult to compete. Some find it a challenge to promote their values successfully and so never gain support from consumers or investors. Others lack an internal organisational structure, which leads to inefficiencies. However, few of these problems relate specifically to SRBs but are witnessed in many start-ups. Greater professionalism and business school education can solve all of these issues, ensuring the sector has a bright future.",
]

P3_ENTRIES = [
 E(["economies","economy"], "Economy", "the system of money, trade and industry of a region", "many economies today", "economy \u2192 economic \u2192 economical"),
 E(["witnessing","witness"], "Witness (v)", "to see or experience something happen", "witnessing the rise of SRBs", "witness \u2192 witnessed \u2192 witnessing"),
 E(["rise"], "Rise (n)", "an increase or growth", "the rise of SRBs", "rise \u2192 rising \u2192 risen"),
 E(["socially responsible","responsible"], "Socially responsible", "acting in ways that benefit society", "socially responsible businesses", "responsible \u2192 responsibility \u2192 responsibly"),
 E(["businesses","business"], "Business", "an organisation that sells goods or services", "responsible businesses", "business \u2192 businesses"),
 E(["profit-making","profit"], "Profit-making", "earning money after costs", "profit-making companies", "profit \u2192 profitable \u2192 profitability"),
 E(["companies","company"], "Company", "a commercial business organisation", "profit-making companies", "company \u2192 companies"),
 E(["additional"], "Additional", "extra; added to what exists", "an additional goal", "add \u2192 addition \u2192 additional"),
 E(["goal"], "Goal", "an aim or desired result", "the goal of improving society", "goal \u2192 goals"),
 E(["improving","improve"], "Improve", "to make better", "improving society", "improve \u2192 improvement \u2192 improved"),
 E(["society"], "Society", "people living together in a community", "improving society", "society \u2192 social \u2192 societal"),
 E(["commentators","commentator"], "Commentator", "a person who comments on a subject", "business commentators", "comment \u2192 commentator \u2192 commentary"),
 E(["describe"], "Describe", "to say what something is like", "describe SRBs as modern", "describe \u2192 description \u2192 descriptive"),
 E(["fundamentally","fundamental"], "Fundamentally", "in a basic and essential way", "a fundamentally modern phenomenon", "fundamental \u2192 fundamentally"),
 E(["phenomenon"], "Phenomenon", "a notable fact or occurrence", "a 21st-century phenomenon", "phenomenon \u2192 phenomena \u2192 phenomenal"),
 E(["generalisation"], "Generalisation", "a broad statement based on limited cases", "this common generalisation", "general \u2192 generalise \u2192 generalisation"),
 E(["overlooks","overlook"], "Overlook", "to fail to notice or consider", "overlooks the contribution", "overlook \u2192 overlooked"),
 E(["significant"], "Significant", "important; large enough to matter", "the significant contribution", "signify \u2192 significant \u2192 significance"),
 E(["contribution"], "Contribution", "something given to help achieve something", "the contribution of Yunus", "contribute \u2192 contribution \u2192 contributor"),
 E(["entrepreneurs","entrepreneur"], "Entrepreneur", "a person who starts and runs businesses", "other entrepreneurs", "entrepreneur \u2192 entrepreneurial \u2192 entrepreneurship"),
 E(["established"], "Established", "set up or started", "established a bank", "establish \u2192 established \u2192 establishment"),
 E(["successful"], "Successful", "achieving the desired result", "a successful bank", "succeed \u2192 success \u2192 successful"),
 E(["lending","lend"], "Lend", "to give money to be paid back later", "lending money", "lend \u2192 loan \u2192 lender"),
 E(["projects","project"], "Project", "a planned piece of work", "business projects", "project \u2192 projection"),
 E(["attract"], "Attract", "to draw in or gain", "could not attract loans", "attract \u2192 attraction \u2192 attractive"),
 E(["conventional"], "Conventional", "ordinary; following the usual way", "conventional loans", "convention \u2192 conventional \u2192 conventionally"),
 E(["loans","loan"], "Loan", "money lent that must be repaid", "conventional loans", "loan \u2192 lend \u2192 lender"),
 E(["CEO"], "CEO", "the most senior manager of a company (Chief Executive Officer)", "CEO Dan Rathbourne"),
 E(["dismiss"], "Dismiss", "to reject as unimportant", "dismiss SRBs as a fad", "dismiss \u2192 dismissal \u2192 dismissive"),
 E(["passing fad","fad"], "Fad", "a fashion that lasts only a short time", "a passing fad"),
 E(["impact"], "Impact (n)", "a strong effect", "little impact on business", "impact \u2192 impactful"),
 E(["cynical"], "Cynical", "believing people act only for selfish reasons", "this cynical view", "cynic \u2192 cynical \u2192 cynicism"),
 E(["disproved","disprove"], "Disprove", "to show that something is false", "is disproved by the evidence", "prove \u2192 disprove \u2192 disproved"),
 E(["estimated","estimate"], "Estimated", "calculated approximately", "an estimated 80,000 SRBs", "estimate \u2192 estimated \u2192 estimation"),
 E(["turning over","turn over"], "Turn over", "to do business worth a certain amount", "turning over 25 billion", "turnover \u2192 turning over"),
 E(["research"], "Research", "careful study to discover facts", "research by the Quorate Group", "research \u2192 researcher \u2192 researched"),
 E(["interviews","interview"], "Interview", "a formal meeting to ask questions", "based on interviews", "interview \u2192 interviewer \u2192 interviewee"),
 E(["respondents","respondent"], "Respondent", "a person who answers questions in a study", "5,000 respondents", "respond \u2192 respondent \u2192 response"),
 E(["nations","nation"], "Nation", "a country and its people", "twelve nations", "nation \u2192 national \u2192 nationality"),
 E(["consumers","consumer"], "Consumer", "a person who buys goods or services", "consumers support SRBs", "consume \u2192 consumer \u2192 consumption"),
 E(["prepared to","prepared"], "Prepared to", "willing to do something", "prepared to support SRBs", "prepare \u2192 prepared \u2192 preparation"),
 E(["employees","employee"], "Employee", "a person who works for someone", "employees preferred them", "employ \u2192 employee \u2192 employer"),
 E(["preferred","prefer"], "Prefer", "to like better", "employees preferred to work for them", "prefer \u2192 preference \u2192 preferable"),
 E(["corporate finance","corporate"], "Corporate", "relating to large companies", "corporate finance", "corporate \u2192 corporation \u2192 corporately"),
 E(["finance"], "Finance (n)", "the management of money", "experience in finance", "finance \u2192 financial \u2192 financially"),
 E(["coordinates","coordinate"], "Coordinate", "to organise different parts to work together", "coordinates advice and funding", "coordinate \u2192 coordination \u2192 coordinator"),
 E(["funding","fund"], "Funding", "money provided for a purpose", "advice and funding", "fund \u2192 funding \u2192 funded"),
 E(["start-ups","start-up"], "Start-up", "a newly established business", "SRB start-ups"),
 E(["investors","investor"], "Investor", "a person who puts money into something for profit", "professional investors", "invest \u2192 investor \u2192 investment"),
 E(["potential"], "Potential (n)", "the possibility of future success", "the potential of SRBs", "potential \u2192 potentially"),
 E(["niche"], "Niche", "a specialised part of a market", "niche firms", "niche \u2192 niches"),
 E(["firms","firm"], "Firm (n)", "a business company", "niche firms"),
 E(["inevitably","inevitable"], "Inevitably", "in a way that cannot be avoided", "will inevitably multiply", "inevitable \u2192 inevitably \u2192 inevitability"),
 E(["multiply"], "Multiply", "to increase greatly in number", "firms will multiply", "multiply \u2192 multiplication \u2192 multiple"),
 E(["consequence"], "Consequence", "a result or effect of something", "a consequence of the revolution", "consequence \u2192 consequent \u2192 consequently"),
 E(["digital revolution","revolution"], "Digital revolution", "the major change brought by digital technology", "the digital revolution", "revolution \u2192 revolutionary \u2192 revolutionise"),
 E(["persuasive"], "Persuasive", "able to make people believe something", "his persuasive analysis", "persuade \u2192 persuasive \u2192 persuasion"),
 E(["analysis"], "Analysis", "a detailed examination", "his analysis", "analyse \u2192 analysis \u2192 analytical"),
 E(["networks","network"], "Network", "a connected system of people or things", "digital networks", "network \u2192 networking"),
 E(["identify"], "Identify", "to recognise or find", "identify responsible products", "identify \u2192 identification \u2192 identifiable"),
 E(["products","product"], "Product", "something made to be sold", "products and services", "produce \u2192 product \u2192 production"),
 E(["services","service"], "Service", "work done for customers", "products and services", "serve \u2192 service \u2192 servicing"),
 E(["attention"], "Attention", "notice or consideration", "come to my attention", "attend \u2192 attention \u2192 attentive"),
 E(["small-scale","scale"], "Small-scale", "limited in size or extent", "small-scale companies", "scale \u2192 small-scale \u2192 large-scale"),
 E(["searches","search"], "Search (v)", "to look carefully for something", "searches demolition sites", "search \u2192 searching \u2192 searcher"),
 E(["demolition"], "Demolition", "the act of pulling down a building", "demolition sites", "demolish \u2192 demolition"),
 E(["floorboards","floorboard"], "Floorboard", "a long board used for a wooden floor", "wooden floorboards"),
 E(["timber"], "Timber", "wood used for building", "construction timber"),
 E(["resources","resource"], "Resource", "a useful supply of materials or money", "allow resources to be wasted", "resource \u2192 resourceful \u2192 resources"),
 E(["wasted","waste"], "Waste (v)", "to use carelessly or not at all", "resources to be wasted", "waste \u2192 wasteful \u2192 wasted"),
 E(["fashioned","fashion"], "Fashion (v)", "to make or shape something", "fashioned them into tables", "fashion \u2192 fashioned"),
 E(["range"], "Range (n)", "a variety of things of the same type", "a range of tables", "range \u2192 ranging"),
 E(["relatively","relative"], "Relatively", "in comparison with something else", "relatively low cost", "relative \u2192 relatively \u2192 relativity"),
 E(["goals","goal"], "Goals", "aims or desired results", "different goals"),
 E(["amenities","amenity"], "Amenity", "a useful or pleasant facility", "few local amenities"),
 E(["meeting place"], "Meeting place", "a place where people come together", "a meeting place for residents"),
 E(["residents","resident"], "Resident", "a person who lives in a place", "local residents", "reside \u2192 resident \u2192 residence"),
 E(["community hub","hub"], "Hub", "a central place of activity", "a community hub"),
 E(["workshops","workshop"], "Workshop", "a meeting for practical learning or activity", "running workshops"),
 E(["exhibitions","exhibition"], "Exhibition", "a public display of art or objects", "art exhibitions", "exhibit \u2192 exhibition \u2192 exhibitor"),
 E(["corporations","corporation"], "Corporation", "a large company or group of companies", "large corporations", "corporate \u2192 corporation"),
 E(["in a position to","position"], "In a position to", "able to do something", "may not be in a position to change"),
 E(["telecommunications"], "Telecommunications", "communication over distance by cable or radio", "a telecommunications corporation"),
 E(["enables","enable"], "Enable", "to make something possible", "enables its employees", "enable \u2192 enabled \u2192 enabling"),
 E(["take part in","take part"], "Take part in", "to be involved in an activity", "take part in the Green Scheme"),
 E(["scheme"], "Scheme", "an organised plan or programme", "the Green Scheme", "scheme \u2192 schemes"),
 E(["whereby"], "Whereby", "by which; through which", "a scheme whereby staff plant trees"),
 E(["staff"], "Staff", "the people who work for an organisation", "staff give their time"),
 E(["unpaid"], "Unpaid", "without payment", "their time unpaid", "pay \u2192 unpaid \u2192 paid"),
 E(["conservation"], "Conservation", "the protection of nature and the environment", "conservation areas", "conserve \u2192 conservation \u2192 conservationist"),
 E(["initiatives","initiative"], "Initiative", "a new plan or action to solve a problem", "similar initiatives", "initiate \u2192 initiative \u2192 initiated"),
 E(["caught my eye","caught"], "Catch one's eye", "to attract one's attention", "an SRB that caught my eye"),
 E(["engineer"], "Engineer", "a person who designs or builds machines or structures", "engineer Johann Jensen", "engineer \u2192 engineering"),
 E(["investigating","investigate"], "Investigate", "to examine carefully to find facts", "investigating the use of bamboo", "investigate \u2192 investigation \u2192 investigator"),
 E(["bamboo"], "Bamboo", "a tall, fast-growing tropical plant", "bamboo and soya beans"),
 E(["capsules","capsule"], "Capsule", "a small container, e.g. for coffee", "coffee capsules"),
 E(["takeaway"], "Takeaway", "food bought to eat elsewhere", "takeaway cups"),
 E(["break down"], "Break down", "to decay or separate into parts", "cups that break down naturally"),
 E(["decay"], "Decay (v)", "to rot or break down naturally", "break down and decay", "decay \u2192 decayed \u2192 decaying"),
 E(["packaging"], "Packaging", "materials used to wrap or protect goods", "kinds of packaging", "package \u2192 packaging \u2192 packaged"),
 E(["hospitality"], "Hospitality", "the business of providing food, drink and lodging", "the hospitality industries", "host \u2192 hospitality \u2192 hospitable"),
 E(["industries","industry"], "Industry", "a branch of economic or manufacturing activity", "the food industries", "industry \u2192 industrial \u2192 industrialise"),
 E(["decade"], "Decade", "a period of ten years", "its second decade", "decade \u2192 decades"),
 E(["farm-to-table"], "Farm-to-table", "supplying food directly from farm to consumer", "a farm-to-table service"),
 E(["delivery"], "Delivery", "the act of bringing goods to a place", "a delivery box service", "deliver \u2192 delivery \u2192 delivered"),
 E(["inner city","inner-city"], "Inner city", "the central, often poorer, area of a city", "inner city residents"),
 E(["demand"], "Demand (n)", "the desire of consumers for goods", "increase in demand", "demand \u2192 demanded \u2192 demanding"),
 E(["direct service","direct"], "Direct", "without anything coming between; straight", "a direct service", "direct \u2192 directly \u2192 directness"),
 E(["bypassing","bypass"], "Bypass (v)", "to avoid by going around", "bypassing traditional retailers", "bypass \u2192 bypassing"),
 E(["retailers","retailer"], "Retailer", "a business that sells goods to the public", "traditional retailers", "retail \u2192 retailer \u2192 retailing"),
 E(["conscious consumers","conscious"], "Conscious", "aware and acting deliberately", "'conscious consumers'", "conscious \u2192 consciously \u2192 consciousness"),
 E(["environmental"], "Environmental", "relating to the natural world", "the environmental impact", "environment \u2192 environmental \u2192 environmentally"),
 E(["ethically","ethical"], "Ethically", "in a morally correct way", "workers treated ethically", "ethics \u2192 ethical \u2192 ethically"),
 E(["argument"], "Argument", "a reason or set of reasons given", "the argument is put forward", "argue \u2192 argument \u2192 arguable"),
 E(["put forward"], "Put forward", "to suggest or propose", "the argument is put forward"),
 E(["response"], "Response", "a reaction or reply", "a response to consumer values", "respond \u2192 response \u2192 responsive"),
 E(["values","value"], "Values", "principles or standards of behaviour", "consumer values", "value \u2192 valued \u2192 valuable"),
 E(["make a difference","difference"], "Make a difference", "to have a noticeable positive effect", "wanted to make a difference"),
 E(["contributed","contribute"], "Contribute", "to help cause or bring about", "both sides have contributed", "contribute \u2192 contribution \u2192 contributor"),
 E(["fresh approach","approach"], "Approach (n)", "a way of dealing with something", "the fresh approach", "approach \u2192 approaches"),
 E(["members of the public","public"], "The public", "ordinary people in general", "members of the public"),
 E(["procurement officer","procurement"], "Procurement", "the act of obtaining goods or services", "procurement officer", "procure \u2192 procurement"),
 E(["council"], "Council", "a body that governs a local area", "my local council", "council \u2192 councillor"),
 E(["organisation"], "Organisation", "an organised group such as a business", "her organisation", "organise \u2192 organisation \u2192 organisational"),
 E(["purchases","purchase"], "Purchase (v)", "to buy something", "frequently purchases from SRBs", "purchase \u2192 purchased \u2192 purchasing"),
 E(["shared values","shared"], "Shared", "held or experienced in common", "shared values", "share \u2192 shared \u2192 sharing"),
 E(["national"], "National", "relating to a whole nation", "national authorities", "nation \u2192 national \u2192 nationally"),
 E(["purchasing power","purchasing"], "Purchasing power", "the ability to buy goods and services", "huge purchasing power"),
 E(["goods"], "Goods", "things that are produced to be sold", "goods and services"),
 E(["commonplace"], "Commonplace", "usual; happening often", "becoming commonplace", "common \u2192 commonplace"),
 E(["bodies","body"], "Body (organisation)", "an official group or organisation", "these bodies"),
 E(["competitive"], "Competitive", "able to compete; as good as rivals", "competitive on price", "compete \u2192 competitive \u2192 competition"),
 E(["quality"], "Quality", "the standard of how good something is", "price and quality", "quality \u2192 qualitative"),
 E(["in terms of"], "In terms of", "with regard to; concerning", "in terms of goals"),
 E(["benefits","benefit"], "Benefit (n)", "an advantage or positive effect", "social benefits", "benefit \u2192 beneficial \u2192 beneficiary"),
 E(["achieve"], "Achieve", "to succeed in reaching a goal", "hope to achieve", "achieve \u2192 achievement \u2192 achievable"),
 E(["employment"], "Employment", "the state of having paid work", "many concern employment", "employ \u2192 employment \u2192 employer"),
 E(["opportunities","opportunity"], "Opportunity", "a chance to do something", "creating opportunities", "opportunity \u2192 opportune \u2192 opportunistic"),
 E(["deprived"], "Deprived", "lacking the basic things needed in life", "deprived areas", "deprive \u2192 deprived \u2192 deprivation"),
 E(["promoting","promote"], "Promote", "to encourage or support", "promoting gender equality", "promote \u2192 promotion \u2192 promotional"),
 E(["gender equality","equality"], "Equality", "the state of being equal in rights", "gender equality", "equal \u2192 equality \u2192 equally"),
 E(["disabled"], "Disabled", "having a physical or mental condition limiting activity", "jobs for disabled people", "disable \u2192 disabled \u2192 disability"),
 E(["fair"], "Fair", "treating people equally and reasonably", "fair treatment", "fair \u2192 fairly \u2192 fairness"),
 E(["ethical"], "Ethical", "morally right", "ethical treatment", "ethics \u2192 ethical \u2192 ethically"),
 E(["treatment"], "Treatment", "the way someone is dealt with", "fair treatment of employees", "treat \u2192 treatment \u2192 treated"),
 E(["trading partners","partners","partner"], "Trading partner", "a person or country one does business with", "employees and trading partners"),
 E(["develop"], "Develop", "to grow or progress", "as they develop", "develop \u2192 development \u2192 developed"),
 E(["Undoubtedly","undoubtedly"], "Undoubtedly", "certainly; without doubt", "undoubtedly the most common goal", "doubt \u2192 undoubted \u2192 undoubtedly"),
 E(["protection"], "Protection", "the act of keeping something safe", "environmental protection", "protect \u2192 protection \u2192 protective"),
 E(["commendable"], "Commendable", "deserving praise", "this is commendable", "commend \u2192 commendable \u2192 commendation"),
 E(["reflection"], "Reflection", "a sign or result of something", "a reflection of deep concern", "reflect \u2192 reflection \u2192 reflective"),
 E(["contemporary"], "Contemporary", "belonging to the present time", "contemporary society", "contemporary \u2192 contemporaries"),
 E(["diversity"], "Diversity", "the state of having variety", "greater diversity", "diverse \u2192 diversity \u2192 diversify"),
 E(["concept"], "Concept", "an idea or notion", "the SRB concept", "concept \u2192 conceptual \u2192 conceptualise"),
 E(["evolves","evolve"], "Evolve", "to develop gradually", "as the concept evolves", "evolve \u2192 evolution \u2192 evolving"),
 E(["issues","issue"], "Issue (n)", "a problem or matter to be dealt with", "issues to be faced", "issue \u2192 issues"),
 E(["dedication"], "Dedication", "the quality of being committed to a task", "energy and dedication", "dedicate \u2192 dedication \u2192 dedicated"),
 E(["compete"], "Compete", "to try to be more successful than others", "find it difficult to compete", "compete \u2192 competition \u2192 competitive"),
 E(["challenge"], "Challenge (n)", "a difficult task that tests ability", "find it a challenge", "challenge \u2192 challenging \u2192 challenger"),
 E(["gain"], "Gain (v)", "to obtain or win something", "never gain support", "gain \u2192 gained \u2192 gaining"),
 E(["lack"], "Lack (v)", "to be without something", "others lack a structure", "lack \u2192 lacking"),
 E(["internal"], "Internal", "existing or happening inside", "an internal structure", "internal \u2192 internally"),
 E(["organisational"], "Organisational", "relating to the way a group is organised", "organisational structure", "organise \u2192 organisational \u2192 organisation"),
 E(["structure"], "Structure (n)", "the way parts are arranged or organised", "an organisational structure", "structure \u2192 structural \u2192 structured"),
 E(["inefficiencies","inefficiency"], "Inefficiency", "failure to work in a well-organised way", "leads to inefficiencies", "efficient \u2192 inefficiency \u2192 inefficient"),
 E(["specifically","specific"], "Specifically", "in a way that relates to one thing only", "relate specifically to SRBs", "specific \u2192 specifically \u2192 specify"),
 E(["witnessed","witness"], "Witnessed", "seen or observed", "witnessed in many start-ups", "witness \u2192 witnessed"),
 E(["professionalism"], "Professionalism", "the skill and conduct expected of a professional", "greater professionalism", "profession \u2192 professional \u2192 professionalism"),
 E(["solve"], "Solve", "to find an answer to a problem", "can solve these issues", "solve \u2192 solution \u2192 solvable"),
 E(["ensuring","ensure"], "Ensure", "to make certain", "ensuring a bright future", "ensure \u2192 ensured \u2192 ensuring"),
 E(["sector"], "Sector", "a part of an economy or area of activity", "the sector has a future", "sector \u2192 sectors"),
 E(["bright future","bright"], "Bright future", "a promising and successful future", "a bright future"),
]

PASSAGES = [
 {"num": 1, "title": "The History of Modern American Dance", "paragraphs": P1_PARAS, "entries": P1_ENTRIES},
 {"num": 2, "title": "The Science of Human Laughter", "paragraphs": P2_PARAS, "entries": P2_ENTRIES},
 {"num": 3, "title": "Socially Responsible Businesses", "paragraphs": P3_PARAS, "entries": P3_ENTRIES},
]
