# -*- coding: utf-8 -*-
# Test 5 Reading: 3 passages + comprehensive vocab (elementary -> advanced)
E = lambda hl, word, d, coll="", fam="": {"hl": hl, "word": word, "def": d, "coll": coll, "fam": fam}

P1_PARAS = [
"Using wood as a construction material for large buildings is an ancient practice. The 67-metre-high Sakyamuni Pagoda in China was constructed in 1056, while Japan's Horyu-ji Temple is even older, dating from the 7th or 8th century. That these magnificent structures have survived for over a thousand years is evidence of wood's strength and durability as a building material. Still today, 80% of houses in the USA are built of wood. In Australia the proportion is slightly smaller since stone is also a popular choice, particularly in the southern states, while in New Zealand the figure is more like 85%. Certainly, there are problems associated with wooden constructions: wood can rot when exposed to water and is said to be a fire risk. However, with modern technology these issues can be eliminated, which has led to a dramatic renewal of interest in wood as a building material in recent years.",
"Today, architects and engineers recognise the potential of wood not only for private homes but also for larger multi-storey offices and apartment blocks. In 2015, a 52.8-metre wooden tower block was constructed in Norway, then a world record for an apartment block, but this was soon surpassed by a 53-metre student dormitory at the University of British Columbia in Canada. Then came the 84-metre HoHo building in Vienna, home to a hotel, offices and apartments. Although the HoHo building has a concrete core, most of the structure as well as the floors are built of wood. Many of these advances have been made possible by research at the Technical Institute in Graz, Austria, where new engineering systems based on wood construction have been pioneered.",
"A good example of these techniques is found at the Wood Innovation and Design Centre at the University of Northern British Columbia, Canada. The first stage in the construction of the building saw large planks of Douglas fir being fastened to one another with glue, which these days can be stronger than nails or screws. This produced large heavy sheets of wooden material; these became the basic structural components for the building. These sheets then had to be precision cut to create the thousands of columns and beams necessary - the team employed lasers for this purpose. Once the cutting work was complete, all the wooden components were taken to the site for assembly. The building was constructed one storey at a time, layer upon layer, not unlike the system used to make a large cake. Once the eighth and final storey was completed, the building reached a height of 30 metres and became a notable landmark in its neighbourhood. And, of course, one of the great advantages of wood comes at the end of a building's life, in around 100 years' time. When the Wood Innovation and Design Centre eventually has to be demolished, it will be possible for its principal building material to be recycled, which is not usually practical with steel or concrete.",
"Other significant wooden buildings are to be found in locations around the world. Perhaps not surprisingly, given that the Horyu-ji Temple may be the oldest large wooden building in the world, Japanese engineers are at the forefront of this process. One thing that has been learned from maintaining the Horyu-ji Temple over many centuries is that it is often simpler to make major repairs to wooden structures than to those made of concrete and steel. Until quite recently, regulations in Japan have made the construction of very large wooden structures difficult. However, in recognition of new technologies, these are being relaxed by the government, with the result that ever more ambitious projects are being announced. Perhaps the most radical example is the proposed Sumitomo Tower, a skyscraper of 70 storeys to be built largely of wood in central Tokyo; its completion date is 2041.",
"Because wood is more flexible than steel, it has great potential in countries prone to earthquakes, such as Japan and New Zealand. Engineers in New Zealand believe that wood construction can significantly improve building safety in the event of a natural disaster, as has been demonstrated at the new Wynn Williams House. The wood has been left exposed inside the house to showcase how this type of construction provides attractive interiors as well. Another advantage of wood is that it is so light, particularly when compared to steel and concrete. In Australia, the benefits of light weight have been taken advantage of in the city of Melbourne, where a large wooden library has been constructed directly beside water, on land so soft that a heavier building would have been impossible. Furthermore, wood is advantageous even in extreme climates. In Finland, where winter temperatures can fall to -30C, wood provides all the load-bearing structures for the Puukuokka Block, but also guarantees excellent heat insulation as well.",
"As wood construction technologies continue to develop, it seems probable that architects and engineers will dream up ever more uses for this practical, flexible and beautiful building material.",
]

P1_ENTRIES = [
 E(["construction material","construction"], "Construction", "the act or process of building something", "a construction material", "construct \u2192 construction \u2192 constructive"),
 E(["material"], "Material", "a substance from which things are made", "a building material", "material \u2192 materials"),
 E(["ancient"], "Ancient", "very old; from the distant past", "an ancient practice", "ancient \u2192 antiquity"),
 E(["practice"], "Practice (n)", "a usual or customary action", "an ancient practice", "practise \u2192 practice \u2192 practical"),
 E(["Pagoda","pagoda"], "Pagoda", "a tall tower-like temple in Asia", "the Sakyamuni Pagoda"),
 E(["constructed","construct"], "Construct", "to build something", "was constructed in 1056", "construct \u2192 construction \u2192 constructed"),
 E(["Temple","temple"], "Temple", "a building used for religious worship", "the Horyu-ji Temple"),
 E(["dating from","dating","date"], "Dating from", "existing since a particular time", "dating from the 7th century", "date \u2192 dating \u2192 dated"),
 E(["century"], "Century", "a period of one hundred years", "the 8th century", "century \u2192 centuries"),
 E(["magnificent"], "Magnificent", "extremely impressive or beautiful", "magnificent structures", "magnificent \u2192 magnificence \u2192 magnificently"),
 E(["structures","structure"], "Structure", "something built; the arrangement of parts", "magnificent structures", "structure \u2192 structural \u2192 structured"),
 E(["survived","survive"], "Survive", "to continue to exist", "have survived for years", "survive \u2192 survival \u2192 survivor"),
 E(["evidence"], "Evidence", "facts proving something is true", "evidence of strength", "evident \u2192 evidence \u2192 evidently"),
 E(["strength"], "Strength", "the quality of being strong", "wood's strength", "strong \u2192 strength \u2192 strengthen"),
 E(["durability"], "Durability", "the ability to last a long time", "strength and durability", "durable \u2192 durability \u2192 endure"),
 E(["proportion"], "Proportion", "a part or share of a whole", "the proportion is smaller", "proportion \u2192 proportional \u2192 proportionate"),
 E(["slightly","slight"], "Slightly", "to a small degree", "slightly smaller", "slight \u2192 slightly"),
 E(["stone"], "Stone", "hard solid mineral matter; rock", "stone is a popular choice"),
 E(["popular"], "Popular", "liked by many people", "a popular choice", "popular \u2192 popularity \u2192 popularise"),
 E(["particularly"], "Particularly", "especially; more than usual", "particularly in the south", "particular \u2192 particularly"),
 E(["figure"], "Figure (n)", "a number representing an amount", "the figure is more like 85%", "figure \u2192 figures"),
 E(["associated with","associated"], "Associated with", "connected with", "problems associated with wood", "associate \u2192 association \u2192 associated"),
 E(["rot"], "Rot (v)", "to decay through natural processes", "wood can rot", "rot \u2192 rotten \u2192 rotting"),
 E(["exposed to","exposed","expose"], "Expose to", "to leave unprotected from something", "exposed to water", "expose \u2192 exposure \u2192 exposed"),
 E(["fire risk","risk"], "Risk", "the possibility of harm or danger", "a fire risk", "risk \u2192 risky \u2192 risking"),
 E(["modern technology","technology"], "Technology", "scientific knowledge applied practically", "modern technology", "technology \u2192 technological \u2192 technologically"),
 E(["issues","issue"], "Issue (n)", "a problem or matter to deal with", "these issues", "issue \u2192 issues"),
 E(["eliminated","eliminate"], "Eliminate", "to completely remove or get rid of", "issues can be eliminated", "eliminate \u2192 elimination \u2192 eliminated"),
 E(["dramatic"], "Dramatic", "sudden and noticeable; striking", "a dramatic renewal", "drama \u2192 dramatic \u2192 dramatically"),
 E(["renewal"], "Renewal", "the act of beginning again or renewing", "a renewal of interest", "renew \u2192 renewal \u2192 renewable"),
 E(["architects","architect"], "Architect", "a person who designs buildings", "architects and engineers", "architect \u2192 architecture \u2192 architectural"),
 E(["engineers","engineer"], "Engineer", "a person who designs and builds structures", "architects and engineers", "engineer \u2192 engineering"),
 E(["recognise"], "Recognise", "to be aware of or acknowledge", "recognise the potential", "recognise \u2192 recognition \u2192 recognisable"),
 E(["potential"], "Potential (n)", "the capacity to develop or be used", "the potential of wood", "potential \u2192 potentially"),
 E(["private"], "Private", "belonging to one person; not public", "private homes", "private \u2192 privately \u2192 privacy"),
 E(["multi-storey","storey"], "Multi-storey", "having several floors or levels", "multi-storey offices", "storey \u2192 multi-storey"),
 E(["apartment blocks","apartment","apartments"], "Apartment block", "a building divided into separate flats", "apartment blocks"),
 E(["tower block","tower"], "Tower block", "a tall building of many floors", "a wooden tower block"),
 E(["world record","record"], "World record", "the best achievement of its kind worldwide", "a world record"),
 E(["surpassed","surpass"], "Surpass", "to be greater or better than", "soon surpassed by another", "surpass \u2192 surpassed \u2192 surpassing"),
 E(["dormitory"], "Dormitory", "a building with rooms for many people to sleep", "a student dormitory"),
 E(["concrete"], "Concrete (n)", "a hard building material of cement and stone", "a concrete core"),
 E(["core"], "Core", "the central or most important part", "a concrete core", "core \u2192 cores"),
 E(["floors","floor"], "Floor", "a level of a building; a surface to walk on", "the floors are built of wood"),
 E(["advances","advance"], "Advance (n)", "a development or improvement", "many of these advances", "advance \u2192 advanced \u2192 advancement"),
 E(["research"], "Research", "careful study to discover facts", "research at the institute", "research \u2192 researcher \u2192 researched"),
 E(["engineering"], "Engineering", "the design and building of structures", "engineering systems", "engineer \u2192 engineering"),
 E(["pioneered","pioneer"], "Pioneer (v)", "to be the first to develop something", "have been pioneered", "pioneer \u2192 pioneering \u2192 pioneered"),
 E(["techniques","technique"], "Technique", "a particular method of doing something", "these techniques", "technique \u2192 technical \u2192 technician"),
 E(["Innovation","innovation"], "Innovation", "a new idea, method or invention", "Wood Innovation Centre", "innovate \u2192 innovation \u2192 innovative"),
 E(["stage"], "Stage", "a step or point in a process", "the first stage", "stage \u2192 stages"),
 E(["planks","plank"], "Plank", "a long, flat piece of wood", "large planks of fir"),
 E(["fir"], "Fir", "a type of evergreen tree (and its wood)", "Douglas fir"),
 E(["fastened","fasten"], "Fasten", "to join or fix firmly", "fastened to one another", "fasten \u2192 fastener \u2192 fastening"),
 E(["glue"], "Glue", "a sticky substance used to join things", "fastened with glue", "glue \u2192 glued \u2192 gluing"),
 E(["nails","nail"], "Nail", "a thin pointed metal pin for fastening", "stronger than nails"),
 E(["screws","screw"], "Screw", "a metal pin with a spiral ridge for fastening", "nails or screws"),
 E(["sheets","sheet"], "Sheet", "a broad, thin, flat piece of material", "heavy sheets of wood"),
 E(["structural"], "Structural", "relating to the structure of something", "structural components", "structure \u2192 structural \u2192 structurally"),
 E(["components","component"], "Component", "one of the parts that make up a whole", "structural components", "component \u2192 components"),
 E(["precision cut","precision"], "Precision", "exactness and accuracy", "precision cut", "precise \u2192 precision \u2192 precisely"),
 E(["columns","column"], "Column", "an upright pillar supporting a structure", "columns and beams"),
 E(["beams","beam"], "Beam", "a long, heavy piece of timber or metal support", "columns and beams"),
 E(["employed","employ"], "Employ (use)", "to make use of something", "the team employed lasers", "employ \u2192 employment \u2192 employed"),
 E(["lasers","laser"], "Laser", "a device producing a narrow, intense beam of light", "employed lasers"),
 E(["purpose"], "Purpose", "the reason for which something is done", "for this purpose", "purpose \u2192 purposeful \u2192 purposely"),
 E(["complete"], "Complete (adj)", "finished; with nothing missing", "the work was complete", "complete \u2192 completion \u2192 completed"),
 E(["site"], "Site", "the place where something is located", "taken to the site", "site \u2192 sites"),
 E(["assembly"], "Assembly", "the act of fitting parts together", "the site for assembly", "assemble \u2192 assembly \u2192 assembled"),
 E(["layer"], "Layer", "a thickness of material; one of several levels", "layer upon layer", "layer \u2192 layered \u2192 layering"),
 E(["final"], "Final", "last; coming at the end", "the final storey", "final \u2192 finally \u2192 finalise"),
 E(["height"], "Height", "the measurement of how tall something is", "a height of 30 metres", "high \u2192 height \u2192 heighten"),
 E(["notable"], "Notable", "worthy of attention; remarkable", "a notable landmark", "note \u2192 notable \u2192 notably"),
 E(["landmark"], "Landmark", "an easily recognised feature of an area", "a notable landmark"),
 E(["neighbourhood"], "Neighbourhood", "a district within a town or city", "in its neighbourhood", "neighbour \u2192 neighbourhood \u2192 neighbouring"),
 E(["advantages","advantage"], "Advantage", "a beneficial feature; a benefit", "the advantages of wood", "advantage \u2192 advantageous \u2192 advantaged"),
 E(["demolished","demolish"], "Demolish", "to pull down a building", "has to be demolished", "demolish \u2192 demolition \u2192 demolished"),
 E(["principal"], "Principal (adj)", "main; most important", "its principal material", "principal \u2192 principally"),
 E(["recycled","recycle"], "Recycle", "to process used materials for reuse", "to be recycled", "recycle \u2192 recycled \u2192 recycling"),
 E(["practical"], "Practical", "useful; able to be done in practice", "not usually practical", "practice \u2192 practical \u2192 practically"),
 E(["steel"], "Steel", "a strong metal made from iron", "steel or concrete"),
 E(["significant"], "Significant", "important; notable", "significant buildings", "signify \u2192 significant \u2192 significance"),
 E(["locations","location"], "Location", "a particular place or position", "locations around the world", "locate \u2192 location \u2192 located"),
 E(["forefront"], "Forefront", "the leading or most important position", "at the forefront of the process", "fore \u2192 forefront"),
 E(["process"], "Process", "a series of actions to achieve a result", "this process", "process \u2192 procedure \u2192 processing"),
 E(["maintaining","maintain"], "Maintain", "to keep in good condition", "maintaining the temple", "maintain \u2192 maintenance \u2192 maintained"),
 E(["major"], "Major", "important or serious; large", "major repairs", "major \u2192 majority"),
 E(["repairs","repair"], "Repair (n)", "the act of fixing something damaged", "major repairs", "repair \u2192 repaired \u2192 repairing"),
 E(["regulations","regulation"], "Regulation", "an official rule or law", "regulations in Japan", "regulate \u2192 regulation \u2192 regulator"),
 E(["recognition"], "Recognition", "acknowledgement of something", "in recognition of new technologies", "recognise \u2192 recognition \u2192 recognisable"),
 E(["relaxed","relax"], "Relaxed (rules)", "made less strict", "rules are being relaxed", "relax \u2192 relaxation \u2192 relaxed"),
 E(["government"], "Government", "the group that rules a country", "by the government", "govern \u2192 government \u2192 governmental"),
 E(["ambitious"], "Ambitious", "showing a strong desire to achieve a lot", "ambitious projects", "ambition \u2192 ambitious \u2192 ambitiously"),
 E(["projects","project"], "Project", "a planned piece of work", "ambitious projects", "project \u2192 projection"),
 E(["announced","announce"], "Announce", "to make known publicly", "projects are being announced", "announce \u2192 announcement \u2192 announcer"),
 E(["radical"], "Radical", "very new and different; extreme", "the most radical example", "radical \u2192 radically \u2192 radicalism"),
 E(["proposed","propose"], "Proposed", "suggested as a plan", "the proposed Sumitomo Tower", "propose \u2192 proposal \u2192 proposed"),
 E(["skyscraper"], "Skyscraper", "a very tall city building", "a skyscraper of 70 storeys"),
 E(["completion"], "Completion", "the act of finishing something", "its completion date", "complete \u2192 completion \u2192 completed"),
 E(["flexible"], "Flexible", "able to bend without breaking", "wood is more flexible", "flex \u2192 flexible \u2192 flexibility"),
 E(["prone to","prone"], "Prone to", "likely to suffer from something", "countries prone to earthquakes", "prone \u2192 proneness"),
 E(["earthquakes","earthquake"], "Earthquake", "a sudden violent shaking of the ground", "prone to earthquakes"),
 E(["significantly","significant"], "Significantly", "in an important or large way", "significantly improve safety", "significant \u2192 significantly \u2192 significance"),
 E(["improve"], "Improve", "to make better", "improve building safety", "improve \u2192 improvement \u2192 improved"),
 E(["safety"], "Safety", "the state of being safe from harm", "building safety", "safe \u2192 safety \u2192 safely"),
 E(["in the event of","event"], "In the event of", "if something happens", "in the event of a disaster"),
 E(["natural disaster","disaster"], "Disaster", "a sudden event causing great damage", "a natural disaster", "disaster \u2192 disastrous \u2192 disastrously"),
 E(["demonstrated","demonstrate"], "Demonstrate", "to show clearly", "as has been demonstrated", "demonstrate \u2192 demonstration \u2192 demonstrated"),
 E(["exposed"], "Exposed", "not covered; left visible", "wood left exposed", "expose \u2192 exposed \u2192 exposure"),
 E(["showcase"], "Showcase (v)", "to display in an attractive way", "to showcase the construction", "showcase \u2192 showcased"),
 E(["attractive"], "Attractive", "pleasing to look at", "attractive interiors", "attract \u2192 attractive \u2192 attraction"),
 E(["interiors","interior"], "Interior", "the inside of a building", "attractive interiors", "interior \u2192 interiors"),
 E(["light weight","light"], "Light (weight)", "not heavy; weighing little", "the benefits of light weight", "light \u2192 lightness \u2192 lighten"),
 E(["compared to","compared","compare"], "Compared to", "in relation to; against", "compared to steel", "compare \u2192 comparison \u2192 comparable"),
 E(["benefits","benefit"], "Benefit (n)", "an advantage gained from something", "the benefits of light weight", "benefit \u2192 beneficial \u2192 beneficiary"),
 E(["taken advantage of","take advantage"], "Take advantage of", "to make good use of something", "benefits taken advantage of"),
 E(["library"], "Library", "a building holding books for use", "a wooden library"),
 E(["directly","direct"], "Directly", "without anything in between; straight", "directly beside water", "direct \u2192 directly \u2192 direction"),
 E(["beside"], "Beside", "next to; at the side of", "beside water"),
 E(["soft"], "Soft", "easy to press or shape; not firm", "land so soft", "soft \u2192 soften \u2192 softly"),
 E(["heavier","heavy"], "Heavier", "weighing more", "a heavier building", "heavy \u2192 heavier \u2192 heaviness"),
 E(["impossible"], "Impossible", "not able to happen or be done", "would have been impossible", "possible \u2192 impossible \u2192 impossibility"),
 E(["advantageous"], "Advantageous", "giving a benefit; favourable", "wood is advantageous", "advantage \u2192 advantageous \u2192 advantageously"),
 E(["extreme"], "Extreme", "very great in degree", "extreme climates", "extreme \u2192 extremely \u2192 extremity"),
 E(["climates","climate"], "Climate", "the typical weather conditions of a region", "extreme climates", "climate \u2192 climatic"),
 E(["temperatures","temperature"], "Temperature", "the degree of heat or cold", "winter temperatures", "temperature \u2192 temperatures"),
 E(["load-bearing"], "Load-bearing", "supporting the weight of a structure", "load-bearing structures", "load \u2192 load-bearing"),
 E(["guarantees","guarantee"], "Guarantee (v)", "to promise or ensure something", "guarantees insulation", "guarantee \u2192 guaranteed \u2192 guarantor"),
 E(["insulation"], "Insulation", "material that prevents loss of heat", "heat insulation", "insulate \u2192 insulation \u2192 insulated"),
 E(["develop"], "Develop", "to grow or advance", "technologies continue to develop", "develop \u2192 development \u2192 developed"),
 E(["probable"], "Probable", "likely to happen or be true", "it seems probable", "probable \u2192 probably \u2192 probability"),
 E(["dream up","dream"], "Dream up", "to invent or imagine something new", "dream up new uses"),
 E(["beautiful"], "Beautiful", "very pleasing to the senses", "a beautiful material", "beauty \u2192 beautiful \u2192 beautifully"),
]


P2_PARAS = [
"The first sports game was televised in the USA more than fifty years ago. Over the following decades television provided sports coaches with a wealth of information to analyse. By viewing recordings, they could study the number of passes received, tackles avoided, distances covered, speeds achieved and a host of other factors relating to the performance of their teams or athletes. Most of this data, though, consisted of bare statistics without any meaningful context. However, the use of artificial intelligence (AI) is now enabling an alternative approach to coaching. AI means the development of computer systems that can perform tasks usually associated with human intelligence, such as decision making. Increasingly, computers are being trained to understand the rules and objectives of sports so they can coach more directly. AI can analyse not only a player's actions, but also relate those actions to the wider context, including the directives of the coach and the actions of other players. Sports scientists believe that AI is revolutionising sports coaching by analysing patterns of behaviour in ways simply not possible before.",
"There may be limitless ways in which AI technology can be developed, but certain practical applications are already apparent. Recently, a research experiment was conducted into the Spanish football league using an AI algorithm to analyse the passing strategies of 20 teams. The research revealed that two teams, Barcelona and Real Madrid, had more than 150 recurring passing patterns. However, the algorithm detected just 31 passing patterns used by Atletico Madrid. All of Atletico's other plays were one-offs that were never repeated, and the team won the league that season. One conclusion seems to be that teams with a less predictable style of play win more games. What's more, according to Dr Johann Muller, a sports scientist who has studied the Spanish research findings, the number of injuries a team suffers increases when they play in a style that prioritises offence.",
"Since then, there has been a great deal of interest in the potential of AI. Professor of sports education Rebecca Graves believes that AI can provide coaches with invaluable insights. 'Tactics were once closely guarded secrets,' says Professor Graves, 'but now a coach with access to AI can identify how a rival team is likely to play a match based on historic form. Once this was largely guesswork but now it can be achieved with some confidence.' The expense of AI technology means it will probably remain beyond the reach of all but elite teams, but among this group the implications are enormous. Professor Graves argues that AI allows preparations for a match to be tailored to individual players with much greater precision. She identifies fitness work, skills development, diet and numerous other factors that can be minutely customised, based on an individual's particular strengths and weaknesses.",
"Part of the appeal of AI lies in its versatility. Ice hockey coaches in Finland are using AI to analyse the success of different plays. An Indian company has employed wearable technology developed in other fields to analyse stride patterns. This analysis has allowed its technicians to develop sneakers in various styles aimed at both long- and short-distance runners. Coaching practices in professional basketball, American football and tennis are also being transformed by AI. In addition, the technology has applications in highly technical sports such as car racing. Coaches involved in the National Association for Stock Car Auto Racing (NASCAR) believe that AI algorithms not only help drivers go faster but also enhance the safety of the sport because of their ability to monitor and predict potential problems.",
"AI doesn't get tired, has extraordinary powers of vision, particularly for objects moving at speed, and is capable of making complex calculations very quickly. For all these reasons AI is increasingly being used in the high-pressure world of judging gymnastics performances. Research has shown that, particularly over a whole day's worth of events, computers are just as reliable as human judges when it comes to giving gymnasts a score. However, computer scientist Henri Simeonson has been quick to warn about some potential difficulties. In particular, Simeonson is concerned that AI is vulnerable to hackers, who might be able to influence the outcome of a tournament.",
"It should not be forgotten, either, that many sports stars and sports teams are commercially dependent on their fans. If sufficient supporters do not buy tickets to games or pay to view a recording, the teams might struggle to survive. But now teams and stars are making increasing use of chatbots and other 'virtual assistants' to provide fans with statistics, news and background information about their favourite players. Another innovation is seen in Minor League Baseball in the USA, which is promoting the sport and seeking new fans with the use of AI-enhanced journalism. In this way baseball is keeping supporters informed with all the up-to-the-minute developments in ways not possible with more traditional approaches. Analysts believe these sorts of initiatives are crucial to increasing a player or team's revenue stream. It's just one more way that sports stand to benefit from AI technologies, on and off the field.",
]

P2_ENTRIES = [
 E(["televised","televise"], "Televise", "to broadcast on television", "the game was televised", "television \u2192 televise \u2192 televised"),
 E(["decades","decade"], "Decade", "a period of ten years", "over the following decades", "decade \u2192 decades"),
 E(["coaches","coach"], "Coach (n)", "a person who trains a sports team or athlete", "sports coaches", "coach \u2192 coaching \u2192 coached"),
 E(["a wealth of","wealth"], "A wealth of", "a large amount of something valuable", "a wealth of information"),
 E(["analyse"], "Analyse", "to examine something in detail", "information to analyse", "analyse \u2192 analysis \u2192 analytical"),
 E(["viewing","view"], "Viewing", "the act of watching something", "by viewing recordings", "view \u2192 viewing \u2192 viewer"),
 E(["recordings","recording"], "Recording", "a stored copy of sound or images", "viewing recordings", "record \u2192 recording \u2192 recorded"),
 E(["passes","pass"], "Pass (n)", "an act of giving the ball to a teammate", "passes received"),
 E(["tackles","tackle"], "Tackle (n)", "an attempt to take the ball from an opponent", "tackles avoided", "tackle \u2192 tackling \u2192 tackled"),
 E(["avoided","avoid"], "Avoid", "to keep away from; to prevent", "tackles avoided", "avoid \u2192 avoidance \u2192 avoidable"),
 E(["distances","distance"], "Distance", "the amount of space between two points", "distances covered", "distance \u2192 distant \u2192 distantly"),
 E(["a host of","host"], "A host of", "a large number of things", "a host of factors"),
 E(["factors","factor"], "Factor", "one of the things influencing a result", "other factors", "factor \u2192 factors"),
 E(["performance"], "Performance", "how well a person or team does", "the performance of teams", "perform \u2192 performance \u2192 performer"),
 E(["athletes","athlete"], "Athlete", "a person trained in sport or exercise", "teams or athletes", "athlete \u2192 athletic \u2192 athletics"),
 E(["data"], "Data", "facts and figures collected for analysis", "most of this data", "data \u2192 database"),
 E(["consisted of","consist"], "Consist of", "to be made up of", "consisted of statistics", "consist \u2192 consistent \u2192 consistency"),
 E(["bare"], "Bare (adj)", "plain; with nothing added", "bare statistics", "bare \u2192 barely"),
 E(["statistics","statistic"], "Statistics", "numerical facts collected and analysed", "bare statistics", "statistic \u2192 statistics \u2192 statistical"),
 E(["meaningful"], "Meaningful", "having a clear meaning or importance", "meaningful context", "mean \u2192 meaning \u2192 meaningful"),
 E(["context"], "Context", "the circumstances surrounding something", "without context", "context \u2192 contextual \u2192 contextualise"),
 E(["artificial intelligence","artificial"], "Artificial intelligence", "computer systems that imitate human thinking", "the use of AI", "artificial \u2192 artificially"),
 E(["enabling","enable"], "Enable", "to make something possible", "AI is enabling an approach", "enable \u2192 enabled \u2192 enabling"),
 E(["alternative"], "Alternative", "another possible choice", "an alternative approach", "alternative \u2192 alternatively"),
 E(["approach"], "Approach (n)", "a way of dealing with something", "an alternative approach", "approach \u2192 approaches"),
 E(["development"], "Development", "the process of creating or growing", "the development of systems", "develop \u2192 development \u2192 developer"),
 E(["perform"], "Perform", "to carry out a task", "perform tasks", "perform \u2192 performance \u2192 performer"),
 E(["tasks","task"], "Task", "a piece of work to be done", "perform tasks", "task \u2192 tasks"),
 E(["intelligence"], "Intelligence", "the ability to learn and understand", "human intelligence", "intelligent \u2192 intelligence \u2192 intelligently"),
 E(["decision making","decision"], "Decision making", "the process of choosing what to do", "such as decision making", "decide \u2192 decision \u2192 decisive"),
 E(["trained","train"], "Trained", "taught the skills for a task", "computers are trained", "train \u2192 training \u2192 trained"),
 E(["objectives","objective"], "Objective (n)", "a goal or aim", "the objectives of sports", "object \u2192 objective \u2192 objectively"),
 E(["directly","direct"], "Directly", "in a straight or immediate way", "coach more directly", "direct \u2192 directly \u2192 direction"),
 E(["actions","action"], "Action", "the process of doing something", "a player's actions", "act \u2192 action \u2192 active"),
 E(["relate"], "Relate", "to connect or link things", "relate actions to context", "relate \u2192 relation \u2192 related"),
 E(["wider","wide"], "Wider", "broader; more extensive", "the wider context", "wide \u2192 wider \u2192 widely"),
 E(["directives","directive"], "Directive", "an official instruction", "the directives of the coach", "direct \u2192 directive \u2192 direction"),
 E(["revolutionising","revolutionise"], "Revolutionise", "to change something dramatically", "AI is revolutionising coaching", "revolution \u2192 revolutionise \u2192 revolutionary"),
 E(["patterns","pattern"], "Pattern", "a regular, repeated arrangement", "patterns of behaviour"),
 E(["behaviour"], "Behaviour", "the way someone or something acts", "patterns of behaviour", "behave \u2192 behaviour \u2192 behavioural"),
 E(["limitless","limit"], "Limitless", "without limit; endless", "limitless ways", "limit \u2192 limitless \u2192 limited"),
 E(["technology"], "Technology", "scientific knowledge used practically", "AI technology", "technology \u2192 technological \u2192 technologically"),
 E(["applications","application"], "Application", "a practical use of something", "practical applications", "apply \u2192 application \u2192 applicable"),
 E(["apparent"], "Apparent", "clearly seen or understood; obvious", "already apparent", "apparent \u2192 apparently"),
 E(["experiment"], "Experiment", "a scientific test or trial", "a research experiment", "experiment \u2192 experimental \u2192 experimentation"),
 E(["conducted","conduct"], "Conduct (v)", "to organise and carry out", "an experiment was conducted", "conduct \u2192 conducted \u2192 conducting"),
 E(["league"], "League", "a group of sports teams that compete", "the Spanish football league"),
 E(["algorithm"], "Algorithm", "a set of rules a computer follows to solve a problem", "an AI algorithm"),
 E(["strategies","strategy"], "Strategy", "a plan to achieve a goal", "passing strategies", "strategy \u2192 strategic \u2192 strategically"),
 E(["revealed","reveal"], "Reveal", "to make known something hidden", "the research revealed that", "reveal \u2192 revelation \u2192 revealed"),
 E(["recurring","recur"], "Recurring", "happening again and again", "recurring patterns", "recur \u2192 recurring \u2192 recurrence"),
 E(["detected","detect"], "Detect", "to discover or notice", "the algorithm detected", "detect \u2192 detection \u2192 detector"),
 E(["plays","play"], "Play (n)", "a planned move in a sports game", "their other plays"),
 E(["one-offs","one-off"], "One-off", "something done only once", "plays were one-offs"),
 E(["repeated","repeat"], "Repeated", "done again", "never repeated", "repeat \u2192 repeated \u2192 repetition"),
 E(["conclusion"], "Conclusion", "a decision reached after thinking", "one conclusion", "conclude \u2192 conclusion \u2192 conclusive"),
 E(["predictable","predict"], "Predictable", "able to be guessed in advance", "a less predictable style", "predict \u2192 predictable \u2192 prediction"),
 E(["What's more","what's more"], "What's more", "in addition; moreover", "what's more, injuries increase"),
 E(["findings","finding"], "Findings", "the results of research", "the research findings", "find \u2192 finding \u2192 findings"),
 E(["injuries","injury"], "Injury", "physical harm or damage to the body", "the number of injuries", "injure \u2192 injury \u2192 injured"),
 E(["suffers","suffer"], "Suffer", "to experience something bad", "injuries a team suffers", "suffer \u2192 suffering \u2192 suffered"),
 E(["prioritises","prioritise"], "Prioritise", "to treat as most important", "a style that prioritises offence", "priority \u2192 prioritise \u2192 prioritised"),
 E(["offence"], "Offence (attack)", "the attacking part of a sports team", "prioritises offence", "offend \u2192 offence \u2192 offensive"),
 E(["a great deal of","great deal"], "A great deal of", "a large amount of", "a great deal of interest"),
 E(["potential"], "Potential", "the capacity to develop or succeed", "the potential of AI", "potential \u2192 potentially"),
 E(["invaluable"], "Invaluable", "extremely useful; priceless", "invaluable insights", "value \u2192 valuable \u2192 invaluable"),
 E(["insights","insight"], "Insight", "a deep understanding of something", "invaluable insights", "insight \u2192 insightful"),
 E(["Tactics","tactics","tactic"], "Tactic", "a method used to achieve a goal", "tactics were secrets", "tactic \u2192 tactical \u2192 tactically"),
 E(["closely guarded","guarded","guard"], "Closely guarded", "kept very secret and protected", "closely guarded secrets", "guard \u2192 guarded \u2192 guarding"),
 E(["secrets","secret"], "Secret", "something kept hidden from others", "guarded secrets", "secret \u2192 secretly \u2192 secrecy"),
 E(["access to","access"], "Access (n)", "the ability to use or obtain something", "access to AI", "access \u2192 accessible \u2192 accessibility"),
 E(["identify"], "Identify", "to recognise or determine", "identify how a team plays", "identify \u2192 identification \u2192 identifiable"),
 E(["rival"], "Rival (adj)", "competing against another", "a rival team", "rival \u2192 rivalry \u2192 rivals"),
 E(["match"], "Match (n)", "a sports contest between teams", "play a match"),
 E(["historic form","historic"], "Historic form", "past record of performance", "based on historic form", "history \u2192 historic \u2192 historical"),
 E(["guesswork"], "Guesswork", "the act of guessing without sure knowledge", "once this was guesswork", "guess \u2192 guesswork"),
 E(["achieved","achieve"], "Achieve", "to succeed in doing something", "can be achieved", "achieve \u2192 achievement \u2192 achievable"),
 E(["confidence"], "Confidence", "the feeling of being certain", "with some confidence", "confide \u2192 confidence \u2192 confident"),
 E(["expense"], "Expense", "the cost of something", "the expense of AI", "expense \u2192 expensive \u2192 expenses"),
 E(["beyond the reach of","reach"], "Beyond the reach of", "not affordable or obtainable by", "beyond the reach of most teams"),
 E(["elite"], "Elite", "the best or most powerful group", "elite teams", "elite \u2192 elitism \u2192 elitist"),
 E(["implications","implication"], "Implication", "a possible effect or consequence", "the implications are enormous", "imply \u2192 implication \u2192 implied"),
 E(["enormous"], "Enormous", "extremely large", "the implications are enormous", "enormous \u2192 enormously \u2192 enormity"),
 E(["preparations","preparation"], "Preparation", "the act of getting ready", "preparations for a match", "prepare \u2192 preparation \u2192 prepared"),
 E(["tailored","tailor"], "Tailored", "specially adapted for a purpose", "tailored to individual players", "tailor \u2192 tailored \u2192 tailoring"),
 E(["precision"], "Precision", "exactness and accuracy", "much greater precision", "precise \u2192 precision \u2192 precisely"),
 E(["fitness"], "Fitness", "the state of being physically healthy", "fitness work", "fit \u2192 fitness \u2192 fitter"),
 E(["diet"], "Diet", "the food a person usually eats", "skills, diet and other factors", "diet \u2192 dietary"),
 E(["numerous"], "Numerous", "many", "numerous other factors", "number \u2192 numerous \u2192 innumerable"),
 E(["minutely","minute"], "Minutely", "in great detail; very precisely", "minutely customised", "minute \u2192 minutely"),
 E(["customised","customise"], "Customised", "changed to suit a particular person", "minutely customised", "custom \u2192 customise \u2192 customised"),
 E(["strengths","strength"], "Strengths", "the good or strong qualities", "strengths and weaknesses", "strong \u2192 strength \u2192 strengthen"),
 E(["weaknesses","weakness"], "Weaknesses", "the weak points or faults", "strengths and weaknesses", "weak \u2192 weakness \u2192 weaken"),
 E(["appeal"], "Appeal (n)", "the quality of being attractive", "part of the appeal", "appeal \u2192 appealing \u2192 appealingly"),
 E(["versatility","versatile"], "Versatility", "the ability to be used in many ways", "its versatility", "versatile \u2192 versatility"),
 E(["Ice hockey","hockey"], "Ice hockey", "a team sport played on ice with sticks", "ice hockey coaches"),
 E(["success"], "Success", "the achievement of a goal", "the success of plays", "succeed \u2192 success \u2192 successful"),
 E(["company"], "Company", "a commercial business", "an Indian company", "company \u2192 companies"),
 E(["wearable"], "Wearable", "designed to be worn", "wearable technology", "wear \u2192 wearable \u2192 wearer"),
 E(["fields","field"], "Field", "an area of activity or knowledge", "other fields", "field \u2192 fields"),
 E(["stride patterns","stride"], "Stride", "a long step when walking or running", "stride patterns"),
 E(["analysis"], "Analysis", "detailed examination of something", "this analysis", "analyse \u2192 analysis \u2192 analytical"),
 E(["technicians","technician"], "Technician", "a person skilled in technical work", "its technicians", "technical \u2192 technician \u2192 technique"),
 E(["sneakers","sneaker"], "Sneaker", "a soft sports shoe; a trainer", "develop sneakers"),
 E(["various"], "Various", "of different kinds", "various styles", "vary \u2192 various \u2192 variety"),
 E(["aimed at","aim"], "Aimed at", "directed toward a particular group", "aimed at runners", "aim \u2192 aimed \u2192 aiming"),
 E(["runners","runner"], "Runner", "a person who runs, especially in sport", "long-distance runners", "run \u2192 runner \u2192 running"),
 E(["practices","practice"], "Practice (n)", "the usual way of doing something", "coaching practices", "practise \u2192 practice \u2192 practical"),
 E(["professional"], "Professional", "done as a paid job to a high standard", "professional basketball", "profession \u2192 professional \u2192 professionally"),
 E(["transformed","transform"], "Transform", "to change completely", "being transformed by AI", "transform \u2192 transformation \u2192 transformative"),
 E(["in addition"], "In addition", "as an extra thing; also", "in addition, AI has uses"),
 E(["technical"], "Technical", "relating to specialised skills or machines", "highly technical sports", "technical \u2192 technically \u2192 technician"),
 E(["car racing","racing","race"], "Car racing", "the sport of racing motor vehicles", "such as car racing", "race \u2192 racing \u2192 racer"),
 E(["involved in","involved","involve"], "Involved in", "taking part in something", "coaches involved in NASCAR", "involve \u2192 involvement \u2192 involved"),
 E(["enhance"], "Enhance", "to improve the quality of something", "enhance the safety", "enhance \u2192 enhancement \u2192 enhanced"),
 E(["ability"], "Ability", "the power or skill to do something", "their ability to monitor", "able \u2192 ability \u2192 enable"),
 E(["monitor"], "Monitor (v)", "to watch and check over time", "monitor problems", "monitor \u2192 monitoring \u2192 monitored"),
 E(["predict"], "Predict", "to say what will happen in advance", "predict potential problems", "predict \u2192 prediction \u2192 predictable"),
 E(["extraordinary"], "Extraordinary", "very unusual or remarkable", "extraordinary powers", "ordinary \u2192 extraordinary \u2192 extraordinarily"),
 E(["vision"], "Vision", "the ability to see; sight", "powers of vision", "vision \u2192 visual \u2192 visionary"),
 E(["capable of","capable"], "Capable of", "having the ability to do", "capable of calculations", "capable \u2192 capability \u2192 capably"),
 E(["complex"], "Complex (adj)", "complicated; having many parts", "complex calculations", "complex \u2192 complexity"),
 E(["calculations","calculation"], "Calculation", "a result found using mathematics", "complex calculations", "calculate \u2192 calculation \u2192 calculator"),
 E(["high-pressure","pressure"], "High-pressure", "involving stress and difficult demands", "the high-pressure world", "press \u2192 pressure \u2192 pressurise"),
 E(["judging","judge"], "Judging", "the act of deciding the quality of something", "judging gymnastics", "judge \u2192 judging \u2192 judgement"),
 E(["gymnastics","gymnast","gymnasts"], "Gymnastics", "a sport of physical exercises and movements", "judging gymnastics performances"),
 E(["reliable"], "Reliable", "able to be trusted or depended on", "as reliable as human judges", "rely \u2192 reliable \u2192 reliability"),
 E(["score"], "Score (n)", "the number of points achieved", "giving gymnasts a score", "score \u2192 scoring \u2192 scored"),
 E(["warn"], "Warn", "to tell someone of a possible danger", "quick to warn", "warn \u2192 warning \u2192 warned"),
 E(["difficulties","difficulty"], "Difficulty", "a problem or hard situation", "potential difficulties", "difficult \u2192 difficulty"),
 E(["concerned","concern"], "Concerned", "worried about something", "Simeonson is concerned", "concern \u2192 concerned \u2192 concerning"),
 E(["vulnerable to","vulnerable"], "Vulnerable to", "easily harmed or attacked by", "vulnerable to hackers", "vulnerable \u2192 vulnerability"),
 E(["hackers","hacker"], "Hacker", "a person who illegally accesses computer systems", "vulnerable to hackers", "hack \u2192 hacker \u2192 hacking"),
 E(["influence"], "Influence (v)", "to affect or change something", "influence the outcome", "influence \u2192 influential \u2192 influencer"),
 E(["outcome"], "Outcome", "the result of an event", "the outcome of a tournament", "outcome \u2192 outcomes"),
 E(["tournament"], "Tournament", "a competition with many matches", "the outcome of a tournament"),
 E(["commercially","commercial"], "Commercially", "in terms of business and profit", "commercially dependent", "commerce \u2192 commercial \u2192 commercially"),
 E(["dependent on","dependent"], "Dependent on", "relying on something or someone", "dependent on their fans", "depend \u2192 dependent \u2192 dependence"),
 E(["fans","fan"], "Fan", "an enthusiastic supporter or admirer", "their fans", "fan \u2192 fans \u2192 fanbase"),
 E(["sufficient"], "Sufficient", "enough for a need", "if sufficient supporters", "suffice \u2192 sufficient \u2192 sufficiently"),
 E(["supporters","supporter"], "Supporter", "a person who supports a team or cause", "if supporters do not buy tickets", "support \u2192 supporter \u2192 supportive"),
 E(["struggle to survive","struggle"], "Struggle to survive", "to find it hard to continue existing", "teams might struggle to survive"),
 E(["chatbots","chatbot"], "Chatbot", "a computer program that simulates conversation", "make use of chatbots"),
 E(["virtual assistants","virtual"], "Virtual assistant", "a software program that helps users with tasks", "'virtual assistants'", "virtual \u2192 virtually"),
 E(["background information","background"], "Background information", "facts that help explain a situation", "background information", "background \u2192 backgrounds"),
 E(["favourite"], "Favourite", "most liked or preferred", "favourite players", "favour \u2192 favourite \u2192 favoured"),
 E(["innovation"], "Innovation", "a new method or idea", "another innovation", "innovate \u2192 innovation \u2192 innovative"),
 E(["promoting","promote"], "Promote", "to encourage the growth of something", "promoting the sport", "promote \u2192 promotion \u2192 promotional"),
 E(["seeking","seek"], "Seek", "to try to find or attract", "seeking new fans", "seek \u2192 sought \u2192 seeking"),
 E(["AI-enhanced","enhanced","enhance"], "Enhanced", "improved in quality or value", "AI-enhanced journalism", "enhance \u2192 enhanced \u2192 enhancement"),
 E(["journalism"], "Journalism", "the activity of writing news reports", "AI-enhanced journalism", "journal \u2192 journalism \u2192 journalist"),
 E(["informed","inform"], "Informed", "having or kept up with knowledge", "keeping supporters informed", "inform \u2192 informed \u2192 information"),
 E(["up-to-the-minute"], "Up-to-the-minute", "having the very latest information", "up-to-the-minute developments"),
 E(["developments","development"], "Development", "a new event or stage of progress", "the latest developments", "develop \u2192 development \u2192 developer"),
 E(["traditional"], "Traditional", "following older, established methods", "traditional approaches", "tradition \u2192 traditional \u2192 traditionally"),
 E(["Analysts","analysts","analyst"], "Analyst", "a person who examines things in detail", "analysts believe", "analyse \u2192 analyst \u2192 analysis"),
 E(["initiatives","initiative"], "Initiative", "a new plan or action to solve a problem", "these initiatives", "initiate \u2192 initiative \u2192 initiated"),
 E(["crucial"], "Crucial", "extremely important; decisive", "crucial to increasing revenue", "crucial \u2192 crucially"),
 E(["revenue stream","revenue"], "Revenue", "the income a business receives", "a team's revenue stream", "revenue \u2192 revenues"),
 E(["stand to benefit","benefit"], "Stand to benefit", "to be likely to gain an advantage", "sports stand to benefit", "benefit \u2192 beneficial \u2192 beneficiary"),
 E(["field"], "Field (sport)", "the area where a sport is played", "on and off the field"),
]


P3_PARAS = [
"Crime fiction books, in which detectives hunt for the perpetrators of crimes, have been popular with readers for many decades - so popular, in fact, that at a recent London Book Fair sales of the genre overtook general fiction for the first time ever, a development that had been widely anticipated. Commercial success, of course, does not impress everyone and there are those who believe crime fiction should not be held in such high regard. Prominent in this group is Sebastian Franklin, who has argued that most crime fiction books better resemble crossword puzzles than literature. His view is shared by other literary critics. However, increasingly this is a minority opinion as crime fiction becomes recognised around the world as a rich and dynamic literary genre in its own right.",
"Crime writing really came to prominence in the 1920s and 30s with the books of the British author Agatha Christie, and to a slightly lesser extent the American James M. Cain. Agatha Christie was a prolific writer, publishing more than 60 detective novels over a 50-year period, beginning in 1920. However, the majority of the general public have never picked up one of her books and are more familiar with Christie from the numerous adaptations of her work for films. The colourful locations around the world where Christie set many of her stories were not fictional depictions, but were informed by her extensive travels, on the Orient Express train, to Cairo and the River Nile, and elsewhere. Her memoir, Come, Tell Me How You Live, published in 1946, is a non-fiction account of these real-life travels, so is unique among Christie's publications. Success brought Christie considerable wealth and international fame, though she never lost her appetite for work, continuing writing and publishing until shortly before her death in 1976.",
"Without doubt there are certain elements that tend to be repeated in Christie's books. The stories generally revolve around a well-off if not aristocratic circle of people, whose privileged lives are thrown into chaos by an unexplained crime. What's more, the location is often a confined space of some sort: a train, an island, a boat, an isolated house or a village. This is quite different, for example, to the world of the fictional detective Sherlock Holmes, who often has as his hunting ground the entire city of London. But the influence of Christie's sheltered, secluded locations has been immense, for they have been used in countless television series ever since.",
"The writer Michael Utley argues that Christie's characters lack depth and are not convincing people we can believe in. This is a not infrequent complaint, but it is quite untrue. Christie was a perceptive observer of human nature and psychology and she put the traits of people she knew into many of her fictional characters. Part of the reason her appeal has been so widespread is that she wrote about human relationships in a way so many of us can relate to. Her very first book, The Mysterious Affair at Styles, features the amateur detective Hercule Poirot. Poirot and Miss Marple are Christie's two best known and most frequently imitated characters precisely because they are so well drawn and believable. Further evidence of Christie's ability at characterisation was provided by a recent survey. The survey asked readers to identify the villain revealed in the final pages of Christie's sixteenth book, Murder on the Orient Express. Most readers could not recall, because for them the really important aspect of the book had been the interplay between the characters, not the outcome. The truth is that Christie's characters were one of her greatest achievements as a writer.",
"The books are also action-packed, no less so than today's most popular thrillers. Christie mastered the art of the page-turner: events unfold so quickly and unpredictably that we keep reading to find out what happens next. The most significant consequence is that it is so simple to overlook vital clues. It is worth reading a Christie book a second time just to notice how carefully she hides crucial information about the criminal's identity. It was there all along, but we just fail to see it because she has created such tension and so many exciting distractions.",
"Attempts to retell Christie's stories in contemporary times have largely been unsuccessful; they work best in their original early twentieth-century settings and cannot accommodate mobile phones, computers and DNA analysis. But that does not mean her influence has come to an end. Indeed, a new generation of global crime writers is emerging in nations as diverse as Brazil, Singapore, South Korea, India and Nigeria, to name but five. And though each new writer adds something of their own, they all employ conventions first established by Christie. If we take just one of her books, The Murder of Roger Ackroyd, we find near perfect examples of conventions that are still used today: tight plotting, clever sub-plots, unexpected twists, perceptive characterisation. Perhaps this is why Christie herself is believed to have ranked The Murder of Roger Ackroyd above all her other work. Certainly, the digital revolution has transformed crime fighting. But a survey of contemporary crime writing shows that Agatha Christie's legacy is more important now than at any time previously, at the very point when crime writing has become the most popular of all book genres.",
]

P3_ENTRIES = [
 E(["Crime fiction","crime fiction","crime"], "Crime fiction", "stories about crimes and their investigation", "crime fiction books", "crime \u2192 criminal \u2192 criminally"),
 E(["fiction"], "Fiction", "literature describing imaginary events", "general fiction", "fiction \u2192 fictional \u2192 fictionalise"),
 E(["detectives","detective"], "Detective", "a person who investigates crimes", "detectives hunt criminals", "detect \u2192 detective \u2192 detection"),
 E(["hunt"], "Hunt (v)", "to search for or pursue", "detectives hunt for criminals", "hunt \u2192 hunter \u2192 hunting"),
 E(["perpetrators","perpetrator"], "Perpetrator", "a person who commits a crime", "the perpetrators of crimes", "perpetrate \u2192 perpetrator"),
 E(["crimes","crime"], "Crime", "an act that breaks the law", "the perpetrators of crimes", "crime \u2192 criminal \u2192 criminally"),
 E(["popular"], "Popular", "liked by many people", "popular with readers", "popular \u2192 popularity \u2192 popularise"),
 E(["decades","decade"], "Decade", "a period of ten years", "for many decades", "decade \u2192 decades"),
 E(["Book Fair","fair"], "Book fair", "an event where books are displayed and sold", "the London Book Fair"),
 E(["sales","sale"], "Sales", "the amount of goods sold", "sales of the genre", "sell \u2192 sale \u2192 sales"),
 E(["genre"], "Genre", "a category or type of literature or art", "sales of the genre"),
 E(["overtook","overtake"], "Overtake", "to become greater than; to pass", "overtook general fiction", "overtake \u2192 overtook \u2192 overtaken"),
 E(["development"], "Development", "a new event or change", "a development that was expected", "develop \u2192 development \u2192 developing"),
 E(["widely anticipated","anticipated","anticipate"], "Anticipated", "expected or predicted in advance", "widely anticipated", "anticipate \u2192 anticipation \u2192 anticipated"),
 E(["Commercial","commercial"], "Commercial", "relating to business and profit", "commercial success", "commerce \u2192 commercial \u2192 commercially"),
 E(["success"], "Success", "the achievement of a goal", "commercial success", "succeed \u2192 success \u2192 successful"),
 E(["impress"], "Impress", "to make someone admire something", "does not impress everyone", "impress \u2192 impression \u2192 impressive"),
 E(["held in such high regard","high regard","regard"], "Held in high regard", "greatly respected or admired", "held in high regard"),
 E(["Prominent","prominent"], "Prominent", "important and well known", "prominent in this group", "prominent \u2192 prominence \u2192 prominently"),
 E(["argued","argue"], "Argue", "to give reasons for an opinion", "he has argued that", "argue \u2192 argument \u2192 arguably"),
 E(["resemble"], "Resemble", "to be similar to or like", "resemble crossword puzzles", "resemble \u2192 resemblance \u2192 resembling"),
 E(["crossword puzzles","puzzles","puzzle"], "Crossword puzzle", "a word game of filling in a grid", "resemble crossword puzzles"),
 E(["literature"], "Literature", "written works of artistic value", "than literature", "literature \u2192 literary \u2192 literate"),
 E(["literary"], "Literary", "relating to literature", "literary critics", "literature \u2192 literary \u2192 literate"),
 E(["critics","critic"], "Critic", "a person who judges art or writing", "literary critics", "critic \u2192 critical \u2192 criticism"),
 E(["minority"], "Minority", "the smaller number or part", "a minority opinion", "minor \u2192 minority"),
 E(["opinion"], "Opinion", "a personal view or belief", "a minority opinion", "opine \u2192 opinion \u2192 opinionated"),
 E(["recognised","recognise"], "Recognise", "to accept or acknowledge as valid", "becomes recognised", "recognise \u2192 recognition \u2192 recognisable"),
 E(["dynamic"], "Dynamic", "full of energy and change", "a dynamic genre", "dynamic \u2192 dynamically \u2192 dynamism"),
 E(["in its own right"], "In its own right", "considered on its own merits", "a genre in its own right"),
 E(["came to prominence","prominence"], "Come to prominence", "to become important or well known", "came to prominence in the 1920s", "prominent \u2192 prominence"),
 E(["author"], "Author", "a writer of a book", "the British author", "author \u2192 authorship \u2192 authored"),
 E(["lesser extent","extent"], "To a lesser extent", "to a smaller degree", "to a lesser extent"),
 E(["prolific"], "Prolific", "producing many works or results", "a prolific writer", "prolific \u2192 prolifically"),
 E(["publishing","publish"], "Publish", "to produce a book for sale to the public", "publishing 60 novels", "publish \u2192 publication \u2192 publisher"),
 E(["detective novels","novels","novel"], "Novel (n)", "a long fictional story in book form", "detective novels", "novel \u2192 novelist"),
 E(["majority"], "Majority", "the greater number or part", "the majority of the public", "major \u2192 majority"),
 E(["general public","public"], "The general public", "ordinary people as a whole", "the general public"),
 E(["picked up","pick up"], "Pick up (a book)", "to start reading or take hold of", "never picked up her books"),
 E(["familiar with","familiar"], "Familiar with", "having knowledge of something", "familiar with Christie", "familiar \u2192 familiarity \u2192 familiarise"),
 E(["numerous"], "Numerous", "many", "numerous adaptations", "number \u2192 numerous \u2192 innumerable"),
 E(["adaptations","adaptation"], "Adaptation", "a film or play based on another work", "adaptations of her work", "adapt \u2192 adaptation \u2192 adapted"),
 E(["colourful"], "Colourful", "full of interest and variety; vivid", "colourful locations", "colour \u2192 colourful \u2192 colourfully"),
 E(["locations","location"], "Location", "a particular place", "colourful locations", "locate \u2192 location \u2192 located"),
 E(["fictional"], "Fictional", "invented; not real", "fictional depictions", "fiction \u2192 fictional \u2192 fictionalise"),
 E(["depictions","depiction"], "Depiction", "a representation in words or pictures", "fictional depictions", "depict \u2192 depiction \u2192 depicted"),
 E(["informed by","informed","inform"], "Informed by", "shaped by knowledge or experience", "informed by her travels", "inform \u2192 informed \u2192 information"),
 E(["extensive"], "Extensive", "covering a large area or amount", "her extensive travels", "extend \u2192 extensive \u2192 extensively"),
 E(["travels","travel"], "Travels", "journeys to different places", "her extensive travels", "travel \u2192 traveller \u2192 travelling"),
 E(["elsewhere"], "Elsewhere", "in or to another place", "the Nile and elsewhere"),
 E(["memoir"], "Memoir", "a written account of one's own experiences", "her memoir", "memoir \u2192 memoirs"),
 E(["non-fiction"], "Non-fiction", "writing about real facts and events", "a non-fiction account", "fiction \u2192 non-fiction"),
 E(["account"], "Account (n)", "a written or spoken report", "an account of her travels", "account \u2192 accounts"),
 E(["real-life","real"], "Real-life", "actually happening; not invented", "real-life travels", "real \u2192 reality \u2192 really"),
 E(["unique"], "Unique", "being the only one of its kind", "unique among her works", "unique \u2192 uniquely \u2192 uniqueness"),
 E(["publications","publication"], "Publication", "a published book or work", "Christie's publications", "publish \u2192 publication \u2192 publisher"),
 E(["considerable"], "Considerable", "large in amount or degree", "considerable wealth", "consider \u2192 considerable \u2192 considerably"),
 E(["wealth"], "Wealth", "a large amount of money or possessions", "considerable wealth", "wealth \u2192 wealthy \u2192 well-off"),
 E(["international"], "International", "involving more than one country", "international fame", "nation \u2192 international \u2192 internationally"),
 E(["fame"], "Fame", "the state of being well known", "wealth and fame", "fame \u2192 famous \u2192 infamous"),
 E(["appetite for","appetite"], "Appetite for", "a strong desire or enthusiasm for", "her appetite for work", "appetite \u2192 appetising"),
 E(["shortly"], "Shortly", "in a short time; soon", "shortly before her death", "short \u2192 shortly"),
 E(["death"], "Death", "the end of life", "her death in 1976", "die \u2192 death \u2192 dead"),
 E(["Without doubt","doubt"], "Without doubt", "certainly; definitely", "without doubt there are elements", "doubt \u2192 doubtful \u2192 undoubtedly"),
 E(["elements","element"], "Element", "a part or feature of something", "certain elements", "element \u2192 elemental"),
 E(["tend to","tend"], "Tend to", "to be likely to do or be", "elements that tend to repeat", "tend \u2192 tendency \u2192 tending"),
 E(["repeated","repeat"], "Repeated", "done or occurring again", "tend to be repeated", "repeat \u2192 repeated \u2192 repetition"),
 E(["revolve around","revolve"], "Revolve around", "to have as a main focus", "stories revolve around the wealthy", "revolve \u2192 revolving"),
 E(["well-off"], "Well-off", "having plenty of money; wealthy", "a well-off circle", "well-off \u2192 better off"),
 E(["aristocratic"], "Aristocratic", "belonging to the highest social class", "an aristocratic circle", "aristocrat \u2192 aristocratic \u2192 aristocracy"),
 E(["circle"], "Circle (of people)", "a group of people connected socially", "a circle of people", "circle \u2192 circles"),
 E(["privileged"], "Privileged", "having special advantages or wealth", "their privileged lives", "privilege \u2192 privileged"),
 E(["thrown into chaos","chaos"], "Thrown into chaos", "suddenly made disordered and confused", "lives thrown into chaos", "chaos \u2192 chaotic"),
 E(["unexplained","explain"], "Unexplained", "without a known reason or cause", "an unexplained crime", "explain \u2192 unexplained \u2192 explanation"),
 E(["What's more","what's more"], "What's more", "in addition; moreover", "what's more, the location is confined"),
 E(["confined"], "Confined", "limited in space; enclosed", "a confined space", "confine \u2192 confined \u2192 confinement"),
 E(["isolated"], "Isolated", "far away; separated from others", "an isolated house", "isolate \u2192 isolated \u2192 isolation"),
 E(["village"], "Village", "a small community in the countryside", "or a village", "village \u2192 villager"),
 E(["hunting ground","ground"], "Hunting ground", "a place where one searches or operates", "his hunting ground"),
 E(["entire"], "Entire", "whole; complete", "the entire city", "entire \u2192 entirely \u2192 entirety"),
 E(["influence"], "Influence (n)", "the power to affect something", "the influence of her locations", "influence \u2192 influential \u2192 influencer"),
 E(["sheltered","shelter"], "Sheltered", "protected; enclosed and safe", "sheltered locations", "shelter \u2192 sheltered \u2192 sheltering"),
 E(["secluded"], "Secluded", "private and away from others", "secluded locations", "seclude \u2192 secluded \u2192 seclusion"),
 E(["immense"], "Immense", "extremely great in size or degree", "the influence has been immense", "immense \u2192 immensely \u2192 immensity"),
 E(["countless"], "Countless", "too many to count", "countless television series", "count \u2192 countless"),
 E(["series"], "Series", "a set of related programmes or events", "television series", "series \u2192 serial"),
 E(["characters","character"], "Character", "a person in a story or play", "Christie's characters", "character \u2192 characterise \u2192 characteristic"),
 E(["lack"], "Lack (v)", "to be without something", "characters lack depth", "lack \u2192 lacking"),
 E(["depth"], "Depth", "complexity; the quality of being deep", "lack depth", "deep \u2192 depth \u2192 deepen"),
 E(["convincing"], "Convincing", "believable; persuasive", "not convincing people", "convince \u2192 convincing \u2192 conviction"),
 E(["infrequent","frequent"], "Infrequent", "not happening often", "a not infrequent complaint", "frequent \u2192 infrequent \u2192 infrequently"),
 E(["complaint"], "Complaint", "a statement of dissatisfaction", "a common complaint", "complain \u2192 complaint"),
 E(["untrue","true"], "Untrue", "not true; false", "it is quite untrue", "true \u2192 untrue \u2192 truth"),
 E(["perceptive"], "Perceptive", "quick to notice and understand", "a perceptive observer", "perceive \u2192 perceptive \u2192 perception"),
 E(["observer"], "Observer", "a person who watches carefully", "an observer of human nature", "observe \u2192 observer \u2192 observation"),
 E(["human nature","nature"], "Human nature", "the natural ways people think and behave", "human nature and psychology"),
 E(["psychology"], "Psychology", "the study of the mind and behaviour", "nature and psychology", "psychology \u2192 psychological \u2192 psychologist"),
 E(["traits","trait"], "Trait", "a particular quality of a person", "the traits of people", "trait \u2192 traits"),
 E(["appeal"], "Appeal (n)", "the quality of being attractive", "her appeal has been widespread", "appeal \u2192 appealing \u2192 appealingly"),
 E(["widespread"], "Widespread", "existing over a large area or among many", "so widespread", "wide \u2192 widespread"),
 E(["relate to","relate"], "Relate to", "to feel connected to or understand", "relationships we can relate to", "relate \u2192 relation \u2192 related"),
 E(["features","feature"], "Feature (v)", "to include as a main element", "her first book features Poirot", "feature \u2192 featured \u2192 featuring"),
 E(["amateur"], "Amateur", "a non-professional; doing for pleasure", "the amateur detective", "amateur \u2192 amateurish"),
 E(["frequently","frequent"], "Frequently", "often", "most frequently imitated", "frequent \u2192 frequently \u2192 frequency"),
 E(["imitated","imitate"], "Imitated", "copied or modelled on", "frequently imitated characters", "imitate \u2192 imitation \u2192 imitator"),
 E(["precisely","precise"], "Precisely", "exactly", "precisely because they are believable", "precise \u2192 precisely \u2192 precision"),
 E(["well drawn","drawn","draw"], "Well drawn", "described convincingly (of a character)", "so well drawn"),
 E(["believable"], "Believable", "able to be believed; convincing", "well drawn and believable", "believe \u2192 believable \u2192 belief"),
 E(["evidence"], "Evidence", "facts showing something is true", "further evidence", "evident \u2192 evidence \u2192 evidently"),
 E(["ability"], "Ability", "the skill to do something", "her ability at characterisation", "able \u2192 ability \u2192 enable"),
 E(["characterisation"], "Characterisation", "the way characters are created in a story", "ability at characterisation", "character \u2192 characterise \u2192 characterisation"),
 E(["survey"], "Survey", "a study of people's opinions", "a recent survey", "survey \u2192 surveyor"),
 E(["villain"], "Villain", "the main bad character in a story", "identify the villain", "villain \u2192 villainous"),
 E(["revealed","reveal"], "Revealed", "made known; uncovered", "the villain revealed", "reveal \u2192 revelation \u2192 revealed"),
 E(["recall"], "Recall (v)", "to remember something", "could not recall", "recall \u2192 recollection"),
 E(["aspect"], "Aspect", "a particular part or feature", "the important aspect", "aspect \u2192 aspects"),
 E(["interplay"], "Interplay", "the way things affect each other", "the interplay between characters"),
 E(["outcome"], "Outcome", "the result or ending", "not the outcome", "outcome \u2192 outcomes"),
 E(["achievements","achievement"], "Achievement", "a thing done successfully", "her greatest achievements", "achieve \u2192 achievement \u2192 achievable"),
 E(["action-packed","action"], "Action-packed", "full of exciting events", "the books are action-packed"),
 E(["thrillers","thriller"], "Thriller", "an exciting story full of suspense", "popular thrillers", "thrill \u2192 thriller \u2192 thrilling"),
 E(["mastered","master"], "Master (v)", "to gain complete skill in something", "Christie mastered the art", "master \u2192 mastery \u2192 mastered"),
 E(["page-turner"], "Page-turner", "a book so exciting one keeps reading", "the art of the page-turner"),
 E(["unfold"], "Unfold", "to develop or be revealed gradually", "events unfold quickly", "unfold \u2192 unfolding \u2192 unfolded"),
 E(["unpredictably","unpredictable"], "Unpredictably", "in a way that cannot be foreseen", "unfold unpredictably", "predict \u2192 unpredictable \u2192 unpredictably"),
 E(["significant"], "Significant", "important; meaningful", "the most significant consequence", "signify \u2192 significant \u2192 significance"),
 E(["consequence"], "Consequence", "a result or effect", "the consequence is", "consequence \u2192 consequent \u2192 consequently"),
 E(["overlook"], "Overlook", "to fail to notice", "overlook vital clues", "overlook \u2192 overlooked"),
 E(["vital clues","vital"], "Vital", "extremely important; essential", "vital clues", "vital \u2192 vitally \u2192 vitality"),
 E(["clues","clue"], "Clue", "a piece of evidence helping solve a mystery", "vital clues"),
 E(["worth"], "Worth (doing)", "deserving of the effort", "it is worth reading again", "worth \u2192 worthy \u2192 worthwhile"),
 E(["carefully","careful"], "Carefully", "with great attention and caution", "how carefully she hides clues", "care \u2192 careful \u2192 carefully"),
 E(["hides","hide"], "Hide (v)", "to keep something from being seen", "she hides information", "hide \u2192 hidden \u2192 hiding"),
 E(["crucial"], "Crucial", "extremely important; decisive", "crucial information", "crucial \u2192 crucially"),
 E(["criminal's","criminal"], "Criminal (n)", "a person who has committed a crime", "the criminal's identity", "crime \u2192 criminal \u2192 criminally"),
 E(["identity"], "Identity", "who or what someone or something is", "the criminal's identity", "identify \u2192 identity \u2192 identical"),
 E(["all along"], "All along", "from the very beginning", "it was there all along"),
 E(["fail to","fail"], "Fail to", "to not succeed in doing something", "we fail to see it", "fail \u2192 failure \u2192 failing"),
 E(["tension"], "Tension", "a feeling of nervous excitement or suspense", "such tension", "tense \u2192 tension"),
 E(["distractions","distraction"], "Distraction", "something that takes attention away", "exciting distractions", "distract \u2192 distraction \u2192 distracted"),
 E(["retell"], "Retell", "to tell a story again, often differently", "to retell her stories", "tell \u2192 retell \u2192 retelling"),
 E(["contemporary"], "Contemporary", "belonging to the present time", "contemporary times", "contemporary \u2192 contemporaries"),
 E(["unsuccessful","success"], "Unsuccessful", "not achieving the desired result", "largely unsuccessful", "succeed \u2192 successful \u2192 unsuccessful"),
 E(["original"], "Original", "existing from the start; first", "their original settings", "origin \u2192 original \u2192 originally"),
 E(["settings","setting"], "Setting", "the place and time of a story", "their original settings", "set \u2192 setting"),
 E(["accommodate"], "Accommodate", "to provide room for; to include", "cannot accommodate phones", "accommodate \u2192 accommodation \u2192 accommodating"),
 E(["come to an end","end"], "Come to an end", "to stop; to finish", "her influence has not come to an end"),
 E(["generation"], "Generation", "all people of about the same age or period", "a new generation of writers", "generate \u2192 generation \u2192 generational"),
 E(["global"], "Global", "relating to the whole world", "global crime writers", "globe \u2192 global \u2192 globally"),
 E(["emerging","emerge"], "Emerging", "newly appearing or developing", "writers are emerging", "emerge \u2192 emergence \u2192 emerging"),
 E(["diverse"], "Diverse", "very different and varied", "nations as diverse as Brazil", "diverse \u2192 diversity \u2192 diversify"),
 E(["to name but five","name"], "To name but five", "giving only five examples of many", "to name but five"),
 E(["employ"], "Employ (use)", "to make use of something", "they employ conventions", "employ \u2192 employment \u2192 employed"),
 E(["conventions","convention"], "Convention", "an accepted, traditional way of doing something", "conventions established by Christie", "convene \u2192 convention \u2192 conventional"),
 E(["established"], "Established", "set up and accepted", "conventions first established", "establish \u2192 established \u2192 establishment"),
 E(["near perfect","perfect"], "Near perfect", "almost completely without faults", "near perfect examples", "perfect \u2192 perfection \u2192 perfectly"),
 E(["tight plotting","plotting","plot"], "Plot (n)", "the main sequence of events in a story", "tight plotting", "plot \u2192 plotting \u2192 plotted"),
 E(["sub-plots","sub-plot"], "Sub-plot", "a secondary story within the main plot", "clever sub-plots"),
 E(["unexpected","expect"], "Unexpected", "not foreseen; surprising", "unexpected twists", "expect \u2192 unexpected \u2192 unexpectedly"),
 E(["twists","twist"], "Twist (n)", "a surprising change in a story", "unexpected twists", "twist \u2192 twisted \u2192 twisting"),
 E(["ranked","rank"], "Rank (v)", "to place in order of importance", "ranked it above others", "rank \u2192 ranking \u2192 ranked"),
 E(["digital revolution","revolution"], "Digital revolution", "the major change brought by digital technology", "the digital revolution", "revolution \u2192 revolutionary \u2192 revolutionise"),
 E(["transformed","transform"], "Transform", "to change completely", "transformed crime fighting", "transform \u2192 transformation \u2192 transformative"),
 E(["legacy"], "Legacy", "something handed down from the past", "Christie's legacy", "legacy \u2192 legacies"),
 E(["previously","previous"], "Previously", "at an earlier time", "than at any time previously", "previous \u2192 previously"),
 E(["genres","genre"], "Genre", "a category of literature, art or music", "all book genres"),
]

PASSAGES = [
 {"num": 1, "title": "Wooden Buildings", "paragraphs": P1_PARAS, "entries": P1_ENTRIES},
 {"num": 2, "title": "Artificial Intelligence in Sport", "paragraphs": P2_PARAS, "entries": P2_ENTRIES},
 {"num": 3, "title": "The Influence of the Crime Writer Agatha Christie", "paragraphs": P3_PARAS, "entries": P3_ENTRIES},
]
